#!/bin/bash
if [ -z "$1" ]
then
  env -i $0 CLEAN_ENV
elif [ "$1" == "CLEAN_ENV" ]
then
  EXPORTCMD="$0"
  MDSPLUS_DIR=`/bin/cat /etc/.mdsplus_dir`
  . $MDSPLUS_DIR/setup.sh
else
  echo setenv $1 "$2" 
fi

