/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/*
 * BASLERACASetup.java
 *
 * Created on May 18, 2017, 11:42:15 AM
 */
/**
 *
 * @author F.Molon
 */
public class BASLERACASetup extends DeviceSetup {
    /** Creates new form FLIR655Setup */
    public BASLERACASetup() {
        initComponents();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        deviceField16 = new DeviceField();
        deviceField17 = new DeviceField();
        deviceDispatch1 = new DeviceDispatch();
        jPanel17 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        deviceField27 = new DeviceField();
        deviceField28 = new DeviceField();
        deviceField29 = new DeviceField();
        deviceField30 = new DeviceField();
        jPanel18 = new javax.swing.JPanel();
        deviceChoice3 = new DeviceChoice();
        jPanel12 = new javax.swing.JPanel();
        deviceChoice6 = new DeviceChoice();
        deviceField4 = new DeviceField();
        deviceChoice7 = new DeviceChoice();
        deviceChoice9 = new DeviceChoice();
        deviceField6 = new DeviceField();
        jPanel4 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        deviceChoice4 = new DeviceChoice();
        deviceField5 = new DeviceField();
        jPanel16 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        deviceField8 = new DeviceField();
        deviceField9 = new DeviceField();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        deviceChoice5 = new DeviceChoice();
        deviceField18 = new DeviceField();
        jPanel21 = new javax.swing.JPanel();
        deviceField21 = new DeviceField();
        jPanel20 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        deviceChoice8 = new DeviceChoice();
        deviceField19 = new DeviceField();
        deviceField20 = new DeviceField();
        jPanel24 = new javax.swing.JPanel();
        deviceField7 = new DeviceField();
        deviceField10 = new DeviceField();
        deviceField11 = new DeviceField();
        deviceField12 = new DeviceField();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        deviceButtons1 = new DeviceButtons();

        setDeviceProvider("localhost:8000");
        setDeviceTitle("BASLER ACA Camera Device");
        setDeviceType("BASLERACA");
        setHeight(450);
        setWidth(900);

        jPanel1.setMinimumSize(new java.awt.Dimension(690, 470));
        jPanel1.setPreferredSize(new java.awt.Dimension(690, 470));
        jPanel1.setLayout(new java.awt.BorderLayout(5, 5));

        jPanel8.setMinimumSize(new java.awt.Dimension(690, 40));
        jPanel8.setPreferredSize(new java.awt.Dimension(690, 40));

        deviceField16.setIdentifier("");
        deviceField16.setLabelString("Name (IP): ");
        deviceField16.setNumCols(20);
        deviceField16.setOffsetNid(1);
        deviceField16.setTextOnly(true);
        jPanel8.add(deviceField16);

        deviceField17.setIdentifier("");
        deviceField17.setLabelString("Comment:");
        deviceField17.setNumCols(30);
        deviceField17.setOffsetNid(2);
        jPanel8.add(deviceField17);
        jPanel8.add(deviceDispatch1);

        jPanel1.add(jPanel8, java.awt.BorderLayout.NORTH);

        jPanel17.setMinimumSize(new java.awt.Dimension(690, 440));
        jPanel17.setPreferredSize(new java.awt.Dimension(690, 440));
        jPanel17.setLayout(new java.awt.BorderLayout());

        jTabbedPane1.setMinimumSize(new java.awt.Dimension(680, 390));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(680, 390));

        jPanel5.setLayout(new java.awt.GridLayout(3, 1));

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder("Frame Area"));

        deviceField27.setIdentifier("");
        deviceField27.setLabelString("Start X:");
        deviceField27.setNumCols(4);
        deviceField27.setOffsetNid(4);
        jPanel14.add(deviceField27);

        deviceField28.setIdentifier("");
        deviceField28.setLabelString("Start Y:");
        deviceField28.setNumCols(4);
        deviceField28.setOffsetNid(5);
        jPanel14.add(deviceField28);

        deviceField29.setIdentifier("");
        deviceField29.setLabelString("Width: ");
        deviceField29.setNumCols(4);
        deviceField29.setOffsetNid(6);
        jPanel14.add(deviceField29);

        deviceField30.setIdentifier("");
        deviceField30.setLabelString("Height: ");
        deviceField30.setNumCols(4);
        deviceField30.setOffsetNid(7);
        jPanel14.add(deviceField30);

        jPanel5.add(jPanel14);

        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder("Image Settings"));

        deviceChoice3.setChoiceItems(new String[] {"Mono8", "Mono12", "BayerRG8", "YUV422P"});
        deviceChoice3.setIdentifier("");
        deviceChoice3.setLabelString("Pixel Format:");
        deviceChoice3.setOffsetNid(8);
        deviceChoice3.setUpdateIdentifier("");
        jPanel18.add(deviceChoice3);

        jPanel5.add(jPanel18);

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Camera Settings"));
        jPanel12.setLayout(new java.awt.GridLayout(2, 3));

        deviceChoice6.setChoiceItems(new String[] {"Off", "Once", "Continuous"});
        deviceChoice6.setIdentifier("");
        deviceChoice6.setLabelString("Gain Auto:");
        deviceChoice6.setOffsetNid(10);
        deviceChoice6.setUpdateIdentifier("");
        jPanel12.add(deviceChoice6);

        deviceField4.setLabelString("Gain : ");
        deviceField4.setOffsetNid(11);
        jPanel12.add(deviceField4);

        deviceChoice7.setChoiceItems(new String[] {"Off", "On"});
        deviceChoice7.setIdentifier("");
        deviceChoice7.setLabelString("Gamma Enable:");
        deviceChoice7.setOffsetNid(12);
        deviceChoice7.setUpdateIdentifier("");
        jPanel12.add(deviceChoice7);

        deviceChoice9.setChoiceItems(new String[] {"Off", "Once", "Continuous"});
        deviceChoice9.setIdentifier("");
        deviceChoice9.setLabelString("Exposure Auto:");
        deviceChoice9.setOffsetNid(13);
        deviceChoice9.setUpdateIdentifier("");
        jPanel12.add(deviceChoice9);

        deviceField6.setLabelString("Exposure [us] : ");
        deviceField6.setOffsetNid(14);
        jPanel12.add(deviceField6);

        jPanel5.add(jPanel12);

        jTabbedPane1.addTab("Image & Camera Settings", jPanel5);
        jPanel5.getAccessibleContext().setAccessibleName("Frame Area");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.setLayout(new java.awt.GridLayout(3, 1));

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder("Synchronization"));

        deviceChoice4.setChoiceItems(new String[] {"INTERNAL", "EXTERNAL"});
        deviceChoice4.setIdentifier("");
        deviceChoice4.setLabelString("Trigger Mode:");
        deviceChoice4.setOffsetNid(16);
        deviceChoice4.setUpdateIdentifier("");
        jPanel15.add(deviceChoice4);

        deviceField5.setIdentifier("");
        deviceField5.setLabelString("Trigger Source: ");
        deviceField5.setNumCols(25);
        deviceField5.setOffsetNid(17);
        jPanel15.add(deviceField5);

        jPanel4.add(jPanel15);

        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder("Frames Acquisition"));
        jPanel16.setLayout(new java.awt.GridLayout(1, 1));

        deviceField8.setIdentifier("");
        deviceField8.setLabelString("Frame Rate [fps]:");
        deviceField8.setNumCols(20);
        deviceField8.setOffsetNid(19);
        jPanel6.add(deviceField8);

        deviceField9.setIdentifier("");
        deviceField9.setLabelString("Burst Duration [s]:");
        deviceField9.setNumCols(20);
        deviceField9.setOffsetNid(20);
        jPanel6.add(deviceField9);

        jPanel16.add(jPanel6);

        jPanel4.add(jPanel16);

        jTabbedPane1.addTab("Timing", jPanel4);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel9.setLayout(new java.awt.GridLayout(3, 1));

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Storage and Streaming"));

        deviceChoice5.setChoiceItems(new String[] {"Stream and Store", "Only Stream", "Only Store"});
        deviceChoice5.setIdentifier("");
        deviceChoice5.setLabelString("Acquisition Mode:");
        deviceChoice5.setOffsetNid(23);
        deviceChoice5.setUpdateIdentifier("");
        jPanel10.add(deviceChoice5);

        deviceField18.setIdentifier("");
        deviceField18.setLabelString("Streaming Port:");
        deviceField18.setNumCols(4);
        deviceField18.setOffsetNid(25);
        jPanel10.add(deviceField18);

        jPanel9.add(jPanel10);

        jPanel21.setBorder(javax.swing.BorderFactory.createTitledBorder("Frames Decimation for Storing"));

        deviceField21.setIdentifier("");
        deviceField21.setLabelString("Save one frame and skip:");
        deviceField21.setNumCols(4);
        deviceField21.setOffsetNid(21);
        jPanel21.add(deviceField21);

        jPanel9.add(jPanel21);

        jPanel20.setBorder(javax.swing.BorderFactory.createTitledBorder("Dynamic Range for Streaming"));

        deviceChoice8.setChoiceItems(new String[] {"YES", "NO"});
        deviceChoice8.setIdentifier("");
        deviceChoice8.setLabelString("Auto Adjustment:");
        deviceChoice8.setOffsetNid(26);
        deviceChoice8.setUpdateIdentifier("");
        jPanel2.add(deviceChoice8);

        deviceField19.setIdentifier("");
        deviceField19.setLabelString("Manual Low Limit [0..2^(n-1)]:");
        deviceField19.setNumCols(4);
        deviceField19.setOffsetNid(27);
        jPanel2.add(deviceField19);

        deviceField20.setIdentifier("");
        deviceField20.setLabelString("Manual High Limit [0..2^(n-1)]:");
        deviceField20.setNumCols(4);
        deviceField20.setOffsetNid(28);
        jPanel2.add(deviceField20);

        jPanel20.add(jPanel2);

        deviceField7.setLabelString("AutoAdj.ROI x:");
        deviceField7.setNumCols(4);
        deviceField7.setOffsetNid(29);
        jPanel24.add(deviceField7);

        deviceField10.setLabelString("AutoAdj.ROI y:");
        deviceField10.setNumCols(4);
        deviceField10.setOffsetNid(30);
        jPanel24.add(deviceField10);

        deviceField11.setLabelString("AutoAdj.ROI w:");
        deviceField11.setNumCols(4);
        deviceField11.setOffsetNid(31);
        jPanel24.add(deviceField11);

        deviceField12.setLabelString("AutoAdj.ROI h:");
        deviceField12.setNumCols(4);
        deviceField12.setOffsetNid(32);
        jPanel24.add(deviceField12);

        jPanel20.add(jPanel24);

        jPanel9.add(jPanel20);

        jTabbedPane1.addTab("Storage & Streaming", jPanel9);

        jPanel22.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel22.setLayout(new java.awt.GridLayout(1, 1));

        jPanel23.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1)));
        jPanel23.setToolTipText("");
        jPanel23.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(242, 241, 240));
        jTextArea1.setColumns(50);
        jTextArea1.setRows(8);
        jTextArea1.setText("------ ACTION ------\ninit: initialize the camera with the current device configuration\nstartAcquisition: start frames acquisition from camera and streaming if enabled. Saving start with HW or SW trigger.\nswTrigger: start saving frames in MDSplus (if store is enabled and trigger mode is set to internal)\nstopAcquisition: stop frames acquisition and streaming.\nchangeExposure: apply exposure auto and exposure to the camera. \n\n------ TIMING ------\nTrigger Mode Internal: Set frame rate and burst duration. Trigger source is auto generated as relative time start from 0.\nTrigger Mode External: Each trigger perform a single frame storing in MDSplus. \n\n");
        jTextArea1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setViewportView(jTextArea1);

        jPanel23.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel22.add(jPanel23);

        jTabbedPane1.addTab("Help", jPanel22);

        jPanel17.add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel17, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        deviceButtons1.setCheckExpressions(new String[] {});
        deviceButtons1.setCheckMessages(new String[] {});
        deviceButtons1.setMethods(new String[] {"init", "startAcquisition", "swTrigger", "stopAcquisition", "changeGain", "changeExposure", "readTemperature"});
        getContentPane().add(deviceButtons1, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private DeviceButtons deviceButtons1;
    private DeviceChoice deviceChoice3;
    private DeviceChoice deviceChoice4;
    private DeviceChoice deviceChoice5;
    private DeviceChoice deviceChoice6;
    private DeviceChoice deviceChoice7;
    private DeviceChoice deviceChoice8;
    private DeviceChoice deviceChoice9;
    private DeviceDispatch deviceDispatch1;
    private DeviceField deviceField10;
    private DeviceField deviceField11;
    private DeviceField deviceField12;
    private DeviceField deviceField16;
    private DeviceField deviceField17;
    private DeviceField deviceField18;
    private DeviceField deviceField19;
    private DeviceField deviceField20;
    private DeviceField deviceField21;
    private DeviceField deviceField27;
    private DeviceField deviceField28;
    private DeviceField deviceField29;
    private DeviceField deviceField30;
    private DeviceField deviceField4;
    private DeviceField deviceField5;
    private DeviceField deviceField6;
    private DeviceField deviceField7;
    private DeviceField deviceField8;
    private DeviceField deviceField9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
