/*
Copyright (c) 2017, Massachusetts Institute of Technology All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

Redistributions of source code must retain the above copyright notice, this
list of conditions and the following disclaimer.

Redistributions in binary form must reproduce the above copyright notice, this
list of conditions and the following disclaimer in the documentation and/or
other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
/*
**	This file is automatically generated.  Do not edit it by hand.
**/
/*  Table of the class type of children
    The table is indexed by child with each entry the
    permitted class for that child.
*/

static unsigned char child_class_table_vec[] = {
  0,
  sym_k_XmPushButton_object,
  sym_k_XmPushButton_object,
  sym_k_XmLabel_object,
  sym_k_XmScrolledList_object,
  sym_k_XmPushButton_object,
  sym_k_XmLabel_object,
  sym_k_XmText_object,
  sym_k_XmPushButton_object,
  sym_k_XmScrollBar_object,
  sym_k_XmLabel_object,
  sym_k_XmScrolledList_object,
  sym_k_XmLabel_object,
  sym_k_XmPushButton_object,
  sym_k_XmCascadeButtonGadget_object,
  sym_k_XmLabelGadget_object,
  sym_k_XmLabel_object,
  sym_k_XmSeparator_object,
  sym_k_XmSeparator_object,
  sym_k_XmSeparator_object,
  sym_k_XmSeparator_object,
  sym_k_XmLabel_object,
  sym_k_XmTearOffButton_object,
  sym_k_XmText_object,
  sym_k_XmLabel_object,
  sym_k_XmScrollBar_object,
};

externaldef(uil_sym_glbl)
unsigned char *child_class_table = child_class_table_vec;
