#!/bin/sh
#
#
# Create wmd file
#
mkdir wmltemp
cd wmltemp
ln -s /usr/examples/motif/wml/tokens.dat .
/usr/examples/motif/wml/wml ../xmdsuil.wml
cc -o wmdcreate -DMDS_EXTENSION -I../../include -I/usr/examples/motif/wml -I. ../wmldbcreate-xmdsshr.c -lXt -lXm
./wmdcreate -o ../xmdsuil.wmd
cd ..
rm -R wmltemp
