from MDSplus import *
from numpy import *
from threading import *
import time
class SPIDER_SM(Device):
    print 'SpiderStateMachine'
    Int32(1).setTdiVar('_PyReleaseThreadLock')
    """SPIDER State Machine Configuration"""
    print 'SpiderStateMachine 1'
    parts=[
      {'path':'.MASTER_SM', 'type':'structure'},
      {'path':'.MASTER_SM.IS_MASTER', 'type':'structure'},
      {'path':'.MASTER_SM.IS_MASTER:PV_NAME', 'type':'text', 'value':'MASTER_SM:IS_MASTER'},
      {'path':'.MASTER_SM.IS_MASTER:VAL', 'type':'numeric', 'value':1},
      {'path':'.MASTER_SM.CHILD_MASK', 'type':'structure'},
      {'path':'.MASTER_SM.CHILD_MASK:PV_NAME', 'type':'text', 'value':'MASTER_SM:CHILDREN_MASK'},
      {'path':'.MASTER_SM.CHILD_MASK:VAL', 'type':'numeric', 'value':31},
      {'path':'.MASTER_SM.ESSENTIAL', 'type':'structure'},
      {'path':'.MASTER_SM.ESSENTIAL:PV_NAME', 'type':'text', 'value':'MASTER_SM:ESSENTIAL'},
      {'path':'.MASTER_SM.ESSENTIAL:VAL', 'type':'numeric', 'value':1},
      {'path':'.PRIMA', 'type':'structure'},
      {'path':'.PRIMA.IS_MASTER', 'type':'structure'},
      {'path':'.PRIMA.IS_MASTER:PV_NAME', 'type':'text', 'value':'PRIMA:IS_MASTER'},
      {'path':'.PRIMA.IS_MASTER:VAL', 'type':'numeric', 'value':0},
      {'path':'.PRIMA.CHILD_MASK', 'type':'structure'},
      {'path':'.PRIMA.CHILD_MASK:PV_NAME', 'type':'text', 'value':'PRIMA:CHILDREN_MASK'},
      {'path':'.PRIMA.CHILD_MASK:VAL', 'type':'numeric', 'value':7},
      {'path':'.PRIMA.ESSENTIAL', 'type':'structure'},
      {'path':'.PRIMA.ESSENTIAL:PV_NAME', 'type':'text', 'value':'PRIMA:ESSENTIAL'},
      {'path':'.PRIMA.ESSENTIAL:VAL', 'type':'numeric', 'value':1},
      {'path':'.COOLING', 'type':'structure'},
      {'path':'.COOLING.IS_MASTER', 'type':'structure'},
      {'path':'.COOLING.IS_MASTER:PV_NAME', 'type':'text', 'value':'COOLING:IS_MASTER'},
      {'path':'.COOLING.IS_MASTER:VAL', 'type':'numeric', 'value':0},
      {'path':'.COOLING.CHILD_MASK', 'type':'structure'},
      {'path':'.COOLING.CHILD_MASK:PV_NAME', 'type':'text', 'value':'COOLING:CHILDREN_MASK'},
      {'path':'.COOLING.CHILD_MASK:VAL', 'type':'numeric', 'value':1},
      {'path':'.COOLING.ESSENTIAL', 'type':'structure'},
      {'path':'.COOLING.ESSENTIAL:PV_NAME', 'type':'text', 'value':'COOLING:ESSENTIAL'},
      {'path':'.COOLING.ESSENTIAL:VAL', 'type':'numeric', 'value':1},
      {'path':'.VACUUM', 'type':'structure'},
      {'path':'.VACUUM.IS_MASTER', 'type':'structure'},
      {'path':'.VACUUM.IS_MASTER:PV_NAME', 'type':'text', 'value':'VACUUM:IS_MASTER'},
      {'path':'.VACUUM.IS_MASTER:VAL', 'type':'numeric', 'value':0},
      {'path':'.VACUUM.CHILD_MASK', 'type':'structure'},
      {'path':'.VACUUM.CHILD_MASK:PV_NAME', 'type':'text', 'value':'VACUUM:CHILDREN_MASK'},
      {'path':'.VACUUM.CHILD_MASK:VAL', 'type':'numeric', 'value':1},
      {'path':'.VACUUM.ESSENTIAL', 'type':'structure'},
      {'path':'.VACUUM.ESSENTIAL:PV_NAME', 'type':'text', 'value':'VACUUM:ESSENTIAL'},
      {'path':'.VACUUM.ESSENTIAL:VAL', 'type':'numeric', 'value':1},
      {'path':'.POWER22', 'type':'structure'},
      {'path':'.POWER22.IS_MASTER', 'type':'structure'},
      {'path':'.POWER22.IS_MASTER:PV_NAME', 'type':'text', 'value':'POWER22:IS_MASTER'},
      {'path':'.POWER22.IS_MASTER:VAL', 'type':'numeric', 'value':0},
      {'path':'.POWER22.CHILD_MASK', 'type':'structure'},
      {'path':'.POWER22.CHILD_MASK:PV_NAME', 'type':'text', 'value':'POWER22:CHILDREN_MASK'},
      {'path':'.POWER22.CHILD_MASK:VAL', 'type':'numeric', 'value':1},
      {'path':'.POWER22.ESSENTIAL', 'type':'structure'},
      {'path':'.POWER22.ESSENTIAL:PV_NAME', 'type':'text', 'value':'POWER22:ESSENTIAL'},
      {'path':'.POWER22.ESSENTIAL:VAL', 'type':'numeric', 'value':1},
      {'path':'.POWER', 'type':'structure'},
      {'path':'.POWER.IS_MASTER', 'type':'structure'},
      {'path':'.POWER.IS_MASTER:PV_NAME', 'type':'text', 'value':'POWER:IS_MASTER'},
      {'path':'.POWER.IS_MASTER:VAL', 'type':'numeric', 'value':0},
      {'path':'.POWER.CHILD_MASK', 'type':'structure'},
      {'path':'.POWER.CHILD_MASK:PV_NAME', 'type':'text', 'value':'POWER:CHILDREN_MASK'},
      {'path':'.POWER.CHILD_MASK:VAL', 'type':'numeric', 'value':15},
      {'path':'.POWER.ESSENTIAL', 'type':'structure'},
      {'path':'.POWER.ESSENTIAL:PV_NAME', 'type':'text', 'value':'POWER:ESSENTIAL'},
      {'path':'.POWER.ESSENTIAL:VAL', 'type':'numeric', 'value':1},
      {'path':'.AGPS', 'type':'structure'},
      {'path':'.AGPS.IS_MASTER', 'type':'structure'},
      {'path':'.AGPS.IS_MASTER:PV_NAME', 'type':'text', 'value':'AGPS:IS_MASTER'},
      {'path':'.AGPS.IS_MASTER:VAL', 'type':'numeric', 'value':0},
      {'path':'.AGPS.CHILD_MASK', 'type':'structure'},
      {'path':'.AGPS.CHILD_MASK:PV_NAME', 'type':'text', 'value':'AGPS:CHILDREN_MASK'},
      {'path':'.AGPS.CHILD_MASK:VAL', 'type':'numeric', 'value':1},
      {'path':'.AGPS.ESSENTIAL', 'type':'structure'},
      {'path':'.AGPS.ESSENTIAL:PV_NAME', 'type':'text', 'value':'AGPS:ESSENTIAL'},
      {'path':'.AGPS.ESSENTIAL:VAL', 'type':'numeric', 'value':1},
      {'path':'.ISEPS', 'type':'structure'},
      {'path':'.ISEPS.IS_MASTER', 'type':'structure'},
      {'path':'.ISEPS.IS_MASTER:PV_NAME', 'type':'text', 'value':'ISEPS:IS_MASTER'},
      {'path':'.ISEPS.IS_MASTER:VAL', 'type':'numeric', 'value':0},
      {'path':'.ISEPS.CHILD_MASK', 'type':'structure'},
      {'path':'.ISEPS.CHILD_MASK:PV_NAME', 'type':'text', 'value':'ISEPS:CHILDREN_MASK'},
      {'path':'.ISEPS.CHILD_MASK:VAL', 'type':'numeric', 'value':1},
      {'path':'.ISEPS.ESSENTIAL', 'type':'structure'},
      {'path':'.ISEPS.ESSENTIAL:PV_NAME', 'type':'text', 'value':'ISEPS:ESSENTIAL'},
      {'path':'.ISEPS.ESSENTIAL:VAL', 'type':'numeric', 'value':1},
      {'path':'.CAESIUM', 'type':'structure'},
      {'path':'.CAESIUM.IS_MASTER', 'type':'structure'},
      {'path':'.CAESIUM.IS_MASTER:PV_NAME', 'type':'text', 'value':'CAESIUM:IS_MASTER'},
      {'path':'.CAESIUM.IS_MASTER:VAL', 'type':'numeric', 'value':0},
      {'path':'.CAESIUM.CHILD_MASK', 'type':'structure'},
      {'path':'.CAESIUM.CHILD_MASK:PV_NAME', 'type':'text', 'value':'CAESIUM:CHILDREN_MASK'},
      {'path':'.CAESIUM.CHILD_MASK:VAL', 'type':'numeric', 'value':1},
      {'path':'.CAESIUM.ESSENTIAL', 'type':'structure'},
      {'path':'.CAESIUM.ESSENTIAL:PV_NAME', 'type':'text', 'value':'CAESIUM:ESSENTIAL'},
      {'path':'.CAESIUM.ESSENTIAL:VAL', 'type':'numeric', 'value':1},
      {'path':'.ELECTRIC', 'type':'structure'},
      {'path':'.ELECTRIC.IS_MASTER', 'type':'structure'},
      {'path':'.ELECTRIC.IS_MASTER:PV_NAME', 'type':'text', 'value':'ELECTRIC:IS_MASTER'},
      {'path':'.ELECTRIC.IS_MASTER:VAL', 'type':'numeric', 'value':0},
      {'path':'.ELECTRIC.CHILD_MASK', 'type':'structure'},
      {'path':'.ELECTRIC.CHILD_MASK:PV_NAME', 'type':'text', 'value':'ELECTRIC:CHILDREN_MASK'},
      {'path':'.ELECTRIC.CHILD_MASK:VAL', 'type':'numeric', 'value':1},      
      {'path':'.ELECTRIC.ESSENTIAL', 'type':'structure'},
      {'path':'.ELECTRIC.ESSENTIAL:PV_NAME', 'type':'text', 'value':'ELECTRIC:ESSENTIAL'},
      {'path':'.ELECTRIC.ESSENTIAL:VAL', 'type':'numeric', 'value':1},
      {'path':'.SOURCE', 'type':'structure'},
      {'path':'.SOURCE.IS_MASTER', 'type':'structure'},
      {'path':'.SOURCE.IS_MASTER:PV_NAME', 'type':'text', 'value':'SOURCE:IS_MASTER'},
      {'path':'.SOURCE.IS_MASTER:VAL', 'type':'numeric', 'value':0},
      {'path':'.SOURCE.CHILD_MASK', 'type':'structure'},
      {'path':'.SOURCE.CHILD_MASK:PV_NAME', 'type':'text', 'value':'SOURCE:CHILDREN_MASK'},
      {'path':'.SOURCE.CHILD_MASK:VAL', 'type':'numeric', 'value':127},
      {'path':'.SOURCE.ESSENTIAL', 'type':'structure'},
      {'path':'.SOURCE.ESSENTIAL:PV_NAME', 'type':'text', 'value':'SOURCE:ESSENTIAL'},
      {'path':'.SOURCE.ESSENTIAL:VAL', 'type':'numeric', 'value':1},
      {'path':'.SPECTRO', 'type':'structure'},
      {'path':'.SPECTRO.IS_MASTER', 'type':'structure'},
      {'path':'.SPECTRO.IS_MASTER:PV_NAME', 'type':'text', 'value':'SPECTRO:IS_MASTER'},
      {'path':'.SPECTRO.IS_MASTER:VAL', 'type':'numeric', 'value':0},
      {'path':'.SPECTRO.CHILD_MASK', 'type':'structure'},
      {'path':'.SPECTRO.CHILD_MASK:PV_NAME', 'type':'text', 'value':'SPECTRO:CHILDREN_MASK'},
      {'path':'.SPECTRO.CHILD_MASK:VAL', 'type':'numeric', 'value':127},
      {'path':'.SPECTRO.ESSENTIAL', 'type':'structure'},
      {'path':'.SPECTRO.ESSENTIAL:PV_NAME', 'type':'text', 'value':'SPECTRO:ESSENTIAL'},
      {'path':'.SPECTRO.ESSENTIAL:VAL', 'type':'numeric', 'value':1},
      {'path':'.THERMO_S', 'type':'structure'},
      {'path':'.THERMO_S.IS_MASTER', 'type':'structure'},
      {'path':'.THERMO_S.IS_MASTER:PV_NAME', 'type':'text', 'value':'THERMO_S:IS_MASTER'},
      {'path':'.THERMO_S.IS_MASTER:VAL', 'type':'numeric', 'value':0},
      {'path':'.THERMO_S.CHILD_MASK', 'type':'structure'},
      {'path':'.THERMO_S.CHILD_MASK:PV_NAME', 'type':'text', 'value':'THERMO_S:CHILDREN_MASK'},
      {'path':'.THERMO_S.CHILD_MASK:VAL', 'type':'numeric', 'value':1},
      {'path':'.THERMO_S.ESSENTIAL', 'type':'structure'},
      {'path':'.THERMO_S.ESSENTIAL:PV_NAME', 'type':'text', 'value':'THERMO_S:ESSENTIAL'},
      {'path':'.THERMO_S.ESSENTIAL:VAL', 'type':'numeric', 'value':1},
      {'path':'.THERMO_V', 'type':'structure'},
      {'path':'.THERMO_V.IS_MASTER', 'type':'structure'},
      {'path':'.THERMO_V.IS_MASTER:PV_NAME', 'type':'text', 'value':'THERMO_V:IS_MASTER'},
      {'path':'.THERMO_V.IS_MASTER:VAL', 'type':'numeric', 'value':0},
      {'path':'.THERMO_V.CHILD_MASK', 'type':'structure'},
      {'path':'.THERMO_V.CHILD_MASK:PV_NAME', 'type':'text', 'value':'THERMO_V:CHILDREN_MASK'},
      {'path':'.THERMO_V.CHILD_MASK:VAL', 'type':'numeric', 'value':1},
      {'path':'.THERMO_V.ESSENTIAL', 'type':'structure'},
      {'path':'.THERMO_V.ESSENTIAL:PV_NAME', 'type':'text', 'value':'THERMO_V:ESSENTIAL'},
      {'path':'.THERMO_V.ESSENTIAL:VAL', 'type':'numeric', 'value':1},
      {'path':'.THERMO_D', 'type':'structure'},
      {'path':'.THERMO_D.IS_MASTER', 'type':'structure'},
      {'path':'.THERMO_D.IS_MASTER:PV_NAME', 'type':'text', 'value':'THERMO_D:IS_MASTER'},
      {'path':'.THERMO_D.IS_MASTER:VAL', 'type':'numeric', 'value':0},
      {'path':'.THERMO_D.CHILD_MASK', 'type':'structure'},
      {'path':'.THERMO_D.CHILD_MASK:PV_NAME', 'type':'text', 'value':'THERMO_D:CHILDREN_MASK'},
      {'path':'.THERMO_D.CHILD_MASK:VAL', 'type':'numeric', 'value':1},
      {'path':'.THERMO_D.ESSENTIAL', 'type':'structure'},
      {'path':'.THERMO_D.ESSENTIAL:PV_NAME', 'type':'text', 'value':'THERMO_D:ESSENTIAL'},
      {'path':'.THERMO_D.ESSENTIAL:VAL', 'type':'numeric', 'value':1},
      {'path':'.THERMO_G', 'type':'structure'},
      {'path':'.THERMO_G.IS_MASTER', 'type':'structure'},
      {'path':'.THERMO_G.IS_MASTER:PV_NAME', 'type':'text', 'value':'THERMO_G:IS_MASTER'},
      {'path':'.THERMO_G.IS_MASTER:VAL', 'type':'numeric', 'value':0},
      {'path':'.THERMO_G.CHILD_MASK', 'type':'structure'},
      {'path':'.THERMO_G.CHILD_MASK:PV_NAME', 'type':'text', 'value':'THERMO_G:CHILDREN_MASK'},
      {'path':'.THERMO_G.CHILD_MASK:VAL', 'type':'numeric', 'value':1},
      {'path':'.THERMO_G.ESSENTIAL', 'type':'structure'},
      {'path':'.THERMO_G.ESSENTIAL:PV_NAME', 'type':'text', 'value':'THERMO_G:ESSENTIAL'},
      {'path':'.THERMO_G.ESSENTIAL:VAL', 'type':'numeric', 'value':1},
      {'path':'.CALOR', 'type':'structure'},
      {'path':'.CALOR.IS_MASTER', 'type':'structure'},
      {'path':'.CALOR.IS_MASTER:PV_NAME', 'type':'text', 'value':'CALOR:IS_MASTER'},
      {'path':'.CALOR.IS_MASTER:VAL', 'type':'numeric', 'value':0},
      {'path':'.CALOR.CHILD_MASK', 'type':'structure'},
      {'path':'.CALOR.CHILD_MASK:PV_NAME', 'type':'text', 'value':'CALOR:CHILDREN_MASK'},
      {'path':'.CALOR.CHILD_MASK:VAL', 'type':'numeric', 'value':1},
      {'path':'.CALOR.ESSENTIAL', 'type':'structure'},
      {'path':'.CALOR.ESSENTIAL:PV_NAME', 'type':'text', 'value':'CALOR:ESSENTIAL'},
      {'path':'.CALOR.ESSENTIAL:VAL', 'type':'numeric', 'value':1},
      {'path':'.SOURCE_I', 'type':'structure'},
      {'path':'.SOURCE_I.IS_MASTER', 'type':'structure'},
      {'path':'.SOURCE_I.IS_MASTER:PV_NAME', 'type':'text', 'value':'SOURCE_I:IS_MASTER'},
      {'path':'.SOURCE_I.IS_MASTER:VAL', 'type':'numeric', 'value':0},
      {'path':'.SOURCE_I.CHILD_MASK', 'type':'structure'},
      {'path':'.SOURCE_I.CHILD_MASK:PV_NAME', 'type':'text', 'value':'SOURCE_I:CHILDREN_MASK'},
      {'path':'.SOURCE_I.CHILD_MASK:VAL', 'type':'numeric', 'value':1},
      {'path':'.SOURCE_I.ESSENTIAL', 'type':'structure'},
      {'path':'.SOURCE_I.ESSENTIAL:PV_NAME', 'type':'text', 'value':'SOURCE_I:ESSENTIAL'},
      {'path':'.SOURCE_I.ESSENTIAL:VAL', 'type':'numeric', 'value':1},
      {'path':'.DIAG', 'type':'structure'},
      {'path':'.DIAG.IS_MASTER', 'type':'structure'},
      {'path':'.DIAG.IS_MASTER:PV_NAME', 'type':'text', 'value':'DIAG:IS_MASTER'},
      {'path':'.DIAG.IS_MASTER:VAL', 'type':'numeric', 'value':0},
      {'path':'.DIAG.CHILD_MASK', 'type':'structure'},
      {'path':'.DIAG.CHILD_MASK:PV_NAME', 'type':'text', 'value':'DIAG:CHILDREN_MASK'},
      {'path':'.DIAG.CHILD_MASK:VAL', 'type':'numeric', 'value':127},
      {'path':'.DIAG.ESSENTIAL', 'type':'structure'},
      {'path':'.DIAG.ESSENTIAL:PV_NAME', 'type':'text', 'value':'DIAG:ESSENTIAL'},
      {'path':'.DIAG.ESSENTIAL:VAL', 'type':'numeric', 'value':1},
      {'path':'.SPECTRO_B', 'type':'structure'},
      {'path':'.SPECTRO_B.IS_MASTER', 'type':'structure'},
      {'path':'.SPECTRO_B.IS_MASTER:PV_NAME', 'type':'text', 'value':'SPECTRO_B:IS_MASTER'},
      {'path':'.SPECTRO_B.IS_MASTER:VAL', 'type':'numeric', 'value':0},
      {'path':'.SPECTRO_B.CHILD_MASK', 'type':'structure'},
      {'path':'.SPECTRO_B.CHILD_MASK:PV_NAME', 'type':'text', 'value':'SPECTRO_B:CHILDREN_MASK'},
      {'path':'.SPECTRO_B.CHILD_MASK:VAL', 'type':'numeric', 'value':1},
      {'path':'.SPECTRO_B.ESSENTIAL', 'type':'structure'},
      {'path':'.SPECTRO_B.ESSENTIAL:PV_NAME', 'type':'text', 'value':'SPECTRO_B:ESSENTIAL'},
      {'path':'.SPECTRO_B.ESSENTIAL:VAL', 'type':'numeric', 'value':1},
      {'path':'.CAVITY_R', 'type':'structure'},
      {'path':'.CAVITY_R.IS_MASTER', 'type':'structure'},
      {'path':'.CAVITY_R.IS_MASTER:PV_NAME', 'type':'text', 'value':'CAVITY_R:IS_MASTER'},
      {'path':'.CAVITY_R.IS_MASTER:VAL', 'type':'numeric', 'value':0},
      {'path':'.CAVITY_R.CHILD_MASK', 'type':'structure'},
      {'path':'.CAVITY_R.CHILD_MASK:PV_NAME', 'type':'text', 'value':'CAVITY_R:CHILDREN_MASK'},
      {'path':'.CAVITY_R.CHILD_MASK:VAL', 'type':'numeric', 'value':1},
      {'path':'.CAVITY_R.ESSENTIAL', 'type':'structure'},
      {'path':'.CAVITY_R.ESSENTIAL:PV_NAME', 'type':'text', 'value':'CAVITY_R:ESSENTIAL'},
      {'path':'.CAVITY_R.ESSENTIAL:VAL', 'type':'numeric', 'value':1},
      {'path':'.DIAG_IMG', 'type':'structure'},
      {'path':'.DIAG_IMG.IS_MASTER', 'type':'structure'},
      {'path':'.DIAG_IMG.IS_MASTER:PV_NAME', 'type':'text', 'value':'DIAG_IMG:IS_MASTER'},
      {'path':'.DIAG_IMG.IS_MASTER:VAL', 'type':'numeric', 'value':0},
      {'path':'.DIAG_IMG.CHILD_MASK', 'type':'structure'},
      {'path':'.DIAG_IMG.CHILD_MASK:PV_NAME', 'type':'text', 'value':'DIAG_IMG:CHILDREN_MASK'},
      {'path':'.DIAG_IMG.CHILD_MASK:VAL', 'type':'numeric', 'value':1},
      {'path':'.DIAG_IMG.ESSENTIAL', 'type':'structure'},
      {'path':'.DIAG_IMG.ESSENTIAL:PV_NAME', 'type':'text', 'value':'DIAG_IMG:ESSENTIAL'},
      {'path':'.DIAG_IMG.ESSENTIAL:VAL', 'type':'numeric', 'value':1},
      {'path':'.INSP_IMG', 'type':'structure'},
      {'path':'.INSP_IMG.IS_MASTER', 'type':'structure'},
      {'path':'.INSP_IMG.IS_MASTER:PV_NAME', 'type':'text', 'value':'INSP_IMG:IS_MASTER'},
      {'path':'.INSP_IMG.IS_MASTER:VAL', 'type':'numeric', 'value':0},
      {'path':'.INSP_IMG.CHILD_MASK', 'type':'structure'},
      {'path':'.INSP_IMG.CHILD_MASK:PV_NAME', 'type':'text', 'value':'INSP_IMG:CHILDREN_MASK'},
      {'path':'.INSP_IMG.CHILD_MASK:VAL', 'type':'numeric', 'value':1},
      {'path':'.INSP_IMG.ESSENTIAL', 'type':'structure'},
      {'path':'.INSP_IMG.ESSENTIAL:PV_NAME', 'type':'text', 'value':'INSP_IMG:ESSENTIAL'},
      {'path':'.INSP_IMG.ESSENTIAL:VAL', 'type':'numeric', 'value':1},
      {'path':'.NEUTRON', 'type':'structure'},
      {'path':'.NEUTRON.IS_MASTER', 'type':'structure'},
      {'path':'.NEUTRON.IS_MASTER:PV_NAME', 'type':'text', 'value':'NEUTRON:IS_MASTER'},
      {'path':'.NEUTRON.IS_MASTER:VAL', 'type':'numeric', 'value':0},
      {'path':'.NEUTRON.CHILD_MASK', 'type':'structure'},
      {'path':'.NEUTRON.CHILD_MASK:PV_NAME', 'type':'text', 'value':'NEUTRON:CHILDREN_MASK'},
      {'path':'.NEUTRON.CHILD_MASK:VAL', 'type':'numeric', 'value':1},
      {'path':'.NEUTRON.ESSENTIAL', 'type':'structure'},
      {'path':'.NEUTRON.ESSENTIAL:PV_NAME', 'type':'text', 'value':'NEUTRON:ESSENTIAL'},
      {'path':'.NEUTRON.ESSENTIAL:VAL', 'type':'numeric', 'value':1},
      {'path':'.EL_PROBE', 'type':'structure'},
      {'path':'.EL_PROBE.IS_MASTER', 'type':'structure'},
      {'path':'.EL_PROBE.IS_MASTER:PV_NAME', 'type':'text', 'value':'EL_PROBE:IS_MASTER'},
      {'path':'.EL_PROBE.IS_MASTER:VAL', 'type':'numeric', 'value':0},
      {'path':'.EL_PROBE.CHILD_MASK', 'type':'structure'},
      {'path':'.EL_PROBE.CHILD_MASK:PV_NAME', 'type':'text', 'value':'EL_PROBE:CHILDREN_MASK'},
      {'path':'.EL_PROBE.CHILD_MASK:VAL', 'type':'numeric', 'value':1},
      {'path':'.EL_PROBE.ESSENTIAL', 'type':'structure'},
      {'path':'.EL_PROBE.ESSENTIAL:PV_NAME', 'type':'text', 'value':'EL_PROBE:ESSENTIAL'},
      {'path':'.EL_PROBE.ESSENTIAL:VAL', 'type':'numeric', 'value':1},
      {'path':'.TOMO', 'type':'structure'},
      {'path':'.TOMO.IS_MASTER', 'type':'structure'},
      {'path':'.TOMO.IS_MASTER:PV_NAME', 'type':'text', 'value':'TOMO:IS_MASTER'},
      {'path':'.TOMO.IS_MASTER:VAL', 'type':'numeric', 'value':0},
      {'path':'.TOMO.CHILD_MASK', 'type':'structure'},
      {'path':'.TOMO.CHILD_MASK:PV_NAME', 'type':'text', 'value':'TOMO:CHILDREN_MASK'},
      {'path':'.TOMO.CHILD_MASK:VAL', 'type':'numeric', 'value':1},
      {'path':'.TOMO.ESSENTIAL', 'type':'structure'},
      {'path':'.TOMO.ESSENTIAL:PV_NAME', 'type':'text', 'value':'TOMO:ESSENTIAL'},
      {'path':'.TOMO.ESSENTIAL:VAL', 'type':'numeric', 'value':1},
      {'path':'.INTERLOCK', 'type':'structure'},
      {'path':'.INTERLOCK.IS_MASTER', 'type':'structure'},
      {'path':'.INTERLOCK.IS_MASTER:PV_NAME', 'type':'text', 'value':'INTERLOCK:IS_MASTER'},
      {'path':'.INTERLOCK.IS_MASTER:VAL', 'type':'numeric', 'value':0},
      {'path':'.INTERLOCK.CHILD_MASK', 'type':'structure'},
      {'path':'.INTERLOCK.CHILD_MASK:PV_NAME', 'type':'text', 'value':'INTERLOCK:CHILDREN_MASK'},
      {'path':'.INTERLOCK.CHILD_MASK:VAL', 'type':'numeric', 'value':3},
      {'path':'.INTERLOCK.ESSENTIAL', 'type':'structure'},
      {'path':'.INTERLOCK.ESSENTIAL:PV_NAME', 'type':'text', 'value':'INTERLOCK:ESSENTIAL'},
      {'path':'.INTERLOCK.ESSENTIAL:VAL', 'type':'numeric', 'value':1},
      {'path':'.INT_SYS', 'type':'structure'},
      {'path':'.INT_SYS.IS_MASTER', 'type':'structure'},
      {'path':'.INT_SYS.IS_MASTER:PV_NAME', 'type':'text', 'value':'INT_SYS:IS_MASTER'},
      {'path':'.INT_SYS.IS_MASTER:VAL', 'type':'numeric', 'value':0},
      {'path':'.INT_SYS.CHILD_MASK', 'type':'structure'},
      {'path':'.INT_SYS.CHILD_MASK:PV_NAME', 'type':'text', 'value':'INT_SYS:CHILDREN_MASK'},
      {'path':'.INT_SYS.CHILD_MASK:VAL', 'type':'numeric', 'value':1},
      {'path':'.INT_SYS.ESSENTIAL', 'type':'structure'},
      {'path':'.INT_SYS.ESSENTIAL:PV_NAME', 'type':'text', 'value':'INT_SYS:ESSENTIAL'},
      {'path':'.INT_SYS.ESSENTIAL:VAL', 'type':'numeric', 'value':1},
      {'path':'.SAFE_SYS', 'type':'structure'},
      {'path':'.SAFE_SYS.IS_MASTER', 'type':'structure'},
      {'path':'.SAFE_SYS.IS_MASTER:PV_NAME', 'type':'text', 'value':'SAFE_SYS:IS_MASTER'},
      {'path':'.SAFE_SYS.IS_MASTER:VAL', 'type':'numeric', 'value':0},
      {'path':'.SAFE_SYS.CHILD_MASK', 'type':'structure'},
      {'path':'.SAFE_SYS.CHILD_MASK:PV_NAME', 'type':'text', 'value':'SAFE_SYS:CHILDREN_MASK'},
      {'path':'.SAFE_SYS.CHILD_MASK:VAL', 'type':'numeric', 'value':1},
      {'path':'.SAFE_SYS.ESSENTIAL', 'type':'structure'},
      {'path':'.SAFE_SYS.ESSENTIAL:PV_NAME', 'type':'text', 'value':'SAFE_SYS:ESSENTIAL'},
      {'path':'.SAFE_SYS.ESSENTIAL:VAL', 'type':'numeric', 'value':1}]
    print 'SpiderStateMachine 2'
