#! /bin/sh

PATH=$PATH:/bin:/usr/bin:/usr/local/bin

if [ -z "$CVSROOT" ]
then
   echo "You must set environment variable CVSROOT to the new repository"
   exit 1
fi

echo "Changing stored CVSROOT to - $CVSROOT"
find . -name Root -print | while read file
do
     dir=`dirname $file`
     dir=`dirname $dir`
     echo "     fixing directory $dir"
     echo $CVSROOT > $file
done
