CFLAGS = -c -I../include -I. -g -migrate -U__DECC -assume noaligned_objects

OBJECTS = \
	MdsGet1DxA.o \
	MdsGet1DxS.o \
	MdsXdRoutines.o \
	MdsCmprs.o \
	MdsPk.o \
	librtl.o

libMdsShr.so : libMdsShr.a
	$(LD) -o $@ -shared -all $< -lc -lm -lots

libMdsShr.a : $(OBJECTS)
	$(AR) $(ARFLAGS) $@ *.o

