#!/bin/sh
#
cd $HOME
rev=1.2
mkdir mdskit
cd mdskit
cvs -d :pserver:`whoami`@www.mdsplus.org:/mdsplus/repos -Q checkout mdsplus
if (test "$GLOBUS_LOCATION" = "")
then
  globus-kit=-globus
else
  globus-kit=
fi
mv mdsplus mdsplus$globus-kit-$rev
find . -name CVS -exec rm -Rf {} \; 2> /dev/null
tar cf $HOME/rpm/SOURCES/mdsplus-$rev.tar mdsplus$globus-kit-$rev 
gzip -f $HOME/rpm/SOURCES/mdsplus-$rev.tar
rpm -ba mdsplus$globus_kit-$rev/rpm/mdsplus$globus-kit.rpm.spec
cd $HOME
rm -Rf mdskit
