#!/bin/sh
#
rev=1.2
cd $HOME
if (test "$GLOBUS_LOCATION" = "")
then
  globuskit=
else
  globuskit=-globus
fi
mkdir mdskit$globuskit
cd mdskit$globuskit
cvs -d :pserver:`whoami`@www.mdsplus.org:/mdsplus/repos -Q checkout mdsplus
mv mdsplus mdsplus$globuskit-$rev
find . -name CVS -exec rm -Rf {} \; 2> /dev/null
tar cf $HOME/rpm/SOURCES/mdsplus$globuskit-$rev.tar mdsplus$globuskit-$rev 
gzip -f $HOME/rpm/SOURCES/mdsplus$globuskit-$rev.tar
rpm -ba mdsplus$globuskit-$rev/rpm/mdsplus$globuskit.rpm.spec
cd $HOME
rm -Rf mdskit$globuskit
