#!/bin/sh
case "`uname`" in
Linux*)
#
# Linux post install script
#
# Add /usr/local/mdsplus/lib to /etc/ld.so.conf
#
echo Configuring mdsplus libraries
if grep "^/usr/local/mdsplus/lib" /etc/ld.so.conf > /dev/null
then
	true
else
	echo "/usr/local/mdsplus/lib" >> /etc/ld.so.conf
fi
/sbin/ldconfig
#
# Add /usr/local/mdsplus/man to manpath
#
echo Configuring mdsplus man pages
if grep "^MANPATH /usr/local/mdsplus/man" /etc/man.config > /dev/null
then
	true
else
	echo "MANPATH /usr/local/mdsplus/man" >> /etc/man.config
fi
#
# Add mdsip to services
#
echo Adding mdsip MDSplus data server
if grep "^mdsip " /etc/services >/dev/null
then
        true
else
        echo "mdsip    8000/tcp # Added by package mdsplus" >> /etc/services
fi
#
# Add mdsipd to inetd.conf
#
mkdirhier /var/log/mdsplus/mdsipd
if grep "^mdsip " /etc/inetd.conf > /dev/null
then
  true
else
  echo "mdsip stream	tcp	nowait root /usr/local/mdsplus/bin/mdsipd mdsipd mdsip /var/log/mdsplus/mdsipd" >> /etc/inetd.conf
  kill -HUP `/sbin/pidof inetd`
fi
echo Adding MDSplus login scripts
ln -s /usr/local/mdsplus/etc/profile.d/mdsplus.* /etc/profile.d/
echo Creating sample /etc/mdsip.hosts file for mdsip server to user mapping
if [ -r /etc/mdsip.hosts ]; then
  cp /usr/local/mdsplus/etc/mdsip.hosts /etc/
fi
;;
OSF1*)
#
# Compaq TruUNIX post install script
#
# Put symlinks in /usr/local/lib to all MDSplus shared libraries
#
echo Configuring mdsplus libraries
ln -sf /usr/local/mdsplus/lib/*.so /usr/local/lib
#
# Put symlinks in /usr/local/man to all MDSplus man pages
#
echo Configuring mdsplus man pages
if [ ! -r /usr/local/man ]; then
mkdir /usr/local/man
mkdir /usr/local/man/man1
mkdir /usr/local/man/man5
mkdir /usr/local/man/man8
chmod -R 755 /usr/local/man
else
if [ ! -r /usr/local/man/man1 ]; then
mkdir /usr/local/man/man1
chmod 755 /usr/local/man/man1
fi
if [ ! -r /usr/local/man/man5 ]; then
mkdir /usr/local/man/man5
chmod 755 /usr/local/man/man5
fi
if [ ! -r /usr/local/man/man8 ]; then
mkdir /usr/local/man/man8
chmod 755 /usr/local/man/man8
fi
fi
ln -sf /usr/local/mdsplus/man/man1/*.gz /usr/local/man/man1
ln -sf /usr/local/mdsplus/man/man5/*.gz /usr/local/man/man5
ln -sf /usr/local/mdsplus/man/man8/*.gz /usr/local/man/man8
#
# Add mdsip to services
#
echo Adding mdsip MDSplus data server
if grep "^mdsip " /etc/services >/dev/null
then
        true
else
        echo "mdsip    8000/tcp # Added by package mdsplus" >> /etc/services
fi
#
# Add mdsipd to inetd.conf
#
/usr/bin/X11/mkdirhier /var/log/mdsplus/mdsipd
if grep "^mdsip " /etc/inetd.conf > /dev/null
then
  true
else
  echo "mdsip stream	tcp	nowait root /usr/local/mdsplus/bin/mdsipd mdsipd mdsip /var/log/mdsplus/mdsipd" >> /etc/inetd.conf
  kill -HUP `/bin/ps -e -o pid -o command | /bin/grep /usr/sbin/inetd | /bin/grep -v grep | /bin/awk '{print $1}'`
fi
echo Adding MDSplus login scripts
if grep "^. /usr/local/mdsplus/etc/profile.d/mdsplus.sh" /etc/profile > /dev/null
then
  true
else
  echo ". /usr/local/mdsplus/etc/profile.d/mdsplus.sh" >> /etc/profile
fi
if grep "^source /usr/local/mdsplus/etc/profile.d/mdsplus.csh" /etc/csh.login > /dev/null
then
  true
else
  echo "source /usr/local/mdsplus/etc/profile.d/mdsplus.csh" >> /etc/csh.login
fi
echo Creating sample /etc/mdsip.hosts file for mdsip server to user mapping
if [ -r /etc/mdsip.hosts ]; then 
  cp /usr/local/mdsplus/etc/mdsip.hosts /etc/ 
fi
;;
SunOS*)
#
# SunOS post install script
#
# Put symlinks in /usr/local/lib to all MDSplus shared libraries
#
echo Configuring mdsplus libraries
ln -sf /usr/local/mdsplus/lib/*.so /usr/local/lib
#
# Put symlinks in /usr/local/man to all MDSplus man pages
#
echo Configuring mdsplus man pages
if [ ! -r /usr/local/man ]; then
mkdir /usr/local/man
mkdir /usr/local/man/man1
mkdir /usr/local/man/man5
mkdir /usr/local/man/man8
chmod -R 755 /usr/local/man
else
if [ ! -r /usr/local/man/man1 ]; then
mkdir /usr/local/man/man1
chmod 755 /usr/local/man/man1
fi
if [ ! -r /usr/local/man/man5 ]; then
mkdir /usr/local/man/man5
chmod 755 /usr/local/man/man5
fi
if [ ! -r /usr/local/man/man8 ]; then
mkdir /usr/local/man/man8
chmod 755 /usr/local/man/man8
fi
fi
ln -sf /usr/local/mdsplus/man/man1/*.gz /usr/local/man/man1
ln -sf /usr/local/mdsplus/man/man5/*.gz /usr/local/man/man5
ln -sf /usr/local/mdsplus/man/man8/*.gz /usr/local/man/man8
#
# Add mdsip to services
#
echo Adding mdsip MDSplus data server
if grep "^mdsip " /etc/services >/dev/null
then
        true
else
        echo "mdsip    8000/tcp # Added by package mdsplus" >> /etc/services
fi
#
# Add mdsipd to inetd.conf
#
/usr/bin/X11/mkdirhier /var/log/mdsplus/mdsipd
if grep "^mdsip " /etc/inetd.conf > /dev/null
then
  true
else
  echo "mdsip stream	tcp	nowait root /usr/local/mdsplus/bin/mdsipd mdsipd mdsip /var/log/mdsplus/mdsipd" >> /etc/inetd.conf
  kill -HUP `/bin/ps -e -o pid -o command | /bin/grep /usr/sbin/inetd | /bin/grep -v grep | /bin/awk '{print $1}'`
fi
echo Adding MDSplus login scripts
if grep "^. /usr/local/mdsplus/etc/profile.d/mdsplus.sh" /etc/profile > /dev/null
then
  true
else
  echo ". /usr/local/mdsplus/etc/profile.d/mdsplus.sh" >> /etc/profile
fi
if grep "^source /usr/local/mdsplus/etc/profile.d/mdsplus.csh" /etc/csh.login > /dev/null
then
  true
else
  echo "source /usr/local/mdsplus/etc/profile.d/mdsplus.csh" >> /etc/csh.login
fi
echo Creating sample /etc/mdsip.hosts file for mdsip server to user mapping
if [ -r /etc/mdsip.hosts ]; then 
  cp /usr/local/mdsplus/etc/mdsip.hosts /etc/ 
fi
;;
esac
cp /usr/local/mdsplus/rpm/post_uninstall_script /usr/local/mdsplus_post_uninstall_script
