#!/bin/sh
if (test "$MDSPLUS_DIR" = "")
then
  MDSPLUS_DIR=/usr/local/mdsplus
  if ( test -r /etc/.mdsplus_dir )
  then
    MDSPLUS_DIR=`/bin/cat /etc/.mdsplus_dir`
  fi
fi
if ( test -L /etc/profile.d/mdsplus.csh ); then
  rm -f /etc/profile.d/mdsplus.csh
else
  /bin/cp /etc/csh.login /etc/csh.login.before_mdsplus_removal
  /bin/grep -v "^source $MDSPLUS_DIR/etc/profile.d/mdsplus.csh" /etc/csh.login.before_mdsplus_removal > /etc/csh.login
fi
if ( test -L /etc/profile.d/mdsplus.sh ); then
  rm -f /etc/profile.d/mdsplus.sh
else
  /bin/cp /etc/profile /etc/profile.before_mdsplus_removal
  /bin/grep -v "^. $MDSPLUS_DIR/setup.sh" /etc/profile.before_mdsplus_removal > /etc/profile
fi
if ( test -L /etc/profile.d/globus.sh ); then
  rm -f /etc/profile.d/globus.sh
fi
if ( test -L /etc/profile.d/globus.csh ); then
  rm -f /etc/profile.d/globus.csh
fi
if ( test -r /etc/xinetd.d/globus-gatekeeper ); then
  rm -f /etc/xinetd.d/globus-gatekeeper
fi
if ( test -r /etc/xinetd.d/globus-gridftp ); then
  rm -f /etc/xinetd.d/globus-gridftp
fi
if ( test -r /etc/xinetd.d/mdsip ); then
  rm -f /etc/xinetd.d/mdsip
fi
if ( test -r /etc/xinetd.d/mdsips ); then
  rm -f /etc/xinetd.d/mdsips
fi
if (test -r $MDSPLUS_DIR/local/mdsplus_post_uninstall_script)
then
  rm $MDSPLUS_DIR/local/mdsplus_post_uninstall_script
fi
if (test -r /etc/.mdsplus_dir)
then
  rm -f /etc/.mdsplus_dir
fi
