#!/bin/sh
# Create a read-only disk image of the contents of a folder
#
# Usage: make-diskimage <image_file>
#                       <src_folder>
#                       <volume_name>
#

DMG_DIRNAME=`dirname $1`
DMG_DIR=`cd $DMG_DIRNAME; pwd`
DMG_NAME=`basename $1`
DMG_TEMP_NAME=${DMG_DIR}/rw.${DMG_NAME}
SRC_FOLDER=`cd $2; pwd`
VOLUME_NAME=$3
 
# Find the size of the folder contents
FOLDER_SIZE=`du -s $SRC_FOLDER | sed s/[^0-9].*//`
 
# Allow for partition table and other overhead (3%)
IMAGE_SIZE=$(($FOLDER_SIZE * 103/100))
# minimum size for an HFS+ partition is 4Mb
[ $IMAGE_SIZE -lt 8300 ] && IMAGE_SIZE=8300
 
echo FOLDER_SIZE=$FOLDER_SIZE
echo IMAGE_SIZE=$IMAGE_SIZE

# Create the image
echo "creating disk image"
hdiutil create -sectors $IMAGE_SIZE -fs HFS+ $DMG_TEMP_NAME -volname "${VOLUME_NAME}"
  

# mount it
echo "mounting disk image"
# `hdid -nomount rw.$DMG_NAME | grep "^/dev/disk.s2" | sed -e "s?^/dev/??" -e "s/[^0-9a-z].*//"`
DEV_NAME=`hdid $DMG_TEMP_NAME | sed 1q | cut -f1`
MOUNT_DIR=`hdid $DMG_TEMP_NAME | grep Apple_HFS | cut -f3`
echo $MOUNT_DIR 

# copy content
echo "copying content to disk image"
ditto --rsrc "$SRC_FOLDER" "$MOUNT_DIR"

# make the top window open itself on mount:
#open ${MOUNT_DIR}

# unmnount
echo "unmounting disk image"
hdiutil detach $DEV_NAME

# convert to read-only image
echo "converting disk image to read-only"
hdiutil convert $DMG_TEMP_NAME -format UDZO -imagekey zlib-level=9 -o ${DMG_DIR}/${DMG_NAME}
rm -f $DMG_TEMP_NAME

echo "internet enabling.."
hdiutil internet-enable -yes ${DMG_DIR}/${DMG_NAME} 

echo "disk image done"
