/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Data */

#ifndef _Included_Data
#define _Included_Data
#ifdef __cplusplus
extern "C" {
#endif
#undef Data_DTYPE_BU
#define Data_DTYPE_BU 2L
#undef Data_DTYPE_WU
#define Data_DTYPE_WU 3L
#undef Data_DTYPE_LU
#define Data_DTYPE_LU 4L
#undef Data_DTYPE_QU
#define Data_DTYPE_QU 5L
#undef Data_DTYPE_OU
#define Data_DTYPE_OU 25L
#undef Data_DTYPE_B
#define Data_DTYPE_B 6L
#undef Data_DTYPE_W
#define Data_DTYPE_W 7L
#undef Data_DTYPE_L
#define Data_DTYPE_L 8L
#undef Data_DTYPE_Q
#define Data_DTYPE_Q 9L
#undef Data_DTYPE_O
#define Data_DTYPE_O 26L
#undef Data_DTYPE_FLOAT
#define Data_DTYPE_FLOAT 52L
#undef Data_DTYPE_DOUBLE
#define Data_DTYPE_DOUBLE 53L
#undef Data_DTYPE_T
#define Data_DTYPE_T 14L
#undef Data_DTYPE_IDENT
#define Data_DTYPE_IDENT 191L
#undef Data_DTYPE_NID
#define Data_DTYPE_NID 192L
#undef Data_DTYPE_PATH
#define Data_DTYPE_PATH 193L
#undef Data_DTYPE_PARAM
#define Data_DTYPE_PARAM 194L
#undef Data_DTYPE_SIGNAL
#define Data_DTYPE_SIGNAL 195L
#undef Data_DTYPE_DIMENSION
#define Data_DTYPE_DIMENSION 196L
#undef Data_DTYPE_WINDOW
#define Data_DTYPE_WINDOW 197L
#undef Data_DTYPE_FUNCTION
#define Data_DTYPE_FUNCTION 199L
#undef Data_DTYPE_CONGLOM
#define Data_DTYPE_CONGLOM 200L
#undef Data_DTYPE_RANGE
#define Data_DTYPE_RANGE 201L
#undef Data_DTYPE_ACTION
#define Data_DTYPE_ACTION 202L
#undef Data_DTYPE_DISPATCH
#define Data_DTYPE_DISPATCH 203L
#undef Data_DTYPE_PROGRAM
#define Data_DTYPE_PROGRAM 204L
#undef Data_DTYPE_ROUTINE
#define Data_DTYPE_ROUTINE 205L
#undef Data_DTYPE_PROCEDURE
#define Data_DTYPE_PROCEDURE 206L
#undef Data_DTYPE_METHOD
#define Data_DTYPE_METHOD 207L
#undef Data_DTYPE_DEPENDENCY
#define Data_DTYPE_DEPENDENCY 208L
#undef Data_DTYPE_CONDITION
#define Data_DTYPE_CONDITION 209L
#undef Data_DTYPE_EVENT
#define Data_DTYPE_EVENT 210L
#undef Data_DTYPE_WITH_UNITS
#define Data_DTYPE_WITH_UNITS 211L
#undef Data_DTYPE_CALL
#define Data_DTYPE_CALL 212L
#undef Data_DTYPE_WITH_ERROR
#define Data_DTYPE_WITH_ERROR 213L
#undef Data_CLASS_S
#define Data_CLASS_S 1L
#undef Data_CLASS_D
#define Data_CLASS_D 2L
#undef Data_CLASS_A
#define Data_CLASS_A 4L
#undef Data_CLASS_R
#define Data_CLASS_R 194L
#undef Data_CLASS_APD
#define Data_CLASS_APD 196L
/*
 * Class:     Data
 * Method:    fromExpr
 * Signature: (Ljava/lang/String;)LData;
 */
JNIEXPORT jobject JNICALL Java_Data_fromExpr
  (JNIEnv *, jclass, jstring);

/*
 * Class:     Data
 * Method:    toString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Data_toString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
