#!/bin/sh
check() {
if (! $1)
then
  echo $2
  exit 1
fi
}

flavor=$1
if [ "$flavor" == "stable" ]
then
  flav=""
else
  flav="-${flavor}"
fi

grep -v MDSplus /etc/apt/sources.list > /etc/apt/sources.list.save
mv -f /etc/apt/sources.list.save /etc/apt/sources.list
echo "deb http://www.mdsplus.org/dist/Ubuntu11/repo MDSplus $1" >>/etc/apt/sources.list
sudo /usr/bin/apt-get autoremove -y "mdsplus*"
check "sudo /usr/bin/apt-get update" "Error doing update"
check "sudo /usr/bin/apt-get install -y mdsplus${flav}-python" "Error doing ${flavor} python install"
check "sudo /usr/bin/apt-get autoremove -y mdsplus${flav}-python" "Error doing ${flavor} python remove"
check "sudo /usr/bin/apt-get install -y mdsplus${flav}" "Error doing full ${flavor} install"
check "sudo /usr/bin/apt-get autoremove -y mdsplus${flav}" "Error doing ${flavor} remove"

