#!/usr/bin/env python
import MDSplus
import sys
sys.path.insert(0,MDSplus.__path__[0])
from unittest import TextTestRunner
from MDSplus.tests import test_all
t=TextTestRunner()
result=t.run(test_all())
if result.wasSuccessful():
  sys.exit(0)
else:
  sys.exit(1)
