#!/bin/sh
repo=$(dirname $(dirname $(realpath $0)))
supp=$repo/conf/valgrind.supp
suppressions="--suppressions=$supp/mdsplus.supp"
if test -f "$supp/${DISTNAME}.supp"
then suppressions="${suppressions} --suppressions=$supp/${DISTNAME}.supp"
fi
exec valgrind --tool=memcheck --leak-check=full --show-reachable=no\
 --xml=yes --xml-file=$(basename $1)-memcheck-%p.xml\
 --gen-suppressions=all --num-callers=64\
 --trace-children-skip='*/ld,*/collect2,*/ldconfig,*/sh'\
 --trace-children=yes --child-silent-after-fork=yes\
 --trace-children-skip-by-arg='*SetMdsplusFileProtection*'\
 $suppressions\
 "$@"
