#!/bin/bash
test=$(basename $4)
test=${test:0:-11}
echo $test
srcdir=$(readlink -f $(dirname ${0})/..)
if [ "$test" == "dcl" ]; then
  if [ -z $ACTION_SERVER ]
  then
    if [ -z $ACTION_PORT ]
    then
      ACTION_PORT=8800
    fi
    cmd="wine mdsip -s -p ${ACTION_PORT} -h $(winepath -w ${srcdir}/mdsobjects/python/tests/mdsip.hosts)"
    echo "$cmd";$cmd  &>server_0.log &
    export ACTION_SERVER=localhost:${ACTION_PORT}
  fi
  if [ -z $ACTION_MONITOR ]
  then
    if [ -z $MONITOR_PORT ]
    then
      MONITOR_PORT=4400
    fi
    cmd="wine mdsip -s -p ${MONITOR_PORT} -h $(winepath -w ${srcdir}/mdsobjects/python/tests/mdsip.hosts)"
    echo "$cmd";$cmd &>monitor_0.log &
    export ACTION_MONITOR=localhost:${MONITOR_PORT}
  fi
fi
wine $1 $2 $(winepath -w $3) $(winepath -w $4)
status=$?
if [ "$test" == "dcl" ]; then
  :&&killall -s 9 mdsip.exe
fi
exit $status
