#!/bin/sh
MDSPLUS_DIR=`cat /etc/.mdsplus_dir`
export MDSPLUS_DIR
. $MDSPLUS_DIR/setup.sh
MDS_PATH=$MDSPLUS_DIR/local/tdi\;$MDS_PATH
export MDS_PATH
set > /tmp/twftest
$MDSPLUS_DIR/bin/mdsip -s 2 -H TDIcheck_access_mdsips >> /var/log/mdsips.log 2>> /var/log/mdsips.error
