#!/bin/sh
MDSPLUS_DIR=`cat /etc/.mdsplus_dir`
export MDSPLUS_DIR
. $MDSPLUS_DIR/setup.sh
MDS_PATH=$MDSPLUS_DIR/local/tdi\;$MDS_PATH
export MDS_PATH
$MDSPLUS_DIR/bin/mdsip -s 0 -H /etc/mdsip.hosts >> /var/log/mdsip.log 2>> /var/log/mdsip.error
