#!/bin/sh
#
# update any submodules used by mdsplus
#
SUBMODULE_ERROR='Could not recursively update all git submodules. You may experience compilation problems if some submodules are out of date'
srcdir=$(dirname $0)/..
if [ -r ${srcdir}/.git ]
then
  ( git -C $srcdir submodule --quiet update --init --recursive ) \
    || ( git -C $srcdir submodule --quiet init && git submodule update --recursive ) \
    || ( git -C $srcdir submodule --quiet init && git submodule update && echo $SUBMODULE_ERROR ) \
    || (echo 'Git submodules could not be updated. Compilation will fail')
fi
