#!/bin/sh
if ( test -r $HOME/.scope_printers )
then
	cat $HOME/.scope_printers
else 
  if ( test -x /bin/awk )
  then
    awkcmd=/bin/awk
  elif ( test -x /usr/bin/awk )
  then
    awkcmd=/usr/bin/awk
  else
    awkcmd=awk
  fi
  if ( test -r $MDSPLUS_DIR/local/scope_printers )
  then
	cat $MDSPLUS_DIR/local/scope_printers
  else
    $awkcmd  -F\| '{\
      if (match($0,/^#/) != 0 || match($0,/^[:blank:]*$/) != 0) \
        next; \
      while (match($0,/\\[:blank:]*$/) != 0) \
      {\
        split($0,a,/\\[:blank:]*$/);\
        line = line a[1];\
        getline;\
      }\
      if (length(line) > 0)\
      {\
        gsub(/\ /,"",line);\
        gsub(/\t/,"",line);\
        split(line,a,/\|/);\
        print a[1];\
        line="";\
      }\
      else\
        print $1;\
    }' /etc/printcap 2>/dev/null | $awkcmd -F: '{print $1;}' - 
  fi
fi
