#
# Copyright (c) 2017, Massachusetts Institute of Technology All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# Redistributions of source code must retain the above copyright notice, this
# list of conditions and the following disclaimer.
#
# Redistributions in binary form must reproduce the above copyright notice, this
# list of conditions and the following disclaimer in the documentation and/or
# other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

MC = __import__('MARTE2_COMPONENT', globals())


@MC.BUILDER('SpiderCalGAM', MC.MARTE2_COMPONENT.MODE_GAM)
class MARTE2_SPIDER_CAL(MC.MARTE2_COMPONENT):
    inputs = [
        {'name': 'VPGbias', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'Vbias', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'IPG1', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'Pv', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'V_EG', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'V_acc', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'I_EG', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'I_acc', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'RF1_Pf', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'RF2_Pf', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'RF3_Pf', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'RF4_Pf', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'PLight1', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'PLight2', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'PLight3', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'PLight4', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'PLight5', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'PLight6', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'PLight7', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'PLight8', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'FSB_TT1', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'FSB_TT2', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'FSB_TT3', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'FSB_TT4', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'FSB_TT5', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'FSB_TT6', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'FSB_TT7', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'FSB_TT8', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'FSW_TT1', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'FSW_TT2', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'FSW_TT3', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'FSW_TT4', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'FSW_TT5', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'FSW_TT6', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'FSW_TT7', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'FSW_TT8', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'RF1', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'RF2', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'RF3', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'RF4', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'TC_BP21', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'TC_BP22', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'TC_BP31', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'TC_BP32', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'TC_BP41', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'TC_BP42', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'PG_TT12', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'PG_TT13', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'PG_TT22', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'PG_TT23', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'PG_TT32', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'PG_TT33', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'PG_TT42', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'PG_TT43', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'Tout_FSLW1_trend', 'type': 'float32',
            'dimensions': 0, 'parameters': {}},
        {'name': 'Tout_FSLW2_trend', 'type': 'float32',
            'dimensions': 0, 'parameters': {}},
        {'name': 'Tout_RF_trend', 'type': 'float32',
            'dimensions': 0, 'parameters': {}},
        {'name': 'Tout_FSBP_trend', 'type': 'float32',
            'dimensions': 0, 'parameters': {}},
        {'name': 'Tout_SCLW_trend', 'type': 'float32',
            'dimensions': 0, 'parameters': {}},
        {'name': 'Tout_BP_trend', 'type': 'float32',
            'dimensions': 0, 'parameters': {}},
        {'name': 'Tout_DP_trend', 'type': 'float32',
            'dimensions': 0, 'parameters': {}},
        {'name': 'Tout_PG1_trend', 'type': 'float32',
            'dimensions': 0, 'parameters': {}},
        {'name': 'Tout_PG2_trend', 'type': 'float32',
            'dimensions': 0, 'parameters': {}},
        {'name': 'Tout_PG3_trend', 'type': 'float32',
            'dimensions': 0, 'parameters': {}},
        {'name': 'Tout_PG4_trend', 'type': 'float32',
            'dimensions': 0, 'parameters': {}},
        {'name': 'Tout_EG1_trend', 'type': 'float32',
            'dimensions': 0, 'parameters': {}},
        {'name': 'Tout_EG2_trend', 'type': 'float32',
            'dimensions': 0, 'parameters': {}},
        {'name': 'Tout_EG3_trend', 'type': 'float32',
            'dimensions': 0, 'parameters': {}},
        {'name': 'Tout_EG4_trend', 'type': 'float32',
            'dimensions': 0, 'parameters': {}},
        {'name': 'Tout_GG1_trend', 'type': 'float32',
            'dimensions': 0, 'parameters': {}},
        {'name': 'Tout_GG2_trend', 'type': 'float32',
            'dimensions': 0, 'parameters': {}},
        {'name': 'Tout_GG3_trend', 'type': 'float32',
            'dimensions': 0, 'parameters': {}},
        {'name': 'Tout_GG4_trend', 'type': 'float32',
            'dimensions': 0, 'parameters': {}},
        {'name': 'Tin_PC02_trend', 'type': 'float32',
            'dimensions': 0, 'parameters': {}},
        {'name': 'Tin_PC03_trend', 'type': 'float32',
            'dimensions': 0, 'parameters': {}},
        {'name': 'flow_PG', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'flow_EG', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'flow_GG', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'flow_FSLW', 'type': 'float32',
            'dimensions': 0, 'parameters': {}},
        {'name': 'flow_RF', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'flow_FSBP', 'type': 'float32',
            'dimensions': 0, 'parameters': {}},
        {'name': 'flow_SCLW', 'type': 'float32',
            'dimensions': 0, 'parameters': {}},
        {'name': 'flow_BP', 'type': 'float32', 'dimensions': 0, 'parameters': {}},
        {'name': 'flow_DP', 'type': 'float32', 'dimensions': 0, 'parameters': {}}]

    outputs = [
        {'name': 'VPGbias', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'Vbias', 'type': 'float32', 'dimensions': 0,
            'seg_len': 100, 'parameters': {}},
        {'name': 'IPG1', 'type': 'float32', 'dimensions': 0,
            'seg_len': 100, 'parameters': {}},
        {'name': 'Pv', 'type': 'float32', 'dimensions': 0,
            'seg_len': 100, 'parameters': {}},
        {'name': 'V_EG', 'type': 'float32', 'dimensions': 0,
            'seg_len': 100, 'parameters': {}},
        {'name': 'V_acc', 'type': 'float32', 'dimensions': 0,
            'seg_len': 100, 'parameters': {}},
        {'name': 'I_EG', 'type': 'float32', 'dimensions': 0,
            'seg_len': 100, 'parameters': {}},
        {'name': 'I_acc', 'type': 'float32', 'dimensions': 0,
            'seg_len': 100, 'parameters': {}},
        {'name': 'Power_on_EG', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'Peak_temp_blue', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'Peak_temp_red', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'RF1_Pf', 'type': 'float32', 'dimensions': 0,
            'seg_len': 100, 'parameters': {}},
        {'name': 'RF2_Pf', 'type': 'float32', 'dimensions': 0,
            'seg_len': 100, 'parameters': {}},
        {'name': 'RF3_Pf', 'type': 'float32', 'dimensions': 0,
            'seg_len': 100, 'parameters': {}},
        {'name': 'RF4_Pf', 'type': 'float32', 'dimensions': 0,
            'seg_len': 100, 'parameters': {}},
        {'name': 'PLight1', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'PLight2', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'PLight3', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'PLight4', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'PLight5', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'PLight6', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'PLight7', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'PLight8', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'RF1_pfave', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'RF2_pfave', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'RF3_pfave', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'RF4_pfave', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'PLight1ave', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'PLight2ave', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'PLight3ave', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'PLight4ave', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'PLight5ave', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'PLight6ave', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'PLight7ave', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'PLight8ave', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'FSB_TT1', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'FSB_TT2', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'FSB_TT3', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'FSB_TT4', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'FSB_TT5', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'FSB_TT6', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'FSB_TT7', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'FSB_TT8', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'FSB_TT1_mean', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'FSB_TT2_mean', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'FSB_TT3_mean', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'FSB_TT4_mean', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'FSB_TT5_mean', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'FSB_TT6_mean', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'FSB_TT7_mean', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'FSB_TT8_mean', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'FSW_TT1', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'FSW_TT2', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'FSW_TT3', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'FSW_TT4', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'FSW_TT5', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'FSW_TT6', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'FSW_TT7', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'FSW_TT8', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'FSW_TT1_mean', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'FSW_TT2_mean', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'FSW_TT3_mean', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'FSW_TT4_mean', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'FSW_TT5_mean', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'FSW_TT6_mean', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'FSW_TT7_mean', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'FSW_TT8_mean', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'RF1', 'type': 'float32', 'dimensions': 0,
            'seg_len': 100, 'parameters': {}},
        {'name': 'RF2', 'type': 'float32', 'dimensions': 0,
            'seg_len': 100, 'parameters': {}},
        {'name': 'RF3', 'type': 'float32', 'dimensions': 0,
            'seg_len': 100, 'parameters': {}},
        {'name': 'RF4', 'type': 'float32', 'dimensions': 0,
            'seg_len': 100, 'parameters': {}},
        {'name': 'RF1ave', 'type': 'float32', 'dimensions': 0,
            'seg_len': 100, 'parameters': {}},
        {'name': 'RF2ave', 'type': 'float32', 'dimensions': 0,
            'seg_len': 100, 'parameters': {}},
        {'name': 'RF3ave', 'type': 'float32', 'dimensions': 0,
            'seg_len': 100, 'parameters': {}},
        {'name': 'RF4ave', 'type': 'float32', 'dimensions': 0,
            'seg_len': 100, 'parameters': {}},
        {'name': 'TC_BP21', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'TC_BP22', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'TC_BP31', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'TC_BP32', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'TC_BP41', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'TC_BP42', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'BP21heat', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'BP22heat', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'BP31heat', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'BP32heat', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'BP41heat', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'BP42heat', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'PG_TT12', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'PG_TT13', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'PG_TT22', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'PG_TT23', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'PG_TT32', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'PG_TT33', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'PG_TT42', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'PG_TT43', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'PG_TT12heat', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'PG_TT13heat', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'PG_TT22heat', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'PG_TT23heat', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'PG_TT32heat', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'PG_TT33heat', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'PG_TT42heat', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'PG_TT43heat', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'PG12heat', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'PG13heat', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'PG22heat', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'PG23heat', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'PG32heat', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'PG33heat', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'PG42heat', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'PG43heat', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'Tout_FSLW1_trend', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'Tout_FSLW2_trend', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'Tout_RF_trend', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'Tout_FSBP_trend', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'Tout_SCLW_trend', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'Tout_BP_trend', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'Tout_DP_trend', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'Tout_PG1_trend', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'Tout_PG2_trend', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'Tout_PG3_trend', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'Tout_PG4_trend', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'Tout_EG1_trend', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'Tout_EG2_trend', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'Tout_EG3_trend', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'Tout_EG4_trend', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'Tout_GG1_trend', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'Tout_GG2_trend', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'Tout_GG3_trend', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'Tout_GG4_trend', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'Tin_PC02_trend', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'Tin_PC03_trend', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'DT_FSLW1', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'DT_FSLW2', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'DT_RF', 'type': 'float32', 'dimensions': 0,
            'seg_len': 100, 'parameters': {}},
        {'name': 'DT_FSBP', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'DT_SCLW', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'DT_BP', 'type': 'float32', 'dimensions': 0,
            'seg_len': 100, 'parameters': {}},
        {'name': 'DT_DP', 'type': 'float32', 'dimensions': 0,
            'seg_len': 100, 'parameters': {}},
        {'name': 'DT_PG1', 'type': 'float32', 'dimensions': 0,
            'seg_len': 100, 'parameters': {}},
        {'name': 'DT_PG2', 'type': 'float32', 'dimensions': 0,
            'seg_len': 100, 'parameters': {}},
        {'name': 'DT_PG3', 'type': 'float32', 'dimensions': 0,
            'seg_len': 100, 'parameters': {}},
        {'name': 'DT_PG4', 'type': 'float32', 'dimensions': 0,
            'seg_len': 100, 'parameters': {}},
        {'name': 'DT_EG1', 'type': 'float32', 'dimensions': 0,
            'seg_len': 100, 'parameters': {}},
        {'name': 'DT_EG2', 'type': 'float32', 'dimensions': 0,
            'seg_len': 100, 'parameters': {}},
        {'name': 'DT_EG3', 'type': 'float32', 'dimensions': 0,
            'seg_len': 100, 'parameters': {}},
        {'name': 'DT_EG4', 'type': 'float32', 'dimensions': 0,
            'seg_len': 100, 'parameters': {}},
        {'name': 'DT_GG1', 'type': 'float32', 'dimensions': 0,
            'seg_len': 100, 'parameters': {}},
        {'name': 'DT_GG2', 'type': 'float32', 'dimensions': 0,
            'seg_len': 100, 'parameters': {}},
        {'name': 'DT_GG3', 'type': 'float32', 'dimensions': 0,
            'seg_len': 100, 'parameters': {}},
        {'name': 'DT_GG4', 'type': 'float32', 'dimensions': 0,
            'seg_len': 100, 'parameters': {}},
        {'name': 'DT_FSLW1_heat', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'DT_FSLW2_heat', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'DT_RF_heat', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'DT_FSBP_heat', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'DT_SCLW_heat', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'DT_BP_heat', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'DT_DP_heat', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'DT_PG1_heat', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'DT_PG2_heat', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'DT_PG3_heat', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'DT_PG4_heat', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'DT_EG1_heat', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'DT_EG2_heat', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'DT_EG3_heat', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'DT_EG4_heat', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'DT_GG1_heat', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'DT_GG2_heat', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'DT_GG3_heat', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'DT_GG4_heat', 'type': 'float32',
            'dimensions': 0, 'seg_len': 100, 'parameters': {}},
        {'name': 'DT_Tot_heat', 'type': 'float32', 'dimensions': 0, 'seg_len': 100, 'parameters': {}}]
    parameters = [
        {'name': 'Period', 'type': 'float32'}]
    parts = []
