from MDSplus import mdsExceptions, Device


class SPIDER_PARAMS(Device):
    """SPIDER Experiment Parameters"""
    parts = [
             {'path':'.POWER', 'type':'structure'},
             {'path': '.POWER:COMMENT', 'type': 'TEXT'},
             {'path': '.POWER:R_ISBP',  'type': 'NUMERIC', 'value': 0.420},
             {'path': '.POWER:R_ISBP_D','type': 'TEXT', 'value':  'Bias Plate parallel resistance'},
             {'path': '.POWER:R_ISBI',  'type': 'NUMERIC', 'value': 0.420},
             {'path': '.POWER:R_ISBI_D', 'type': 'TEXT', 'value':  'Bias  parallel resistance'},
             {'path': '.POWER:CS1',     'type': 'NUMERIC', 'value': 10.e-9},
             {'path': '.POWER:CS1_D',    'type': 'TEXT', 'value': 'Series capacitor DR1 and DR2'},
             {'path': '.POWER:CP1',    'type': 'NUMERIC', 'value': 10.e-9},
             {'path': '.POWER:CP1_D',    'type': 'TEXT', 'value': 'Parallel capacitor DR1 and DR2'},
             {'path': '.POWER:CS2',    'type': 'NUMERIC', 'value': 10.e-9},
             {'path': '.POWER:CS2_D',    'type': 'TEXT', 'value': 'Series capacitor DR7 and DR7'},
             {'path': '.POWER:CP2',    'type': 'NUMERIC', 'value': 10.e-9},
             {'path': '.POWER:CP2_D',    'type': 'TEXT', 'value': 'Parallel capacitor DR7 and DR8'},
             {'path': '.POWER:CS3',    'type': 'NUMERIC', 'value': 10.e-9},
             {'path': '.POWER:CS3_D',    'type': 'TEXT', 'value': 'Series capacitor DR3 and DR4'},
             {'path': '.POWER:CP3',    'type': 'NUMERIC', 'value': 11.5e-9},
             {'path': '.POWER:CP3_D',    'type': 'TEXT', 'value': 'Parallel capacitor DR3 and DR4'},
             {'path': '.POWER:CS4',    'type': 'NUMERIC', 'value': 10.e-9},
             {'path': '.POWER:CS4_D',    'type': 'TEXT', 'value': 'Series capacitor DR5 and DR5'},
             {'path': '.POWER:CP4',    'type': 'NUMERIC', 'value': 10.e-9},
             {'path': '.POWER:CP4_D',    'type': 'TEXT', 'value': 'Parallel capacitor DR5 and DR6'},
             {'path': '.POWER:MF_DIR',     'type': 'TEXT', 'value': 'REVERSE'},
             {'path': '.POWER:MF_DIR_D',   'type': 'TEXT', 'value': ''},
             {'path':'.GVS', 'type':'structure'},
             {'path': '.GVS:COMMENT', 'type': 'text'},
             {'path': '.GVS:VG_3013',    'type': 'TEXT', 'value': 'OFF'},
             {'path': '.GVS:VG_3013_D',  'type': 'TEXT', 'value': ''},
             {'path': '.GVS:VG_3014',    'type': 'TEXT', 'value': 'OFF'},
             {'path': '.GVS:VG_3014_D',  'type': 'TEXT', 'value': ''},
             {'path': '.GVS:TANK',     'type': 'TEXT', 'value': '3090'},
             {'path': '.GVS:TANK_D',     'type': 'TEXT', 'value': 'Gas Tank 3090 (H2) or 3091 (D2)'},
             {'path': '.GVS:GAS_TYPE',   'type': 'TEXT', 'value': 'H2'},
             {'path': '.GVS:GAS_TYPE_D',   'type': 'TEXT', 'value': 'Type of Gas'},
             {'path': '.GVS:VC3001_TR',   'type': 'NUMERIC', 'value': 5},
             {'path': '.GVS:VC3001_TR_D',   'type': 'TEXT', 'value': 'Number of turns of the microvalve on 25'},
             {'path': '.GVS:VC3002_TR',   'type': 'NUMERIC', 'value': 2},
             {'path': '.GVS:VC3002_TR_D',   'type': 'TEXT', 'value': 'Number of turns of the microvalve on 25'},
             {'path': '.POWER:RF_DR12',     'type': 'numeric', 'value': 1},
             {'path': '.POWER:RF_DR12_D',    'type': 'TEXT', 'value': 'RF driver12 order'},
             {'path': '.POWER:RF_DR34',     'type': 'numeric', 'value': 3},
             {'path': '.POWER:RF_DR34_D',    'type': 'TEXT', 'value': 'RF driver34 order'},
             {'path': '.POWER:RF_DR56',     'type': 'numeric', 'value': 4},
             {'path': '.POWER:RF_DR56_D',    'type': 'TEXT', 'value': 'RF driver56 order'},
             {'path': '.POWER:RF_DR78',     'type': 'numeric', 'value': 2},
             {'path': '.POWER:RF_DR78_D',    'type': 'TEXT', 'value': 'RF driver78 order'},
             ]
