#!/bin/bash
#
# Run during builds if /EGGS is found
#

set -o verbose

if [ -z "$EGGS_DIR" ]
then
    export EGGS_DIR="/EGGS"
fi
if [ -z "$BUILDROOT" ]
then
    export BUILDROOT="/buildroot"
fi
cd ${BUILDROOT}/usr/local/mdsplus/mdsobjects/python
python setup.py bdist_egg --dist-dir=${EGGS_DIR}
if [ -r /usr/bin/python3 ]
then
  python3 setup.py bdist_egg --dist-dir=${EGGS_DIR}
fi

