#!/bin/bash
#
# Run during builds if /EGGS is found
#

set -o verbose

if [ "${BUILDROOT}" = "" ]
then
  BUILDROOT=/buildroot
fi
if [ "${EGGS_DIR}" = "" ]
then
  EGGS_DIR=/EGGS
fi
cd ${BUILDROOT}/usr/local/mdsplus/mdsobjects/python
python setup.py bdist --dist-dir=${EGGS_DIR}
if [ -r /usr/bin/python3 ]
then
  python3 setup.py bdist --dist-dir=${EGGS_DIR}
fi

