#!/bin/bash
#
# script to obtain the latest release tag for a branch in MDSplus/mdsplus
#
# This script uses the https://github.com/name/repo/releases api for getting lists
# of release tags. It is complicated by the fact that this api is paginated so if
# a release tag is not found for the desired branch then the script has to get the
# next page and so on. It does this by parsing the content of the page and finds
# the line with Next in it and graps the url for the next page from that line.
#
branch=$1
release=""
tries=0
while [ "$tries" -lt 10 ]
do
    url="https://github.com/MDSplus/mdsplus/releases" 
    while ( wget -O /tmp/release_info -q $url )
    do
	if ( grep ${branch}_release /tmp/release_info > /dev/null )
	then
	    release="$(grep ${branch}_release /tmp/release_info | \
grep "\-\-\-\-" | awk '{print $NF; exit}')"
	    break
	else
	    url=$(grep Next /tmp/release_info | awk -F\" '{print $(NF-3)}')
	fi
    done
    if [ ! -z "$release" ]
    then
	echo $release
	break
    else
	let tries=$tries+1
	sleep 5
    fi
done

