#!/bin/sh
PATH=/bin:/sbin:$PATH
export PATH

MDSPLUS_DIR="$2/mdsplus"

if [ ! -d "$MDSPLUS_DIR/tdi" ]
then
  MDSPLUS_DIR=/usr/local/mdsplus
fi

echo $MDSPLUS_DIR > /etc/.mdsplus_dir

if ( grep mdsplus/setup.sh /etc/profile > /dev/null 2>&1 )
then
  mv /etc/profile /etc/profile.preinst
  grep -v mdsplus/setup.sh /etc/profile.preinst > /etc/profile
fi
echo ". $MDSPLUS_DIR/setup.sh" >> /etc/profile

if ( grep mdsplus/setup.csh /etc/csh.login > /dev/null 2>& 1 )
then
  mv /etc/csh.login /etc/csh.login.preinst
  grep -v mdsplus/setup.csh /etc/csh.login.preinst > /etc/csh.login
fi
echo "source $MDSPLUS_DIR/setup.csh" >> /etc/csh.login

if ( ! grep mdsip /etc/services > /dev/null 2>&1 )
then
  echo "mdsip 8000/tcp # MDSplus mdsip data service" >> /etc/services
fi

date > /var/log/mdsplus_postinstall
pushd ${MDSPLUS_DIR}/python/MDSplus >> /var/log/mdsplus_postinstall 2>&1
python setup.py install >>/var/log/mdsplus_postinstall 2>&1
popd >> /var/log/mdsplus_postinstall 2>&1
pushd ${MDSPLUS_DIR}/tdi/MitDevices >> /var/log/mdsplus_postinstall 2>&1
python setup.py install >>/var/log/mdsplus_postinstall 2>&1
popd >> /var/log/mdsplus_postinstall 2>&1
exit 0
