#!/bin/sh
PATH=/bin:/sbin:$PATH
export PATH

MDSPLUS_DIR=$2/mdsplus
echo $MDSPLUS_DIR > /etc/.mdsplus_dir

if ( grep mdsplus/setup.sh /etc/profile > /dev/null 2>&1 )
then
  mv /etc/profile /etc/profile.preinst
  grep -v mdsplus/setup.sh /etc/profile.preinst > /etc/profile
fi
echo ". $MDSPLUS_DIR/setup.sh" >> /etc/profile

if ( grep mdsplus/setup.csh /etc/csh.login > /dev/null 2>& 1 )
then
  mv /etc/csh.login /etc/csh.login.preinst
  grep -v mdsplus/setup.csh /etc/csh.login.preinst > /etc/csh.login
fi
echo "source $MDSPLUS_DIR/setup.csh" >> /etc/csh.login

if ( ! grep mdsip /etc/services > /dev/null 2>&1 )
  echo "mdsip 8000/tcp # MDSplus mdsip data service"" >> /etc/services
fi

easy_install $2/mdsplus/mdsobjects/python/dist/*.egg
