#!/bin/bash
touch /var/log/mdsplus-preflight
touch ~root/mdsplus-preflight
touch /tmp/mdsplus-preflight
echo Executing $0 of $2 > /var/log/$(basename $0).log
for f in $(ls $2/mdsplus | grep -v local)
do
  rm -Rvf $2/mdsplus/$f >> /var/log/$(basename $0).log
done
