#!/bin/sh
PATH=/bin:/sbin:$PATH
export PATH

MDSPLUS_DIR="$2/mdsplus"
if [ ! -d $MDSPLUS_DIR/tdi ]
then
  MDSPLUS_DIR=/usr/local/mdsplus
fi
for f in $(ls $MDSPLUS_DIR 2>/dev/null | grep -v local)
do
  rm -Rvf $MDSPLUS_DIR/$f >/dev/null 2>&1
done
