#define MIT_DECODER_K_CONG_NODES 15
#define MIT_DECODER_N_HEAD 0
#define MIT_DECODER_N_NAME 1
#define MIT_DECODER_N_COMMENT 2
#define MIT_DECODER_N_MASTER_REG 3
#define MIT_DECODER_N_CHANNEL_0 4
#define MIT_DECODER_N_CHANNEL_0_PSEUDO_DEV 5
#define MIT_DECODER_N_CHANNEL_1 6
#define MIT_DECODER_N_CHANNEL_1_PSEUDO_DEV 7
#define MIT_DECODER_N_CHANNEL_2 8
#define MIT_DECODER_N_CHANNEL_2_PSEUDO_DEV 9
#define MIT_DECODER_N_CHANNEL_3 10
#define MIT_DECODER_N_CHANNEL_3_PSEUDO_DEV 11
#define MIT_DECODER_N_CHANNEL_4 12
#define MIT_DECODER_N_CHANNEL_4_PSEUDO_DEV 13
#define MIT_DECODER_N_INIT_ACTION 14
typedef struct {
  struct descriptor_xd *__xds;
  int __num_xds;
  int head_nid;
  char *name;
} InInitStruct;
