/*
Copyright (c) 2017, Massachusetts Institute of Technology All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

Redistributions of source code must retain the above copyright notice, this
list of conditions and the following disclaimer.

Redistributions in binary form must reproduce the above copyright notice, this
list of conditions and the following disclaimer in the documentation and/or
other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
#define T2812_K_CONG_NODES 33
#define T2812_N_HEAD 0
#define T2812_N_INPUT_1 1
#define T2812_N_INPUT_1_CALIBRATION 2
#define T2812_N_INPUT_1_STARTIDX 3
#define T2812_N_INPUT_1_ENDIDX 4
#define T2812_N_INPUT_2 5
#define T2812_N_INPUT_2_CALIBRATION 6
#define T2812_N_INPUT_2_STARTIDX 7
#define T2812_N_INPUT_2_ENDIDX 8
#define T2812_N_INPUT_3 9
#define T2812_N_INPUT_3_CALIBRATION 10
#define T2812_N_INPUT_3_STARTIDX 11
#define T2812_N_INPUT_3_ENDIDX 12
#define T2812_N_INPUT_4 13
#define T2812_N_INPUT_4_CALIBRATION 14
#define T2812_N_INPUT_4_STARTIDX 15
#define T2812_N_INPUT_4_ENDIDX 16
#define T2812_N_INPUT_5 17
#define T2812_N_INPUT_5_CALIBRATION 18
#define T2812_N_INPUT_5_STARTIDX 19
#define T2812_N_INPUT_5_ENDIDX 20
#define T2812_N_INPUT_6 21
#define T2812_N_INPUT_6_CALIBRATION 22
#define T2812_N_INPUT_6_STARTIDX 23
#define T2812_N_INPUT_6_ENDIDX 24
#define T2812_N_INPUT_7 25
#define T2812_N_INPUT_7_CALIBRATION 26
#define T2812_N_INPUT_7_STARTIDX 27
#define T2812_N_INPUT_7_ENDIDX 28
#define T2812_N_INPUT_8 29
#define T2812_N_INPUT_8_CALIBRATION 30
#define T2812_N_INPUT_8_STARTIDX 31
#define T2812_N_INPUT_8_ENDIDX 32
