CFLAGS = -c -I../include -I. -g

OBJECTS = \
	mdsipshr.o

t : t.c ../shlib/libMdsIpShr.so
	cc -o t $(CFLAGS) t.c -L../shlib -lMdsIpShr

../shlib/libMdsIpShr.so : $(OBJECTS) ../shlib
	$(LD) -o $@ -shared -no_archive $(OBJECTS) -lc
	-rm so_locations

../shlib :
	mkdir ../shlib

clean :
	- rm *.o
	- rm so_locations
	- rm ../shlib/libMdsIpShr.so
	- rm .depend
	- rm t

depend : .depend

.depend :
	- rm .depend
	find *.c -exec cc -I../include -M {} > .depend \;

include .depend

