SHARE_TYPE = o
MAKE_DEPEND = $(CC) $(CFLAGS) -M {} > .depend \;
CFLAGS = -c -g  -DAXPVME -DCPU=21064  -DVME_ENV  -std -DvxWorks -I$(VXWORKS_BASE)/h  -I$(MDSPLUS)/include -I/usr/include

OBJECTS = \
	mdsipshr.o \
	mdsiputil.o

mdstcpip:  ../vxWorks ../vxWorks/Alpha $(OBJECTS)
	ld -o ../vxWorks/Alpha/MdsIpShr.o -r *.o
	rm *.o

../vxWorks :
	mkdir ../vxWorks

../vxWorks/Alpha :
	mkdir ../vxWorks/Alpha

clean :
	rm ../vxWorks/*.o
	rm .depend

