CFLAGS = -c -I../include -I. -g -assume noaligned_objects

OBJECTS = \
	mdsipshr.o

t : t.c
	cc -o t t.c -lMdsIpShr

../shlib/libMdsIpShr.so : $(OBJECTS) ../shlib
	$(LD) -o $@ -shared -no_archive $(OBJECTS) -lc
	-rm so_locations

../shlib :
	mkdir ../shlib

clean :
	- rm *.o
	- rm so_locations
	- rm ../shlib/libMdsIpShr.so
	- rm .depend

depend : .depend

.depend :
	- rm .depend
	find *.c -exec cc -I../include -M {} > .depend \;

include .depend

