#!/bin/bash
# $1 is [user@]server[:port]
[[ $1 =~ ^(([^@]+)@|)([^:]+)(:([0-9]+)|) ]]
if [ -z ${BASH_REMATCH[2]} ]
then user=$USER
else user=${BASH_REMATCH[2]}
fi
server=${BASH_REMATCH[3]}
if [ -z ${BASH_REMATCH[5]} ]
then port=8000
else port=${BASH_REMATCH[5]}
fi
exec ssh ${user}@${server} nc localhost ${port}
