CFLAGS = -I../include -I. -g -Ae

OBJECTS = \
tditest.o

all : .depend
	make -f Makefile.HPUX -f .depend ../bin/tditest

../bin/tditest : $(OBJECTS) ../bin
	cc -o $@ $(OBJECTS) -Wl,+s -Wl,-E -lc -L../shlib -lTdiShr /opt/langtools/lib/end.o

../bin :
	mkdir ../bin

clean :
	- rm *.o
	- rm ../bin/tditest
	- rm .depend

depend : .depend

.depend :
	- rm .depend
	- find *.c -exec /usr/ccs/lbin/cpp -I../include -M {} /dev/null 2> .depend \;
