CFLAGS = -c -I../include -I. -g

OBJECTS = \
tditest.o

../bin/tditest : $(OBJECTS) ../bin
	cc -o $@ $(OBJECTS) -lc -L../shlib -lTdiShr 

../bin :
	mkdir ../bin

clean :
	- rm *.o
	- rm ../bin/tditest

depend : .depend

.depend :
	- rm .depend
	find *.c -exec cc -I../include -M {} > .depend \;

include .depend
