include $(MAKE_OPTIONS)

OBJECTS = \
tditest.o

_tditest : ../bin ../bin/tditest

../bin/tditest : $(OBJECTS)
	$(CC) -o $@ $(OBJECTS) $(CC_IMAGE_OPTIONS) -L../shlib -lTdiShr $(DLD)

../bin :
	mkdir ../bin

clean :
	- rm .depend
	- rm *.o
	- rm ../bin/tditest

.depend :
	find *.c -exec $(MAKE_DEPEND)

include $(DEPEND)
