#!/bin/sh
lib=lib
if java -d64 -version >  /dev/null 2>&1; then
  if [ -r $MDSPLUS_DIR/lib64 ] ; then
    lib=/lib64
  fi
else
  if [ -r $MDSPLUS_DIR/lib32 ]; then
     lib=lib32
  fi
fi
exec env \
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$MDSPLUS_DIR/${lib} \
SHLIB_PATH=$SHLIB_PATH:$MDSPLUS_DIR/${lib} \
DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$MDSPLUS_DIR/${lib} \
java -Xmx2G -Dsun.java2d.xrender=false -Djava.library.path=$MDSPLUS_DIR/${lib} -jar $MDSPLUS_DIR/java/classes/jScope.jar $*
