CFLAGS = -c -I../include -I. -g -assume noaligned_objects

OBJECTS = \
rec2dsc.o \
stuff.o \
treefindnode.o \
treegetdbi.o \
treegetnci.o \
treegetrecord.o \
treeopen.o \
treesetdefault.o \
remote.o

libTreeShr.so : $(OBJECTS)
	ld -o $@ -shared -no_archive $(OBJECTS) -lc -lm -lots -L../mdsshr -lMdsShr









