#!/bin/sh
PATH=/bin:/sbin:$PATH
export PATH

MDSPLUS_DIR=/usr/local/mdsplus

echo $MDSPLUS_DIR > /etc/.mdsplus_dir

echo Adding MDSplus login scripts
if [ -r /etc/profile.d ]; then
  ln -s $MDSPLUS_DIR/setup.csh /etc/profile.d/mdsplus.csh
  ln -s $MDSPLUS_DIR/setup.sh /etc/profile.d/mdsplus.sh
else
  if grep "^. $MDSPLUS_DIR/setup.sh" /etc/profile > /dev/null
  then
    true
  else
    echo ". $MDSPLUS_DIR/setup.sh" >> /etc/profile
  fi
  if grep "^source $MDSPLUS_DIR/setup.csh" /etc/csh.login > /dev/null
  then
    true
  else
    echo "source $MDSPLUS_DIR/setup.csh" >> /etc/csh.login
  fi
fi


