#!/bin/sh
PATH=/bin:/sbin:$PATH
export PATH

MDSPLUS_DIR=/usr/local/mdsplus
echo $MDSPLUS_DIR > /etc/.mdsplus_dir

MDSplusSrv=y

if (test "$MDSplusSrv" = "y")
then
  echo Creating sample /etc/mdsip.hosts file for mdsip server to user mapping
  if [ ! -r /etc/mdsip.hosts ]; then 
    cp $MDSPLUS_DIR/etc/mdsip.hosts /etc/ 
  fi
#
# Add mdsip to services
#
#  echo Adding mdsip service to /etc/service
#  if grep "^mdsip " /etc/services >/dev/null
#  then
#          true
#  else
#          echo "mdsip    8000/tcp # Added by package mdsplus" >> /etc/services
#  fi
#
# Add mdsipd to /etc/inetd.conf or /etc/xinetd.d
#
  if [ -r /etc/xinetd.d ] ; then
    echo Adding mdsip to /etc/xinetd.d
    cp $MDSPLUS_DIR/rpm/mdsipd.xinetd /etc/xinetd.d/mdsip
    if [ -r /var/run/xinetd.pid ] ; then
      kill -HUP `cat /var/run/xinetd.pid`
    else
      echo "Starting xinetd..."
      xinetd -pidfile /var/run/xinetd.pid
    fi
  else
    echo Adding mdsipd service to /etc/inetd.conf
    if grep "^mdsip " /etc/inetd.conf > /dev/null
    then
      true
    else
      echo "mdsip stream	tcp	nowait root $MDSPLUS_DIR/bin/mdsipd mdsipd mdsip /var/log/mdsplus/mdsipd" >> /etc/inetd.conf
    fi
    killall -HUP inetd
  fi
fi
unset MDSplusSrv
