import java.awt.*;
import javax.swing.*;

/**
 * <p>
 * Title:
 * </p>
 * <p>
 * Description:
 * </p>
 * <p>
 * Copyright: Copyright (c) 2003
 * </p>
 * <p>
 * Company:
 * </p>
 *
 * @author not attributable
 * @version 1.0
 */
public class EM_FLU_TESTSetup extends DeviceSetup
{
	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	BorderLayout borderLayout1 = new BorderLayout();
	JPanel jPanel1 = new JPanel();
	DeviceField deviceField1 = new DeviceField();
	JTabbedPane jTabbedPane1 = new JTabbedPane();
	JPanel jPanel2 = new JPanel();
	BorderLayout borderLayout2 = new BorderLayout();
	JPanel jPanel4 = new JPanel();
	GridLayout gridLayout2 = new GridLayout();
	JPanel jPanel5 = new JPanel();
	JPanel jPanel6 = new JPanel();
	DeviceField deviceField2 = new DeviceField();
	DeviceField deviceField3 = new DeviceField();
	DeviceField deviceField4 = new DeviceField();
	DeviceField deviceField5 = new DeviceField();
	JScrollPane jScrollPane1 = new JScrollPane();
	JPanel jPanel7 = new JPanel();
	GridLayout gridLayout3 = new GridLayout();
	DeviceChannel deviceChannel1 = new DeviceChannel();
	BorderLayout borderLayout3 = new BorderLayout();
	JPanel jPanel8 = new JPanel();
	DeviceField deviceField6 = new DeviceField();
	DeviceField deviceField7 = new DeviceField();
	JPanel jPanel9 = new JPanel();
	JLabel jLabel1 = new JLabel();
	FlowLayout flowLayout1 = new FlowLayout();
	FlowLayout flowLayout2 = new FlowLayout();
	FlowLayout flowLayout3 = new FlowLayout();
	DeviceField deviceField8 = new DeviceField();
	DeviceField deviceField9 = new DeviceField();
	JPanel jPanel10 = new JPanel();
	DeviceChannel deviceChannel2 = new DeviceChannel();
	BorderLayout borderLayout4 = new BorderLayout();
	FlowLayout flowLayout4 = new FlowLayout();
	DeviceField deviceField10 = new DeviceField();
	DeviceField deviceField11 = new DeviceField();
	JPanel jPanel11 = new JPanel();
	DeviceChannel deviceChannel3 = new DeviceChannel();
	BorderLayout borderLayout5 = new BorderLayout();
	FlowLayout flowLayout5 = new FlowLayout();
	DeviceField deviceField12 = new DeviceField();
	DeviceField deviceField13 = new DeviceField();
	JPanel jPanel12 = new JPanel();
	DeviceChannel deviceChannel4 = new DeviceChannel();
	BorderLayout borderLayout6 = new BorderLayout();
	FlowLayout flowLayout6 = new FlowLayout();
	DeviceField deviceField14 = new DeviceField();
	DeviceField deviceField15 = new DeviceField();
	JPanel jPanel13 = new JPanel();
	DeviceChannel deviceChannel5 = new DeviceChannel();
	BorderLayout borderLayout7 = new BorderLayout();
	FlowLayout flowLayout7 = new FlowLayout();
	DeviceField deviceField16 = new DeviceField();
	DeviceField deviceField17 = new DeviceField();
	JPanel jPanel14 = new JPanel();
	DeviceChannel deviceChannel6 = new DeviceChannel();
	BorderLayout borderLayout8 = new BorderLayout();
	FlowLayout flowLayout8 = new FlowLayout();
	DeviceField deviceField18 = new DeviceField();
	DeviceField deviceField19 = new DeviceField();
	JPanel jPanel15 = new JPanel();
	DeviceChannel deviceChannel7 = new DeviceChannel();
	BorderLayout borderLayout9 = new BorderLayout();
	FlowLayout flowLayout9 = new FlowLayout();
	DeviceField deviceField110 = new DeviceField();
	DeviceField deviceField111 = new DeviceField();
	JPanel jPanel16 = new JPanel();
	DeviceChannel deviceChannel8 = new DeviceChannel();
	BorderLayout borderLayout10 = new BorderLayout();
	FlowLayout flowLayout10 = new FlowLayout();
	DeviceField deviceField112 = new DeviceField();
	DeviceField deviceField113 = new DeviceField();
	JPanel jPanel17 = new JPanel();
	DeviceChannel deviceChannel9 = new DeviceChannel();
	BorderLayout borderLayout11 = new BorderLayout();
	FlowLayout flowLayout11 = new FlowLayout();
	DeviceField deviceField114 = new DeviceField();
	DeviceField deviceField115 = new DeviceField();
	JPanel jPanel18 = new JPanel();
	DeviceChannel deviceChannel10 = new DeviceChannel();
	BorderLayout borderLayout12 = new BorderLayout();
	FlowLayout flowLayout12 = new FlowLayout();
	DeviceField deviceField116 = new DeviceField();
	DeviceField deviceField117 = new DeviceField();
	JPanel jPanel19 = new JPanel();
	DeviceChannel deviceChannel11 = new DeviceChannel();
	BorderLayout borderLayout13 = new BorderLayout();
	FlowLayout flowLayout13 = new FlowLayout();
	DeviceField deviceField118 = new DeviceField();
	DeviceField deviceField119 = new DeviceField();
	JPanel jPanel110 = new JPanel();
	DeviceChannel deviceChannel12 = new DeviceChannel();
	BorderLayout borderLayout14 = new BorderLayout();
	DeviceButtons deviceButtons1 = new DeviceButtons();
	FlowLayout flowLayout14 = new FlowLayout();
	FlowLayout flowLayout15 = new FlowLayout();
	FlowLayout flowLayout16 = new FlowLayout();
	DeviceField deviceField20 = new DeviceField();
	DeviceField deviceField21 = new DeviceField();
	GridLayout gridLayout4 = new GridLayout();
	JPanel jPanel21 = new JPanel();
	JPanel jPanel22 = new JPanel();
	FlowLayout flowLayout111 = new FlowLayout();
	JLabel jLabel2 = new JLabel();
	FlowLayout flowLayout113 = new FlowLayout();
	JPanel jPanel23 = new JPanel();
	JPanel jPanel24 = new JPanel();
	FlowLayout flowLayout25 = new FlowLayout();
	DeviceField deviceField26 = new DeviceField();
	BorderLayout borderLayout21 = new BorderLayout();
	JPanel jPanel26 = new JPanel();
	DeviceField deviceField27 = new DeviceField();
	JScrollPane jScrollPane2 = new JScrollPane();
	JPanel jPanel3 = new JPanel();
	GridLayout gridLayout1 = new GridLayout();
	FlowLayout flowLayout17 = new FlowLayout();
	DeviceField deviceField22 = new DeviceField();
	DeviceChannel deviceChannel13 = new DeviceChannel();
	DeviceField deviceField23 = new DeviceField();
	JPanel jPanel20 = new JPanel();
	BorderLayout borderLayout15 = new BorderLayout();
	FlowLayout flowLayout18 = new FlowLayout();
	DeviceField deviceField24 = new DeviceField();
	DeviceChannel deviceChannel14 = new DeviceChannel();
	DeviceField deviceField25 = new DeviceField();
	JPanel jPanel25 = new JPanel();
	BorderLayout borderLayout16 = new BorderLayout();
	FlowLayout flowLayout19 = new FlowLayout();
	DeviceField deviceField28 = new DeviceField();
	DeviceChannel deviceChannel15 = new DeviceChannel();
	DeviceField deviceField29 = new DeviceField();
	JPanel jPanel27 = new JPanel();
	BorderLayout borderLayout17 = new BorderLayout();
	FlowLayout flowLayout110 = new FlowLayout();
	DeviceField deviceField210 = new DeviceField();
	DeviceChannel deviceChannel16 = new DeviceChannel();
	DeviceField deviceField211 = new DeviceField();
	JPanel jPanel28 = new JPanel();
	BorderLayout borderLayout18 = new BorderLayout();
	FlowLayout flowLayout112 = new FlowLayout();
	DeviceField deviceField212 = new DeviceField();
	DeviceChannel deviceChannel17 = new DeviceChannel();
	DeviceField deviceField213 = new DeviceField();
	JPanel jPanel29 = new JPanel();
	BorderLayout borderLayout19 = new BorderLayout();
	FlowLayout flowLayout114 = new FlowLayout();
	DeviceField deviceField214 = new DeviceField();
	DeviceChannel deviceChannel18 = new DeviceChannel();
	DeviceField deviceField215 = new DeviceField();
	JPanel jPanel210 = new JPanel();
	BorderLayout borderLayout110 = new BorderLayout();
	FlowLayout flowLayout115 = new FlowLayout();
	DeviceField deviceField216 = new DeviceField();
	DeviceChannel deviceChannel19 = new DeviceChannel();
	DeviceField deviceField217 = new DeviceField();
	JPanel jPanel211 = new JPanel();
	BorderLayout borderLayout111 = new BorderLayout();
	FlowLayout flowLayout116 = new FlowLayout();
	DeviceField deviceField218 = new DeviceField();
	DeviceChannel deviceChannel110 = new DeviceChannel();
	DeviceField deviceField219 = new DeviceField();
	JPanel jPanel212 = new JPanel();
	BorderLayout borderLayout112 = new BorderLayout();
	FlowLayout flowLayout117 = new FlowLayout();
	DeviceField deviceField2110 = new DeviceField();
	DeviceChannel deviceChannel111 = new DeviceChannel();
	DeviceField deviceField2111 = new DeviceField();
	JPanel jPanel213 = new JPanel();
	BorderLayout borderLayout113 = new BorderLayout();
	FlowLayout flowLayout118 = new FlowLayout();
	DeviceField deviceField2112 = new DeviceField();
	DeviceChannel deviceChannel112 = new DeviceChannel();
	DeviceField deviceField2113 = new DeviceField();
	JPanel jPanel214 = new JPanel();
	BorderLayout borderLayout114 = new BorderLayout();
	FlowLayout flowLayout119 = new FlowLayout();
	DeviceField deviceField2114 = new DeviceField();
	DeviceChannel deviceChannel113 = new DeviceChannel();
	DeviceField deviceField2115 = new DeviceField();
	JPanel jPanel215 = new JPanel();
	BorderLayout borderLayout115 = new BorderLayout();
	FlowLayout flowLayout1110 = new FlowLayout();
	DeviceField deviceField2116 = new DeviceField();
	DeviceChannel deviceChannel114 = new DeviceChannel();
	DeviceField deviceField2117 = new DeviceField();
	JPanel jPanel216 = new JPanel();
	BorderLayout borderLayout116 = new BorderLayout();
	DeviceChannel deviceChannel20 = new DeviceChannel();
	BorderLayout borderLayout20 = new BorderLayout();
	JPanel jPanel30 = new JPanel();
	BorderLayout borderLayout22 = new BorderLayout();
	DeviceChannel deviceChannel21 = new DeviceChannel();
	BorderLayout borderLayout23 = new BorderLayout();
	JPanel jPanel31 = new JPanel();
	BorderLayout borderLayout24 = new BorderLayout();

	public EM_FLU_TESTSetup()
	{
		try
		{
			jbInit();
		}
		catch (final Exception e)
		{
			e.printStackTrace();
		}
	}

	private void jbInit() throws Exception
	{
		this.setWidth(750);
		this.setHeight(520);
		this.setDeviceType("EM_FLU_TEST");
		this.setDeviceProvider("150.178.3.33");
		this.setDeviceTitle("Eletromagnetic Test");
		this.getContentPane().setLayout(borderLayout1);
		jPanel1.setLayout(flowLayout14);
		deviceField1.setOffsetNid(1);
		deviceField1.setLabelString("Comment: ");
		deviceField1.setNumCols(50);
		deviceField1.setIdentifier("");
		jPanel2.setLayout(borderLayout2);
		jPanel4.setLayout(gridLayout2);
		gridLayout2.setRows(3);
		deviceField3.setOffsetNid(44);
		deviceField3.setTextOnly(true);
		deviceField3.setLabelString("Decoder 1: ");
		deviceField3.setNumCols(20);
		deviceField3.setIdentifier("");
		deviceField2.setOffsetNid(45);
		deviceField2.setTextOnly(true);
		deviceField2.setLabelString("Decoder 2:");
		deviceField2.setNumCols(20);
		deviceField5.setOffsetNid(46);
		deviceField5.setLabelString("Signal Test Delay: ");
		deviceField5.setNumCols(15);
		deviceField4.setOffsetNid(47);
		deviceField4.setLabelString("Signal Test Duration");
		deviceField4.setNumCols(15);
		jPanel7.setLayout(gridLayout3);
		gridLayout3.setRows(12);
		deviceChannel1.setLabelString("02");
		deviceChannel1.setOffsetNid(51);
		deviceChannel1.setInSameLine(true);
		deviceChannel1.setUpdateIdentifier("");
		deviceChannel1.setShowVal("");
		deviceChannel1.setLayout(borderLayout3);
		deviceField6.setOffsetNid(52);
		deviceField6.setTextOnly(true);
		deviceField6.setNumCols(25);
		deviceField7.setOffsetNid(53);
		deviceField7.setTextOnly(true);
		deviceField7.setNumCols(25);
		jLabel1.setText("   CARD                                GAIN                      "
				+ "                                              ADC");
		jPanel9.setLayout(flowLayout1);
		flowLayout1.setAlignment(FlowLayout.LEFT);
		flowLayout1.setHgap(0);
		flowLayout1.setVgap(0);
		jPanel8.setLayout(flowLayout2);
		flowLayout2.setAlignment(FlowLayout.LEFT);
		flowLayout2.setHgap(0);
		flowLayout2.setVgap(0);
		flowLayout3.setVgap(0);
		flowLayout3.setHgap(0);
		flowLayout3.setAlignment(FlowLayout.LEFT);
		deviceField8.setOffsetNid(83);
		deviceField8.setTextOnly(true);
		deviceField8.setNumCols(25);
		deviceField9.setOffsetNid(82);
		deviceField9.setTextOnly(true);
		deviceField9.setNumCols(25);
		jPanel10.setLayout(flowLayout3);
		deviceChannel2.setLabelString("12");
		deviceChannel2.setOffsetNid(81);
		deviceChannel2.setInSameLine(true);
		deviceChannel2.setLayout(borderLayout4);
		flowLayout4.setVgap(0);
		flowLayout4.setHgap(0);
		flowLayout4.setAlignment(FlowLayout.LEFT);
		deviceField10.setOffsetNid(80);
		deviceField10.setTextOnly(true);
		deviceField10.setNumCols(25);
		deviceField11.setOffsetNid(79);
		deviceField11.setTextOnly(true);
		deviceField11.setNumCols(25);
		jPanel11.setLayout(flowLayout4);
		deviceChannel3.setLabelString("11");
		deviceChannel3.setOffsetNid(78);
		deviceChannel3.setInSameLine(true);
		deviceChannel3.setLayout(borderLayout5);
		flowLayout5.setVgap(0);
		flowLayout5.setHgap(0);
		flowLayout5.setAlignment(FlowLayout.LEFT);
		deviceField12.setOffsetNid(77);
		deviceField12.setTextOnly(true);
		deviceField12.setNumCols(25);
		deviceField13.setOffsetNid(76);
		deviceField13.setTextOnly(true);
		deviceField13.setNumCols(25);
		jPanel12.setLayout(flowLayout5);
		deviceChannel4.setLabelString("10");
		deviceChannel4.setOffsetNid(75);
		deviceChannel4.setInSameLine(true);
		deviceChannel4.setLayout(borderLayout6);
		flowLayout6.setVgap(0);
		flowLayout6.setHgap(0);
		flowLayout6.setAlignment(FlowLayout.LEFT);
		deviceField14.setOffsetNid(74);
		deviceField14.setTextOnly(true);
		deviceField14.setNumCols(25);
		deviceField15.setOffsetNid(73);
		deviceField15.setTextOnly(true);
		deviceField15.setNumCols(25);
		jPanel13.setLayout(flowLayout6);
		deviceChannel5.setLabelString("09");
		deviceChannel5.setOffsetNid(72);
		deviceChannel5.setInSameLine(true);
		deviceChannel5.setLayout(borderLayout7);
		flowLayout7.setVgap(0);
		flowLayout7.setHgap(0);
		flowLayout7.setAlignment(FlowLayout.LEFT);
		deviceField16.setOffsetNid(71);
		deviceField16.setTextOnly(true);
		deviceField16.setNumCols(25);
		deviceField17.setOffsetNid(70);
		deviceField17.setTextOnly(true);
		deviceField17.setNumCols(25);
		jPanel14.setLayout(flowLayout7);
		deviceChannel6.setLabelString("08");
		deviceChannel6.setOffsetNid(69);
		deviceChannel6.setInSameLine(true);
		deviceChannel6.setLayout(borderLayout8);
		flowLayout8.setVgap(0);
		flowLayout8.setHgap(0);
		flowLayout8.setAlignment(FlowLayout.LEFT);
		deviceField18.setOffsetNid(68);
		deviceField18.setTextOnly(true);
		deviceField18.setNumCols(25);
		deviceField19.setOffsetNid(67);
		deviceField19.setTextOnly(true);
		deviceField19.setNumCols(25);
		jPanel15.setLayout(flowLayout8);
		deviceChannel7.setLabelString("07");
		deviceChannel7.setOffsetNid(66);
		deviceChannel7.setInSameLine(true);
		deviceChannel7.setLayout(borderLayout9);
		flowLayout9.setVgap(0);
		flowLayout9.setHgap(0);
		flowLayout9.setAlignment(FlowLayout.LEFT);
		deviceField110.setOffsetNid(65);
		deviceField110.setTextOnly(true);
		deviceField110.setNumCols(25);
		deviceField111.setOffsetNid(64);
		deviceField111.setTextOnly(true);
		deviceField111.setNumCols(25);
		jPanel16.setLayout(flowLayout9);
		deviceChannel8.setLabelString("06");
		deviceChannel8.setOffsetNid(63);
		deviceChannel8.setInSameLine(true);
		deviceChannel8.setLayout(borderLayout10);
		flowLayout10.setVgap(0);
		flowLayout10.setHgap(0);
		flowLayout10.setAlignment(FlowLayout.LEFT);
		deviceField112.setOffsetNid(62);
		deviceField112.setTextOnly(true);
		deviceField112.setNumCols(25);
		deviceField113.setOffsetNid(61);
		deviceField113.setTextOnly(true);
		deviceField113.setNumCols(25);
		jPanel17.setLayout(flowLayout10);
		deviceChannel9.setLabelString("05");
		deviceChannel9.setOffsetNid(60);
		deviceChannel9.setInSameLine(true);
		deviceChannel9.setLayout(borderLayout11);
		flowLayout11.setVgap(0);
		flowLayout11.setHgap(0);
		flowLayout11.setAlignment(FlowLayout.LEFT);
		deviceField114.setOffsetNid(59);
		deviceField114.setTextOnly(true);
		deviceField114.setNumCols(25);
		deviceField115.setOffsetNid(58);
		deviceField115.setTextOnly(true);
		deviceField115.setNumCols(25);
		jPanel18.setLayout(flowLayout11);
		deviceChannel10.setLabelString("04");
		deviceChannel10.setOffsetNid(57);
		deviceChannel10.setInSameLine(true);
		deviceChannel10.setLayout(borderLayout12);
		flowLayout12.setVgap(0);
		flowLayout12.setHgap(0);
		flowLayout12.setAlignment(FlowLayout.LEFT);
		deviceField116.setOffsetNid(56);
		deviceField116.setTextOnly(true);
		deviceField116.setNumCols(25);
		deviceField117.setOffsetNid(55);
		deviceField117.setTextOnly(true);
		deviceField117.setNumCols(25);
		jPanel19.setLayout(flowLayout12);
		deviceChannel11.setLabelString("03");
		deviceChannel11.setOffsetNid(54);
		deviceChannel11.setInSameLine(true);
		deviceChannel11.setLayout(borderLayout13);
		flowLayout13.setVgap(0);
		flowLayout13.setHgap(0);
		flowLayout13.setAlignment(FlowLayout.LEFT);
		deviceField118.setOffsetNid(50);
		deviceField118.setTextOnly(true);
		deviceField118.setNumCols(25);
		deviceField119.setOffsetNid(49);
		deviceField119.setTextOnly(true);
		deviceField119.setNumCols(25);
		jPanel110.setLayout(flowLayout13);
		deviceChannel12.setLabelString("01");
		deviceChannel12.setOffsetNid(48);
		deviceChannel12.setInSameLine(true);
		deviceChannel12.setLayout(borderLayout14);
		flowLayout14.setAlignment(FlowLayout.LEFT);
		flowLayout14.setHgap(0);
		flowLayout14.setVgap(0);
		jPanel5.setLayout(flowLayout15);
		flowLayout15.setAlignment(FlowLayout.LEFT);
		flowLayout15.setHgap(0);
		flowLayout15.setVgap(0);
		jPanel6.setLayout(flowLayout16);
		flowLayout16.setAlignment(FlowLayout.LEFT);
		flowLayout16.setHgap(0);
		flowLayout16.setVgap(0);
		deviceField20.setNumCols(15);
		deviceField20.setIdentifier("");
		deviceField20.setOffsetNid(5);
		deviceField20.setLabelString("Signal Test Delay: ");
		deviceField21.setOffsetNid(6);
		deviceField21.setLabelString("Signal Test Duration");
		deviceField21.setNumCols(15);
		deviceField21.setIdentifier("");
		gridLayout4.setRows(3);
		jPanel21.setLayout(flowLayout111);
		jPanel22.setLayout(gridLayout4);
		flowLayout111.setAlignment(FlowLayout.LEFT);
		flowLayout111.setHgap(0);
		flowLayout111.setVgap(0);
		jLabel2.setText("   CARD                                GAIN                      "
				+ "                                              ADC");
		flowLayout113.setAlignment(FlowLayout.LEFT);
		flowLayout113.setHgap(0);
		flowLayout113.setVgap(0);
		jPanel23.setLayout(borderLayout21);
		jPanel24.setLayout(flowLayout113);
		flowLayout25.setAlignment(FlowLayout.LEFT);
		flowLayout25.setHgap(0);
		flowLayout25.setVgap(0);
		deviceField26.setOffsetNid(3);
		deviceField26.setTextOnly(true);
		deviceField26.setLabelString("Decoder 1: ");
		deviceField26.setNumCols(20);
		deviceField26.setIdentifier("");
		jPanel26.setLayout(flowLayout25);
		deviceField27.setOffsetNid(4);
		deviceField27.setTextOnly(true);
		deviceField27.setLabelString("Decoder 2:");
		deviceField27.setNumCols(20);
		deviceField27.setIdentifier("");
		jPanel3.setLayout(gridLayout1);
		gridLayout1.setRows(12);
		flowLayout17.setVgap(0);
		flowLayout17.setHgap(0);
		flowLayout17.setAlignment(FlowLayout.LEFT);
		deviceField22.setOffsetNid(8);
		deviceField22.setTextOnly(true);
		deviceField22.setNumCols(25);
		deviceField22.setIdentifier("");
		deviceChannel13.setLayout(borderLayout15);
		deviceChannel13.setInSameLine(true);
		deviceChannel13.setUpdateIdentifier("");
		deviceChannel13.setShowVal("");
		deviceChannel13.setLabelString("01");
		deviceChannel13.setOffsetNid(7);
		deviceField23.setOffsetNid(9);
		deviceField23.setTextOnly(true);
		deviceField23.setNumCols(25);
		deviceField23.setIdentifier("");
		jPanel20.setLayout(flowLayout17);
		flowLayout18.setVgap(0);
		flowLayout18.setHgap(0);
		flowLayout18.setAlignment(FlowLayout.LEFT);
		deviceField24.setOffsetNid(41);
		deviceField24.setTextOnly(true);
		deviceField24.setNumCols(25);
		deviceChannel14.setLayout(borderLayout16);
		deviceChannel14.setInSameLine(true);
		deviceChannel14.setLabelString("12");
		deviceChannel14.setOffsetNid(40);
		deviceField25.setOffsetNid(42);
		deviceField25.setTextOnly(true);
		deviceField25.setNumCols(25);
		jPanel25.setLayout(flowLayout18);
		flowLayout19.setVgap(0);
		flowLayout19.setHgap(0);
		flowLayout19.setAlignment(FlowLayout.LEFT);
		deviceField28.setOffsetNid(38);
		deviceField28.setTextOnly(true);
		deviceField28.setNumCols(25);
		deviceChannel15.setLayout(borderLayout17);
		deviceChannel15.setInSameLine(true);
		deviceChannel15.setLabelString("11");
		deviceChannel15.setOffsetNid(37);
		deviceField29.setOffsetNid(39);
		deviceField29.setTextOnly(true);
		deviceField29.setNumCols(25);
		jPanel27.setLayout(flowLayout19);
		flowLayout110.setVgap(0);
		flowLayout110.setHgap(0);
		flowLayout110.setAlignment(FlowLayout.LEFT);
		deviceField210.setOffsetNid(35);
		deviceField210.setTextOnly(true);
		deviceField210.setNumCols(25);
		deviceChannel16.setLayout(borderLayout18);
		deviceChannel16.setInSameLine(true);
		deviceChannel16.setLabelString("10");
		deviceChannel16.setOffsetNid(34);
		deviceField211.setOffsetNid(36);
		deviceField211.setTextOnly(true);
		deviceField211.setNumCols(25);
		jPanel28.setLayout(flowLayout110);
		flowLayout112.setVgap(0);
		flowLayout112.setHgap(0);
		flowLayout112.setAlignment(FlowLayout.LEFT);
		deviceField212.setOffsetNid(32);
		deviceField212.setTextOnly(true);
		deviceField212.setNumCols(25);
		deviceChannel17.setLayout(borderLayout19);
		deviceChannel17.setInSameLine(true);
		deviceChannel17.setLabelString("09");
		deviceChannel17.setOffsetNid(31);
		deviceField213.setOffsetNid(33);
		deviceField213.setTextOnly(true);
		deviceField213.setNumCols(25);
		jPanel29.setLayout(flowLayout112);
		flowLayout114.setVgap(0);
		flowLayout114.setHgap(0);
		flowLayout114.setAlignment(FlowLayout.LEFT);
		deviceField214.setOffsetNid(29);
		deviceField214.setTextOnly(true);
		deviceField214.setNumCols(25);
		deviceChannel18.setLayout(borderLayout110);
		deviceChannel18.setInSameLine(true);
		deviceChannel18.setLabelString("08");
		deviceChannel18.setOffsetNid(28);
		deviceField215.setOffsetNid(30);
		deviceField215.setTextOnly(true);
		deviceField215.setNumCols(25);
		jPanel210.setLayout(flowLayout114);
		flowLayout115.setVgap(0);
		flowLayout115.setHgap(0);
		flowLayout115.setAlignment(FlowLayout.LEFT);
		deviceField216.setOffsetNid(26);
		deviceField216.setTextOnly(true);
		deviceField216.setNumCols(25);
		deviceChannel19.setLayout(borderLayout111);
		deviceChannel19.setInSameLine(true);
		deviceChannel19.setLabelString("07");
		deviceChannel19.setOffsetNid(25);
		deviceField217.setOffsetNid(27);
		deviceField217.setTextOnly(true);
		deviceField217.setNumCols(25);
		jPanel211.setLayout(flowLayout115);
		flowLayout116.setVgap(0);
		flowLayout116.setHgap(0);
		flowLayout116.setAlignment(FlowLayout.LEFT);
		deviceField218.setOffsetNid(23);
		deviceField218.setTextOnly(true);
		deviceField218.setNumCols(25);
		deviceChannel110.setLayout(borderLayout112);
		deviceChannel110.setInSameLine(true);
		deviceChannel110.setLabelString("06");
		deviceChannel110.setOffsetNid(22);
		deviceField219.setOffsetNid(24);
		deviceField219.setTextOnly(true);
		deviceField219.setNumCols(25);
		jPanel212.setLayout(flowLayout116);
		flowLayout117.setVgap(0);
		flowLayout117.setHgap(0);
		flowLayout117.setAlignment(FlowLayout.LEFT);
		deviceField2110.setOffsetNid(20);
		deviceField2110.setTextOnly(true);
		deviceField2110.setNumCols(25);
		deviceChannel111.setLayout(borderLayout113);
		deviceChannel111.setInSameLine(true);
		deviceChannel111.setLabelString("05");
		deviceChannel111.setOffsetNid(19);
		deviceChannel111.setLines(1);
		deviceField2111.setOffsetNid(21);
		deviceField2111.setTextOnly(true);
		deviceField2111.setNumCols(25);
		jPanel213.setLayout(flowLayout117);
		flowLayout118.setVgap(0);
		flowLayout118.setHgap(0);
		flowLayout118.setAlignment(FlowLayout.LEFT);
		deviceField2112.setOffsetNid(17);
		deviceField2112.setTextOnly(true);
		deviceField2112.setNumCols(25);
		deviceChannel112.setLayout(borderLayout114);
		deviceChannel112.setInSameLine(true);
		deviceChannel112.setLabelString("04");
		deviceChannel112.setOffsetNid(16);
		deviceChannel112.setLines(1);
		deviceField2113.setOffsetNid(18);
		deviceField2113.setTextOnly(true);
		deviceField2113.setNumCols(25);
		jPanel214.setLayout(flowLayout118);
		flowLayout119.setVgap(0);
		flowLayout119.setHgap(0);
		flowLayout119.setAlignment(FlowLayout.LEFT);
		deviceField2114.setOffsetNid(14);
		deviceField2114.setTextOnly(true);
		deviceField2114.setNumCols(25);
		deviceChannel113.setLayout(borderLayout115);
		deviceChannel113.setInSameLine(true);
		deviceChannel113.setLabelString("03");
		deviceChannel113.setOffsetNid(13);
		deviceChannel113.setLines(1);
		deviceField2115.setOffsetNid(15);
		deviceField2115.setTextOnly(true);
		deviceField2115.setNumCols(25);
		jPanel215.setLayout(flowLayout119);
		flowLayout1110.setVgap(0);
		flowLayout1110.setHgap(0);
		flowLayout1110.setAlignment(FlowLayout.LEFT);
		deviceField2116.setOffsetNid(11);
		deviceField2116.setTextOnly(true);
		deviceField2116.setNumCols(25);
		deviceChannel114.setLayout(borderLayout116);
		deviceChannel114.setInSameLine(true);
		deviceChannel114.setUpdateIdentifier("");
		deviceChannel114.setShowVal("");
		deviceChannel114.setLabelString("02");
		deviceChannel114.setOffsetNid(10);
		deviceField2117.setOffsetNid(12);
		deviceField2117.setTextOnly(true);
		deviceField2117.setNumCols(25);
		jPanel216.setLayout(flowLayout1110);
		deviceButtons1.setMethods(new String[]
		{ "init" });
		deviceChannel20.setLayout(borderLayout20);
		jPanel30.setLayout(borderLayout22);
		deviceChannel20.setLabelString("");
		deviceChannel20.setOffsetNid(2);
		deviceChannel20.setUpdateIdentifier("");
		deviceChannel20.setShowVal("");
		deviceChannel21.setLayout(borderLayout23);
		jPanel31.setLayout(borderLayout24);
		deviceChannel21.setLabelString("");
		deviceChannel21.setOffsetNid(43);
		deviceChannel21.setUpdateIdentifier("");
		deviceChannel21.setShowVal("");
		this.getContentPane().add(jPanel1, BorderLayout.NORTH);
		jPanel1.add(deviceField1, null);
		this.getContentPane().add(jTabbedPane1, BorderLayout.CENTER);
		jPanel5.add(deviceField3, null);
		jPanel5.add(deviceField2, null);
		jPanel4.add(jPanel6, null);
		jPanel4.add(jPanel5, null);
		jPanel6.add(deviceField5, null);
		jPanel6.add(deviceField4, null);
		jPanel4.add(jPanel9, null);
		jPanel9.add(jLabel1, null);
		jPanel2.add(deviceChannel21, BorderLayout.NORTH);
		deviceChannel21.add(jPanel31, BorderLayout.CENTER);
//    jPanel2.add(jScrollPane1, BorderLayout.CENTER);
		jPanel31.add(jScrollPane1, BorderLayout.CENTER);
		jScrollPane1.getViewport().add(jPanel7, null);
//    jPanel2.add(jPanel4, BorderLayout.SOUTH);
		jPanel31.add(jPanel4, BorderLayout.NORTH);
		jPanel8.add(deviceField6, null);
		jPanel8.add(deviceField7, null);
		jPanel7.add(deviceChannel12, null);
		deviceChannel12.add(jPanel110, BorderLayout.CENTER);
		jPanel7.add(deviceChannel1, null);
		deviceChannel1.add(jPanel8, BorderLayout.CENTER);
		jPanel110.add(deviceField119, null);
		jPanel110.add(deviceField118, null);
		jPanel7.add(deviceChannel11, null);
		deviceChannel11.add(jPanel19, BorderLayout.CENTER);
		jPanel19.add(deviceField117, null);
		jPanel19.add(deviceField116, null);
		jPanel7.add(deviceChannel10, null);
		deviceChannel10.add(jPanel18, BorderLayout.CENTER);
		jPanel18.add(deviceField115, null);
		jPanel18.add(deviceField114, null);
		jPanel7.add(deviceChannel9, null);
		deviceChannel9.add(jPanel17, BorderLayout.CENTER);
		jPanel17.add(deviceField113, null);
		jPanel17.add(deviceField112, null);
		jPanel7.add(deviceChannel8, null);
		deviceChannel8.add(jPanel16, BorderLayout.CENTER);
		jPanel16.add(deviceField111, null);
		jPanel16.add(deviceField110, null);
		jPanel7.add(deviceChannel7, null);
		deviceChannel7.add(jPanel15, BorderLayout.CENTER);
		jPanel15.add(deviceField19, null);
		jPanel15.add(deviceField18, null);
		jPanel7.add(deviceChannel6, null);
		deviceChannel6.add(jPanel14, BorderLayout.CENTER);
		jPanel14.add(deviceField17, null);
		jPanel14.add(deviceField16, null);
		jPanel7.add(deviceChannel5, null);
		deviceChannel5.add(jPanel13, BorderLayout.CENTER);
		jPanel13.add(deviceField15, null);
		jPanel13.add(deviceField14, null);
		jPanel7.add(deviceChannel4, null);
		deviceChannel4.add(jPanel12, BorderLayout.CENTER);
		jPanel12.add(deviceField13, null);
		jPanel12.add(deviceField12, null);
		jPanel7.add(deviceChannel3, null);
		deviceChannel3.add(jPanel11, BorderLayout.CENTER);
		jPanel11.add(deviceField11, null);
		jPanel11.add(deviceField10, null);
		jPanel7.add(deviceChannel2, null);
		deviceChannel2.add(jPanel10, BorderLayout.CENTER);
		jPanel10.add(deviceField9, null);
		jPanel10.add(deviceField8, null);
		jTabbedPane1.add(jPanel23, "POLOIDAL");
		jPanel24.add(deviceField26, null);
		jPanel24.add(deviceField27, null);
		jPanel22.add(jPanel21, null);
		jPanel22.add(jPanel24, null);
		jPanel21.add(deviceField20, null);
		jPanel21.add(deviceField21, null);
		jPanel22.add(jPanel26, null);
		jPanel26.add(jLabel2, null);
		jPanel23.add(deviceChannel20, BorderLayout.NORTH);
		deviceChannel20.add(jPanel30, BorderLayout.CENTER);
		// jPanel23.add(jScrollPane2, BorderLayout.CENTER);
		jPanel30.add(jScrollPane2, BorderLayout.CENTER);
		jTabbedPane1.add(jPanel2, "TOROIDAL");
		jScrollPane2.getViewport().add(jPanel3, null);
		jPanel3.add(deviceChannel13, null);
		deviceChannel13.add(jPanel20, BorderLayout.CENTER);
		jPanel20.add(deviceField22, null);
		jPanel20.add(deviceField23, null);
		jPanel3.add(deviceChannel114, null);
		deviceChannel114.add(jPanel216, BorderLayout.CENTER);
		jPanel216.add(deviceField2116, null);
		jPanel216.add(deviceField2117, null);
		jPanel3.add(deviceChannel113, null);
		deviceChannel113.add(jPanel215, BorderLayout.CENTER);
		jPanel215.add(deviceField2114, null);
		jPanel215.add(deviceField2115, null);
		jPanel3.add(deviceChannel112, null);
		deviceChannel112.add(jPanel214, BorderLayout.CENTER);
		jPanel214.add(deviceField2112, null);
		jPanel214.add(deviceField2113, null);
		jPanel3.add(deviceChannel111, null);
		deviceChannel111.add(jPanel213, BorderLayout.CENTER);
		jPanel213.add(deviceField2110, null);
		jPanel213.add(deviceField2111, null);
		jPanel3.add(deviceChannel110, null);
		deviceChannel110.add(jPanel212, BorderLayout.CENTER);
		jPanel212.add(deviceField218, null);
		jPanel212.add(deviceField219, null);
		jPanel3.add(deviceChannel19, null);
		deviceChannel19.add(jPanel211, BorderLayout.CENTER);
		jPanel211.add(deviceField216, null);
		jPanel211.add(deviceField217, null);
		jPanel3.add(deviceChannel18, null);
		deviceChannel18.add(jPanel210, BorderLayout.CENTER);
		jPanel210.add(deviceField214, null);
		jPanel210.add(deviceField215, null);
		jPanel3.add(deviceChannel17, null);
		deviceChannel17.add(jPanel29, BorderLayout.CENTER);
		jPanel29.add(deviceField212, null);
		jPanel29.add(deviceField213, null);
		jPanel3.add(deviceChannel16, null);
		deviceChannel16.add(jPanel28, BorderLayout.CENTER);
		jPanel28.add(deviceField210, null);
		jPanel28.add(deviceField211, null);
		jPanel3.add(deviceChannel15, null);
		deviceChannel15.add(jPanel27, BorderLayout.CENTER);
		jPanel27.add(deviceField28, null);
		jPanel27.add(deviceField29, null);
		jPanel3.add(deviceChannel14, null);
		deviceChannel14.add(jPanel25, BorderLayout.CENTER);
		jPanel25.add(deviceField24, null);
		jPanel25.add(deviceField25, null);
//    jPanel23.add(jPanel22, BorderLayout.SOUTH);
		jPanel30.add(jPanel22, BorderLayout.NORTH);
		this.getContentPane().add(deviceButtons1, BorderLayout.SOUTH);
	}
}
