import java.awt.*;
import javax.swing.*;

/**
 * <p>
 * Title:
 * </p>
 * <p>
 * Description:
 * </p>
 * <p>
 * Copyright: Copyright (c) 2003
 * </p>
 * <p>
 * Company:
 * </p>
 *
 * @author not attributable
 * @version 1.0
 */
public class FLU_GAINSetup extends DeviceSetup
{
	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	BorderLayout borderLayout1 = new BorderLayout();
	JPanel jPanel1 = new JPanel();
	GridLayout gridLayout1 = new GridLayout();
	JPanel jPanel2 = new JPanel();
	JPanel jPanel3 = new JPanel();
	DeviceField deviceField1 = new DeviceField();
	FlowLayout flowLayout1 = new FlowLayout();
	DeviceDispatch deviceDispatch1 = new DeviceDispatch();
	FlowLayout flowLayout2 = new FlowLayout();
	DeviceField deviceField2 = new DeviceField();
	DeviceChoice deviceChoice1 = new DeviceChoice();
	DeviceButtons deviceButtons1 = new DeviceButtons();
	JScrollPane jScrollPane1 = new JScrollPane();
	JPanel jPanel4 = new JPanel();
	GridLayout gridLayout2 = new GridLayout();
	JPanel jPanel5 = new JPanel();
	DeviceChannel deviceChannel1 = new DeviceChannel();
	FlowLayout flowLayout3 = new FlowLayout();
	JPanel jPanel6 = new JPanel();
	DeviceChoice deviceChoice2 = new DeviceChoice();
	BorderLayout borderLayout2 = new BorderLayout();
	FlowLayout flowLayout4 = new FlowLayout();
	DeviceField deviceField3 = new DeviceField();
	DeviceField deviceField4 = new DeviceField();
	DeviceField deviceField5 = new DeviceField();
	DeviceField deviceField6 = new DeviceField();
	DeviceChoice deviceChoice3 = new DeviceChoice();
	JPanel jPanel7 = new JPanel();
	FlowLayout flowLayout5 = new FlowLayout();
	JLabel jLabel1 = new JLabel();
	FlowLayout flowLayout6 = new FlowLayout();
	DeviceField deviceField7 = new DeviceField();
	JPanel jPanel8 = new JPanel();
	DeviceField deviceField8 = new DeviceField();
	DeviceChoice deviceChoice4 = new DeviceChoice();
	BorderLayout borderLayout3 = new BorderLayout();
	DeviceChannel deviceChannel2 = new DeviceChannel();
	DeviceField deviceField9 = new DeviceField();
	FlowLayout flowLayout7 = new FlowLayout();
	JPanel jPanel9 = new JPanel();
	DeviceChoice deviceChoice5 = new DeviceChoice();
	DeviceField deviceField10 = new DeviceField();
	FlowLayout flowLayout8 = new FlowLayout();
	DeviceField deviceField11 = new DeviceField();
	JPanel jPanel10 = new JPanel();
	DeviceField deviceField12 = new DeviceField();
	DeviceChoice deviceChoice6 = new DeviceChoice();
	BorderLayout borderLayout4 = new BorderLayout();
	DeviceChannel deviceChannel3 = new DeviceChannel();
	DeviceField deviceField13 = new DeviceField();
	FlowLayout flowLayout9 = new FlowLayout();
	JPanel jPanel11 = new JPanel();
	DeviceChoice deviceChoice7 = new DeviceChoice();
	DeviceField deviceField14 = new DeviceField();
	FlowLayout flowLayout10 = new FlowLayout();
	DeviceField deviceField15 = new DeviceField();
	JPanel jPanel12 = new JPanel();
	DeviceField deviceField16 = new DeviceField();
	DeviceChoice deviceChoice8 = new DeviceChoice();
	BorderLayout borderLayout5 = new BorderLayout();
	DeviceChannel deviceChannel4 = new DeviceChannel();
	DeviceField deviceField17 = new DeviceField();
	FlowLayout flowLayout11 = new FlowLayout();
	JPanel jPanel13 = new JPanel();
	DeviceChoice deviceChoice9 = new DeviceChoice();
	DeviceField deviceField18 = new DeviceField();
	FlowLayout flowLayout12 = new FlowLayout();
	DeviceField deviceField19 = new DeviceField();
	JPanel jPanel14 = new JPanel();
	DeviceField deviceField110 = new DeviceField();
	DeviceChoice deviceChoice10 = new DeviceChoice();
	BorderLayout borderLayout6 = new BorderLayout();
	DeviceChannel deviceChannel5 = new DeviceChannel();
	DeviceField deviceField111 = new DeviceField();
	FlowLayout flowLayout13 = new FlowLayout();
	JPanel jPanel15 = new JPanel();
	DeviceChoice deviceChoice11 = new DeviceChoice();
	DeviceField deviceField112 = new DeviceField();
	FlowLayout flowLayout14 = new FlowLayout();
	DeviceField deviceField113 = new DeviceField();
	JPanel jPanel16 = new JPanel();
	DeviceField deviceField114 = new DeviceField();
	DeviceChoice deviceChoice12 = new DeviceChoice();
	BorderLayout borderLayout7 = new BorderLayout();
	DeviceChannel deviceChannel6 = new DeviceChannel();
	DeviceField deviceField115 = new DeviceField();
	FlowLayout flowLayout15 = new FlowLayout();
	JPanel jPanel17 = new JPanel();
	DeviceChoice deviceChoice13 = new DeviceChoice();
	DeviceField deviceField116 = new DeviceField();
	FlowLayout flowLayout16 = new FlowLayout();
	DeviceField deviceField117 = new DeviceField();
	JPanel jPanel18 = new JPanel();
	DeviceField deviceField118 = new DeviceField();
	DeviceChoice deviceChoice14 = new DeviceChoice();
	BorderLayout borderLayout8 = new BorderLayout();
	DeviceChannel deviceChannel7 = new DeviceChannel();
	DeviceField deviceField119 = new DeviceField();
	FlowLayout flowLayout17 = new FlowLayout();
	JPanel jPanel19 = new JPanel();
	DeviceChoice deviceChoice15 = new DeviceChoice();
	DeviceField deviceField1110 = new DeviceField();
	FlowLayout flowLayout18 = new FlowLayout();
	DeviceField deviceField1111 = new DeviceField();
	JPanel jPanel110 = new JPanel();
	DeviceField deviceField1112 = new DeviceField();
	DeviceChoice deviceChoice16 = new DeviceChoice();
	BorderLayout borderLayout9 = new BorderLayout();
	DeviceChannel deviceChannel8 = new DeviceChannel();
	DeviceField deviceField1113 = new DeviceField();
	FlowLayout flowLayout19 = new FlowLayout();
	JPanel jPanel111 = new JPanel();
	DeviceChoice deviceChoice17 = new DeviceChoice();
	DeviceField deviceField1114 = new DeviceField();
	FlowLayout flowLayout110 = new FlowLayout();
	DeviceField deviceField1115 = new DeviceField();
	JPanel jPanel112 = new JPanel();
	DeviceField deviceField1116 = new DeviceField();
	DeviceChoice deviceChoice18 = new DeviceChoice();
	BorderLayout borderLayout10 = new BorderLayout();
	DeviceChannel deviceChannel9 = new DeviceChannel();
	DeviceField deviceField1117 = new DeviceField();
	FlowLayout flowLayout111 = new FlowLayout();
	JPanel jPanel113 = new JPanel();
	DeviceChoice deviceChoice19 = new DeviceChoice();
	DeviceField deviceField1118 = new DeviceField();
	FlowLayout flowLayout112 = new FlowLayout();
	DeviceField deviceField1119 = new DeviceField();
	JPanel jPanel114 = new JPanel();
	DeviceField deviceField11110 = new DeviceField();
	DeviceChoice deviceChoice110 = new DeviceChoice();
	BorderLayout borderLayout11 = new BorderLayout();
	DeviceChannel deviceChannel10 = new DeviceChannel();
	DeviceField deviceField11111 = new DeviceField();
	FlowLayout flowLayout113 = new FlowLayout();
	JPanel jPanel115 = new JPanel();
	DeviceChoice deviceChoice111 = new DeviceChoice();
	DeviceField deviceField11112 = new DeviceField();
	FlowLayout flowLayout114 = new FlowLayout();
	DeviceField deviceField11113 = new DeviceField();
	JPanel jPanel116 = new JPanel();
	DeviceField deviceField11114 = new DeviceField();
	DeviceChoice deviceChoice112 = new DeviceChoice();
	BorderLayout borderLayout12 = new BorderLayout();
	DeviceChannel deviceChannel11 = new DeviceChannel();
	DeviceField deviceField11115 = new DeviceField();
	FlowLayout flowLayout115 = new FlowLayout();
	JPanel jPanel117 = new JPanel();
	DeviceChoice deviceChoice113 = new DeviceChoice();
	DeviceField deviceField11116 = new DeviceField();
	FlowLayout flowLayout116 = new FlowLayout();
	DeviceField deviceField11117 = new DeviceField();
	JPanel jPanel118 = new JPanel();
	DeviceField deviceField11118 = new DeviceField();
	DeviceChoice deviceChoice114 = new DeviceChoice();
	BorderLayout borderLayout13 = new BorderLayout();
	DeviceChannel deviceChannel12 = new DeviceChannel();
	DeviceField deviceField11119 = new DeviceField();
	FlowLayout flowLayout117 = new FlowLayout();
	JPanel jPanel119 = new JPanel();
	DeviceChoice deviceChoice115 = new DeviceChoice();
	DeviceField deviceField111110 = new DeviceField();
	FlowLayout flowLayout118 = new FlowLayout();
	DeviceField deviceField111111 = new DeviceField();
	JPanel jPanel1110 = new JPanel();
	DeviceField deviceField111112 = new DeviceField();
	DeviceChoice deviceChoice116 = new DeviceChoice();
	BorderLayout borderLayout14 = new BorderLayout();
	DeviceChannel deviceChannel13 = new DeviceChannel();
	DeviceField deviceField111113 = new DeviceField();
	FlowLayout flowLayout119 = new FlowLayout();
	JPanel jPanel1111 = new JPanel();
	DeviceChoice deviceChoice117 = new DeviceChoice();
	DeviceField deviceField111114 = new DeviceField();
	FlowLayout flowLayout1110 = new FlowLayout();
	DeviceField deviceField111115 = new DeviceField();
	JPanel jPanel1112 = new JPanel();
	DeviceField deviceField111116 = new DeviceField();
	DeviceChoice deviceChoice118 = new DeviceChoice();
	BorderLayout borderLayout15 = new BorderLayout();
	DeviceChannel deviceChannel14 = new DeviceChannel();
	DeviceField deviceField111117 = new DeviceField();
	FlowLayout flowLayout1111 = new FlowLayout();
	JPanel jPanel1113 = new JPanel();
	DeviceChoice deviceChoice119 = new DeviceChoice();
	DeviceField deviceField111118 = new DeviceField();
	FlowLayout flowLayout1112 = new FlowLayout();
	DeviceField deviceField111119 = new DeviceField();
	JPanel jPanel1114 = new JPanel();
	DeviceField deviceField1111110 = new DeviceField();
	DeviceChoice deviceChoice1110 = new DeviceChoice();
	BorderLayout borderLayout16 = new BorderLayout();
	DeviceChannel deviceChannel15 = new DeviceChannel();
	DeviceField deviceField1111111 = new DeviceField();
	FlowLayout flowLayout1113 = new FlowLayout();
	JPanel jPanel1115 = new JPanel();
	DeviceChoice deviceChoice1111 = new DeviceChoice();
	DeviceField deviceField1111112 = new DeviceField();
	FlowLayout flowLayout1114 = new FlowLayout();
	DeviceField deviceField1111113 = new DeviceField();
	JPanel jPanel1116 = new JPanel();
	DeviceField deviceField1111114 = new DeviceField();
	DeviceChoice deviceChoice1112 = new DeviceChoice();
	BorderLayout borderLayout17 = new BorderLayout();
	DeviceChannel deviceChannel16 = new DeviceChannel();
	DeviceField deviceField1111115 = new DeviceField();
	FlowLayout flowLayout1115 = new FlowLayout();
	JPanel jPanel1117 = new JPanel();
	DeviceChoice deviceChoice1113 = new DeviceChoice();
	DeviceField deviceField1111116 = new DeviceField();

	public FLU_GAINSetup()
	{
		try
		{
			jbInit();
		}
		catch (final Exception e)
		{
			e.printStackTrace();
		}
	}

	private void jbInit() throws Exception
	{
		this.setWidth(690);
		this.setHeight(750);
		this.setDeviceType("FLU_GAIN");
		this.setDeviceProvider("150.178.3.33");
		this.setDeviceTitle("Electomagnetic Gain & Front-end HARDWARE Configuration");
		this.getContentPane().setLayout(borderLayout1);
		jPanel1.setLayout(gridLayout1);
		gridLayout1.setRows(3);
		deviceField1.setOffsetNid(1);
		deviceField1.setLabelString("Comment: ");
		deviceField1.setNumCols(25);
		deviceField1.setIdentifier("");
		jPanel2.setLayout(flowLayout1);
		flowLayout1.setAlignment(FlowLayout.LEFT);
		flowLayout1.setHgap(0);
		flowLayout1.setVgap(0);
		jPanel3.setLayout(flowLayout2);
		flowLayout2.setAlignment(FlowLayout.LEFT);
		flowLayout2.setHgap(0);
		flowLayout2.setVgap(0);
		deviceField2.setOffsetNid(2);
		deviceField2.setLabelString("ADC :");
		deviceField2.setNumCols(25);
		deviceField2.setIdentifier("");
		deviceChoice1.setChoiceIntValues(null);
		deviceChoice1.setChoiceFloatValues(null);
		deviceChoice1.setOffsetNid(3);
		deviceChoice1.setLabelString("Acquired Signals: ");
		deviceChoice1.setChoiceItems(new String[]
		{ "INTEGRAL", "LINEAR" });
		deviceChoice1.setUpdateIdentifier("");
		deviceChoice1.setIdentifier("");
		jPanel4.setLayout(gridLayout2);
		gridLayout2.setRows(16);
		jPanel5.setLayout(flowLayout3);
		deviceChannel1.setLabelString("01");
		deviceChannel1.setOffsetNid(4);
		deviceChannel1.setInSameLine(true);
		deviceChannel1.setUpdateIdentifier("");
		deviceChannel1.setShowVal("");
		deviceChannel1.setLayout(borderLayout2);
		flowLayout3.setAlignment(FlowLayout.LEFT);
		flowLayout3.setHgap(0);
		flowLayout3.setVgap(0);
		deviceChoice2.setChoiceIntValues(null);
		deviceChoice2.setChoiceFloatValues(new float[]
		{ (float) 1.0, (float) 2.9, (float) 4.0 });
		deviceChoice2.setOffsetNid(5);
		deviceChoice2.setLabelString(" ");
		deviceChoice2.setChoiceItems(new String[]
		{ "1", "2.9", "4" });
		deviceChoice2.setUpdateIdentifier("");
		deviceChoice2.setIdentifier("");
		jPanel6.setLayout(flowLayout4);
		flowLayout4.setAlignment(FlowLayout.LEFT);
		flowLayout4.setHgap(0);
		flowLayout4.setVgap(0);
		deviceChoice3.setChoiceIntValues(new int[]
		{ 1, 2, 4, 8 });
		deviceChoice3.setChoiceFloatValues(null);
		deviceChoice3.setOffsetNid(12);
		deviceChoice3.setLabelString(" ");
		deviceChoice3.setChoiceItems(new String[]
		{ "1", "2", "4", "8" });
		deviceChoice3.setUpdateIdentifier("");
		deviceChoice3.setIdentifier("");
		jPanel7.setLayout(flowLayout5);
		flowLayout5.setAlignment(FlowLayout.LEFT);
		flowLayout5.setHgap(0);
		flowLayout5.setVgap(0);
		jLabel1.setText("Channel      Att.            Linear Name                Lin. "
				+ "Calib.               Int. Name                  Int. Calib  " + "          Int Gain ");
		deviceField3.setOffsetNid(6);
		deviceField3.setTextOnly(true);
		deviceField3.setIdentifier("");
		deviceField3.setEditable(false);
		deviceField6.setOffsetNid(7);
		deviceField6.setIdentifier("");
		deviceField5.setOffsetNid(10);
		deviceField5.setTextOnly(true);
		deviceField5.setIdentifier("");
		deviceField5.setEditable(false);
		deviceField4.setOffsetNid(11);
		deviceField4.setIdentifier("");
		flowLayout6.setVgap(0);
		flowLayout6.setHgap(0);
		flowLayout6.setAlignment(FlowLayout.LEFT);
		deviceField7.setIdentifier("");
		deviceField7.setEditable(false);
		deviceField7.setOffsetNid(175);
		deviceField7.setTextOnly(true);
		jPanel8.setLayout(flowLayout7);
		deviceField8.setOffsetNid(171);
		deviceField8.setTextOnly(true);
		deviceField8.setIdentifier("");
		deviceField8.setEditable(false);
		deviceChoice4.setChoiceIntValues(null);
		deviceChoice4.setChoiceFloatValues(new float[]
		{ (float) 1.0, (float) 2.9, (float) 4.0 });
		deviceChoice4.setOffsetNid(170);
		deviceChoice4.setLabelString(" ");
		deviceChoice4.setChoiceItems(new String[]
		{ "1", "2.9", "4" });
		deviceChoice4.setUpdateIdentifier("");
		deviceChoice4.setIdentifier("");
		deviceChannel2.setLabelString("16");
		deviceChannel2.setOffsetNid(169);
		deviceChannel2.setInSameLine(true);
		deviceChannel2.setUpdateIdentifier("");
		deviceChannel2.setShowVal("");
		deviceChannel2.setLayout(borderLayout3);
		deviceField9.setOffsetNid(172);
		deviceField9.setIdentifier("");
		flowLayout7.setAlignment(FlowLayout.LEFT);
		flowLayout7.setHgap(0);
		flowLayout7.setVgap(0);
		jPanel9.setLayout(flowLayout6);
		deviceChoice5.setChoiceIntValues(new int[]
		{ 1, 2, 4, 8 });
		deviceChoice5.setChoiceFloatValues(null);
		deviceChoice5.setOffsetNid(177);
		deviceChoice5.setLabelString(" ");
		deviceChoice5.setChoiceItems(new String[]
		{ "1", "2", "4", "8" });
		deviceChoice5.setUpdateIdentifier("");
		deviceChoice5.setIdentifier("");
		deviceField10.setOffsetNid(176);
		deviceField10.setIdentifier("");
		flowLayout8.setVgap(0);
		flowLayout8.setHgap(0);
		flowLayout8.setAlignment(FlowLayout.LEFT);
		deviceField11.setIdentifier("");
		deviceField11.setEditable(false);
		deviceField11.setOffsetNid(164);
		deviceField11.setTextOnly(true);
		jPanel10.setLayout(flowLayout9);
		deviceField12.setOffsetNid(160);
		deviceField12.setTextOnly(true);
		deviceField12.setIdentifier("");
		deviceField12.setEditable(false);
		deviceChoice6.setChoiceIntValues(null);
		deviceChoice6.setChoiceFloatValues(new float[]
		{ (float) 1.0, (float) 2.9, (float) 4.0 });
		deviceChoice6.setOffsetNid(159);
		deviceChoice6.setLabelString(" ");
		deviceChoice6.setChoiceItems(new String[]
		{ "1", "2.9", "4" });
		deviceChoice6.setUpdateIdentifier("");
		deviceChoice6.setIdentifier("");
		deviceChannel3.setLabelString("15");
		deviceChannel3.setOffsetNid(158);
		deviceChannel3.setInSameLine(true);
		deviceChannel3.setUpdateIdentifier("");
		deviceChannel3.setShowVal("");
		deviceChannel3.setLayout(borderLayout4);
		deviceField13.setOffsetNid(161);
		deviceField13.setIdentifier("");
		flowLayout9.setAlignment(FlowLayout.LEFT);
		flowLayout9.setHgap(0);
		flowLayout9.setVgap(0);
		jPanel11.setLayout(flowLayout8);
		deviceChoice7.setChoiceIntValues(new int[]
		{ 1, 2, 4, 8 });
		deviceChoice7.setChoiceFloatValues(null);
		deviceChoice7.setOffsetNid(166);
		deviceChoice7.setLabelString(" ");
		deviceChoice7.setChoiceItems(new String[]
		{ "1", "2", "4", "8" });
		deviceChoice7.setUpdateIdentifier("");
		deviceChoice7.setIdentifier("");
		deviceField14.setOffsetNid(165);
		deviceField14.setIdentifier("");
		flowLayout10.setVgap(0);
		flowLayout10.setHgap(0);
		flowLayout10.setAlignment(FlowLayout.LEFT);
		deviceField15.setIdentifier("");
		deviceField15.setEditable(false);
		deviceField15.setOffsetNid(153);
		deviceField15.setTextOnly(true);
		jPanel12.setLayout(flowLayout11);
		deviceField16.setOffsetNid(149);
		deviceField16.setTextOnly(true);
		deviceField16.setIdentifier("");
		deviceField16.setEditable(false);
		deviceChoice8.setChoiceIntValues(null);
		deviceChoice8.setChoiceFloatValues(new float[]
		{ (float) 1.0, (float) 2.9, (float) 4.0 });
		deviceChoice8.setOffsetNid(148);
		deviceChoice8.setLabelString(" ");
		deviceChoice8.setChoiceItems(new String[]
		{ "1", "2.9", "4" });
		deviceChoice8.setUpdateIdentifier("");
		deviceChoice8.setIdentifier("");
		deviceChannel4.setLabelString("14");
		deviceChannel4.setOffsetNid(147);
		deviceChannel4.setInSameLine(true);
		deviceChannel4.setUpdateIdentifier("");
		deviceChannel4.setShowVal("");
		deviceChannel4.setLayout(borderLayout5);
		deviceField17.setOffsetNid(150);
		deviceField17.setIdentifier("");
		flowLayout11.setAlignment(FlowLayout.LEFT);
		flowLayout11.setHgap(0);
		flowLayout11.setVgap(0);
		jPanel13.setLayout(flowLayout10);
		deviceChoice9.setChoiceIntValues(new int[]
		{ 1, 2, 4, 8 });
		deviceChoice9.setChoiceFloatValues(null);
		deviceChoice9.setOffsetNid(155);
		deviceChoice9.setLabelString(" ");
		deviceChoice9.setChoiceItems(new String[]
		{ "1", "2", "4", "8" });
		deviceChoice9.setUpdateIdentifier("");
		deviceChoice9.setIdentifier("");
		deviceField18.setOffsetNid(154);
		deviceField18.setIdentifier("");
		flowLayout12.setVgap(0);
		flowLayout12.setHgap(0);
		flowLayout12.setAlignment(FlowLayout.LEFT);
		deviceField19.setIdentifier("");
		deviceField19.setEditable(false);
		deviceField19.setOffsetNid(142);
		deviceField19.setTextOnly(true);
		jPanel14.setLayout(flowLayout13);
		deviceField110.setOffsetNid(138);
		deviceField110.setTextOnly(true);
		deviceField110.setIdentifier("");
		deviceField110.setEditable(false);
		deviceChoice10.setChoiceIntValues(null);
		deviceChoice10.setChoiceFloatValues(new float[]
		{ (float) 1.0, (float) 2.9, (float) 4.0 });
		deviceChoice10.setOffsetNid(137);
		deviceChoice10.setLabelString(" ");
		deviceChoice10.setChoiceItems(new String[]
		{ "1", "2.9", "4" });
		deviceChoice10.setUpdateIdentifier("");
		deviceChoice10.setIdentifier("");
		deviceChannel5.setLabelString("13");
		deviceChannel5.setOffsetNid(136);
		deviceChannel5.setInSameLine(true);
		deviceChannel5.setUpdateIdentifier("");
		deviceChannel5.setShowVal("");
		deviceChannel5.setLayout(borderLayout6);
		deviceField111.setOffsetNid(139);
		deviceField111.setNumCols(10);
		deviceField111.setIdentifier("");
		flowLayout13.setAlignment(FlowLayout.LEFT);
		flowLayout13.setHgap(0);
		flowLayout13.setVgap(0);
		jPanel15.setLayout(flowLayout12);
		deviceChoice11.setChoiceIntValues(new int[]
		{ 1, 2, 4, 8 });
		deviceChoice11.setChoiceFloatValues(null);
		deviceChoice11.setOffsetNid(144);
		deviceChoice11.setLabelString(" ");
		deviceChoice11.setChoiceItems(new String[]
		{ "1", "2", "4", "8" });
		deviceChoice11.setUpdateIdentifier("");
		deviceChoice11.setIdentifier("");
		deviceField112.setOffsetNid(143);
		deviceField112.setIdentifier("");
		flowLayout14.setVgap(0);
		flowLayout14.setHgap(0);
		flowLayout14.setAlignment(FlowLayout.LEFT);
		deviceField113.setIdentifier("");
		deviceField113.setEditable(false);
		deviceField113.setOffsetNid(131);
		deviceField113.setTextOnly(true);
		jPanel16.setLayout(flowLayout15);
		deviceField114.setOffsetNid(127);
		deviceField114.setTextOnly(true);
		deviceField114.setIdentifier("");
		deviceField114.setEditable(false);
		deviceChoice12.setChoiceIntValues(null);
		deviceChoice12.setChoiceFloatValues(new float[]
		{ (float) 1.0, (float) 2.9, (float) 4.0 });
		deviceChoice12.setOffsetNid(126);
		deviceChoice12.setLabelString(" ");
		deviceChoice12.setChoiceItems(new String[]
		{ "1", "2.9", "4" });
		deviceChoice12.setUpdateIdentifier("");
		deviceChoice12.setIdentifier("");
		deviceChannel6.setLabelString("12");
		deviceChannel6.setOffsetNid(125);
		deviceChannel6.setInSameLine(true);
		deviceChannel6.setUpdateIdentifier("");
		deviceChannel6.setShowVal("");
		deviceChannel6.setLayout(borderLayout7);
		deviceField115.setOffsetNid(128);
		deviceField115.setIdentifier("");
		flowLayout15.setAlignment(FlowLayout.LEFT);
		flowLayout15.setHgap(0);
		flowLayout15.setVgap(0);
		jPanel17.setLayout(flowLayout14);
		deviceChoice13.setChoiceIntValues(new int[]
		{ 1, 2, 4, 8 });
		deviceChoice13.setChoiceFloatValues(null);
		deviceChoice13.setOffsetNid(133);
		deviceChoice13.setLabelString(" ");
		deviceChoice13.setChoiceItems(new String[]
		{ "1", "2", "4", "8" });
		deviceChoice13.setUpdateIdentifier("");
		deviceChoice13.setIdentifier("");
		deviceField116.setOffsetNid(132);
		deviceField116.setIdentifier("");
		flowLayout16.setVgap(0);
		flowLayout16.setHgap(0);
		flowLayout16.setAlignment(FlowLayout.LEFT);
		deviceField117.setIdentifier("");
		deviceField117.setEditable(false);
		deviceField117.setOffsetNid(120);
		deviceField117.setTextOnly(true);
		jPanel18.setLayout(flowLayout17);
		deviceField118.setOffsetNid(116);
		deviceField118.setTextOnly(true);
		deviceField118.setIdentifier("");
		deviceField118.setEditable(false);
		deviceChoice14.setChoiceIntValues(null);
		deviceChoice14.setChoiceFloatValues(new float[]
		{ (float) 1.0, (float) 2.9, (float) 4.0 });
		deviceChoice14.setOffsetNid(115);
		deviceChoice14.setLabelString(" ");
		deviceChoice14.setChoiceItems(new String[]
		{ "1", "2.9", "4" });
		deviceChoice14.setUpdateIdentifier("");
		deviceChoice14.setIdentifier("");
		deviceChannel7.setLabelString("11");
		deviceChannel7.setOffsetNid(114);
		deviceChannel7.setInSameLine(true);
		deviceChannel7.setUpdateIdentifier("");
		deviceChannel7.setShowVal("");
		deviceChannel7.setLayout(borderLayout8);
		deviceField119.setOffsetNid(117);
		deviceField119.setIdentifier("");
		flowLayout17.setAlignment(FlowLayout.LEFT);
		flowLayout17.setHgap(0);
		flowLayout17.setVgap(0);
		jPanel19.setLayout(flowLayout16);
		deviceChoice15.setChoiceIntValues(new int[]
		{ 1, 2, 4, 8 });
		deviceChoice15.setChoiceFloatValues(null);
		deviceChoice15.setOffsetNid(122);
		deviceChoice15.setLabelString(" ");
		deviceChoice15.setChoiceItems(new String[]
		{ "1", "2", "4", "8" });
		deviceChoice15.setUpdateIdentifier("");
		deviceChoice15.setIdentifier("");
		deviceField1110.setOffsetNid(121);
		deviceField1110.setIdentifier("");
		flowLayout18.setVgap(0);
		flowLayout18.setHgap(0);
		flowLayout18.setAlignment(FlowLayout.LEFT);
		deviceField1111.setIdentifier("");
		deviceField1111.setEditable(false);
		deviceField1111.setOffsetNid(109);
		deviceField1111.setTextOnly(true);
		jPanel110.setLayout(flowLayout19);
		deviceField1112.setOffsetNid(105);
		deviceField1112.setTextOnly(true);
		deviceField1112.setIdentifier("");
		deviceField1112.setEditable(false);
		deviceChoice16.setChoiceIntValues(null);
		deviceChoice16.setChoiceFloatValues(new float[]
		{ (float) 1.0, (float) 2.9, (float) 4.0 });
		deviceChoice16.setOffsetNid(104);
		deviceChoice16.setLabelString(" ");
		deviceChoice16.setChoiceItems(new String[]
		{ "1", "2.9", "4" });
		deviceChoice16.setUpdateIdentifier("");
		deviceChoice16.setIdentifier("");
		deviceChannel8.setLabelString("10");
		deviceChannel8.setOffsetNid(103);
		deviceChannel8.setInSameLine(true);
		deviceChannel8.setUpdateIdentifier("");
		deviceChannel8.setShowVal("");
		deviceChannel8.setLayout(borderLayout9);
		deviceField1113.setOffsetNid(106);
		deviceField1113.setIdentifier("");
		flowLayout19.setAlignment(FlowLayout.LEFT);
		flowLayout19.setHgap(0);
		flowLayout19.setVgap(0);
		jPanel111.setLayout(flowLayout18);
		deviceChoice17.setChoiceIntValues(new int[]
		{ 1, 2, 4, 8 });
		deviceChoice17.setChoiceFloatValues(null);
		deviceChoice17.setOffsetNid(111);
		deviceChoice17.setLabelString(" ");
		deviceChoice17.setChoiceItems(new String[]
		{ "1", "2", "4", "8" });
		deviceChoice17.setUpdateIdentifier("");
		deviceChoice17.setIdentifier("");
		deviceField1114.setOffsetNid(110);
		deviceField1114.setIdentifier("");
		flowLayout110.setVgap(0);
		flowLayout110.setHgap(0);
		flowLayout110.setAlignment(FlowLayout.LEFT);
		deviceField1115.setIdentifier("");
		deviceField1115.setEditable(false);
		deviceField1115.setOffsetNid(98);
		deviceField1115.setTextOnly(true);
		jPanel112.setLayout(flowLayout111);
		deviceField1116.setOffsetNid(94);
		deviceField1116.setTextOnly(true);
		deviceField1116.setIdentifier("");
		deviceField1116.setEditable(false);
		deviceChoice18.setChoiceIntValues(null);
		deviceChoice18.setChoiceFloatValues(new float[]
		{ (float) 1.0, (float) 2.9, (float) 4.0 });
		deviceChoice18.setOffsetNid(93);
		deviceChoice18.setLabelString(" ");
		deviceChoice18.setChoiceItems(new String[]
		{ "1", "2.9", "4" });
		deviceChoice18.setUpdateIdentifier("");
		deviceChoice18.setIdentifier("");
		deviceChannel9.setLabelString("09");
		deviceChannel9.setOffsetNid(92);
		deviceChannel9.setInSameLine(true);
		deviceChannel9.setUpdateIdentifier("");
		deviceChannel9.setShowVal("");
		deviceChannel9.setLayout(borderLayout10);
		deviceField1117.setOffsetNid(95);
		deviceField1117.setIdentifier("");
		flowLayout111.setAlignment(FlowLayout.LEFT);
		flowLayout111.setHgap(0);
		flowLayout111.setVgap(0);
		jPanel113.setLayout(flowLayout110);
		deviceChoice19.setChoiceIntValues(new int[]
		{ 1, 2, 4, 8 });
		deviceChoice19.setChoiceFloatValues(null);
		deviceChoice19.setOffsetNid(100);
		deviceChoice19.setLabelString(" ");
		deviceChoice19.setChoiceItems(new String[]
		{ "1", "2", "4", "8" });
		deviceChoice19.setUpdateIdentifier("");
		deviceChoice19.setIdentifier("");
		deviceField1118.setOffsetNid(99);
		deviceField1118.setIdentifier("");
		flowLayout112.setVgap(0);
		flowLayout112.setHgap(0);
		flowLayout112.setAlignment(FlowLayout.LEFT);
		deviceField1119.setIdentifier("");
		deviceField1119.setEditable(false);
		deviceField1119.setOffsetNid(87);
		deviceField1119.setTextOnly(true);
		jPanel114.setLayout(flowLayout113);
		deviceField11110.setOffsetNid(83);
		deviceField11110.setTextOnly(true);
		deviceField11110.setIdentifier("");
		deviceField11110.setEditable(false);
		deviceChoice110.setChoiceIntValues(null);
		deviceChoice110.setChoiceFloatValues(new float[]
		{ (float) 1.0, (float) 2.9, (float) 4.0 });
		deviceChoice110.setOffsetNid(82);
		deviceChoice110.setLabelString(" ");
		deviceChoice110.setChoiceItems(new String[]
		{ "1", "2.9", "4" });
		deviceChoice110.setUpdateIdentifier("");
		deviceChoice110.setIdentifier("");
		deviceChannel10.setLabelString("08");
		deviceChannel10.setOffsetNid(81);
		deviceChannel10.setInSameLine(true);
		deviceChannel10.setUpdateIdentifier("");
		deviceChannel10.setShowVal("");
		deviceChannel10.setLayout(borderLayout11);
		deviceField11111.setOffsetNid(84);
		deviceField11111.setIdentifier("");
		flowLayout113.setAlignment(FlowLayout.LEFT);
		flowLayout113.setHgap(0);
		flowLayout113.setVgap(0);
		jPanel115.setLayout(flowLayout112);
		deviceChoice111.setChoiceIntValues(new int[]
		{ 1, 2, 4, 8 });
		deviceChoice111.setChoiceFloatValues(null);
		deviceChoice111.setOffsetNid(89);
		deviceChoice111.setLabelString(" ");
		deviceChoice111.setChoiceItems(new String[]
		{ "1", "2", "4", "8" });
		deviceChoice111.setUpdateIdentifier("");
		deviceChoice111.setIdentifier("");
		deviceField11112.setOffsetNid(88);
		deviceField11112.setIdentifier("");
		flowLayout114.setVgap(0);
		flowLayout114.setHgap(0);
		flowLayout114.setAlignment(FlowLayout.LEFT);
		deviceField11113.setIdentifier("");
		deviceField11113.setEditable(false);
		deviceField11113.setOffsetNid(76);
		deviceField11113.setTextOnly(true);
		jPanel116.setLayout(flowLayout115);
		deviceField11114.setOffsetNid(72);
		deviceField11114.setTextOnly(true);
		deviceField11114.setIdentifier("");
		deviceField11114.setEditable(false);
		deviceChoice112.setChoiceIntValues(null);
		deviceChoice112.setChoiceFloatValues(new float[]
		{ (float) 1.0, (float) 2.9, (float) 4.0 });
		deviceChoice112.setOffsetNid(71);
		deviceChoice112.setLabelString(" ");
		deviceChoice112.setChoiceItems(new String[]
		{ "1", "2.9", "4" });
		deviceChoice112.setUpdateIdentifier("");
		deviceChoice112.setIdentifier("");
		deviceChannel11.setLabelString("07");
		deviceChannel11.setOffsetNid(70);
		deviceChannel11.setInSameLine(true);
		deviceChannel11.setUpdateIdentifier("");
		deviceChannel11.setShowVal("");
		deviceChannel11.setLayout(borderLayout12);
		deviceField11115.setOffsetNid(73);
		deviceField11115.setIdentifier("");
		flowLayout115.setAlignment(FlowLayout.LEFT);
		flowLayout115.setHgap(0);
		flowLayout115.setVgap(0);
		jPanel117.setLayout(flowLayout114);
		deviceChoice113.setChoiceIntValues(new int[]
		{ 1, 2, 4, 8 });
		deviceChoice113.setChoiceFloatValues(null);
		deviceChoice113.setOffsetNid(78);
		deviceChoice113.setLabelString(" ");
		deviceChoice113.setChoiceItems(new String[]
		{ "1", "2", "4", "8" });
		deviceChoice113.setUpdateIdentifier("");
		deviceChoice113.setIdentifier("");
		deviceField11116.setOffsetNid(77);
		deviceField11116.setIdentifier("");
		flowLayout116.setVgap(0);
		flowLayout116.setHgap(0);
		flowLayout116.setAlignment(FlowLayout.LEFT);
		deviceField11117.setIdentifier("");
		deviceField11117.setEditable(false);
		deviceField11117.setOffsetNid(65);
		deviceField11117.setTextOnly(true);
		jPanel118.setLayout(flowLayout117);
		deviceField11118.setOffsetNid(61);
		deviceField11118.setTextOnly(true);
		deviceField11118.setIdentifier("");
		deviceField11118.setEditable(false);
		deviceChoice114.setChoiceIntValues(null);
		deviceChoice114.setChoiceFloatValues(new float[]
		{ (float) 1.0, (float) 2.9, (float) 4.0 });
		deviceChoice114.setOffsetNid(60);
		deviceChoice114.setLabelString(" ");
		deviceChoice114.setChoiceItems(new String[]
		{ "1", "2.9", "4" });
		deviceChoice114.setUpdateIdentifier("");
		deviceChoice114.setIdentifier("");
		deviceChannel12.setLabelString("06");
		deviceChannel12.setOffsetNid(59);
		deviceChannel12.setInSameLine(true);
		deviceChannel12.setUpdateIdentifier("");
		deviceChannel12.setShowVal("");
		deviceChannel12.setLayout(borderLayout13);
		deviceField11119.setOffsetNid(62);
		deviceField11119.setIdentifier("");
		flowLayout117.setAlignment(FlowLayout.LEFT);
		flowLayout117.setHgap(0);
		flowLayout117.setVgap(0);
		jPanel119.setLayout(flowLayout116);
		deviceChoice115.setChoiceIntValues(new int[]
		{ 1, 2, 4, 8 });
		deviceChoice115.setChoiceFloatValues(null);
		deviceChoice115.setOffsetNid(67);
		deviceChoice115.setLabelString(" ");
		deviceChoice115.setChoiceItems(new String[]
		{ "1", "2", "4", "8" });
		deviceChoice115.setUpdateIdentifier("");
		deviceChoice115.setIdentifier("");
		deviceField111110.setOffsetNid(66);
		deviceField111110.setIdentifier("");
		flowLayout118.setVgap(0);
		flowLayout118.setHgap(0);
		flowLayout118.setAlignment(FlowLayout.LEFT);
		deviceField111111.setIdentifier("");
		deviceField111111.setEditable(false);
		deviceField111111.setOffsetNid(54);
		deviceField111111.setTextOnly(true);
		jPanel1110.setLayout(flowLayout119);
		deviceField111112.setOffsetNid(50);
		deviceField111112.setTextOnly(true);
		deviceField111112.setIdentifier("");
		deviceField111112.setEditable(false);
		deviceChoice116.setChoiceIntValues(null);
		deviceChoice116.setChoiceFloatValues(new float[]
		{ (float) 1.0, (float) 2.9, (float) 4.0 });
		deviceChoice116.setOffsetNid(49);
		deviceChoice116.setLabelString(" ");
		deviceChoice116.setChoiceItems(new String[]
		{ "1", "2.9", "4" });
		deviceChoice116.setUpdateIdentifier("");
		deviceChoice116.setIdentifier("");
		deviceChannel13.setLabelString("05");
		deviceChannel13.setOffsetNid(48);
		deviceChannel13.setInSameLine(true);
		deviceChannel13.setUpdateIdentifier("");
		deviceChannel13.setShowVal("");
		deviceChannel13.setLayout(borderLayout14);
		deviceField111113.setOffsetNid(51);
		deviceField111113.setIdentifier("");
		flowLayout119.setAlignment(FlowLayout.LEFT);
		flowLayout119.setHgap(0);
		flowLayout119.setVgap(0);
		jPanel1111.setLayout(flowLayout118);
		deviceChoice117.setChoiceIntValues(new int[]
		{ 1, 2, 4, 8 });
		deviceChoice117.setChoiceFloatValues(null);
		deviceChoice117.setOffsetNid(56);
		deviceChoice117.setLabelString(" ");
		deviceChoice117.setChoiceItems(new String[]
		{ "1", "2", "4", "8" });
		deviceChoice117.setUpdateIdentifier("");
		deviceChoice117.setIdentifier("");
		deviceField111114.setOffsetNid(55);
		deviceField111114.setIdentifier("");
		flowLayout1110.setVgap(0);
		flowLayout1110.setHgap(0);
		flowLayout1110.setAlignment(FlowLayout.LEFT);
		deviceField111115.setIdentifier("");
		deviceField111115.setEditable(false);
		deviceField111115.setOffsetNid(43);
		deviceField111115.setTextOnly(true);
		jPanel1112.setLayout(flowLayout1111);
		deviceField111116.setOffsetNid(39);
		deviceField111116.setTextOnly(true);
		deviceField111116.setIdentifier("");
		deviceField111116.setEditable(false);
		deviceChoice118.setChoiceIntValues(null);
		deviceChoice118.setChoiceFloatValues(new float[]
		{ (float) 1.0, (float) 2.9, (float) 4.0 });
		deviceChoice118.setOffsetNid(38);
		deviceChoice118.setLabelString(" ");
		deviceChoice118.setChoiceItems(new String[]
		{ "1", "2.9", "4" });
		deviceChoice118.setUpdateIdentifier("");
		deviceChoice118.setIdentifier("");
		deviceChannel14.setLabelString("04");
		deviceChannel14.setOffsetNid(37);
		deviceChannel14.setInSameLine(true);
		deviceChannel14.setUpdateIdentifier("");
		deviceChannel14.setShowVal("");
		deviceChannel14.setLayout(borderLayout15);
		deviceField111117.setOffsetNid(40);
		deviceField111117.setIdentifier("");
		flowLayout1111.setAlignment(FlowLayout.LEFT);
		flowLayout1111.setHgap(0);
		flowLayout1111.setVgap(0);
		jPanel1113.setLayout(flowLayout1110);
		deviceChoice119.setChoiceIntValues(new int[]
		{ 1, 2, 4, 8 });
		deviceChoice119.setChoiceFloatValues(null);
		deviceChoice119.setOffsetNid(45);
		deviceChoice119.setLabelString(" ");
		deviceChoice119.setChoiceItems(new String[]
		{ "1", "2", "4", "8" });
		deviceChoice119.setUpdateIdentifier("");
		deviceChoice119.setIdentifier("");
		deviceField111118.setOffsetNid(44);
		deviceField111118.setIdentifier("");
		flowLayout1112.setVgap(0);
		flowLayout1112.setHgap(0);
		flowLayout1112.setAlignment(FlowLayout.LEFT);
		deviceField111119.setIdentifier("");
		deviceField111119.setEditable(false);
		deviceField111119.setOffsetNid(32);
		deviceField111119.setTextOnly(true);
		jPanel1114.setLayout(flowLayout1113);
		deviceField1111110.setOffsetNid(28);
		deviceField1111110.setTextOnly(true);
		deviceField1111110.setIdentifier("");
		deviceField1111110.setEditable(false);
		deviceChoice1110.setChoiceIntValues(null);
		deviceChoice1110.setChoiceFloatValues(new float[]
		{ (float) 1.0, (float) 2.9, (float) 4.0 });
		deviceChoice1110.setOffsetNid(27);
		deviceChoice1110.setLabelString(" ");
		deviceChoice1110.setChoiceItems(new String[]
		{ "1", "2.9", "4" });
		deviceChoice1110.setUpdateIdentifier("");
		deviceChoice1110.setIdentifier("");
		deviceChannel15.setLabelString("03");
		deviceChannel15.setOffsetNid(26);
		deviceChannel15.setInSameLine(true);
		deviceChannel15.setUpdateIdentifier("");
		deviceChannel15.setShowVal("");
		deviceChannel15.setLayout(borderLayout16);
		deviceField1111111.setOffsetNid(29);
		deviceField1111111.setIdentifier("");
		flowLayout1113.setAlignment(FlowLayout.LEFT);
		flowLayout1113.setHgap(0);
		flowLayout1113.setVgap(0);
		jPanel1115.setLayout(flowLayout1112);
		deviceChoice1111.setChoiceIntValues(new int[]
		{ 1, 2, 4, 8 });
		deviceChoice1111.setChoiceFloatValues(null);
		deviceChoice1111.setOffsetNid(34);
		deviceChoice1111.setLabelString(" ");
		deviceChoice1111.setChoiceItems(new String[]
		{ "1", "2", "4", "8" });
		deviceChoice1111.setUpdateIdentifier("");
		deviceChoice1111.setIdentifier("");
		deviceField1111112.setOffsetNid(33);
		deviceField1111112.setIdentifier("");
		flowLayout1114.setVgap(0);
		flowLayout1114.setHgap(0);
		flowLayout1114.setAlignment(FlowLayout.LEFT);
		deviceField1111113.setIdentifier("");
		deviceField1111113.setEditable(false);
		deviceField1111113.setOffsetNid(21);
		deviceField1111113.setTextOnly(true);
		jPanel1116.setLayout(flowLayout1115);
		deviceField1111114.setOffsetNid(17);
		deviceField1111114.setTextOnly(true);
		deviceField1111114.setIdentifier("");
		deviceField1111114.setEditable(false);
		deviceChoice1112.setChoiceIntValues(null);
		deviceChoice1112.setChoiceFloatValues(new float[]
		{ (float) 1.0, (float) 2.9, (float) 4.0 });
		deviceChoice1112.setOffsetNid(16);
		deviceChoice1112.setLabelString(" ");
		deviceChoice1112.setChoiceItems(new String[]
		{ "1", "2.9", "4" });
		deviceChoice1112.setUpdateIdentifier("");
		deviceChoice1112.setIdentifier("");
		deviceChannel16.setLabelString("02");
		deviceChannel16.setOffsetNid(15);
		deviceChannel16.setInSameLine(true);
		deviceChannel16.setUpdateIdentifier("");
		deviceChannel16.setShowVal("");
		deviceChannel16.setLayout(borderLayout17);
		deviceField1111115.setOffsetNid(18);
		deviceField1111115.setIdentifier("");
		flowLayout1115.setAlignment(FlowLayout.LEFT);
		flowLayout1115.setHgap(0);
		flowLayout1115.setVgap(0);
		jPanel1117.setLayout(flowLayout1114);
		deviceChoice1113.setChoiceIntValues(new int[]
		{ 1, 2, 4, 8 });
		deviceChoice1113.setChoiceFloatValues(null);
		deviceChoice1113.setOffsetNid(23);
		deviceChoice1113.setLabelString(" ");
		deviceChoice1113.setChoiceItems(new String[]
		{ "1", "2", "4", "8" });
		deviceChoice1113.setUpdateIdentifier("");
		deviceChoice1113.setIdentifier("");
		deviceField1111116.setOffsetNid(22);
		deviceField1111116.setIdentifier("");
		deviceButtons1.setMethods(new String[]
		{ "init" });
		this.getContentPane().add(jPanel1, BorderLayout.NORTH);
		jPanel1.add(jPanel2, null);
		jPanel2.add(deviceField1, null);
		jPanel2.add(deviceDispatch1, null);
		jPanel1.add(jPanel3, null);
		jPanel3.add(deviceField2, null);
		jPanel3.add(deviceChoice1, null);
		jPanel1.add(jPanel7, null);
		jPanel7.add(jLabel1, null);
		this.getContentPane().add(deviceButtons1, BorderLayout.SOUTH);
		this.getContentPane().add(jScrollPane1, BorderLayout.CENTER);
		jScrollPane1.getViewport().add(jPanel4, null);
		jPanel4.add(jPanel5, null);
		jPanel5.add(deviceChannel1, null);
		deviceChannel1.add(jPanel6, BorderLayout.CENTER);
		jPanel6.add(deviceChoice2, null);
		jPanel6.add(deviceField3, null);
		jPanel6.add(deviceField6, null);
		jPanel6.add(deviceField5, null);
		jPanel6.add(deviceField4, null);
		jPanel6.add(deviceChoice3, null);
		jPanel4.add(jPanel1117, null);
		jPanel1117.add(deviceChannel16, null);
		deviceChannel16.add(jPanel1116, BorderLayout.CENTER);
		jPanel1116.add(deviceChoice1112, null);
		jPanel1116.add(deviceField1111114, null);
		jPanel1116.add(deviceField1111115, null);
		jPanel1116.add(deviceField1111113, null);
		jPanel1116.add(deviceField1111116, null);
		jPanel1116.add(deviceChoice1113, null);
		jPanel4.add(jPanel1115, null);
		jPanel1115.add(deviceChannel15, null);
		deviceChannel15.add(jPanel1114, BorderLayout.CENTER);
		jPanel1114.add(deviceChoice1110, null);
		jPanel1114.add(deviceField1111110, null);
		jPanel1114.add(deviceField1111111, null);
		jPanel1114.add(deviceField111119, null);
		jPanel1114.add(deviceField1111112, null);
		jPanel1114.add(deviceChoice1111, null);
		jPanel4.add(jPanel1113, null);
		jPanel1113.add(deviceChannel14, null);
		deviceChannel14.add(jPanel1112, BorderLayout.CENTER);
		jPanel1112.add(deviceChoice118, null);
		jPanel1112.add(deviceField111116, null);
		jPanel1112.add(deviceField111117, null);
		jPanel1112.add(deviceField111115, null);
		jPanel1112.add(deviceField111118, null);
		jPanel1112.add(deviceChoice119, null);
		jPanel4.add(jPanel1111, null);
		jPanel1111.add(deviceChannel13, null);
		deviceChannel13.add(jPanel1110, BorderLayout.CENTER);
		jPanel1110.add(deviceChoice116, null);
		jPanel1110.add(deviceField111112, null);
		jPanel1110.add(deviceField111113, null);
		jPanel1110.add(deviceField111111, null);
		jPanel1110.add(deviceField111114, null);
		jPanel1110.add(deviceChoice117, null);
		jPanel4.add(jPanel119, null);
		jPanel119.add(deviceChannel12, null);
		deviceChannel12.add(jPanel118, BorderLayout.CENTER);
		jPanel118.add(deviceChoice114, null);
		jPanel118.add(deviceField11118, null);
		jPanel118.add(deviceField11119, null);
		jPanel118.add(deviceField11117, null);
		jPanel118.add(deviceField111110, null);
		jPanel118.add(deviceChoice115, null);
		jPanel4.add(jPanel117, null);
		jPanel117.add(deviceChannel11, null);
		deviceChannel11.add(jPanel116, BorderLayout.CENTER);
		jPanel116.add(deviceChoice112, null);
		jPanel116.add(deviceField11114, null);
		jPanel116.add(deviceField11115, null);
		jPanel116.add(deviceField11113, null);
		jPanel116.add(deviceField11116, null);
		jPanel116.add(deviceChoice113, null);
		jPanel4.add(jPanel115, null);
		jPanel115.add(deviceChannel10, null);
		deviceChannel10.add(jPanel114, BorderLayout.CENTER);
		jPanel114.add(deviceChoice110, null);
		jPanel114.add(deviceField11110, null);
		jPanel114.add(deviceField11111, null);
		jPanel114.add(deviceField1119, null);
		jPanel114.add(deviceField11112, null);
		jPanel114.add(deviceChoice111, null);
		jPanel4.add(jPanel113, null);
		jPanel113.add(deviceChannel9, null);
		deviceChannel9.add(jPanel112, BorderLayout.CENTER);
		jPanel112.add(deviceChoice18, null);
		jPanel112.add(deviceField1116, null);
		jPanel112.add(deviceField1117, null);
		jPanel112.add(deviceField1115, null);
		jPanel112.add(deviceField1118, null);
		jPanel112.add(deviceChoice19, null);
		jPanel4.add(jPanel111, null);
		jPanel111.add(deviceChannel8, null);
		deviceChannel8.add(jPanel110, BorderLayout.CENTER);
		jPanel110.add(deviceChoice16, null);
		jPanel110.add(deviceField1112, null);
		jPanel110.add(deviceField1113, null);
		jPanel110.add(deviceField1111, null);
		jPanel110.add(deviceField1114, null);
		jPanel110.add(deviceChoice17, null);
		jPanel4.add(jPanel19, null);
		jPanel19.add(deviceChannel7, null);
		deviceChannel7.add(jPanel18, BorderLayout.CENTER);
		jPanel18.add(deviceChoice14, null);
		jPanel18.add(deviceField118, null);
		jPanel18.add(deviceField119, null);
		jPanel18.add(deviceField117, null);
		jPanel18.add(deviceField1110, null);
		jPanel18.add(deviceChoice15, null);
		jPanel4.add(jPanel17, null);
		jPanel17.add(deviceChannel6, null);
		deviceChannel6.add(jPanel16, BorderLayout.CENTER);
		jPanel16.add(deviceChoice12, null);
		jPanel16.add(deviceField114, null);
		jPanel16.add(deviceField115, null);
		jPanel16.add(deviceField113, null);
		jPanel16.add(deviceField116, null);
		jPanel16.add(deviceChoice13, null);
		jPanel4.add(jPanel15, null);
		jPanel15.add(deviceChannel5, null);
		deviceChannel5.add(jPanel14, BorderLayout.CENTER);
		jPanel14.add(deviceChoice10, null);
		jPanel14.add(deviceField110, null);
		jPanel14.add(deviceField111, null);
		jPanel14.add(deviceField19, null);
		jPanel14.add(deviceField112, null);
		jPanel14.add(deviceChoice11, null);
		jPanel4.add(jPanel13, null);
		jPanel13.add(deviceChannel4, null);
		deviceChannel4.add(jPanel12, BorderLayout.CENTER);
		jPanel12.add(deviceChoice8, null);
		jPanel12.add(deviceField16, null);
		jPanel12.add(deviceField17, null);
		jPanel12.add(deviceField15, null);
		jPanel12.add(deviceField18, null);
		jPanel12.add(deviceChoice9, null);
		jPanel4.add(jPanel11, null);
		jPanel11.add(deviceChannel3, null);
		deviceChannel3.add(jPanel10, BorderLayout.CENTER);
		jPanel10.add(deviceChoice6, null);
		jPanel10.add(deviceField12, null);
		jPanel10.add(deviceField13, null);
		jPanel10.add(deviceField11, null);
		jPanel10.add(deviceField14, null);
		jPanel10.add(deviceChoice7, null);
		jPanel4.add(jPanel9, null);
		jPanel9.add(deviceChannel2, null);
		deviceChannel2.add(jPanel8, BorderLayout.CENTER);
		jPanel8.add(deviceChoice4, null);
		jPanel8.add(deviceField8, null);
		jPanel8.add(deviceField9, null);
		jPanel8.add(deviceField7, null);
		jPanel8.add(deviceField10, null);
		jPanel8.add(deviceChoice5, null);
	}
}
