import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;

/**
 * <p>
 * Title:
 * </p>
 * <p>
 * Description:
 * </p>
 * <p>
 * Copyright: Copyright (c) 2003
 * </p>
 * <p>
 * Company:
 * </p>
 *
 * @author not attributable
 * @version 1.0
 */
public class FR10Setup extends DeviceSetup
{
	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	JPanel jPanel2 = new JPanel();
	JTabbedPane jTabbedPane1 = new JTabbedPane();
	JScrollPane jScrollPane1 = new JScrollPane();
	JPanel jPanel3 = new JPanel();
	GridLayout gridLayout1 = new GridLayout();
	DeviceChannel deviceChannel1 = new DeviceChannel();
	FlowLayout flowLayout1 = new FlowLayout();
	JPanel jPanel5 = new JPanel();
	DeviceField deviceField1 = new DeviceField();
	DeviceField deviceField2 = new DeviceField();
	JScrollPane jScrollPane2 = new JScrollPane();
	JPanel jPanel4 = new JPanel();
	GridLayout gridLayout2 = new GridLayout();
	DeviceChannel deviceChannel17 = new DeviceChannel();
	FlowLayout flowLayout2 = new FlowLayout();
	JPanel jPanel6 = new JPanel();
	DeviceField deviceField3 = new DeviceField();
	DeviceField deviceField4 = new DeviceField();
	FlowLayout flowLayout3 = new FlowLayout();
	DeviceField deviceField5 = new DeviceField();
	DeviceChannel deviceChannel2 = new DeviceChannel();
	JPanel jPanel7 = new JPanel();
	DeviceField deviceField6 = new DeviceField();
	FlowLayout flowLayout4 = new FlowLayout();
	DeviceField deviceField7 = new DeviceField();
	DeviceChannel deviceChannel3 = new DeviceChannel();
	DeviceField deviceField8 = new DeviceField();
	JPanel jPanel8 = new JPanel();
	DeviceField deviceField9 = new DeviceField();
	DeviceField deviceField10 = new DeviceField();
	JPanel jPanel9 = new JPanel();
	FlowLayout flowLayout5 = new FlowLayout();
	DeviceChannel deviceChannel4 = new DeviceChannel();
	DeviceField deviceField11 = new DeviceField();
	FlowLayout flowLayout6 = new FlowLayout();
	DeviceChannel deviceChannel5 = new DeviceChannel();
	DeviceField deviceField12 = new DeviceField();
	JPanel jPanel10 = new JPanel();
	JPanel jPanel11 = new JPanel();
	DeviceField deviceField13 = new DeviceField();
	DeviceField deviceField14 = new DeviceField();
	FlowLayout flowLayout7 = new FlowLayout();
	DeviceChannel deviceChannel6 = new DeviceChannel();
	DeviceField deviceField15 = new DeviceField();
	DeviceField deviceField16 = new DeviceField();
	FlowLayout flowLayout8 = new FlowLayout();
	JPanel jPanel12 = new JPanel();
	DeviceChannel deviceChannel7 = new DeviceChannel();
	JPanel jPanel13 = new JPanel();
	DeviceChannel deviceChannel8 = new DeviceChannel();
	DeviceField deviceField17 = new DeviceField();
	DeviceField deviceField18 = new DeviceField();
	FlowLayout flowLayout9 = new FlowLayout();
	DeviceField deviceField19 = new DeviceField();
	DeviceField deviceField110 = new DeviceField();
	JPanel jPanel14 = new JPanel();
	DeviceChannel deviceChannel9 = new DeviceChannel();
	FlowLayout flowLayout10 = new FlowLayout();
	DeviceField deviceField111 = new DeviceField();
	DeviceField deviceField112 = new DeviceField();
	DeviceChannel deviceChannel10 = new DeviceChannel();
	JPanel jPanel15 = new JPanel();
	FlowLayout flowLayout11 = new FlowLayout();
	FlowLayout flowLayout12 = new FlowLayout();
	DeviceField deviceField113 = new DeviceField();
	DeviceChannel deviceChannel11 = new DeviceChannel();
	JPanel jPanel16 = new JPanel();
	DeviceField deviceField114 = new DeviceField();
	JPanel jPanel17 = new JPanel();
	FlowLayout flowLayout13 = new FlowLayout();
	DeviceChannel deviceChannel12 = new DeviceChannel();
	DeviceField deviceField115 = new DeviceField();
	DeviceField deviceField116 = new DeviceField();
	DeviceChannel deviceChannel13 = new DeviceChannel();
	DeviceField deviceField117 = new DeviceField();
	JPanel jPanel18 = new JPanel();
	FlowLayout flowLayout14 = new FlowLayout();
	DeviceField deviceField118 = new DeviceField();
	FlowLayout flowLayout15 = new FlowLayout();
	DeviceField deviceField119 = new DeviceField();
	DeviceChannel deviceChannel14 = new DeviceChannel();
	JPanel jPanel19 = new JPanel();
	DeviceField deviceField1110 = new DeviceField();
	DeviceField deviceField1111 = new DeviceField();
	DeviceField deviceField1112 = new DeviceField();
	DeviceChannel deviceChannel15 = new DeviceChannel();
	JPanel jPanel110 = new JPanel();
	FlowLayout flowLayout16 = new FlowLayout();
	DeviceChannel deviceChannel16 = new DeviceChannel();
	FlowLayout flowLayout17 = new FlowLayout();
	DeviceField deviceField1113 = new DeviceField();
	DeviceField deviceField1114 = new DeviceField();
	JPanel jPanel111 = new JPanel();
	DeviceChannel deviceChannel18 = new DeviceChannel();
	JPanel jPanel20 = new JPanel();
	DeviceField deviceField20 = new DeviceField();
	FlowLayout flowLayout18 = new FlowLayout();
	DeviceField deviceField21 = new DeviceField();
	FlowLayout flowLayout19 = new FlowLayout();
	JPanel jPanel21 = new JPanel();
	DeviceChannel deviceChannel19 = new DeviceChannel();
	DeviceField deviceField22 = new DeviceField();
	DeviceField deviceField23 = new DeviceField();
	DeviceField deviceField24 = new DeviceField();
	DeviceChannel deviceChannel110 = new DeviceChannel();
	DeviceField deviceField25 = new DeviceField();
	FlowLayout flowLayout110 = new FlowLayout();
	JPanel jPanel22 = new JPanel();
	DeviceField deviceField26 = new DeviceField();
	DeviceField deviceField27 = new DeviceField();
	JPanel jPanel23 = new JPanel();
	FlowLayout flowLayout111 = new FlowLayout();
	DeviceChannel deviceChannel111 = new DeviceChannel();
	FlowLayout flowLayout112 = new FlowLayout();
	DeviceChannel deviceChannel112 = new DeviceChannel();
	DeviceField deviceField28 = new DeviceField();
	DeviceField deviceField29 = new DeviceField();
	JPanel jPanel24 = new JPanel();
	DeviceField deviceField210 = new DeviceField();
	JPanel jPanel25 = new JPanel();
	FlowLayout flowLayout113 = new FlowLayout();
	DeviceField deviceField211 = new DeviceField();
	DeviceChannel deviceChannel113 = new DeviceChannel();
	DeviceField deviceField212 = new DeviceField();
	FlowLayout flowLayout114 = new FlowLayout();
	DeviceChannel deviceChannel114 = new DeviceChannel();
	DeviceField deviceField213 = new DeviceField();
	JPanel jPanel26 = new JPanel();
	DeviceField deviceField214 = new DeviceField();
	JPanel jPanel27 = new JPanel();
	DeviceField deviceField215 = new DeviceField();
	FlowLayout flowLayout115 = new FlowLayout();
	DeviceChannel deviceChannel115 = new DeviceChannel();
	DeviceChannel deviceChannel116 = new DeviceChannel();
	DeviceField deviceField216 = new DeviceField();
	FlowLayout flowLayout116 = new FlowLayout();
	DeviceField deviceField217 = new DeviceField();
	JPanel jPanel28 = new JPanel();
	DeviceChannel deviceChannel117 = new DeviceChannel();
	DeviceField deviceField218 = new DeviceField();
	JPanel jPanel29 = new JPanel();
	DeviceField deviceField219 = new DeviceField();
	FlowLayout flowLayout117 = new FlowLayout();
	DeviceField deviceField2110 = new DeviceField();
	FlowLayout flowLayout118 = new FlowLayout();
	JPanel jPanel210 = new JPanel();
	DeviceChannel deviceChannel118 = new DeviceChannel();
	DeviceField deviceField2111 = new DeviceField();
	DeviceField deviceField2112 = new DeviceField();
	DeviceChannel deviceChannel119 = new DeviceChannel();
	DeviceField deviceField2113 = new DeviceField();
	JPanel jPanel211 = new JPanel();
	FlowLayout flowLayout119 = new FlowLayout();
	DeviceChannel deviceChannel1110 = new DeviceChannel();
	JPanel jPanel212 = new JPanel();
	DeviceField deviceField2114 = new DeviceField();
	DeviceField deviceField2115 = new DeviceField();
	FlowLayout flowLayout1110 = new FlowLayout();
	JPanel jPanel213 = new JPanel();
	DeviceField deviceField2116 = new DeviceField();
	DeviceChannel deviceChannel1111 = new DeviceChannel();
	DeviceField deviceField2117 = new DeviceField();
	FlowLayout flowLayout1111 = new FlowLayout();
	DeviceField deviceField2118 = new DeviceField();
	DeviceChannel deviceChannel1112 = new DeviceChannel();
	FlowLayout flowLayout1112 = new FlowLayout();
	JPanel jPanel214 = new JPanel();
	DeviceField deviceField2119 = new DeviceField();
	JPanel jPanel31 = new JPanel();
	DeviceField deviceField30 = new DeviceField();
	DeviceChoice deviceChoice1 = new DeviceChoice();
	DeviceField deviceField31 = new DeviceField();
	DeviceField deviceField32 = new DeviceField();
	DeviceDispatch deviceDispatch1 = new DeviceDispatch();
	JPanel jPanel32 = new JPanel();
	DeviceField deviceField34 = new DeviceField();
	DeviceChoice deviceChoice2 = new DeviceChoice();
	DeviceChoice deviceChoice3 = new DeviceChoice();
	JPanel jPanel33 = new JPanel();
	DeviceChoice deviceChoice4 = new DeviceChoice();
	DeviceField deviceField35 = new DeviceField();
	DeviceChoice deviceChoice5 = new DeviceChoice();
	DeviceChoice deviceChoice6 = new DeviceChoice();
	DeviceButtons deviceButtons1 = new DeviceButtons();
	JPanel jPanel30 = new JPanel();
	JPanel jPanel34 = new JPanel();
	GridLayout gridLayout3 = new GridLayout();
	JPanel jPanel35 = new JPanel();
	JPanel jPanel36 = new JPanel();
	GridLayout gridLayout4 = new GridLayout();
	JPanel jPanel37 = new JPanel();
	JPanel jPanel38 = new JPanel();
	GridLayout gridLayout5 = new GridLayout();
	JPanel jPanel39 = new JPanel();
	GridLayout gridLayout6 = new GridLayout();
	BorderLayout borderLayout1 = new BorderLayout();
	BorderLayout borderLayout2 = new BorderLayout();

	public FR10Setup()
	{
		try
		{
			jbInit();
		}
		catch (final Exception e)
		{
			e.printStackTrace();
		}
	}

	private void jbInit() throws Exception
	{
		this.setWidth(638);
		this.setHeight(638);
		this.setDeviceType("FR10");
		this.setDeviceProvider("150.178.3.101");
		this.setDeviceTitle("FR10");
		this.getContentPane().setLayout(borderLayout1);
		jPanel2.setBorder(
				new TitledBorder(BorderFactory.createEtchedBorder(Color.white, new Color(142, 142, 142)), "Channels"));
		jPanel2.setLayout(borderLayout2);
		jTabbedPane1.setBackground(new Color(153, 153, 153));
		jPanel3.setLayout(gridLayout1);
		gridLayout1.setRows(16);
		deviceChannel1.setLabelString("Ch 01");
		deviceChannel1.setOffsetNid(13);
		deviceChannel1.setInSameLine(true);
		deviceChannel1.setUpdateIdentifier("");
		deviceChannel1.setShowVal("");
		deviceChannel1.setLayout(flowLayout1);
		deviceField1.setOffsetNid(14);
		deviceField1.setLabelString("Start :");
		deviceField1.setNumCols(12);
		deviceField1.setIdentifier("");
		deviceField2.setOffsetNid(15);
		deviceField2.setLabelString("End :");
		deviceField2.setNumCols(12);
		deviceField2.setIdentifier("");
		jScrollPane1.setViewportBorder(BorderFactory.createEtchedBorder(Color.white, new Color(142, 142, 142)));
		jScrollPane1.setBorder(BorderFactory.createEmptyBorder());
		jPanel4.setLayout(gridLayout2);
		gridLayout2.setRows(16);
		deviceChannel17.setLabelString("Ch 01");
		deviceChannel17.setOffsetNid(13);
		deviceChannel17.setInSameLine(true);
		deviceChannel17.setUpdateIdentifier("");
		deviceChannel17.setShowVal("");
		deviceChannel17.setLayout(flowLayout2);
		deviceField3.setOffsetNid(16);
		deviceField3.setLabelString("Start :");
		deviceField3.setNumCols(12);
		deviceField3.setIdentifier("");
		deviceField4.setOffsetNid(17);
		deviceField4.setLabelString("End :");
		deviceField4.setNumCols(12);
		deviceField4.setIdentifier("");
		jScrollPane2.setViewportBorder(BorderFactory.createEtchedBorder(Color.white, new Color(142, 142, 142)));
		jScrollPane2.setBorder(BorderFactory.createEmptyBorder());
		deviceField5.setIdentifier("");
		deviceField5.setNumCols(12);
		deviceField5.setLabelString("Start :");
		deviceField5.setOffsetNid(20);
		deviceChannel2.setLayout(flowLayout3);
		deviceChannel2.setShowVal("");
		deviceChannel2.setUpdateIdentifier("");
		deviceChannel2.setInSameLine(true);
		deviceChannel2.setOffsetNid(19);
		deviceChannel2.setLabelString("Ch 02");
		deviceField6.setOffsetNid(21);
		deviceField6.setLabelString("End :");
		deviceField6.setNumCols(12);
		deviceField6.setIdentifier("");
		deviceField7.setOffsetNid(26);
		deviceField7.setLabelString("Start :");
		deviceField7.setNumCols(12);
		deviceField7.setIdentifier("");
		deviceChannel3.setLabelString("Ch 03");
		deviceChannel3.setOffsetNid(25);
		deviceChannel3.setInSameLine(true);
		deviceChannel3.setUpdateIdentifier("");
		deviceChannel3.setShowVal("");
		deviceChannel3.setLayout(flowLayout4);
		deviceField8.setOffsetNid(27);
		deviceField8.setLabelString("End :");
		deviceField8.setNumCols(12);
		deviceField8.setIdentifier("");
		deviceField9.setIdentifier("");
		deviceField9.setNumCols(12);
		deviceField9.setLabelString("Start :");
		deviceField9.setOffsetNid(32);
		deviceField10.setIdentifier("");
		deviceField10.setNumCols(12);
		deviceField10.setLabelString("End :");
		deviceField10.setOffsetNid(33);
		deviceChannel4.setLabelString("Ch 04");
		deviceChannel4.setOffsetNid(31);
		deviceChannel4.setInSameLine(true);
		deviceChannel4.setUpdateIdentifier("");
		deviceChannel4.setShowVal("");
		deviceChannel4.setLayout(flowLayout5);
		deviceField11.setOffsetNid(39);
		deviceField11.setLabelString("End :");
		deviceField11.setNumCols(12);
		deviceField11.setIdentifier("");
		deviceChannel5.setLayout(flowLayout6);
		deviceChannel5.setShowVal("");
		deviceChannel5.setUpdateIdentifier("");
		deviceChannel5.setInSameLine(true);
		deviceChannel5.setOffsetNid(37);
		deviceChannel5.setLabelString("Ch 05");
		deviceField12.setIdentifier("");
		deviceField12.setNumCols(12);
		deviceField12.setLabelString("Start :");
		deviceField12.setOffsetNid(38);
		deviceField13.setOffsetNid(45);
		deviceField13.setLabelString("End :");
		deviceField13.setNumCols(12);
		deviceField13.setIdentifier("");
		deviceField14.setIdentifier("");
		deviceField14.setNumCols(12);
		deviceField14.setLabelString("Start :");
		deviceField14.setOffsetNid(44);
		deviceChannel6.setLayout(flowLayout7);
		deviceChannel6.setShowVal("");
		deviceChannel6.setUpdateIdentifier("");
		deviceChannel6.setInSameLine(true);
		deviceChannel6.setOffsetNid(43);
		deviceChannel6.setLabelString("Ch 06");
		deviceField15.setOffsetNid(50);
		deviceField15.setLabelString("Start :");
		deviceField15.setNumCols(12);
		deviceField15.setIdentifier("");
		deviceField16.setIdentifier("");
		deviceField16.setNumCols(12);
		deviceField16.setLabelString("End :");
		deviceField16.setOffsetNid(51);
		deviceChannel7.setLayout(flowLayout8);
		deviceChannel7.setShowVal("");
		deviceChannel7.setUpdateIdentifier("");
		deviceChannel7.setInSameLine(true);
		deviceChannel7.setOffsetNid(49);
		deviceChannel7.setLabelString("Ch 07");
		deviceChannel8.setLayout(flowLayout9);
		deviceChannel8.setShowVal("");
		deviceChannel8.setUpdateIdentifier("");
		deviceChannel8.setInSameLine(true);
		deviceChannel8.setOffsetNid(55);
		deviceChannel8.setLabelString("Ch 08");
		deviceField17.setOffsetNid(56);
		deviceField17.setLabelString("Start :");
		deviceField17.setNumCols(12);
		deviceField17.setIdentifier("");
		deviceField18.setIdentifier("");
		deviceField18.setNumCols(12);
		deviceField18.setLabelString("End :");
		deviceField18.setOffsetNid(57);
		deviceField19.setIdentifier("");
		deviceField19.setNumCols(12);
		deviceField19.setLabelString("Start :");
		deviceField19.setOffsetNid(62);
		deviceField110.setOffsetNid(63);
		deviceField110.setLabelString("End :");
		deviceField110.setNumCols(12);
		deviceField110.setIdentifier("");
		deviceChannel9.setLayout(flowLayout10);
		deviceChannel9.setShowVal("");
		deviceChannel9.setUpdateIdentifier("");
		deviceChannel9.setInSameLine(true);
		deviceChannel9.setOffsetNid(61);
		deviceChannel9.setLabelString("Ch 09");
		deviceField111.setIdentifier("");
		deviceField111.setNumCols(12);
		deviceField111.setLabelString("End :");
		deviceField111.setOffsetNid(69);
		deviceField112.setOffsetNid(68);
		deviceField112.setLabelString("Start :");
		deviceField112.setNumCols(12);
		deviceField112.setIdentifier("");
		deviceChannel10.setLabelString("Ch 10");
		deviceChannel10.setOffsetNid(67);
		deviceChannel10.setInSameLine(true);
		deviceChannel10.setUpdateIdentifier("");
		deviceChannel10.setShowVal("");
		deviceChannel10.setLayout(flowLayout11);
		deviceField113.setIdentifier("");
		deviceField113.setNumCols(12);
		deviceField113.setLabelString("Start :");
		deviceField113.setOffsetNid(74);
		deviceChannel11.setLayout(flowLayout12);
		deviceChannel11.setShowVal("");
		deviceChannel11.setUpdateIdentifier("");
		deviceChannel11.setInSameLine(true);
		deviceChannel11.setOffsetNid(73);
		deviceChannel11.setLabelString("Ch 11");
		deviceField114.setIdentifier("");
		deviceField114.setNumCols(12);
		deviceField114.setLabelString("End :");
		deviceField114.setOffsetNid(75);
		deviceChannel12.setLayout(flowLayout13);
		deviceChannel12.setShowVal("");
		deviceChannel12.setUpdateIdentifier("");
		deviceChannel12.setInSameLine(true);
		deviceChannel12.setOffsetNid(79);
		deviceChannel12.setLabelString("Ch 12");
		deviceField115.setIdentifier("");
		deviceField115.setNumCols(12);
		deviceField115.setLabelString("End :");
		deviceField115.setOffsetNid(81);
		deviceField116.setIdentifier("");
		deviceField116.setNumCols(12);
		deviceField116.setLabelString("Start :");
		deviceField116.setOffsetNid(80);
		deviceChannel13.setLabelString("Ch 13");
		deviceChannel13.setOffsetNid(85);
		deviceChannel13.setInSameLine(true);
		deviceChannel13.setUpdateIdentifier("");
		deviceChannel13.setShowVal("");
		deviceChannel13.setLayout(flowLayout14);
		deviceField117.setIdentifier("");
		deviceField117.setNumCols(12);
		deviceField117.setLabelString("End :");
		deviceField117.setOffsetNid(87);
		deviceField118.setIdentifier("");
		deviceField118.setNumCols(12);
		deviceField118.setLabelString("Start :");
		deviceField118.setOffsetNid(86);
		deviceField119.setOffsetNid(93);
		deviceField119.setLabelString("End :");
		deviceField119.setNumCols(12);
		deviceField119.setIdentifier("");
		deviceChannel14.setLayout(flowLayout15);
		deviceChannel14.setShowVal("");
		deviceChannel14.setUpdateIdentifier("");
		deviceChannel14.setInSameLine(true);
		deviceChannel14.setOffsetNid(91);
		deviceChannel14.setLabelString("Ch 14");
		deviceField1110.setIdentifier("");
		deviceField1110.setNumCols(12);
		deviceField1110.setLabelString("Start :");
		deviceField1110.setOffsetNid(92);
		deviceField1111.setOffsetNid(98);
		deviceField1111.setLabelString("Start :");
		deviceField1111.setNumCols(12);
		deviceField1111.setIdentifier("");
		deviceField1112.setIdentifier("");
		deviceField1112.setNumCols(12);
		deviceField1112.setLabelString("End :");
		deviceField1112.setOffsetNid(99);
		deviceChannel15.setLabelString("Ch 15");
		deviceChannel15.setOffsetNid(97);
		deviceChannel15.setInSameLine(true);
		deviceChannel15.setUpdateIdentifier("");
		deviceChannel15.setShowVal("");
		deviceChannel15.setLayout(flowLayout16);
		deviceChannel16.setLayout(flowLayout17);
		deviceChannel16.setShowVal("");
		deviceChannel16.setUpdateIdentifier("");
		deviceChannel16.setInSameLine(true);
		deviceChannel16.setOffsetNid(103);
		deviceChannel16.setLabelString("Ch 16");
		deviceField1113.setIdentifier("");
		deviceField1113.setNumCols(12);
		deviceField1113.setLabelString("End :");
		deviceField1113.setOffsetNid(105);
		deviceField1114.setOffsetNid(104);
		deviceField1114.setLabelString("Start :");
		deviceField1114.setNumCols(12);
		deviceField1114.setIdentifier("");
		deviceChannel18.setLayout(flowLayout18);
		deviceChannel18.setShowVal("");
		deviceChannel18.setUpdateIdentifier("");
		deviceChannel18.setInSameLine(true);
		deviceChannel18.setOffsetNid(19);
		deviceChannel18.setLabelString("Ch 02");
		deviceField20.setOffsetNid(22);
		deviceField20.setLabelString("Start :");
		deviceField20.setNumCols(12);
		deviceField20.setIdentifier("");
		deviceField21.setOffsetNid(23);
		deviceField21.setLabelString("End :");
		deviceField21.setNumCols(12);
		deviceField21.setIdentifier("");
		deviceChannel19.setLayout(flowLayout19);
		deviceChannel19.setShowVal("");
		deviceChannel19.setUpdateIdentifier("");
		deviceChannel19.setInSameLine(true);
		deviceChannel19.setOffsetNid(25);
		deviceChannel19.setLabelString("Ch 03");
		deviceField22.setOffsetNid(28);
		deviceField22.setLabelString("Start :");
		deviceField22.setNumCols(12);
		deviceField22.setIdentifier("");
		deviceField23.setOffsetNid(29);
		deviceField23.setLabelString("End :");
		deviceField23.setNumCols(12);
		deviceField23.setIdentifier("");
		deviceField24.setIdentifier("");
		deviceField24.setNumCols(12);
		deviceField24.setLabelString("Start :");
		deviceField24.setOffsetNid(34);
		deviceChannel110.setLabelString("Ch 04");
		deviceChannel110.setOffsetNid(31);
		deviceChannel110.setInSameLine(true);
		deviceChannel110.setUpdateIdentifier("");
		deviceChannel110.setShowVal("");
		deviceChannel110.setLayout(flowLayout110);
		deviceField25.setOffsetNid(35);
		deviceField25.setLabelString("End :");
		deviceField25.setNumCols(12);
		deviceField25.setIdentifier("");
		deviceField26.setIdentifier("");
		deviceField26.setNumCols(12);
		deviceField26.setLabelString("End :");
		deviceField26.setOffsetNid(41);
		deviceField27.setOffsetNid(40);
		deviceField27.setLabelString("Start :");
		deviceField27.setNumCols(12);
		deviceField27.setIdentifier("");
		deviceChannel111.setLabelString("Ch 05");
		deviceChannel111.setOffsetNid(37);
		deviceChannel111.setInSameLine(true);
		deviceChannel111.setUpdateIdentifier("");
		deviceChannel111.setShowVal("");
		deviceChannel111.setLayout(flowLayout111);
		deviceChannel112.setLayout(flowLayout112);
		deviceChannel112.setShowVal("");
		deviceChannel112.setUpdateIdentifier("");
		deviceChannel112.setInSameLine(true);
		deviceChannel112.setOffsetNid(43);
		deviceChannel112.setLabelString("Ch 06");
		deviceField28.setIdentifier("");
		deviceField28.setNumCols(12);
		deviceField28.setLabelString("End :");
		deviceField28.setOffsetNid(47);
		deviceField29.setOffsetNid(46);
		deviceField29.setLabelString("Start :");
		deviceField29.setNumCols(12);
		deviceField29.setIdentifier("");
		deviceField210.setOffsetNid(53);
		deviceField210.setLabelString("End :");
		deviceField210.setNumCols(12);
		deviceField210.setIdentifier("");
		deviceField211.setOffsetNid(52);
		deviceField211.setLabelString("Start :");
		deviceField211.setNumCols(12);
		deviceField211.setIdentifier("");
		deviceChannel113.setLayout(flowLayout113);
		deviceChannel113.setShowVal("");
		deviceChannel113.setUpdateIdentifier("");
		deviceChannel113.setInSameLine(true);
		deviceChannel113.setOffsetNid(49);
		deviceChannel113.setLabelString("Ch 07");
		deviceField212.setIdentifier("");
		deviceField212.setNumCols(12);
		deviceField212.setLabelString("Start :");
		deviceField212.setOffsetNid(58);
		deviceChannel114.setLabelString("Ch 08");
		deviceChannel114.setOffsetNid(55);
		deviceChannel114.setInSameLine(true);
		deviceChannel114.setUpdateIdentifier("");
		deviceChannel114.setShowVal("");
		deviceChannel114.setLayout(flowLayout114);
		deviceField213.setOffsetNid(59);
		deviceField213.setLabelString("End :");
		deviceField213.setNumCols(12);
		deviceField213.setIdentifier("");
		deviceField214.setIdentifier("");
		deviceField214.setNumCols(12);
		deviceField214.setLabelString("End :");
		deviceField214.setOffsetNid(65);
		deviceField215.setIdentifier("");
		deviceField215.setNumCols(12);
		deviceField215.setLabelString("Start :");
		deviceField215.setOffsetNid(64);
		deviceChannel115.setLabelString("Ch 09");
		deviceChannel115.setOffsetNid(61);
		deviceChannel115.setInSameLine(true);
		deviceChannel115.setUpdateIdentifier("");
		deviceChannel115.setShowVal("");
		deviceChannel115.setLayout(flowLayout115);
		deviceChannel116.setLayout(flowLayout116);
		deviceChannel116.setShowVal("");
		deviceChannel116.setUpdateIdentifier("");
		deviceChannel116.setInSameLine(true);
		deviceChannel116.setOffsetNid(67);
		deviceChannel116.setLabelString("Ch 10");
		deviceField216.setIdentifier("");
		deviceField216.setNumCols(12);
		deviceField216.setLabelString("End :");
		deviceField216.setOffsetNid(71);
		deviceField217.setIdentifier("");
		deviceField217.setNumCols(12);
		deviceField217.setLabelString("Start :");
		deviceField217.setOffsetNid(70);
		deviceChannel117.setLabelString("Ch 11");
		deviceChannel117.setOffsetNid(73);
		deviceChannel117.setInSameLine(true);
		deviceChannel117.setUpdateIdentifier("");
		deviceChannel117.setShowVal("");
		deviceChannel117.setLayout(flowLayout117);
		deviceField218.setIdentifier("");
		deviceField218.setNumCols(12);
		deviceField218.setLabelString("End :");
		deviceField218.setOffsetNid(77);
		deviceField219.setIdentifier("");
		deviceField219.setNumCols(12);
		deviceField219.setLabelString("Start :");
		deviceField219.setOffsetNid(76);
		deviceField2110.setOffsetNid(83);
		deviceField2110.setLabelString("End :");
		deviceField2110.setNumCols(12);
		deviceField2110.setIdentifier("");
		deviceChannel118.setLabelString("Ch 12");
		deviceChannel118.setOffsetNid(79);
		deviceChannel118.setInSameLine(true);
		deviceChannel118.setUpdateIdentifier("");
		deviceChannel118.setShowVal("");
		deviceChannel118.setLayout(flowLayout118);
		deviceField2111.setIdentifier("");
		deviceField2111.setNumCols(12);
		deviceField2111.setLabelString("Start :");
		deviceField2111.setOffsetNid(82);
		deviceField2112.setOffsetNid(88);
		deviceField2112.setLabelString("Start :");
		deviceField2112.setNumCols(12);
		deviceField2112.setIdentifier("");
		deviceChannel119.setLayout(flowLayout119);
		deviceChannel119.setShowVal("");
		deviceChannel119.setUpdateIdentifier("");
		deviceChannel119.setInSameLine(true);
		deviceChannel119.setOffsetNid(85);
		deviceChannel119.setLabelString("Ch 13");
		deviceField2113.setOffsetNid(89);
		deviceField2113.setLabelString("End :");
		deviceField2113.setNumCols(12);
		deviceField2113.setIdentifier("");
		deviceChannel1110.setLabelString("Ch 14");
		deviceChannel1110.setOffsetNid(91);
		deviceChannel1110.setInSameLine(true);
		deviceChannel1110.setUpdateIdentifier("");
		deviceChannel1110.setShowVal("");
		deviceChannel1110.setLayout(flowLayout1110);
		deviceField2114.setOffsetNid(95);
		deviceField2114.setLabelString("End :");
		deviceField2114.setNumCols(12);
		deviceField2114.setIdentifier("");
		deviceField2115.setOffsetNid(94);
		deviceField2115.setLabelString("Start :");
		deviceField2115.setNumCols(12);
		deviceField2115.setIdentifier("");
		deviceField2116.setOffsetNid(100);
		deviceField2116.setLabelString("Start :");
		deviceField2116.setNumCols(12);
		deviceField2116.setIdentifier("");
		deviceChannel1111.setLabelString("Ch 15");
		deviceChannel1111.setOffsetNid(97);
		deviceChannel1111.setInSameLine(true);
		deviceChannel1111.setUpdateIdentifier("");
		deviceChannel1111.setShowVal("");
		deviceChannel1111.setLayout(flowLayout1111);
		deviceField2117.setOffsetNid(101);
		deviceField2117.setLabelString("End :");
		deviceField2117.setNumCols(12);
		deviceField2117.setIdentifier("");
		deviceField2118.setIdentifier("");
		deviceField2118.setNumCols(12);
		deviceField2118.setLabelString("Start :");
		deviceField2118.setOffsetNid(106);
		deviceChannel1112.setLayout(flowLayout1112);
		deviceChannel1112.setShowVal("");
		deviceChannel1112.setUpdateIdentifier("");
		deviceChannel1112.setInSameLine(true);
		deviceChannel1112.setOffsetNid(103);
		deviceChannel1112.setLabelString("Ch 16");
		deviceField2119.setOffsetNid(107);
		deviceField2119.setLabelString("End :");
		deviceField2119.setNumCols(12);
		deviceField2119.setIdentifier("");
		jPanel31.setBorder(
				new TitledBorder(BorderFactory.createEtchedBorder(Color.white, new Color(142, 142, 142)), "General"));
		jPanel31.setLayout(gridLayout3);
		deviceField30.setOffsetNid(1);
		deviceField30.setLabelString("Board Id :");
		deviceField30.setNumCols(3);
		deviceField30.setIdentifier("");
		deviceChoice1.setChoiceIntValues(null);
		deviceChoice1.setChoiceFloatValues(null);
		deviceChoice1.setOffsetNid(2);
		deviceChoice1.setLabelString("Software Mode :");
		deviceChoice1.setChoiceItems(new String[]
		{ "LOCAL", "REMOTE" });
		deviceChoice1.setUpdateIdentifier("");
		deviceChoice1.setIdentifier("");
		deviceField31.setOffsetNid(4);
		deviceField31.setTextOnly(true);
		deviceField31.setLabelString("Comment :");
		deviceField31.setNumCols(20);
		deviceField31.setIdentifier("");
		deviceField32.setOffsetNid(3);
		deviceField32.setTextOnly(true);
		deviceField32.setLabelString("Ip Addr. :");
		deviceField32.setNumCols(11);
		deviceField32.setIdentifier("");
		jPanel32.setLayout(gridLayout4);
		jPanel32.setBorder(
				new TitledBorder(BorderFactory.createEtchedBorder(Color.white, new Color(142, 142, 142)), "Clock"));
		deviceField34.setOffsetNid(5);
		deviceField34.setLabelString("Source :");
		deviceField34.setNumCols(30);
		deviceField34.setIdentifier("");
		deviceChoice2.setChoiceIntValues(null);
		deviceChoice2.setChoiceFloatValues(null);
		deviceChoice2.setOffsetNid(6);
		deviceChoice2.setLabelString("Mode :");
		deviceChoice2.setChoiceItems(new String[]
		{ "INTERNAL", "EXTERNAL" });
		deviceChoice2.setUpdateIdentifier("");
		deviceChoice2.setIdentifier("");
		deviceChoice3.setIdentifier("");
		deviceChoice3.setUpdateIdentifier("");
		deviceChoice3.setChoiceItems(new String[]
		{ "200E3", "100E3", "50E3", "20E3", "10E3", "5E3", "2E3", "1E3", "500", "200", "100" });
		deviceChoice3.setLabelString("Frequency (Hz) :");
		deviceChoice3.setOffsetNid(7);
		deviceChoice3.setChoiceFloatValues(new float[]
		{ (float) 200000.0, (float) 100000.0, (float) 50000.0, (float) 20000.0, (float) 10000.0, (float) 5000.0,
				(float) 2000.0, (float) 1000.0, (float) 500.0, (float) 200.0, (float) 100.0 });
		deviceChoice3.setChoiceIntValues(null);
		jPanel33.setBorder(
				new TitledBorder(BorderFactory.createEtchedBorder(Color.white, new Color(142, 142, 142)), "Trigger"));
		jPanel33.setLayout(gridLayout5);
		deviceChoice4.setChoiceIntValues(null);
		deviceChoice4.setChoiceFloatValues(null);
		deviceChoice4.setOffsetNid(9);
		deviceChoice4.setLabelString("Mode :");
		deviceChoice4.setChoiceItems(new String[]
		{ "INTERNAL", "EXTERNAL" });
		deviceChoice4.setUpdateIdentifier("");
		deviceChoice4.setIdentifier("");
		deviceField35.setOffsetNid(8);
		deviceField35.setLabelString("Source :");
		deviceField35.setNumCols(30);
		deviceField35.setIdentifier("");
		deviceChoice5.setIdentifier("");
		deviceChoice5.setUpdateIdentifier("");
		deviceChoice5.setChoiceItems(new String[]
		{ "RISING", "FALLING" });
		deviceChoice5.setLabelString("Edge :");
		deviceChoice5.setOffsetNid(10);
		deviceChoice5.setChoiceFloatValues(null);
		deviceChoice5.setChoiceIntValues(null);
		deviceChoice6.setChoiceIntValues(null);
		deviceChoice6.setChoiceFloatValues(null);
		deviceChoice6.setOffsetNid(12);
		deviceChoice6.setLabelString("Use Times :");
		deviceChoice6.setChoiceItems(new String[]
		{ "TRUE", "FALSE" });
		deviceChoice6.setUpdateIdentifier("");
		deviceChoice6.setIdentifier("");
		deviceButtons1.setCheckExpressions(null);
		deviceButtons1.setCheckMessages(null);
		deviceButtons1.setMethods(new String[]
		{ "INIT", "TRIGGER", "STORE" });
		gridLayout3.setColumns(1);
		gridLayout3.setRows(2);
		gridLayout4.setColumns(1);
		gridLayout4.setRows(2);
		gridLayout5.setColumns(1);
		gridLayout5.setRows(2);
		jPanel39.setLayout(gridLayout6);
		gridLayout6.setColumns(1);
		gridLayout6.setRows(3);
		jPanel34.setMinimumSize(new Dimension(298, 30));
		jPanel34.setPreferredSize(new Dimension(508, 30));
		jPanel39.setAlignmentX((float) 0.5);
		jPanel39.setAlignmentY((float) 0.5);
		jTabbedPane1.add(jScrollPane1, "Times");
		jTabbedPane1.add(jScrollPane2, "Samples");
		this.getContentPane().add(deviceButtons1, BorderLayout.SOUTH);
		jScrollPane2.getViewport().add(jPanel4, null);
		jScrollPane1.getViewport().add(jPanel3, null);
		jPanel2.add(deviceChoice6, BorderLayout.NORTH);
		jPanel2.add(jTabbedPane1, BorderLayout.CENTER);
		jPanel30.add(deviceField30, null);
		jPanel30.add(deviceField32, null);
		jPanel30.add(deviceDispatch1, null);
		this.getContentPane().add(jPanel2, BorderLayout.CENTER);
		jPanel34.add(deviceField31, null);
		jPanel34.add(deviceChoice1, null);
		jPanel35.add(deviceChoice2, null);
		jPanel35.add(deviceChoice3, null);
		jPanel36.add(deviceField34, null);
		jPanel37.add(deviceChoice4, null);
		jPanel37.add(deviceChoice5, null);
		jPanel38.add(deviceField35, null);
		this.getContentPane().add(jPanel39, BorderLayout.NORTH);
		deviceChannel17.add(jPanel6, null);
		jPanel6.add(deviceField3, null);
		jPanel6.add(deviceField4, null);
		deviceChannel1112.add(jPanel214, null);
		jPanel214.add(deviceField2118, null);
		jPanel214.add(deviceField2119, null);
		deviceChannel1111.add(jPanel213, null);
		jPanel213.add(deviceField2116, null);
		jPanel213.add(deviceField2117, null);
		deviceChannel1110.add(jPanel212, null);
		jPanel212.add(deviceField2115, null);
		jPanel212.add(deviceField2114, null);
		deviceChannel119.add(jPanel211, null);
		jPanel211.add(deviceField2112, null);
		jPanel211.add(deviceField2113, null);
		deviceChannel118.add(jPanel210, null);
		jPanel210.add(deviceField2111, null);
		jPanel210.add(deviceField2110, null);
		deviceChannel117.add(jPanel29, null);
		jPanel29.add(deviceField219, null);
		jPanel29.add(deviceField218, null);
		deviceChannel116.add(jPanel28, null);
		jPanel28.add(deviceField217, null);
		jPanel28.add(deviceField216, null);
		deviceChannel115.add(jPanel27, null);
		jPanel27.add(deviceField215, null);
		jPanel27.add(deviceField214, null);
		deviceChannel114.add(jPanel26, null);
		jPanel26.add(deviceField212, null);
		jPanel26.add(deviceField213, null);
		deviceChannel113.add(jPanel25, null);
		jPanel25.add(deviceField211, null);
		jPanel25.add(deviceField210, null);
		deviceChannel112.add(jPanel24, null);
		jPanel24.add(deviceField29, null);
		jPanel24.add(deviceField28, null);
		deviceChannel111.add(jPanel23, null);
		jPanel23.add(deviceField27, null);
		jPanel23.add(deviceField26, null);
		deviceChannel110.add(jPanel22, null);
		jPanel22.add(deviceField24, null);
		jPanel22.add(deviceField25, null);
		deviceChannel19.add(jPanel21, null);
		jPanel21.add(deviceField22, null);
		jPanel21.add(deviceField23, null);
		deviceChannel18.add(jPanel20, null);
		jPanel20.add(deviceField20, null);
		jPanel20.add(deviceField21, null);
		deviceChannel1.add(jPanel5, null);
		jPanel5.add(deviceField1, null);
		jPanel5.add(deviceField2, null);
		deviceChannel16.add(jPanel111, null);
		jPanel111.add(deviceField1114, null);
		jPanel111.add(deviceField1113, null);
		deviceChannel15.add(jPanel110, null);
		jPanel110.add(deviceField1111, null);
		jPanel110.add(deviceField1112, null);
		deviceChannel14.add(jPanel19, null);
		jPanel19.add(deviceField1110, null);
		jPanel19.add(deviceField119, null);
		deviceChannel13.add(jPanel18, null);
		jPanel18.add(deviceField118, null);
		jPanel18.add(deviceField117, null);
		deviceChannel12.add(jPanel17, null);
		jPanel17.add(deviceField116, null);
		jPanel17.add(deviceField115, null);
		deviceChannel11.add(jPanel16, null);
		jPanel16.add(deviceField113, null);
		jPanel16.add(deviceField114, null);
		deviceChannel10.add(jPanel15, null);
		jPanel15.add(deviceField112, null);
		jPanel15.add(deviceField111, null);
		deviceChannel9.add(jPanel14, null);
		jPanel14.add(deviceField19, null);
		jPanel14.add(deviceField110, null);
		deviceChannel8.add(jPanel13, null);
		jPanel13.add(deviceField17, null);
		jPanel13.add(deviceField18, null);
		deviceChannel7.add(jPanel12, null);
		jPanel12.add(deviceField15, null);
		jPanel12.add(deviceField16, null);
		deviceChannel6.add(jPanel11, null);
		jPanel11.add(deviceField14, null);
		jPanel11.add(deviceField13, null);
		deviceChannel5.add(jPanel10, null);
		jPanel10.add(deviceField12, null);
		jPanel10.add(deviceField11, null);
		deviceChannel4.add(jPanel9, null);
		jPanel9.add(deviceField9, null);
		jPanel9.add(deviceField10, null);
		deviceChannel3.add(jPanel8, null);
		jPanel8.add(deviceField7, null);
		jPanel8.add(deviceField8, null);
		deviceChannel2.add(jPanel7, null);
		jPanel7.add(deviceField5, null);
		jPanel7.add(deviceField6, null);
		jPanel31.add(jPanel30, null);
		jPanel31.add(jPanel34, null);
		jPanel32.add(jPanel35, null);
		jPanel32.add(jPanel36, null);
		jPanel33.add(jPanel37, null);
		jPanel33.add(jPanel38, null);
		jPanel39.add(jPanel31, null);
		jPanel39.add(jPanel32, null);
		jPanel39.add(jPanel33, null);
		jPanel3.add(deviceChannel1, null);
		jPanel3.add(deviceChannel2, null);
		jPanel3.add(deviceChannel3, null);
		jPanel3.add(deviceChannel4, null);
		jPanel3.add(deviceChannel5, null);
		jPanel3.add(deviceChannel6, null);
		jPanel3.add(deviceChannel7, null);
		jPanel3.add(deviceChannel8, null);
		jPanel3.add(deviceChannel9, null);
		jPanel3.add(deviceChannel10, null);
		jPanel3.add(deviceChannel11, null);
		jPanel3.add(deviceChannel12, null);
		jPanel3.add(deviceChannel13, null);
		jPanel3.add(deviceChannel14, null);
		jPanel3.add(deviceChannel15, null);
		jPanel3.add(deviceChannel16, null);
		jPanel4.add(deviceChannel17, null);
		jPanel4.add(deviceChannel18, null);
		jPanel4.add(deviceChannel19, null);
		jPanel4.add(deviceChannel110, null);
		jPanel4.add(deviceChannel111, null);
		jPanel4.add(deviceChannel112, null);
		jPanel4.add(deviceChannel113, null);
		jPanel4.add(deviceChannel114, null);
		jPanel4.add(deviceChannel115, null);
		jPanel4.add(deviceChannel116, null);
		jPanel4.add(deviceChannel117, null);
		jPanel4.add(deviceChannel118, null);
		jPanel4.add(deviceChannel119, null);
		jPanel4.add(deviceChannel1110, null);
		jPanel4.add(deviceChannel1111, null);
		jPanel4.add(deviceChannel1112, null);
	}
}
