import java.awt.*;
import javax.swing.*;

/**
 * <p>
 * Title:
 * </p>
 * <p>
 * Description:
 * </p>
 * <p>
 * Copyright: Copyright (c) 2003
 * </p>
 * <p>
 * Company:
 * </p>
 *
 * @author not attributable
 * @version 1.0
 */
public class GEN_GAINSetup extends DeviceSetup
{
	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	BorderLayout borderLayout1 = new BorderLayout();
	JPanel jPanel1 = new JPanel();
	GridLayout gridLayout1 = new GridLayout();
	JPanel jPanel2 = new JPanel();
	DeviceField deviceField1 = new DeviceField();
	FlowLayout flowLayout1 = new FlowLayout();
	DeviceField deviceField2 = new DeviceField();
	DeviceButtons deviceButtons1 = new DeviceButtons();
	JScrollPane jScrollPane1 = new JScrollPane();
	JPanel jPanel4 = new JPanel();
	GridLayout gridLayout2 = new GridLayout();
	JPanel jPanel5 = new JPanel();
	DeviceChannel deviceChannel1 = new DeviceChannel();
	FlowLayout flowLayout3 = new FlowLayout();
	JPanel jPanel6 = new JPanel();
	BorderLayout borderLayout2 = new BorderLayout();
	FlowLayout flowLayout4 = new FlowLayout();
	DeviceField deviceField3 = new DeviceField();
	DeviceField deviceField6 = new DeviceField();
	JPanel jPanel7 = new JPanel();
	FlowLayout flowLayout5 = new FlowLayout();
	JLabel jLabel1 = new JLabel();
	FlowLayout flowLayout6 = new FlowLayout();
	JPanel jPanel8 = new JPanel();
	DeviceField deviceField8 = new DeviceField();
	BorderLayout borderLayout3 = new BorderLayout();
	DeviceChannel deviceChannel2 = new DeviceChannel();
	DeviceField deviceField9 = new DeviceField();
	FlowLayout flowLayout7 = new FlowLayout();
	JPanel jPanel9 = new JPanel();
	FlowLayout flowLayout8 = new FlowLayout();
	JPanel jPanel10 = new JPanel();
	DeviceField deviceField12 = new DeviceField();
	BorderLayout borderLayout4 = new BorderLayout();
	DeviceChannel deviceChannel3 = new DeviceChannel();
	DeviceField deviceField13 = new DeviceField();
	FlowLayout flowLayout9 = new FlowLayout();
	JPanel jPanel11 = new JPanel();
	FlowLayout flowLayout10 = new FlowLayout();
	JPanel jPanel12 = new JPanel();
	DeviceField deviceField16 = new DeviceField();
	BorderLayout borderLayout5 = new BorderLayout();
	DeviceChannel deviceChannel4 = new DeviceChannel();
	DeviceField deviceField17 = new DeviceField();
	FlowLayout flowLayout11 = new FlowLayout();
	JPanel jPanel13 = new JPanel();
	FlowLayout flowLayout12 = new FlowLayout();
	JPanel jPanel14 = new JPanel();
	DeviceField deviceField110 = new DeviceField();
	BorderLayout borderLayout6 = new BorderLayout();
	DeviceChannel deviceChannel5 = new DeviceChannel();
	DeviceField deviceField111 = new DeviceField();
	FlowLayout flowLayout13 = new FlowLayout();
	JPanel jPanel15 = new JPanel();
	FlowLayout flowLayout14 = new FlowLayout();
	JPanel jPanel16 = new JPanel();
	DeviceField deviceField114 = new DeviceField();
	BorderLayout borderLayout7 = new BorderLayout();
	DeviceChannel deviceChannel6 = new DeviceChannel();
	DeviceField deviceField115 = new DeviceField();
	FlowLayout flowLayout15 = new FlowLayout();
	JPanel jPanel17 = new JPanel();
	FlowLayout flowLayout16 = new FlowLayout();
	JPanel jPanel18 = new JPanel();
	DeviceField deviceField118 = new DeviceField();
	BorderLayout borderLayout8 = new BorderLayout();
	DeviceChannel deviceChannel7 = new DeviceChannel();
	DeviceField deviceField119 = new DeviceField();
	FlowLayout flowLayout17 = new FlowLayout();
	JPanel jPanel19 = new JPanel();
	FlowLayout flowLayout18 = new FlowLayout();
	JPanel jPanel110 = new JPanel();
	DeviceField deviceField1112 = new DeviceField();
	BorderLayout borderLayout9 = new BorderLayout();
	DeviceChannel deviceChannel8 = new DeviceChannel();
	DeviceField deviceField1113 = new DeviceField();
	FlowLayout flowLayout19 = new FlowLayout();
	JPanel jPanel111 = new JPanel();
	FlowLayout flowLayout110 = new FlowLayout();
	JPanel jPanel112 = new JPanel();
	DeviceField deviceField1116 = new DeviceField();
	BorderLayout borderLayout10 = new BorderLayout();
	DeviceChannel deviceChannel9 = new DeviceChannel();
	DeviceField deviceField1117 = new DeviceField();
	FlowLayout flowLayout111 = new FlowLayout();
	JPanel jPanel113 = new JPanel();
	FlowLayout flowLayout112 = new FlowLayout();
	JPanel jPanel114 = new JPanel();
	DeviceField deviceField11110 = new DeviceField();
	BorderLayout borderLayout11 = new BorderLayout();
	DeviceChannel deviceChannel10 = new DeviceChannel();
	DeviceField deviceField11111 = new DeviceField();
	FlowLayout flowLayout113 = new FlowLayout();
	JPanel jPanel115 = new JPanel();
	FlowLayout flowLayout114 = new FlowLayout();
	JPanel jPanel116 = new JPanel();
	DeviceField deviceField11114 = new DeviceField();
	BorderLayout borderLayout12 = new BorderLayout();
	DeviceChannel deviceChannel11 = new DeviceChannel();
	DeviceField deviceField11115 = new DeviceField();
	FlowLayout flowLayout115 = new FlowLayout();
	JPanel jPanel117 = new JPanel();
	FlowLayout flowLayout116 = new FlowLayout();
	JPanel jPanel118 = new JPanel();
	DeviceField deviceField11118 = new DeviceField();
	BorderLayout borderLayout13 = new BorderLayout();
	DeviceChannel deviceChannel12 = new DeviceChannel();
	DeviceField deviceField11119 = new DeviceField();
	FlowLayout flowLayout117 = new FlowLayout();
	JPanel jPanel119 = new JPanel();
	FlowLayout flowLayout118 = new FlowLayout();
	JPanel jPanel1110 = new JPanel();
	DeviceField deviceField111112 = new DeviceField();
	BorderLayout borderLayout14 = new BorderLayout();
	DeviceChannel deviceChannel13 = new DeviceChannel();
	DeviceField deviceField111113 = new DeviceField();
	FlowLayout flowLayout119 = new FlowLayout();
	JPanel jPanel1111 = new JPanel();
	FlowLayout flowLayout1110 = new FlowLayout();
	JPanel jPanel1112 = new JPanel();
	DeviceField deviceField111116 = new DeviceField();
	BorderLayout borderLayout15 = new BorderLayout();
	DeviceChannel deviceChannel14 = new DeviceChannel();
	DeviceField deviceField111117 = new DeviceField();
	FlowLayout flowLayout1111 = new FlowLayout();
	JPanel jPanel1113 = new JPanel();
	FlowLayout flowLayout1112 = new FlowLayout();
	JPanel jPanel1114 = new JPanel();
	DeviceField deviceField1111110 = new DeviceField();
	BorderLayout borderLayout16 = new BorderLayout();
	DeviceChannel deviceChannel15 = new DeviceChannel();
	DeviceField deviceField1111111 = new DeviceField();
	FlowLayout flowLayout1113 = new FlowLayout();
	JPanel jPanel1115 = new JPanel();
	FlowLayout flowLayout1114 = new FlowLayout();
	JPanel jPanel1116 = new JPanel();
	DeviceField deviceField1111114 = new DeviceField();
	BorderLayout borderLayout17 = new BorderLayout();
	DeviceChannel deviceChannel16 = new DeviceChannel();
	DeviceField deviceField1111115 = new DeviceField();
	FlowLayout flowLayout1115 = new FlowLayout();
	JPanel jPanel1117 = new JPanel();

	public GEN_GAINSetup()
	{
		try
		{
			jbInit();
		}
		catch (final Exception e)
		{
			e.printStackTrace();
		}
	}

	private void jbInit() throws Exception
	{
		this.setWidth(800);
		this.setHeight(400);
		this.setDeviceType("GEN_GAIN");
		this.setDeviceProvider("150.178.3.33");
		this.setDeviceTitle("General ADC Calibration setup");
		this.getContentPane().setLayout(borderLayout1);
		jPanel1.setLayout(gridLayout1);
		gridLayout1.setRows(2);
		deviceField1.setOffsetNid(1);
		deviceField1.setLabelString("Comment: ");
		deviceField1.setNumCols(25);
		deviceField1.setIdentifier("");
		jPanel2.setLayout(flowLayout1);
		flowLayout1.setAlignment(FlowLayout.LEFT);
		flowLayout1.setHgap(0);
		flowLayout1.setVgap(0);
		deviceField2.setOffsetNid(2);
		deviceField2.setLabelString("ADC :");
		deviceField2.setNumCols(25);
		deviceField2.setIdentifier("");
		jPanel4.setLayout(gridLayout2);
		gridLayout2.setColumns(2);
		gridLayout2.setRows(8);
		jPanel5.setLayout(flowLayout3);
		deviceChannel1.setLabelString("01");
		deviceChannel1.setOffsetNid(3);
		deviceChannel1.setInSameLine(true);
		deviceChannel1.setUpdateIdentifier("");
		deviceChannel1.setShowVal("");
		deviceChannel1.setLayout(borderLayout2);
		flowLayout3.setAlignment(FlowLayout.LEFT);
		flowLayout3.setHgap(0);
		flowLayout3.setVgap(3);
		jPanel6.setLayout(flowLayout4);
		flowLayout4.setAlignment(FlowLayout.LEFT);
		flowLayout4.setHgap(0);
		flowLayout4.setVgap(0);
		jPanel7.setLayout(flowLayout5);
		flowLayout5.setAlignment(FlowLayout.LEFT);
		flowLayout5.setHgap(0);
		flowLayout5.setVgap(0);
		jLabel1.setRequestFocusEnabled(true);
		jLabel1.setText("Channel               Name                                       "
				+ "Calibration               Channel                Name            "
				+ "                    Calibration");
		deviceField3.setOffsetNid(4);
		deviceField3.setTextOnly(true);
		deviceField3.setNumCols(15);
		deviceField3.setIdentifier("");
		deviceField3.setEditable(false);
		deviceField6.setOffsetNid(5);
		deviceField6.setNumCols(15);
		deviceField6.setIdentifier("");
		flowLayout6.setVgap(0);
		flowLayout6.setHgap(0);
		flowLayout6.setAlignment(FlowLayout.LEFT);
		jPanel8.setLayout(flowLayout7);
		deviceField8.setOffsetNid(79);
		deviceField8.setTextOnly(true);
		deviceField8.setNumCols(15);
		deviceField8.setIdentifier("");
		deviceField8.setEditable(false);
		deviceChannel2.setLabelString("16");
		deviceChannel2.setOffsetNid(78);
		deviceChannel2.setInSameLine(true);
		deviceChannel2.setUpdateIdentifier("");
		deviceChannel2.setShowVal("");
		deviceChannel2.setLayout(borderLayout3);
		deviceField9.setOffsetNid(80);
		deviceField9.setNumCols(15);
		deviceField9.setIdentifier("");
		flowLayout7.setAlignment(FlowLayout.LEFT);
		flowLayout7.setHgap(0);
		flowLayout7.setVgap(0);
		jPanel9.setLayout(flowLayout6);
		flowLayout8.setVgap(0);
		flowLayout8.setHgap(0);
		flowLayout8.setAlignment(FlowLayout.LEFT);
		jPanel10.setLayout(flowLayout9);
		deviceField12.setOffsetNid(39);
		deviceField12.setTextOnly(true);
		deviceField12.setNumCols(15);
		deviceField12.setIdentifier("");
		deviceField12.setEditable(false);
		deviceChannel3.setLabelString("08");
		deviceChannel3.setOffsetNid(38);
		deviceChannel3.setInSameLine(true);
		deviceChannel3.setUpdateIdentifier("");
		deviceChannel3.setShowVal("");
		deviceChannel3.setLayout(borderLayout4);
		deviceField13.setOffsetNid(40);
		deviceField13.setNumCols(15);
		deviceField13.setIdentifier("");
		flowLayout9.setAlignment(FlowLayout.LEFT);
		flowLayout9.setHgap(0);
		flowLayout9.setVgap(0);
		jPanel11.setLayout(flowLayout8);
		flowLayout10.setVgap(0);
		flowLayout10.setHgap(0);
		flowLayout10.setAlignment(FlowLayout.LEFT);
		jPanel12.setLayout(flowLayout11);
		deviceField16.setOffsetNid(74);
		deviceField16.setTextOnly(true);
		deviceField16.setNumCols(15);
		deviceField16.setIdentifier("");
		deviceField16.setEditable(false);
		deviceChannel4.setLabelString("15");
		deviceChannel4.setOffsetNid(73);
		deviceChannel4.setInSameLine(true);
		deviceChannel4.setUpdateIdentifier("");
		deviceChannel4.setShowVal("");
		deviceChannel4.setLayout(borderLayout5);
		deviceField17.setOffsetNid(75);
		deviceField17.setNumCols(15);
		deviceField17.setIdentifier("");
		flowLayout11.setAlignment(FlowLayout.LEFT);
		flowLayout11.setHgap(0);
		flowLayout11.setVgap(0);
		jPanel13.setLayout(flowLayout10);
		flowLayout12.setVgap(0);
		flowLayout12.setHgap(0);
		flowLayout12.setAlignment(FlowLayout.LEFT);
		jPanel14.setLayout(flowLayout13);
		deviceField110.setOffsetNid(34);
		deviceField110.setTextOnly(true);
		deviceField110.setNumCols(15);
		deviceField110.setIdentifier("");
		deviceField110.setEditable(false);
		deviceChannel5.setLabelString("07");
		deviceChannel5.setOffsetNid(33);
		deviceChannel5.setInSameLine(true);
		deviceChannel5.setUpdateIdentifier("");
		deviceChannel5.setShowVal("");
		deviceChannel5.setLayout(borderLayout6);
		deviceField111.setOffsetNid(35);
		deviceField111.setNumCols(15);
		deviceField111.setIdentifier("");
		deviceField111.setPreferredWidth(-1);
		flowLayout13.setAlignment(FlowLayout.LEFT);
		flowLayout13.setHgap(0);
		flowLayout13.setVgap(0);
		jPanel15.setLayout(flowLayout12);
		flowLayout14.setVgap(0);
		flowLayout14.setHgap(0);
		flowLayout14.setAlignment(FlowLayout.LEFT);
		jPanel16.setLayout(flowLayout15);
		deviceField114.setOffsetNid(69);
		deviceField114.setTextOnly(true);
		deviceField114.setNumCols(15);
		deviceField114.setIdentifier("");
		deviceField114.setEditable(false);
		deviceChannel6.setLabelString("14");
		deviceChannel6.setOffsetNid(68);
		deviceChannel6.setInSameLine(true);
		deviceChannel6.setUpdateIdentifier("");
		deviceChannel6.setShowVal("");
		deviceChannel6.setLayout(borderLayout7);
		deviceField115.setOffsetNid(70);
		deviceField115.setNumCols(15);
		deviceField115.setIdentifier("");
		flowLayout15.setAlignment(FlowLayout.LEFT);
		flowLayout15.setHgap(0);
		flowLayout15.setVgap(0);
		jPanel17.setLayout(flowLayout14);
		flowLayout16.setVgap(0);
		flowLayout16.setHgap(0);
		flowLayout16.setAlignment(FlowLayout.LEFT);
		jPanel18.setLayout(flowLayout17);
		deviceField118.setOffsetNid(29);
		deviceField118.setTextOnly(true);
		deviceField118.setNumCols(15);
		deviceField118.setIdentifier("");
		deviceField118.setEditable(false);
		deviceChannel7.setLabelString("06");
		deviceChannel7.setOffsetNid(28);
		deviceChannel7.setLines(1);
		deviceChannel7.setInSameLine(true);
		deviceChannel7.setUpdateIdentifier("");
		deviceChannel7.setShowVal("");
		deviceChannel7.setLayout(borderLayout8);
		deviceField119.setOffsetNid(30);
		deviceField119.setNumCols(15);
		deviceField119.setIdentifier("");
		flowLayout17.setAlignment(FlowLayout.LEFT);
		flowLayout17.setHgap(0);
		flowLayout17.setVgap(0);
		jPanel19.setLayout(flowLayout16);
		flowLayout18.setVgap(0);
		flowLayout18.setHgap(0);
		flowLayout18.setAlignment(FlowLayout.LEFT);
		jPanel110.setLayout(flowLayout19);
		deviceField1112.setOffsetNid(64);
		deviceField1112.setTextOnly(true);
		deviceField1112.setNumCols(15);
		deviceField1112.setIdentifier("");
		deviceField1112.setEditable(false);
		deviceChannel8.setLabelString("13");
		deviceChannel8.setOffsetNid(63);
		deviceChannel8.setInSameLine(true);
		deviceChannel8.setUpdateIdentifier("");
		deviceChannel8.setShowVal("");
		deviceChannel8.setLayout(borderLayout9);
		deviceField1113.setOffsetNid(65);
		deviceField1113.setNumCols(15);
		deviceField1113.setIdentifier("");
		flowLayout19.setAlignment(FlowLayout.LEFT);
		flowLayout19.setHgap(0);
		flowLayout19.setVgap(0);
		jPanel111.setLayout(flowLayout18);
		flowLayout110.setVgap(0);
		flowLayout110.setHgap(0);
		flowLayout110.setAlignment(FlowLayout.LEFT);
		jPanel112.setLayout(flowLayout111);
		deviceField1116.setOffsetNid(24);
		deviceField1116.setTextOnly(true);
		deviceField1116.setNumCols(15);
		deviceField1116.setIdentifier("");
		deviceField1116.setEditable(false);
		deviceChannel9.setLabelString("05");
		deviceChannel9.setOffsetNid(23);
		deviceChannel9.setInSameLine(true);
		deviceChannel9.setUpdateIdentifier("");
		deviceChannel9.setShowVal("");
		deviceChannel9.setLayout(borderLayout10);
		deviceField1117.setOffsetNid(25);
		deviceField1117.setNumCols(15);
		deviceField1117.setIdentifier("");
		flowLayout111.setAlignment(FlowLayout.LEFT);
		flowLayout111.setHgap(0);
		flowLayout111.setVgap(0);
		jPanel113.setLayout(flowLayout110);
		flowLayout112.setVgap(0);
		flowLayout112.setHgap(0);
		flowLayout112.setAlignment(FlowLayout.LEFT);
		jPanel114.setLayout(flowLayout113);
		deviceField11110.setOffsetNid(59);
		deviceField11110.setTextOnly(true);
		deviceField11110.setNumCols(15);
		deviceField11110.setIdentifier("");
		deviceField11110.setEditable(false);
		deviceChannel10.setLabelString("12");
		deviceChannel10.setOffsetNid(58);
		deviceChannel10.setInSameLine(true);
		deviceChannel10.setUpdateIdentifier("");
		deviceChannel10.setShowVal("");
		deviceChannel10.setLayout(borderLayout11);
		deviceField11111.setOffsetNid(60);
		deviceField11111.setNumCols(15);
		deviceField11111.setIdentifier("");
		flowLayout113.setAlignment(FlowLayout.LEFT);
		flowLayout113.setHgap(0);
		flowLayout113.setVgap(0);
		jPanel115.setLayout(flowLayout112);
		flowLayout114.setVgap(0);
		flowLayout114.setHgap(0);
		flowLayout114.setAlignment(FlowLayout.LEFT);
		jPanel116.setLayout(flowLayout115);
		deviceField11114.setOffsetNid(19);
		deviceField11114.setTextOnly(true);
		deviceField11114.setNumCols(15);
		deviceField11114.setIdentifier("");
		deviceField11114.setEditable(false);
		deviceChannel11.setLabelString("04");
		deviceChannel11.setOffsetNid(18);
		deviceChannel11.setInSameLine(true);
		deviceChannel11.setUpdateIdentifier("");
		deviceChannel11.setShowVal("");
		deviceChannel11.setLayout(borderLayout12);
		deviceField11115.setOffsetNid(20);
		deviceField11115.setNumCols(15);
		deviceField11115.setIdentifier("");
		flowLayout115.setAlignment(FlowLayout.LEFT);
		flowLayout115.setHgap(0);
		flowLayout115.setVgap(0);
		jPanel117.setLayout(flowLayout114);
		flowLayout116.setVgap(0);
		flowLayout116.setHgap(0);
		flowLayout116.setAlignment(FlowLayout.LEFT);
		jPanel118.setLayout(flowLayout117);
		deviceField11118.setOffsetNid(54);
		deviceField11118.setTextOnly(true);
		deviceField11118.setNumCols(15);
		deviceField11118.setIdentifier("");
		deviceField11118.setEditable(false);
		deviceChannel12.setLabelString("11");
		deviceChannel12.setOffsetNid(53);
		deviceChannel12.setInSameLine(true);
		deviceChannel12.setUpdateIdentifier("");
		deviceChannel12.setShowVal("");
		deviceChannel12.setLayout(borderLayout13);
		deviceField11119.setOffsetNid(55);
		deviceField11119.setNumCols(15);
		deviceField11119.setIdentifier("");
		flowLayout117.setAlignment(FlowLayout.LEFT);
		flowLayout117.setHgap(0);
		flowLayout117.setVgap(0);
		jPanel119.setLayout(flowLayout116);
		flowLayout118.setVgap(0);
		flowLayout118.setHgap(0);
		flowLayout118.setAlignment(FlowLayout.LEFT);
		jPanel1110.setLayout(flowLayout119);
		deviceField111112.setOffsetNid(14);
		deviceField111112.setTextOnly(true);
		deviceField111112.setNumCols(15);
		deviceField111112.setIdentifier("");
		deviceField111112.setEditable(false);
		deviceChannel13.setLabelString("03");
		deviceChannel13.setOffsetNid(13);
		deviceChannel13.setInSameLine(true);
		deviceChannel13.setUpdateIdentifier("");
		deviceChannel13.setShowVal("");
		deviceChannel13.setLayout(borderLayout14);
		deviceField111113.setOffsetNid(15);
		deviceField111113.setNumCols(15);
		deviceField111113.setIdentifier("");
		flowLayout119.setAlignment(FlowLayout.LEFT);
		flowLayout119.setHgap(0);
		flowLayout119.setVgap(0);
		jPanel1111.setLayout(flowLayout118);
		flowLayout1110.setVgap(0);
		flowLayout1110.setHgap(0);
		flowLayout1110.setAlignment(FlowLayout.LEFT);
		jPanel1112.setLayout(flowLayout1111);
		deviceField111116.setOffsetNid(49);
		deviceField111116.setTextOnly(true);
		deviceField111116.setNumCols(15);
		deviceField111116.setIdentifier("");
		deviceField111116.setEditable(false);
		deviceChannel14.setLabelString("10");
		deviceChannel14.setOffsetNid(48);
		deviceChannel14.setInSameLine(true);
		deviceChannel14.setUpdateIdentifier("");
		deviceChannel14.setShowVal("");
		deviceChannel14.setLayout(borderLayout15);
		deviceField111117.setOffsetNid(50);
		deviceField111117.setNumCols(15);
		deviceField111117.setIdentifier("");
		flowLayout1111.setAlignment(FlowLayout.LEFT);
		flowLayout1111.setHgap(0);
		flowLayout1111.setVgap(0);
		jPanel1113.setLayout(flowLayout1110);
		flowLayout1112.setVgap(0);
		flowLayout1112.setHgap(0);
		flowLayout1112.setAlignment(FlowLayout.LEFT);
		jPanel1114.setLayout(flowLayout1113);
		deviceField1111110.setOffsetNid(9);
		deviceField1111110.setTextOnly(true);
		deviceField1111110.setNumCols(15);
		deviceField1111110.setIdentifier("");
		deviceField1111110.setEditable(false);
		deviceChannel15.setLabelString("02");
		deviceChannel15.setOffsetNid(8);
		deviceChannel15.setInSameLine(true);
		deviceChannel15.setUpdateIdentifier("");
		deviceChannel15.setShowVal("");
		deviceChannel15.setLayout(borderLayout16);
		deviceField1111111.setOffsetNid(10);
		deviceField1111111.setNumCols(15);
		deviceField1111111.setIdentifier("");
		flowLayout1113.setAlignment(FlowLayout.LEFT);
		flowLayout1113.setHgap(0);
		flowLayout1113.setVgap(0);
		jPanel1115.setLayout(flowLayout1112);
		flowLayout1114.setVgap(3);
		flowLayout1114.setHgap(0);
		flowLayout1114.setAlignment(FlowLayout.LEFT);
		jPanel1116.setLayout(flowLayout1115);
		deviceField1111114.setOffsetNid(44);
		deviceField1111114.setTextOnly(true);
		deviceField1111114.setNumCols(15);
		deviceField1111114.setIdentifier("");
		deviceField1111114.setEditable(false);
		deviceChannel16.setLabelString("09");
		deviceChannel16.setOffsetNid(43);
		deviceChannel16.setInSameLine(true);
		deviceChannel16.setUpdateIdentifier("");
		deviceChannel16.setShowVal("");
		deviceChannel16.setLayout(borderLayout17);
		deviceField1111115.setOffsetNid(45);
		deviceField1111115.setNumCols(15);
		deviceField1111115.setIdentifier("");
		flowLayout1115.setAlignment(FlowLayout.LEFT);
		flowLayout1115.setHgap(0);
		flowLayout1115.setVgap(0);
		jPanel1117.setLayout(flowLayout1114);
		deviceButtons1.setMethods(new String[]
		{ "setAdc" });
		this.getContentPane().add(jPanel1, BorderLayout.NORTH);
		jPanel1.add(jPanel2, null);
		jPanel2.add(deviceField1, null);
		jPanel2.add(deviceField2, null);
		jPanel1.add(jPanel7, null);
		jPanel7.add(jLabel1, null);
		this.getContentPane().add(deviceButtons1, BorderLayout.SOUTH);
		this.getContentPane().add(jScrollPane1, BorderLayout.CENTER);
		jScrollPane1.getViewport().add(jPanel4, null);
		jPanel4.add(jPanel5, null);
		jPanel5.add(deviceChannel1, null);
		deviceChannel1.add(jPanel6, BorderLayout.CENTER);
		jPanel6.add(deviceField3, null);
		jPanel6.add(deviceField6, null);
		jPanel4.add(jPanel1117, null);
		jPanel1117.add(deviceChannel16, null);
		deviceChannel16.add(jPanel1116, BorderLayout.CENTER);
		jPanel1116.add(deviceField1111114, null);
		jPanel1116.add(deviceField1111115, null);
		jPanel4.add(jPanel1115, null);
		jPanel1115.add(deviceChannel15, null);
		deviceChannel15.add(jPanel1114, BorderLayout.CENTER);
		jPanel1114.add(deviceField1111110, null);
		jPanel1114.add(deviceField1111111, null);
		jPanel4.add(jPanel1113, null);
		jPanel1113.add(deviceChannel14, null);
		deviceChannel14.add(jPanel1112, BorderLayout.CENTER);
		jPanel1112.add(deviceField111116, null);
		jPanel1112.add(deviceField111117, null);
		jPanel4.add(jPanel1111, null);
		jPanel1111.add(deviceChannel13, null);
		deviceChannel13.add(jPanel1110, BorderLayout.CENTER);
		jPanel1110.add(deviceField111112, null);
		jPanel1110.add(deviceField111113, null);
		jPanel4.add(jPanel119, null);
		jPanel119.add(deviceChannel12, null);
		deviceChannel12.add(jPanel118, BorderLayout.CENTER);
		jPanel118.add(deviceField11118, null);
		jPanel118.add(deviceField11119, null);
		jPanel4.add(jPanel117, null);
		jPanel117.add(deviceChannel11, null);
		deviceChannel11.add(jPanel116, BorderLayout.CENTER);
		jPanel116.add(deviceField11114, null);
		jPanel116.add(deviceField11115, null);
		jPanel4.add(jPanel115, null);
		jPanel115.add(deviceChannel10, null);
		deviceChannel10.add(jPanel114, BorderLayout.CENTER);
		jPanel114.add(deviceField11110, null);
		jPanel114.add(deviceField11111, null);
		jPanel4.add(jPanel113, null);
		jPanel113.add(deviceChannel9, null);
		deviceChannel9.add(jPanel112, BorderLayout.CENTER);
		jPanel112.add(deviceField1116, null);
		jPanel112.add(deviceField1117, null);
		jPanel4.add(jPanel111, null);
		jPanel111.add(deviceChannel8, null);
		deviceChannel8.add(jPanel110, BorderLayout.CENTER);
		jPanel110.add(deviceField1112, null);
		jPanel110.add(deviceField1113, null);
		jPanel4.add(jPanel19, null);
		jPanel19.add(deviceChannel7, null);
		deviceChannel7.add(jPanel18, BorderLayout.CENTER);
		jPanel18.add(deviceField118, null);
		jPanel18.add(deviceField119, null);
		jPanel4.add(jPanel17, null);
		jPanel17.add(deviceChannel6, null);
		deviceChannel6.add(jPanel16, BorderLayout.CENTER);
		jPanel16.add(deviceField114, null);
		jPanel16.add(deviceField115, null);
		jPanel4.add(jPanel15, null);
		jPanel15.add(deviceChannel5, null);
		deviceChannel5.add(jPanel14, BorderLayout.CENTER);
		jPanel14.add(deviceField110, null);
		jPanel14.add(deviceField111, null);
		jPanel4.add(jPanel13, null);
		jPanel13.add(deviceChannel4, null);
		deviceChannel4.add(jPanel12, BorderLayout.CENTER);
		jPanel12.add(deviceField16, null);
		jPanel12.add(deviceField17, null);
		jPanel4.add(jPanel11, null);
		jPanel11.add(deviceChannel3, null);
		deviceChannel3.add(jPanel10, BorderLayout.CENTER);
		jPanel10.add(deviceField12, null);
		jPanel10.add(deviceField13, null);
		jPanel4.add(jPanel9, null);
		jPanel9.add(deviceChannel2, null);
		deviceChannel2.add(jPanel8, BorderLayout.CENTER);
		jPanel8.add(deviceField8, null);
		jPanel8.add(deviceField9, null);
	}
}
