import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;

/**
 * <p>
 * Title:
 * </p>
 * <p>
 * Description:
 * </p>
 * <p>
 * Copyright: Copyright (c) 2003
 * </p>
 * <p>
 * Company:
 * </p>
 *
 * @author not attributable
 * @version 1.0
 */
public class K3115Setup extends DeviceSetup
{
	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	JPanel generalpanel = new JPanel();
	JPanel generalROW1panel = new JPanel();
	FlowLayout flowLayout1 = new FlowLayout();
	JLabel jLabel1 = new JLabel();
	DeviceField deviceField1 = new DeviceField();
	JPanel generalROW2panel = new JPanel();
	FlowLayout flowLayout2 = new FlowLayout();
	JLabel jLabel2 = new JLabel();
	DeviceField deviceField2 = new DeviceField();
	JPanel generalROW3panel = new JPanel();
	FlowLayout flowLayout3 = new FlowLayout();
	JLabel jLabel3 = new JLabel();
	DeviceChoice deviceChoice1 = new DeviceChoice();
	JLabel jLabel4 = new JLabel();
	DeviceChoice deviceChoice2 = new DeviceChoice();
	JPanel jPanel5 = new JPanel();
	JPanel clockpanel = new JPanel();
	JPanel clockROW2panel = new JPanel();
	FlowLayout flowLayout4 = new FlowLayout();
	JLabel jLabel5 = new JLabel();
	DeviceField deviceField3 = new DeviceField();
	JPanel clockROW1panel = new JPanel();
	FlowLayout flowLayout5 = new FlowLayout();
	JLabel jLabel6 = new JLabel();
	DeviceChoice deviceChoice3 = new DeviceChoice();
	JLabel jLabel7 = new JLabel();
	DeviceChoice deviceChoice4 = new DeviceChoice();
	JPanel jPanel9 = new JPanel();
	Border border1;
	TitledBorder titledBorder1;
	JPanel jPanel10 = new JPanel();
	FlowLayout flowLayout6 = new FlowLayout();
	JPanel jPanel11 = new JPanel();
	FlowLayout flowLayout7 = new FlowLayout();
	JPanel jPanel12 = new JPanel();
	FlowLayout flowLayout8 = new FlowLayout();
	JPanel jPanel13 = new JPanel();
	FlowLayout flowLayout9 = new FlowLayout();
	JPanel jPanel14 = new JPanel();
	JScrollPane jScrollPane1 = new JScrollPane();
	JPanel jPanel16 = new JPanel();
	GridLayout gridLayout2 = new GridLayout();
	GridLayout gridLayout6 = new GridLayout();
	BorderLayout borderLayout1 = new BorderLayout();
	JPanel jPanel15 = new JPanel();
	DeviceButtons deviceButtons1 = new DeviceButtons();
	GridLayout gridLayout5 = new GridLayout();
	Border border2;
	JLabel jLabel14 = new JLabel();
	DeviceField deviceField6 = new DeviceField();
	DeviceChoice deviceChoice8 = new DeviceChoice();
	JLabel jLabel15 = new JLabel();
	FlowLayout flowLayout17 = new FlowLayout();
	FlowLayout flowLayout18 = new FlowLayout();
	JPanel setupCH02panel = new JPanel();
	JLabel jLabel16 = new JLabel();
	GridLayout gridLayout7 = new GridLayout();
	FlowLayout flowLayout19 = new FlowLayout();
	JPanel jPanel25 = new JPanel();
	FlowLayout flowLayout110 = new FlowLayout();
	FlowLayout flowLayout111 = new FlowLayout();
	DeviceChoice deviceChoice9 = new DeviceChoice();
	JLabel jLabel17 = new JLabel();
	JPanel jPanel26 = new JPanel();
	JLabel jLabel18 = new JLabel();
	DeviceChoice deviceChoice10 = new DeviceChoice();
	DeviceChannel deviceChannel2 = new DeviceChannel();
	JPanel jPanel111 = new JPanel();
	JPanel CH02panel = new JPanel();
	JPanel timesCH02panel = new JPanel();
	JPanel voltagesCH02panel = new JPanel();
	JPanel jPanel29 = new JPanel();
	JLabel jLabel19 = new JLabel();
	FlowLayout flowLayout10 = new FlowLayout();
	FlowLayout flowLayout11 = new FlowLayout();
	FlowLayout flowLayout12 = new FlowLayout();
	DeviceField deviceField4 = new DeviceField();
	FlowLayout flowLayout13 = new FlowLayout();
	JPanel jPanel210 = new JPanel();
	JPanel jPanel211 = new JPanel();
	FlowLayout flowLayout112 = new FlowLayout();
	JPanel setupCH03panel = new JPanel();
	DeviceField deviceField5 = new DeviceField();
	JLabel jLabel110 = new JLabel();
	FlowLayout flowLayout113 = new FlowLayout();
	DeviceChoice deviceChoice11 = new DeviceChoice();
	FlowLayout flowLayout14 = new FlowLayout();
	DeviceField deviceField7 = new DeviceField();
	JPanel timesCH03panel = new JPanel();
	GridLayout gridLayout8 = new GridLayout();
	FlowLayout flowLayout114 = new FlowLayout();
	JLabel jLabel111 = new JLabel();
	JLabel jLabel112 = new JLabel();
	FlowLayout flowLayout15 = new FlowLayout();
	DeviceChoice deviceChoice12 = new DeviceChoice();
	JLabel jLabel113 = new JLabel();
	DeviceChoice deviceChoice13 = new DeviceChoice();
	JLabel jLabel114 = new JLabel();
	JPanel jPanel114 = new JPanel();
	FlowLayout flowLayout16 = new FlowLayout();
	JPanel voltagesCH03panel = new JPanel();
	DeviceChannel deviceChannel3 = new DeviceChannel();
	JPanel jPanel214 = new JPanel();
	FlowLayout flowLayout115 = new FlowLayout();
	JPanel CH03panel = new JPanel();
	FlowLayout flowLayout116 = new FlowLayout();
	JLabel jLabel115 = new JLabel();
	DeviceField deviceField8 = new DeviceField();
	FlowLayout flowLayout117 = new FlowLayout();
	JPanel jPanel215 = new JPanel();
	FlowLayout flowLayout118 = new FlowLayout();
	JPanel CH04panel = new JPanel();
	FlowLayout flowLayout119 = new FlowLayout();
	JLabel jLabel116 = new JLabel();
	DeviceChoice deviceChoice14 = new DeviceChoice();
	FlowLayout flowLayout1110 = new FlowLayout();
	DeviceField deviceField9 = new DeviceField();
	FlowLayout flowLayout120 = new FlowLayout();
	FlowLayout flowLayout1111 = new FlowLayout();
	JLabel jLabel117 = new JLabel();
	DeviceChoice deviceChoice15 = new DeviceChoice();
	JPanel jPanel216 = new JPanel();
	DeviceChannel deviceChannel4 = new DeviceChannel();
	JPanel timesCH04panel = new JPanel();
	JLabel jLabel118 = new JLabel();
	JLabel jLabel119 = new JLabel();
	GridLayout gridLayout9 = new GridLayout();
	FlowLayout flowLayout1112 = new FlowLayout();
	JLabel jLabel1110 = new JLabel();
	JPanel jPanel117 = new JPanel();
	FlowLayout flowLayout1113 = new FlowLayout();
	DeviceChoice deviceChoice16 = new DeviceChoice();
	JPanel setupCH04panel = new JPanel();
	JPanel jPanel218 = new JPanel();
	JLabel jLabel1111 = new JLabel();
	JPanel voltagesCH04panel = new JPanel();
	DeviceChoice deviceChoice17 = new DeviceChoice();
	FlowLayout flowLayout121 = new FlowLayout();
	JLabel jLabel1112 = new JLabel();
	DeviceChoice deviceChoice18 = new DeviceChoice();
	DeviceChannel deviceChannel5 = new DeviceChannel();
	JPanel voltagesCH01panel = new JPanel();
	FlowLayout flowLayout1114 = new FlowLayout();
	JLabel jLabel1113 = new JLabel();
	FlowLayout flowLayout1115 = new FlowLayout();
	JPanel setupCH01panel = new JPanel();
	JPanel jPanel2111 = new JPanel();
	JPanel jPanel2112 = new JPanel();
	FlowLayout flowLayout1116 = new FlowLayout();
	DeviceField deviceField10 = new DeviceField();
	FlowLayout flowLayout1117 = new FlowLayout();
	JPanel jPanel1110 = new JPanel();
	JPanel timesCH01panel = new JPanel();
	JLabel jLabel1114 = new JLabel();
	JPanel CH01panel = new JPanel();
	GridLayout gridLayout10 = new GridLayout();
	JLabel jLabel1115 = new JLabel();
	DeviceField deviceField11 = new DeviceField();
	JLabel jLabel1116 = new JLabel();
	JPanel jPanel2114 = new JPanel();
	JLabel jLabel1117 = new JLabel();
	DeviceChoice deviceChoice19 = new DeviceChoice();
	FlowLayout flowLayout1118 = new FlowLayout();
	FlowLayout flowLayout1119 = new FlowLayout();
	FlowLayout flowLayout11110 = new FlowLayout();
	FlowLayout flowLayout11111 = new FlowLayout();
	JLabel jLabel1118 = new JLabel();
	JPanel voltagesCH05panel = new JPanel();
	FlowLayout flowLayout11112 = new FlowLayout();
	DeviceChannel deviceChannel6 = new DeviceChannel();
	JLabel jLabel1119 = new JLabel();
	FlowLayout flowLayout11113 = new FlowLayout();
	JLabel jLabel11110 = new JLabel();
	DeviceChoice deviceChoice110 = new DeviceChoice();
	JLabel jLabel11111 = new JLabel();
	FlowLayout flowLayout122 = new FlowLayout();
	JPanel CH05panel = new JPanel();
	FlowLayout flowLayout11114 = new FlowLayout();
	DeviceField deviceField12 = new DeviceField();
	JPanel setupCH05panel = new JPanel();
	DeviceField deviceField13 = new DeviceField();
	DeviceChoice deviceChoice111 = new DeviceChoice();
	GridLayout gridLayout11 = new GridLayout();
	JLabel jLabel11112 = new JLabel();
	FlowLayout flowLayout11115 = new FlowLayout();
	JPanel jPanel1114 = new JPanel();
	FlowLayout flowLayout11116 = new FlowLayout();
	DeviceChoice deviceChoice112 = new DeviceChoice();
	JPanel jPanel2116 = new JPanel();
	JPanel timesCH05panel = new JPanel();
	JLabel jLabel11113 = new JLabel();
	JPanel jPanel2118 = new JPanel();
	JPanel jPanel2119 = new JPanel();
	FlowLayout flowLayout11117 = new FlowLayout();
	FlowLayout flowLayout123 = new FlowLayout();
	JPanel voltagesCH06panel = new JPanel();
	DeviceChoice deviceChoice113 = new DeviceChoice();
	JPanel setupCH06panel = new JPanel();
	FlowLayout flowLayout11118 = new FlowLayout();
	DeviceField deviceField14 = new DeviceField();
	JPanel timesCH06panel = new JPanel();
	FlowLayout flowLayout11119 = new FlowLayout();
	DeviceChoice deviceChoice114 = new DeviceChoice();
	JLabel jLabel11114 = new JLabel();
	JPanel jPanel21112 = new JPanel();
	JLabel jLabel11115 = new JLabel();
	DeviceChoice deviceChoice115 = new DeviceChoice();
	FlowLayout flowLayout111110 = new FlowLayout();
	JPanel jPanel21113 = new JPanel();
	DeviceChannel deviceChannel7 = new DeviceChannel();
	JLabel jLabel11116 = new JLabel();
	JPanel CH06panel = new JPanel();
	JLabel jLabel11117 = new JLabel();
	FlowLayout flowLayout111111 = new FlowLayout();
	DeviceField deviceField15 = new DeviceField();
	JPanel jPanel21114 = new JPanel();
	FlowLayout flowLayout111112 = new FlowLayout();
	GridLayout gridLayout12 = new GridLayout();
	JLabel jLabel11118 = new JLabel();
	JPanel jPanel1117 = new JPanel();
	FlowLayout flowLayout111113 = new FlowLayout();
	JLabel jLabel11119 = new JLabel();
	FlowLayout flowLayout111114 = new FlowLayout();
	JPanel jPanel17 = new JPanel();
	FlowLayout flowLayout20 = new FlowLayout();
	JPanel jPanel18 = new JPanel();
	DeviceDispatch deviceDispatch1 = new DeviceDispatch();
	FlowLayout flowLayout21 = new FlowLayout();
	JPanel jPanel19 = new JPanel();
	JPanel jPanel20 = new JPanel();
	JPanel jPanel21 = new JPanel();
	JPanel jPanel22 = new JPanel();
	JPanel jPanel23 = new JPanel();
	JPanel jPanel24 = new JPanel();
	FlowLayout flowLayout22 = new FlowLayout();
	FlowLayout flowLayout23 = new FlowLayout();
	FlowLayout flowLayout24 = new FlowLayout();
	FlowLayout flowLayout25 = new FlowLayout();
	FlowLayout flowLayout26 = new FlowLayout();
	FlowLayout flowLayout27 = new FlowLayout();
	JScrollPane jScrollPane2 = new JScrollPane();
	JPanel jPanel27 = new JPanel();
	GridLayout gridLayout4 = new GridLayout();
	JScrollPane jScrollPane3 = new JScrollPane();
	JPanel jPanel1 = new JPanel();
	GridLayout gridLayout13 = new GridLayout();
	BorderLayout borderLayout3 = new BorderLayout();
	BorderLayout borderLayout2 = new BorderLayout();
	BorderLayout borderLayout4 = new BorderLayout();

	public K3115Setup()
	{
		try
		{
			jbInit();
		}
		catch (final Exception e)
		{
			e.printStackTrace();
		}
	}

	private void jbInit() throws Exception
	{
		border1 = BorderFactory.createEtchedBorder(Color.white, new Color(142, 142, 142));
		titledBorder1 = new TitledBorder(border1, " GENERAL ");
		border2 = BorderFactory.createLineBorder(SystemColor.controlText, 2);
		this.setWidth(723);
		this.setHeight(723);
		this.setDeviceType("K3115");
		this.setDeviceProvider("localhost");
		this.setDeviceTitle("K3115 : programmable waveform generator");
		this.getContentPane().setLayout(borderLayout1);
		generalpanel.setLayout(borderLayout4);
		generalROW1panel.setLayout(flowLayout1);
		flowLayout1.setAlignment(FlowLayout.LEFT);
		jLabel1.setFont(new java.awt.Font("Dialog", 1, 11));
		jLabel1.setPreferredSize(new Dimension(90, 15));
		jLabel1.setToolTipText("");
		jLabel1.setHorizontalAlignment(SwingConstants.RIGHT);
		jLabel1.setText("Camac Name :");
		deviceField1.setOffsetNid(1);
		deviceField1.setTextOnly(true);
		deviceField1.setNumCols(20);
		deviceField1.setIdentifier("");
		generalROW2panel.setLayout(flowLayout2);
		flowLayout2.setAlignment(FlowLayout.LEFT);
		jLabel2.setFont(new java.awt.Font("Dialog", 1, 11));
		jLabel2.setPreferredSize(new Dimension(90, 15));
		jLabel2.setHorizontalAlignment(SwingConstants.RIGHT);
		jLabel2.setText("Comment :");
		deviceField2.setOffsetNid(2);
		deviceField2.setTextOnly(true);
		deviceField2.setNumCols(46);
		deviceField2.setIdentifier("");
		generalROW3panel.setLayout(flowLayout3);
		flowLayout3.setAlignment(FlowLayout.LEFT);
		jLabel3.setFont(new java.awt.Font("Dialog", 1, 11));
		jLabel3.setPreferredSize(new Dimension(90, 15));
		jLabel3.setHorizontalAlignment(SwingConstants.RIGHT);
		jLabel3.setText("Control Mode :");
		deviceChoice1.setChoiceIntValues(null);
		deviceChoice1.setChoiceFloatValues(null);
		deviceChoice1.setOffsetNid(3);
		deviceChoice1.setLabelString("");
		deviceChoice1.setChoiceItems(new String[]
		{ "MASTER", "SLAVE" });
		deviceChoice1.setUpdateIdentifier("");
		deviceChoice1.setIdentifier("");
		jLabel4.setFont(new java.awt.Font("Dialog", 1, 11));
		jLabel4.setPreferredSize(new Dimension(100, 15));
		jLabel4.setHorizontalAlignment(SwingConstants.RIGHT);
		jLabel4.setText("Wave Mode :");
		deviceChoice2.setChoiceIntValues(null);
		deviceChoice2.setChoiceFloatValues(null);
		deviceChoice2.setOffsetNid(4);
		deviceChoice2.setLabelString("");
		deviceChoice2.setChoiceItems(new String[]
		{ "CYCLIC", "ACYCLIC" });
		deviceChoice2.setUpdateIdentifier("");
		deviceChoice2.setIdentifier("");
		jPanel5.setLayout(borderLayout2);
		clockpanel.setLayout(borderLayout3);
		clockROW2panel.setLayout(flowLayout4);
		flowLayout4.setAlignment(FlowLayout.LEFT);
		jLabel5.setFont(new java.awt.Font("Dialog", 1, 11));
		jLabel5.setPreferredSize(new Dimension(90, 15));
		jLabel5.setHorizontalAlignment(SwingConstants.RIGHT);
		jLabel5.setText("Source :");
		deviceField3.setOffsetNid(5);
		deviceField3.setNumCols(46);
		deviceField3.setIdentifier("");
		clockROW1panel.setLayout(flowLayout5);
		flowLayout5.setAlignment(FlowLayout.LEFT);
		flowLayout5.setHgap(5);
		flowLayout5.setVgap(5);
		jLabel6.setFont(new java.awt.Font("Dialog", 1, 11));
		jLabel6.setPreferredSize(new Dimension(90, 15));
		jLabel6.setHorizontalAlignment(SwingConstants.RIGHT);
		jLabel6.setText("Mode :");
		deviceChoice3.setChoiceIntValues(null);
		deviceChoice3.setChoiceFloatValues(null);
		deviceChoice3.setOffsetNid(6);
		deviceChoice3.setLabelString("");
		deviceChoice3.setChoiceItems(new String[]
		{ "INTERNAL", "EXTERNAL" });
		deviceChoice3.setUpdateIdentifier("");
		deviceChoice3.setIdentifier("");
		jLabel7.setFont(new java.awt.Font("Dialog", 1, 11));
		jLabel7.setPreferredSize(new Dimension(100, 15));
		jLabel7.setHorizontalAlignment(SwingConstants.RIGHT);
		jLabel7.setText("Frequency (Hz) :");
		deviceChoice4.setChoiceIntValues(null);
		deviceChoice4.setChoiceFloatValues(new float[]
		{ (float) 10000.0, (float) 5000.0, (float) 2500.0, (float) 1000.0, (float) 500.0, (float) 250.0, (float) 100.0,
				(float) 50.0 });
		deviceChoice4.setOffsetNid(7);
		deviceChoice4.setLabelString("");
		deviceChoice4.setChoiceItems(new String[]
		{ "10E3", "5E3", "2.5E3", "1E3", "500", "250", "100", "50" });
		deviceChoice4.setUpdateIdentifier("");
		deviceChoice4.setIdentifier("");
		generalROW3panel.setMinimumSize(new Dimension(404, 40));
		generalROW3panel.setPreferredSize(new Dimension(388, 40));
		clockROW1panel.setMinimumSize(new Dimension(313, 45));
		clockROW1panel.setPreferredSize(new Dimension(382, 40));
		clockpanel.setBorder(
				new TitledBorder(BorderFactory.createEtchedBorder(Color.white, new Color(142, 142, 142)), " CLOCK "));
		clockpanel.setMinimumSize(new Dimension(313, 90));
		clockpanel.setPreferredSize(new Dimension(684, 110));
		jPanel5.setMinimumSize(new Dimension(369, 270));
		generalpanel.setBorder(
				new TitledBorder(BorderFactory.createEtchedBorder(Color.white, new Color(142, 142, 142)), " GENERAL "));
		generalpanel.setPreferredSize(new Dimension(696, 150));
		jPanel10.setLayout(flowLayout6);
		jPanel11.setLayout(flowLayout7);
		jPanel12.setLayout(flowLayout8);
		jPanel13.setLayout(flowLayout9);
		flowLayout8.setAlignment(FlowLayout.LEFT);
		flowLayout8.setHgap(5);
		flowLayout8.setVgap(5);
		jPanel10.setPreferredSize(new Dimension(130, 45));
		jPanel13.setPreferredSize(new Dimension(120, 45));
		jPanel12.setPreferredSize(new Dimension(130, 45));
		jPanel11.setPreferredSize(new Dimension(120, 45));
		flowLayout7.setAlignment(FlowLayout.LEFT);
		flowLayout9.setAlignment(FlowLayout.LEFT);
		flowLayout9.setHgap(5);
		jPanel9.setLayout(gridLayout5);
		jPanel14.setBorder(new TitledBorder(BorderFactory.createEtchedBorder(Color.white, new Color(148, 145, 140)),
				" CHANNELS "));
		jPanel14.setLayout(gridLayout6);
		jScrollPane1.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
		jScrollPane1.setBorder(BorderFactory.createEmptyBorder());
		jScrollPane1.setPreferredSize(new Dimension(600, 219));
		jPanel16.setLayout(gridLayout2);
		jPanel16.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));
		jPanel16.setPreferredSize(new Dimension(600, 950));
		jLabel14.setText("CH 02 :");
		jLabel14.setFont(new java.awt.Font("Dialog", 1, 11));
		deviceField6.setOffsetNid(21);
		deviceField6.setNumCols(40);
		deviceField6.setIdentifier("");
		deviceChoice8.setIdentifier("");
		deviceChoice8.setUpdateIdentifier("");
		deviceChoice8.setChoiceItems(new String[]
		{ "BIPOLAR", "UNIPOLAR" });
		deviceChoice8.setLabelString("");
		deviceChoice8.setOffsetNid(17);
		deviceChoice8.setChoiceFloatValues(null);
		deviceChoice8.setChoiceIntValues(null);
		jLabel15.setText("Voltages :");
		jLabel15.setHorizontalAlignment(SwingConstants.RIGHT);
		jLabel15.setPreferredSize(new Dimension(80, 15));
		jLabel15.setFont(new java.awt.Font("Dialog", 1, 11));
		flowLayout17.setAlignment(FlowLayout.LEFT);
		flowLayout17.setHgap(5);
		flowLayout17.setVgap(5);
		flowLayout18.setAlignment(FlowLayout.LEFT);
		flowLayout18.setHgap(5);
		flowLayout18.setVgap(5);
		setupCH02panel.setPreferredSize(new Dimension(500, 40));
		setupCH02panel.setLayout(flowLayout17);
		jLabel16.setFont(new java.awt.Font("Dialog", 1, 11));
		jLabel16.setPreferredSize(new Dimension(80, 15));
		jLabel16.setHorizontalAlignment(SwingConstants.RIGHT);
		jLabel16.setText("Times :");
		gridLayout7.setRows(3);
		gridLayout7.setVgap(0);
		flowLayout19.setAlignment(FlowLayout.LEFT);
		flowLayout19.setHgap(5);
		flowLayout19.setVgap(5);
		flowLayout111.setAlignment(FlowLayout.LEFT);
		flowLayout111.setHgap(5);
		flowLayout111.setVgap(5);
		deviceChoice9.setChoiceIntValues(null);
		deviceChoice9.setChoiceFloatValues(null);
		deviceChoice9.setOffsetNid(18);
		deviceChoice9.setLabelString("");
		deviceChoice9.setChoiceItems(new String[]
		{ "AS IS", "VARIABLE" });
		deviceChoice9.setUpdateIdentifier("");
		deviceChoice9.setIdentifier("");
		jLabel17.setFont(new java.awt.Font("Dialog", 1, 11));
		jLabel17.setPreferredSize(new Dimension(80, 15));
		jLabel17.setVerifyInputWhenFocusTarget(true);
		jLabel17.setHorizontalAlignment(SwingConstants.RIGHT);
		jLabel17.setText("Range (Vpp) :");
		jLabel18.setFont(new java.awt.Font("Dialog", 1, 11));
		jLabel18.setText("Time Mode :");
		deviceChoice10.setChoiceIntValues(null);
		deviceChoice10.setChoiceFloatValues(new float[]
		{ (float) 20.0, (float) 10.0, (float) 5.0 });
		deviceChoice10.setOffsetNid(16);
		deviceChoice10.setLabelString("");
		deviceChoice10.setChoiceItems(new String[]
		{ "20", "10", "5" });
		deviceChoice10.setUpdateIdentifier("");
		deviceChoice10.setIdentifier("");
		deviceChannel2.setLayout(flowLayout19);
		deviceChannel2.setLabelString("");
		deviceChannel2.setOffsetNid(15);
		deviceChannel2.setBorderVisible(false);
		deviceChannel2.setInSameLine(true);
		deviceChannel2.setUpdateIdentifier("");
		deviceChannel2.setShowVal("");
		jPanel111.setLayout(gridLayout7);
		CH02panel.setLayout(flowLayout110);
		CH02panel.setBorder(BorderFactory.createLineBorder(Color.gray, 1));
		CH02panel.setPreferredSize(new Dimension(560, 150));
		timesCH02panel.setLayout(flowLayout18);
		voltagesCH02panel.setLayout(flowLayout111);
		jLabel19.setFont(new java.awt.Font("Dialog", 1, 11));
		jLabel19.setText("Polarity :");
		jPanel111.setPreferredSize(new Dimension(560, 120));
		flowLayout110.setAlignment(FlowLayout.LEFT);
		flowLayout110.setHgap(5);
		flowLayout110.setVgap(5);
		jPanel26.setLayout(flowLayout10);
		flowLayout10.setAlignment(FlowLayout.LEFT);
		flowLayout10.setHgap(5);
		flowLayout10.setVgap(5);
		jPanel29.setLayout(flowLayout11);
		flowLayout11.setAlignment(FlowLayout.LEFT);
		flowLayout11.setHgap(5);
		flowLayout11.setVgap(5);
		jPanel25.setLayout(flowLayout12);
		flowLayout12.setAlignment(FlowLayout.LEFT);
		flowLayout12.setHgap(5);
		flowLayout12.setVgap(5);
		deviceField4.setOffsetNid(20);
		deviceField4.setNumCols(40);
		deviceField4.setIdentifier("");
		gridLayout2.setHgap(0);
		gridLayout2.setRows(6);
		gridLayout2.setVgap(5);
		jPanel15.setLayout(flowLayout13);
		flowLayout13.setHgap(0);
		flowLayout13.setVgap(0);
		jPanel210.setLayout(flowLayout15);
		jPanel211.setLayout(flowLayout14);
		flowLayout112.setAlignment(FlowLayout.LEFT);
		flowLayout112.setHgap(5);
		flowLayout112.setVgap(5);
		setupCH03panel.setPreferredSize(new Dimension(500, 40));
		setupCH03panel.setLayout(flowLayout112);
		deviceField5.setOffsetNid(27);
		deviceField5.setNumCols(40);
		deviceField5.setIdentifier("");
		jLabel110.setText("CH 03 :");
		jLabel110.setFont(new java.awt.Font("Dialog", 1, 11));
		flowLayout113.setAlignment(FlowLayout.LEFT);
		flowLayout113.setHgap(5);
		flowLayout113.setVgap(5);
		deviceChoice11.setChoiceIntValues(null);
		deviceChoice11.setChoiceFloatValues(null);
		deviceChoice11.setOffsetNid(25);
		deviceChoice11.setLabelString("");
		deviceChoice11.setChoiceItems(new String[]
		{ "AS IS", "VARIABLE" });
		deviceChoice11.setUpdateIdentifier("");
		deviceChoice11.setIdentifier("");
		flowLayout14.setAlignment(FlowLayout.LEFT);
		flowLayout14.setHgap(5);
		flowLayout14.setVgap(5);
		deviceField7.setOffsetNid(28);
		deviceField7.setNumCols(40);
		deviceField7.setIdentifier("");
		timesCH03panel.setLayout(flowLayout113);
		gridLayout8.setRows(3);
		gridLayout8.setVgap(0);
		flowLayout114.setAlignment(FlowLayout.LEFT);
		flowLayout114.setHgap(5);
		flowLayout114.setVgap(5);
		jLabel111.setFont(new java.awt.Font("Dialog", 1, 11));
		jLabel111.setText("Polarity :");
		jLabel112.setFont(new java.awt.Font("Dialog", 1, 11));
		jLabel112.setPreferredSize(new Dimension(80, 15));
		jLabel112.setHorizontalAlignment(SwingConstants.RIGHT);
		jLabel112.setText("Times :");
		flowLayout15.setAlignment(FlowLayout.LEFT);
		flowLayout15.setHgap(5);
		flowLayout15.setVgap(5);
		deviceChoice12.setIdentifier("");
		deviceChoice12.setUpdateIdentifier("");
		deviceChoice12.setChoiceItems(new String[]
		{ "BIPOLAR", "UNIPOLAR" });
		deviceChoice12.setLabelString("");
		deviceChoice12.setOffsetNid(24);
		deviceChoice12.setChoiceFloatValues(null);
		deviceChoice12.setChoiceIntValues(null);
		jLabel113.setFont(new java.awt.Font("Dialog", 1, 11));
		jLabel113.setText("Time Mode :");
		deviceChoice13.setChoiceIntValues(null);
		deviceChoice13.setChoiceFloatValues(new float[]
		{ (float) 20.0, (float) 10.0, (float) 5.0 });
		deviceChoice13.setOffsetNid(23);
		deviceChoice13.setLabelString("");
		deviceChoice13.setChoiceItems(new String[]
		{ "20", "10", "5" });
		deviceChoice13.setUpdateIdentifier("");
		deviceChoice13.setIdentifier("");
		jLabel114.setFont(new java.awt.Font("Dialog", 1, 11));
		jLabel114.setPreferredSize(new Dimension(80, 15));
		jLabel114.setVerifyInputWhenFocusTarget(true);
		jLabel114.setHorizontalAlignment(SwingConstants.RIGHT);
		jLabel114.setText("Range (Vpp) :");
		jPanel114.setLayout(gridLayout8);
		jPanel114.setPreferredSize(new Dimension(560, 120));
		flowLayout16.setAlignment(FlowLayout.LEFT);
		flowLayout16.setHgap(5);
		flowLayout16.setVgap(5);
		voltagesCH03panel.setLayout(flowLayout114);
		deviceChannel3.setLayout(flowLayout116);
		deviceChannel3.setLabelString("");
		deviceChannel3.setOffsetNid(22);
		deviceChannel3.setBorderVisible(false);
		deviceChannel3.setInSameLine(true);
		deviceChannel3.setUpdateIdentifier("");
		deviceChannel3.setShowVal("");
		jPanel214.setLayout(flowLayout16);
		flowLayout115.setAlignment(FlowLayout.LEFT);
		flowLayout115.setHgap(5);
		flowLayout115.setVgap(5);
		CH03panel.setLayout(flowLayout115);
		CH03panel.setBorder(BorderFactory.createLineBorder(Color.gray, 1));
		CH03panel.setPreferredSize(new Dimension(560, 150));
		flowLayout116.setAlignment(FlowLayout.LEFT);
		flowLayout116.setHgap(5);
		flowLayout116.setVgap(5);
		jLabel115.setText("Voltages :");
		jLabel115.setHorizontalAlignment(SwingConstants.RIGHT);
		jLabel115.setPreferredSize(new Dimension(80, 15));
		jLabel115.setFont(new java.awt.Font("Dialog", 1, 11));
		deviceField8.setIdentifier("");
		deviceField8.setNumCols(40);
		deviceField8.setOffsetNid(34);
		flowLayout117.setVgap(5);
		flowLayout117.setHgap(5);
		flowLayout117.setAlignment(FlowLayout.LEFT);
		jPanel215.setLayout(flowLayout117);
		flowLayout118.setAlignment(FlowLayout.LEFT);
		flowLayout118.setHgap(5);
		flowLayout118.setVgap(5);
		CH04panel.setLayout(flowLayout119);
		CH04panel.setBorder(BorderFactory.createLineBorder(Color.gray, 1));
		CH04panel.setPreferredSize(new Dimension(560, 150));
		flowLayout119.setAlignment(FlowLayout.LEFT);
		flowLayout119.setHgap(5);
		flowLayout119.setVgap(5);
		jLabel116.setText("Voltages :");
		jLabel116.setHorizontalAlignment(SwingConstants.RIGHT);
		jLabel116.setPreferredSize(new Dimension(80, 15));
		jLabel116.setFont(new java.awt.Font("Dialog", 1, 11));
		deviceChoice14.setChoiceIntValues(null);
		deviceChoice14.setChoiceFloatValues(new float[]
		{ (float) 20.0, (float) 10.0, (float) 5.0 });
		deviceChoice14.setOffsetNid(30);
		deviceChoice14.setLabelString("");
		deviceChoice14.setChoiceItems(new String[]
		{ "20", "10", "5" });
		deviceChoice14.setUpdateIdentifier("");
		deviceChoice14.setIdentifier("");
		flowLayout1110.setAlignment(FlowLayout.LEFT);
		flowLayout1110.setHgap(5);
		flowLayout1110.setVgap(5);
		deviceField9.setOffsetNid(35);
		deviceField9.setNumCols(40);
		deviceField9.setIdentifier("");
		flowLayout120.setAlignment(FlowLayout.LEFT);
		flowLayout120.setHgap(5);
		flowLayout120.setVgap(5);
		flowLayout1111.setAlignment(FlowLayout.LEFT);
		flowLayout1111.setHgap(5);
		flowLayout1111.setVgap(5);
		jLabel117.setFont(new java.awt.Font("Dialog", 1, 11));
		jLabel117.setPreferredSize(new Dimension(80, 15));
		jLabel117.setVerifyInputWhenFocusTarget(true);
		jLabel117.setHorizontalAlignment(SwingConstants.RIGHT);
		jLabel117.setText("Range (Vpp) :");
		deviceChoice15.setIdentifier("");
		deviceChoice15.setUpdateIdentifier("");
		deviceChoice15.setChoiceItems(new String[]
		{ "BIPOLAR", "UNIPOLAR" });
		deviceChoice15.setLabelString("");
		deviceChoice15.setOffsetNid(31);
		deviceChoice15.setChoiceFloatValues(null);
		deviceChoice15.setChoiceIntValues(null);
		jPanel216.setLayout(flowLayout120);
		deviceChannel4.setLayout(flowLayout1110);
		deviceChannel4.setLabelString("");
		deviceChannel4.setOffsetNid(29);
		deviceChannel4.setBorderVisible(false);
		deviceChannel4.setInSameLine(true);
		deviceChannel4.setUpdateIdentifier("");
		deviceChannel4.setShowVal("");
		timesCH04panel.setLayout(flowLayout1113);
		jLabel118.setFont(new java.awt.Font("Dialog", 1, 11));
		jLabel118.setText("Time Mode :");
		jLabel119.setFont(new java.awt.Font("Dialog", 1, 11));
		jLabel119.setText("Polarity :");
		gridLayout9.setRows(3);
		gridLayout9.setVgap(0);
		flowLayout1112.setAlignment(FlowLayout.LEFT);
		flowLayout1112.setHgap(5);
		flowLayout1112.setVgap(5);
		jLabel1110.setFont(new java.awt.Font("Dialog", 1, 11));
		jLabel1110.setPreferredSize(new Dimension(80, 15));
		jLabel1110.setHorizontalAlignment(SwingConstants.RIGHT);
		jLabel1110.setText("Times :");
		jPanel117.setLayout(gridLayout9);
		jPanel117.setPreferredSize(new Dimension(560, 120));
		flowLayout1113.setAlignment(FlowLayout.LEFT);
		flowLayout1113.setHgap(5);
		flowLayout1113.setVgap(5);
		deviceChoice16.setChoiceIntValues(null);
		deviceChoice16.setChoiceFloatValues(null);
		deviceChoice16.setOffsetNid(32);
		deviceChoice16.setLabelString("");
		deviceChoice16.setChoiceItems(new String[]
		{ "AS IS", "VARIABLE" });
		deviceChoice16.setUpdateIdentifier("");
		deviceChoice16.setIdentifier("");
		setupCH04panel.setPreferredSize(new Dimension(500, 40));
		setupCH04panel.setLayout(flowLayout1112);
		jPanel218.setLayout(flowLayout118);
		jLabel1111.setText("CH 04 :");
		jLabel1111.setFont(new java.awt.Font("Dialog", 1, 11));
		voltagesCH04panel.setLayout(flowLayout1111);
		deviceChoice17.setChoiceIntValues(null);
		deviceChoice17.setChoiceFloatValues(null);
		deviceChoice17.setOffsetNid(10);
		deviceChoice17.setLabelString("");
		deviceChoice17.setChoiceItems(new String[]
		{ "BIPOLAR", "UNIPOLAR" });
		deviceChoice17.setUpdateIdentifier("");
		deviceChoice17.setIdentifier("");
		flowLayout121.setVgap(5);
		flowLayout121.setHgap(5);
		flowLayout121.setAlignment(FlowLayout.LEFT);
		jLabel1112.setFont(new java.awt.Font("Dialog", 1, 11));
		jLabel1112.setPreferredSize(new Dimension(80, 15));
		jLabel1112.setHorizontalAlignment(SwingConstants.RIGHT);
		jLabel1112.setText("Voltages :");
		deviceChoice18.setIdentifier("");
		deviceChoice18.setUpdateIdentifier("");
		deviceChoice18.setChoiceItems(new String[]
		{ "20", "10", "5" });
		deviceChoice18.setLabelString("");
		deviceChoice18.setOffsetNid(9);
		deviceChoice18.setChoiceFloatValues(new float[]
		{ (float) 20.0, (float) 10.0, (float) 5.0 });
		deviceChoice18.setChoiceIntValues(null);
		deviceChannel5.setShowVal("");
		deviceChannel5.setUpdateIdentifier("");
		deviceChannel5.setInSameLine(true);
		deviceChannel5.setBorderVisible(false);
		deviceChannel5.setOffsetNid(8);
		deviceChannel5.setLabelString("");
		deviceChannel5.setLayout(flowLayout1115);
		voltagesCH01panel.setLayout(flowLayout1114);
		flowLayout1114.setAlignment(FlowLayout.LEFT);
		flowLayout1114.setHgap(5);
		flowLayout1114.setVgap(5);
		jLabel1113.setFont(new java.awt.Font("Dialog", 1, 11));
		jLabel1113.setPreferredSize(new Dimension(80, 15));
		jLabel1113.setHorizontalAlignment(SwingConstants.RIGHT);
		jLabel1113.setText("Times :");
		flowLayout1115.setAlignment(FlowLayout.LEFT);
		flowLayout1115.setHgap(5);
		flowLayout1115.setVgap(5);
		setupCH01panel.setPreferredSize(new Dimension(500, 40));
		setupCH01panel.setLayout(flowLayout11110);
		jPanel2111.setLayout(flowLayout121);
		jPanel2112.setLayout(flowLayout1118);
		flowLayout1116.setAlignment(FlowLayout.LEFT);
		flowLayout1116.setHgap(5);
		flowLayout1116.setVgap(5);
		deviceField10.setIdentifier("");
		deviceField10.setNumCols(40);
		deviceField10.setOffsetNid(13);
		flowLayout1117.setVgap(5);
		flowLayout1117.setHgap(5);
		flowLayout1117.setAlignment(FlowLayout.LEFT);
		jPanel1110.setLayout(gridLayout10);
		jPanel1110.setPreferredSize(new Dimension(560, 120));
		timesCH01panel.setLayout(flowLayout1116);
		jLabel1114.setFont(new java.awt.Font("Dialog", 1, 11));
		jLabel1114.setPreferredSize(new Dimension(80, 15));
		jLabel1114.setVerifyInputWhenFocusTarget(true);
		jLabel1114.setHorizontalAlignment(SwingConstants.RIGHT);
		jLabel1114.setText("Range (Vpp) :");
		CH01panel.setLayout(flowLayout1119);
		CH01panel.setBorder(BorderFactory.createLineBorder(Color.gray, 1));
		CH01panel.setPreferredSize(new Dimension(560, 150));
		gridLayout10.setRows(3);
		gridLayout10.setVgap(0);
		jLabel1115.setText("CH 01 :");
		jLabel1115.setFont(new java.awt.Font("Dialog", 1, 11));
		deviceField11.setOffsetNid(14);
		deviceField11.setNumCols(40);
		deviceField11.setIdentifier("");
		jLabel1116.setFont(new java.awt.Font("Dialog", 1, 11));
		jLabel1116.setText("Polarity :");
		jPanel2114.setLayout(flowLayout1117);
		jLabel1117.setFont(new java.awt.Font("Dialog", 1, 11));
		jLabel1117.setText("Time Mode :");
		deviceChoice19.setChoiceIntValues(null);
		deviceChoice19.setChoiceFloatValues(null);
		deviceChoice19.setOffsetNid(11);
		deviceChoice19.setLabelString("");
		deviceChoice19.setChoiceItems(new String[]
		{ "AS IS", "VARIABLE" });
		deviceChoice19.setUpdateIdentifier("");
		deviceChoice19.setIdentifier("");
		flowLayout1118.setAlignment(FlowLayout.LEFT);
		flowLayout1118.setHgap(5);
		flowLayout1118.setVgap(5);
		flowLayout1119.setAlignment(FlowLayout.LEFT);
		flowLayout1119.setHgap(5);
		flowLayout1119.setVgap(5);
		flowLayout11110.setAlignment(FlowLayout.LEFT);
		flowLayout11110.setHgap(5);
		flowLayout11110.setVgap(5);
		flowLayout11111.setVgap(5);
		flowLayout11111.setHgap(5);
		flowLayout11111.setAlignment(FlowLayout.LEFT);
		jLabel1118.setText("Voltages :");
		jLabel1118.setHorizontalAlignment(SwingConstants.RIGHT);
		jLabel1118.setPreferredSize(new Dimension(80, 15));
		jLabel1118.setFont(new java.awt.Font("Dialog", 1, 11));
		voltagesCH05panel.setLayout(flowLayout11116);
		flowLayout11112.setAlignment(FlowLayout.LEFT);
		flowLayout11112.setHgap(5);
		flowLayout11112.setVgap(5);
		deviceChannel6.setShowVal("");
		deviceChannel6.setUpdateIdentifier("");
		deviceChannel6.setInSameLine(true);
		deviceChannel6.setBorderVisible(false);
		deviceChannel6.setOffsetNid(36);
		deviceChannel6.setLabelString("");
		deviceChannel6.setLayout(flowLayout11114);
		jLabel1119.setText("CH 05 :");
		jLabel1119.setFont(new java.awt.Font("Dialog", 1, 11));
		flowLayout11113.setAlignment(FlowLayout.LEFT);
		flowLayout11113.setHgap(5);
		flowLayout11113.setVgap(5);
		jLabel11110.setFont(new java.awt.Font("Dialog", 1, 11));
		jLabel11110.setPreferredSize(new Dimension(80, 15));
		jLabel11110.setVerifyInputWhenFocusTarget(true);
		jLabel11110.setHorizontalAlignment(SwingConstants.RIGHT);
		jLabel11110.setText("Range (Vpp) :");
		deviceChoice110.setChoiceIntValues(null);
		deviceChoice110.setChoiceFloatValues(null);
		deviceChoice110.setOffsetNid(38);
		deviceChoice110.setLabelString("");
		deviceChoice110.setChoiceItems(new String[]
		{ "BIPOLAR", "UNIPOLAR" });
		deviceChoice110.setUpdateIdentifier("");
		deviceChoice110.setIdentifier("");
		jLabel11111.setFont(new java.awt.Font("Dialog", 1, 11));
		jLabel11111.setPreferredSize(new Dimension(80, 15));
		jLabel11111.setHorizontalAlignment(SwingConstants.RIGHT);
		jLabel11111.setText("Times :");
		flowLayout122.setVgap(5);
		flowLayout122.setHgap(5);
		flowLayout122.setAlignment(FlowLayout.RIGHT);
		CH05panel.setLayout(flowLayout11117);
		CH05panel.setBorder(BorderFactory.createLineBorder(Color.gray, 1));
		CH05panel.setPreferredSize(new Dimension(560, 150));
		flowLayout11114.setAlignment(FlowLayout.LEFT);
		flowLayout11114.setHgap(5);
		flowLayout11114.setVgap(5);
		deviceField12.setIdentifier("");
		deviceField12.setNumCols(40);
		deviceField12.setOffsetNid(41);
		setupCH05panel.setPreferredSize(new Dimension(500, 40));
		setupCH05panel.setLayout(flowLayout11112);
		deviceField13.setOffsetNid(42);
		deviceField13.setNumCols(40);
		deviceField13.setIdentifier("");
		deviceChoice111.setChoiceIntValues(null);
		deviceChoice111.setChoiceFloatValues(null);
		deviceChoice111.setOffsetNid(39);
		deviceChoice111.setLabelString("");
		deviceChoice111.setChoiceItems(new String[]
		{ "AS IS", "VARIABLE" });
		deviceChoice111.setUpdateIdentifier("");
		deviceChoice111.setIdentifier("");
		gridLayout11.setRows(3);
		gridLayout11.setVgap(0);
		jLabel11112.setFont(new java.awt.Font("Dialog", 1, 11));
		jLabel11112.setText("Polarity :");
		flowLayout11115.setVgap(5);
		flowLayout11115.setHgap(5);
		flowLayout11115.setAlignment(FlowLayout.LEFT);
		jPanel1114.setLayout(gridLayout11);
		jPanel1114.setPreferredSize(new Dimension(560, 120));
		flowLayout11116.setAlignment(FlowLayout.LEFT);
		flowLayout11116.setHgap(5);
		flowLayout11116.setVgap(5);
		deviceChoice112.setIdentifier("");
		deviceChoice112.setUpdateIdentifier("");
		deviceChoice112.setChoiceItems(new String[]
		{ "20", "10", "5" });
		deviceChoice112.setLabelString("");
		deviceChoice112.setOffsetNid(37);
		deviceChoice112.setChoiceFloatValues(new float[]
		{ (float) 20.0, (float) 10.0, (float) 5.0 });
		deviceChoice112.setChoiceIntValues(null);
		jPanel2116.setLayout(flowLayout122);
		timesCH05panel.setLayout(flowLayout11113);
		jLabel11113.setFont(new java.awt.Font("Dialog", 1, 11));
		jLabel11113.setText("Time Mode :");
		jPanel2118.setLayout(flowLayout11115);
		jPanel2119.setLayout(flowLayout11111);
		flowLayout11117.setAlignment(FlowLayout.LEFT);
		flowLayout11117.setHgap(5);
		flowLayout11117.setVgap(5);
		flowLayout123.setAlignment(FlowLayout.RIGHT);
		flowLayout123.setHgap(5);
		flowLayout123.setVgap(5);
		voltagesCH06panel.setLayout(flowLayout111110);
		deviceChoice113.setChoiceIntValues(null);
		deviceChoice113.setChoiceFloatValues(null);
		deviceChoice113.setOffsetNid(46);
		deviceChoice113.setLabelString("");
		deviceChoice113.setChoiceItems(new String[]
		{ "AS IS", "VARIABLE" });
		deviceChoice113.setUpdateIdentifier("");
		deviceChoice113.setIdentifier("");
		setupCH06panel.setPreferredSize(new Dimension(500, 40));
		setupCH06panel.setLayout(flowLayout111111);
		flowLayout11118.setAlignment(FlowLayout.LEFT);
		flowLayout11118.setHgap(5);
		flowLayout11118.setVgap(5);
		deviceField14.setOffsetNid(49);
		deviceField14.setNumCols(40);
		deviceField14.setIdentifier("");
		timesCH06panel.setLayout(flowLayout111112);
		flowLayout11119.setVgap(5);
		flowLayout11119.setHgap(5);
		flowLayout11119.setAlignment(FlowLayout.LEFT);
		deviceChoice114.setChoiceIntValues(null);
		deviceChoice114.setChoiceFloatValues(null);
		deviceChoice114.setOffsetNid(45);
		deviceChoice114.setLabelString("");
		deviceChoice114.setChoiceItems(new String[]
		{ "BIPOLAR", "UNIPOLAR" });
		deviceChoice114.setUpdateIdentifier("");
		deviceChoice114.setIdentifier("");
		jLabel11114.setText("CH 06 :");
		jLabel11114.setFont(new java.awt.Font("Dialog", 1, 11));
		jPanel21112.setLayout(flowLayout111114);
		jLabel11115.setFont(new java.awt.Font("Dialog", 1, 11));
		jLabel11115.setText("Time Mode :");
		deviceChoice115.setIdentifier("");
		deviceChoice115.setUpdateIdentifier("");
		deviceChoice115.setChoiceItems(new String[]
		{ "20", "10", "5" });
		deviceChoice115.setLabelString("");
		deviceChoice115.setOffsetNid(44);
		deviceChoice115.setChoiceFloatValues(new float[]
		{ (float) 20.0, (float) 10.0, (float) 5.0 });
		deviceChoice115.setChoiceIntValues(null);
		flowLayout111110.setAlignment(FlowLayout.LEFT);
		flowLayout111110.setHgap(5);
		flowLayout111110.setVgap(5);
		jPanel21113.setLayout(flowLayout11119);
		deviceChannel7.setShowVal("");
		deviceChannel7.setUpdateIdentifier("");
		deviceChannel7.setInSameLine(true);
		deviceChannel7.setBorderVisible(false);
		deviceChannel7.setOffsetNid(43);
		deviceChannel7.setLabelString("");
		deviceChannel7.setLayout(flowLayout111113);
		jLabel11116.setFont(new java.awt.Font("Dialog", 1, 11));
		jLabel11116.setPreferredSize(new Dimension(80, 15));
		jLabel11116.setVerifyInputWhenFocusTarget(true);
		jLabel11116.setHorizontalAlignment(SwingConstants.RIGHT);
		jLabel11116.setText("Range (Vpp) :");
		CH06panel.setLayout(flowLayout11118);
		CH06panel.setBorder(BorderFactory.createLineBorder(Color.gray, 1));
		CH06panel.setPreferredSize(new Dimension(560, 150));
		jLabel11117.setFont(new java.awt.Font("Dialog", 1, 11));
		jLabel11117.setPreferredSize(new Dimension(80, 15));
		jLabel11117.setHorizontalAlignment(SwingConstants.RIGHT);
		jLabel11117.setText("Times :");
		flowLayout111111.setAlignment(FlowLayout.LEFT);
		flowLayout111111.setHgap(5);
		flowLayout111111.setVgap(5);
		deviceField15.setIdentifier("");
		deviceField15.setNumCols(40);
		deviceField15.setOffsetNid(48);
		jPanel21114.setLayout(flowLayout123);
		flowLayout111112.setAlignment(FlowLayout.LEFT);
		flowLayout111112.setHgap(5);
		flowLayout111112.setVgap(5);
		gridLayout12.setRows(3);
		gridLayout12.setVgap(0);
		jLabel11118.setText("Voltages :");
		jLabel11118.setHorizontalAlignment(SwingConstants.RIGHT);
		jLabel11118.setPreferredSize(new Dimension(80, 15));
		jLabel11118.setFont(new java.awt.Font("Dialog", 1, 11));
		jPanel1117.setLayout(gridLayout12);
		jPanel1117.setPreferredSize(new Dimension(560, 120));
		flowLayout111113.setAlignment(FlowLayout.LEFT);
		flowLayout111113.setHgap(5);
		flowLayout111113.setVgap(5);
		jLabel11119.setFont(new java.awt.Font("Dialog", 1, 11));
		jLabel11119.setText("Polarity :");
		flowLayout111114.setVgap(5);
		flowLayout111114.setHgap(5);
		flowLayout111114.setAlignment(FlowLayout.LEFT);
		deviceButtons1.setCheckExpressions(null);
		deviceButtons1.setCheckMessages(null);
		deviceButtons1.setMethods(new String[]
		{ "INIT", "RESET" });
		flowLayout6.setAlignment(FlowLayout.LEFT);
		flowLayout6.setHgap(5);
		flowLayout6.setVgap(5);
		jPanel21114.setMinimumSize(new Dimension(72, 45));
		jPanel21114.setPreferredSize(new Dimension(67, 45));
		jPanel2116.setPreferredSize(new Dimension(67, 45));
		jPanel17.setLayout(flowLayout20);
		jPanel17.setPreferredSize(new Dimension(-11, 10));
		jPanel18.setPreferredSize(new Dimension(-11, 10));
		deviceDispatch1.setLayout(flowLayout21);
		deviceDispatch1.setFont(new java.awt.Font("Dialog", 1, 11));
		jPanel19.setPreferredSize(new Dimension(-11, 10));
		jPanel19.setLayout(flowLayout27);
		jPanel20.setPreferredSize(new Dimension(-11, 10));
		jPanel20.setLayout(flowLayout26);
		jPanel21.setPreferredSize(new Dimension(-11, 10));
		jPanel21.setLayout(flowLayout25);
		jPanel22.setPreferredSize(new Dimension(-11, 10));
		jPanel22.setLayout(flowLayout24);
		jPanel23.setPreferredSize(new Dimension(-11, 10));
		jPanel23.setLayout(flowLayout23);
		jPanel24.setPreferredSize(new Dimension(-11, 10));
		jPanel24.setLayout(flowLayout22);
		generalROW1panel.setMinimumSize(new Dimension(265, 40));
		generalROW1panel.setPreferredSize(new Dimension(493, 40));
		jPanel27.setLayout(gridLayout4);
		gridLayout4.setRows(3);
		jScrollPane2.setBorder(BorderFactory.createEmptyBorder());
		jScrollPane2.setPreferredSize(new Dimension(640, 150));
		jPanel1.setLayout(gridLayout13);
		gridLayout13.setRows(2);
		jScrollPane3.setBorder(BorderFactory.createEmptyBorder());
		generalROW1panel.add(jLabel1, null);
		generalROW1panel.add(deviceField1, null);
		generalROW1panel.add(deviceDispatch1, null);
		generalpanel.add(jScrollPane2, BorderLayout.CENTER);
		jPanel5.add(clockpanel, BorderLayout.CENTER);
		clockpanel.add(jScrollPane3, BorderLayout.CENTER);
		jScrollPane3.getViewport().add(jPanel1, null);
		jScrollPane2.getViewport().add(jPanel27, null);
		generalROW3panel.add(jLabel3, null);
		generalROW3panel.add(jPanel10, null);
		jPanel10.add(jPanel17, null);
		jPanel10.add(deviceChoice1, null);
		generalROW3panel.add(jLabel4, null);
		generalROW3panel.add(jPanel11, null);
		jPanel11.add(deviceChoice2, null);
		this.getContentPane().add(jPanel9, BorderLayout.CENTER);
		jPanel9.add(jPanel14, null);
		jPanel14.add(jScrollPane1, null);
		this.getContentPane().add(jPanel15, BorderLayout.SOUTH);
		jPanel15.add(deviceButtons1, null);
		this.getContentPane().add(jPanel5, BorderLayout.NORTH);
		jScrollPane1.getViewport().add(jPanel16, null);
		CH02panel.add(jLabel14, null);
		CH02panel.add(deviceChannel2, null);
		deviceChannel2.add(jPanel111, null);
		voltagesCH02panel.add(jLabel15, null);
		voltagesCH02panel.add(deviceField4, null);
		setupCH02panel.add(jLabel17, null);
		setupCH02panel.add(jPanel20, null);
		setupCH02panel.add(jPanel26, null);
		jPanel26.add(deviceChoice10, null);
		setupCH02panel.add(jLabel19, null);
		setupCH02panel.add(jPanel29, null);
		jPanel29.add(deviceChoice8, null);
		setupCH02panel.add(jLabel18, null);
		setupCH02panel.add(jPanel25, null);
		jPanel25.add(deviceChoice9, null);
		timesCH02panel.add(jLabel16, null);
		timesCH02panel.add(deviceField6, null);
		CH03panel.add(jLabel110, null);
		CH03panel.add(deviceChannel3, null);
		deviceChannel3.add(jPanel114, null);
		setupCH03panel.add(jLabel114, null);
		setupCH03panel.add(jPanel21, null);
		setupCH03panel.add(jPanel210, null);
		jPanel210.add(deviceChoice13, null);
		setupCH03panel.add(jLabel111, null);
		setupCH03panel.add(jPanel214, null);
		jPanel214.add(deviceChoice12, null);
		setupCH03panel.add(jLabel113, null);
		setupCH03panel.add(jPanel211, null);
		jPanel211.add(deviceChoice11, null);
		voltagesCH03panel.add(jLabel115, null);
		voltagesCH03panel.add(deviceField5, null);
		timesCH03panel.add(jLabel112, null);
		timesCH03panel.add(deviceField7, null);
		CH04panel.add(jLabel1111, null);
		CH04panel.add(deviceChannel4, null);
		deviceChannel4.add(jPanel117, null);
		voltagesCH04panel.add(jLabel116, null);
		voltagesCH04panel.add(deviceField8, null);
		setupCH04panel.add(jLabel117, null);
		setupCH04panel.add(jPanel22, null);
		setupCH04panel.add(jPanel216, null);
		jPanel216.add(deviceChoice14, null);
		setupCH04panel.add(jLabel119, null);
		setupCH04panel.add(jPanel218, null);
		jPanel218.add(deviceChoice15, null);
		setupCH04panel.add(jLabel118, null);
		setupCH04panel.add(jPanel215, null);
		jPanel215.add(deviceChoice16, null);
		timesCH04panel.add(jLabel1110, null);
		timesCH04panel.add(deviceField9, null);
		CH01panel.add(jLabel1115, null);
		CH01panel.add(deviceChannel5, null);
		deviceChannel5.add(jPanel1110, null);
		setupCH01panel.add(jLabel1114, null);
		setupCH01panel.add(jPanel19, null);
		setupCH01panel.add(jPanel2111, null);
		jPanel2111.add(deviceChoice18, null);
		setupCH01panel.add(jLabel1116, null);
		setupCH01panel.add(jPanel2112, null);
		jPanel2112.add(deviceChoice17, null);
		setupCH01panel.add(jLabel1117, null);
		setupCH01panel.add(jPanel2114, null);
		jPanel2114.add(deviceChoice19, null);
		voltagesCH01panel.add(jLabel1112, null);
		voltagesCH01panel.add(deviceField10, null);
		timesCH01panel.add(jLabel1113, null);
		timesCH01panel.add(deviceField11, null);
		CH05panel.add(jLabel1119, null);
		CH05panel.add(deviceChannel6, null);
		deviceChannel6.add(jPanel1114, null);
		voltagesCH05panel.add(jLabel1118, null);
		voltagesCH05panel.add(deviceField12, null);
		setupCH05panel.add(jLabel11110, null);
		setupCH05panel.add(jPanel23, null);
		setupCH05panel.add(jPanel2116, null);
		jPanel2116.add(deviceChoice112, null);
		setupCH05panel.add(jLabel11112, null);
		setupCH05panel.add(jPanel2119, null);
		jPanel2119.add(deviceChoice110, null);
		setupCH05panel.add(jLabel11113, null);
		setupCH05panel.add(jPanel2118, null);
		jPanel2118.add(deviceChoice111, null);
		timesCH05panel.add(jLabel11111, null);
		timesCH05panel.add(deviceField13, null);
		CH06panel.add(jLabel11114, null);
		CH06panel.add(deviceChannel7, null);
		deviceChannel7.add(jPanel1117, null);
		setupCH06panel.add(jLabel11116, null);
		setupCH06panel.add(jPanel24, null);
		setupCH06panel.add(jPanel21114, null);
		jPanel21114.add(deviceChoice115, null);
		setupCH06panel.add(jLabel11119, null);
		setupCH06panel.add(jPanel21112, null);
		jPanel21112.add(deviceChoice114, null);
		setupCH06panel.add(jLabel11115, null);
		setupCH06panel.add(jPanel21113, null);
		jPanel21113.add(deviceChoice113, null);
		voltagesCH06panel.add(jLabel11118, null);
		voltagesCH06panel.add(deviceField15, null);
		timesCH06panel.add(jLabel11117, null);
		timesCH06panel.add(deviceField14, null);
		clockROW2panel.add(jLabel5, null);
		clockROW2panel.add(deviceField3, null);
		clockROW1panel.add(jLabel6, null);
		clockROW1panel.add(jPanel12, null);
		jPanel12.add(jPanel18, null);
		jPanel12.add(deviceChoice3, null);
		clockROW1panel.add(jLabel7, null);
		clockROW1panel.add(jPanel13, null);
		jPanel13.add(deviceChoice4, null);
		jPanel5.add(generalpanel, BorderLayout.NORTH);
		generalROW2panel.add(jLabel2, null);
		generalROW2panel.add(deviceField2, null);
		jPanel27.add(generalROW1panel, null);
		jPanel27.add(generalROW2panel, null);
		jPanel27.add(generalROW3panel, null);
		jPanel1.add(clockROW1panel, null);
		jPanel1.add(clockROW2panel, null);
		jPanel1110.add(setupCH01panel, null);
		jPanel1110.add(voltagesCH01panel, null);
		jPanel1110.add(timesCH01panel, null);
		jPanel111.add(setupCH02panel, null);
		jPanel111.add(voltagesCH02panel, null);
		jPanel111.add(timesCH02panel, null);
		jPanel114.add(setupCH03panel, null);
		jPanel114.add(voltagesCH03panel, null);
		jPanel114.add(timesCH03panel, null);
		jPanel117.add(setupCH04panel, null);
		jPanel117.add(voltagesCH04panel, null);
		jPanel117.add(timesCH04panel, null);
		jPanel1114.add(setupCH05panel, null);
		jPanel1114.add(voltagesCH05panel, null);
		jPanel1114.add(timesCH05panel, null);
		jPanel1117.add(setupCH06panel, null);
		jPanel1117.add(voltagesCH06panel, null);
		jPanel1117.add(timesCH06panel, null);
		jPanel16.add(CH01panel, null);
		jPanel16.add(CH02panel, null);
		jPanel16.add(CH03panel, null);
		jPanel16.add(CH04panel, null);
		jPanel16.add(CH05panel, null);
		jPanel16.add(CH06panel, null);
	}
}
