/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mdsplus
 */
public class MARTE2_EPICS_INSetup extends DeviceSetup {

    /**
     * Creates new form MARTE2_EPICS_INSetup
     */
    public MARTE2_EPICS_INSetup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deviceButtons1 = new DeviceButtons();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        deviceOutputs1 = new DeviceOutputs();
        deviceParameters1 = new DeviceParameters();

        setDeviceProvider("localhost:8100");
        setDeviceTitle("EPICS In");
        setDeviceType("MARTE2_EPICS_IN");
        setHeight(500);
        setWidth(900);
        getContentPane().add(deviceButtons1, java.awt.BorderLayout.PAGE_END);

        deviceOutputs1.setOffsetNid(11);
        jTabbedPane1.addTab("Outputs", deviceOutputs1);
        jTabbedPane1.addTab("Parameters", deviceParameters1);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private DeviceButtons deviceButtons1;
    private DeviceOutputs deviceOutputs1;
    private DeviceParameters deviceParameters1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
