/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mdsplus
 */
public class MARTE2_NI6368_ADCSetup extends DeviceSetup {

    /**
     * Creates new form MARTE2_NI6368_ADCSetup
     */
    public MARTE2_NI6368_ADCSetup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deviceButtons1 = new DeviceButtons();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        deviceField1 = new DeviceField();
        deviceField2 = new DeviceField();
        deviceField3 = new DeviceField();
        jPanel4 = new javax.swing.JPanel();
        deviceChoice1 = new DeviceChoice();
        deviceField4 = new DeviceField();
        deviceField5 = new DeviceField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        deviceChoice2 = new DeviceChoice();
        deviceChoice3 = new DeviceChoice();
        jPanel7 = new javax.swing.JPanel();
        deviceChoice4 = new DeviceChoice();
        deviceChoice5 = new DeviceChoice();
        jPanel8 = new javax.swing.JPanel();
        deviceChoice6 = new DeviceChoice();
        deviceChoice7 = new DeviceChoice();
        jPanel9 = new javax.swing.JPanel();
        deviceChoice8 = new DeviceChoice();
        deviceChoice9 = new DeviceChoice();
        jPanel10 = new javax.swing.JPanel();
        deviceChoice10 = new DeviceChoice();
        deviceChoice11 = new DeviceChoice();
        jPanel11 = new javax.swing.JPanel();
        deviceChoice12 = new DeviceChoice();
        deviceChoice13 = new DeviceChoice();
        jPanel12 = new javax.swing.JPanel();
        deviceChoice14 = new DeviceChoice();
        deviceChoice15 = new DeviceChoice();
        jPanel13 = new javax.swing.JPanel();
        deviceChoice16 = new DeviceChoice();
        deviceChoice17 = new DeviceChoice();
        jPanel14 = new javax.swing.JPanel();
        deviceChoice18 = new DeviceChoice();
        deviceChoice19 = new DeviceChoice();
        jPanel15 = new javax.swing.JPanel();
        deviceChoice20 = new DeviceChoice();
        deviceChoice21 = new DeviceChoice();
        jPanel16 = new javax.swing.JPanel();
        deviceChoice22 = new DeviceChoice();
        deviceChoice23 = new DeviceChoice();
        jPanel17 = new javax.swing.JPanel();
        deviceChoice24 = new DeviceChoice();
        deviceChoice25 = new DeviceChoice();
        jPanel18 = new javax.swing.JPanel();
        deviceChoice26 = new DeviceChoice();
        deviceChoice27 = new DeviceChoice();
        jPanel19 = new javax.swing.JPanel();
        deviceChoice28 = new DeviceChoice();
        deviceChoice29 = new DeviceChoice();
        jPanel20 = new javax.swing.JPanel();
        deviceChoice30 = new DeviceChoice();
        deviceChoice31 = new DeviceChoice();
        jPanel21 = new javax.swing.JPanel();
        deviceChoice32 = new DeviceChoice();
        deviceChoice33 = new DeviceChoice();

        setDeviceProvider("localhost:8100");
        setDeviceTitle("MARTe2  NI6368 ADC");
        setDeviceType("MARTE2_NI6368_ADC");
        setHeight(700);
        setWidth(900);
        getContentPane().add(deviceButtons1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.GridLayout(2, 0));

        deviceField1.setIdentifier("");
        deviceField1.setLabelString("Board Id: ");
        deviceField1.setNumCols(20);
        deviceField1.setOffsetNid(10);
        jPanel3.add(deviceField1);

        deviceField2.setIdentifier("");
        deviceField2.setLabelString("Segment Size: ");
        deviceField2.setNumCols(6);
        deviceField2.setOffsetNid(336);
        jPanel3.add(deviceField2);

        deviceField3.setIdentifier("");
        deviceField3.setLabelString("Segment blocks: ");
        deviceField3.setNumCols(6);
        deviceField3.setOffsetNid(50);
        jPanel3.add(deviceField3);

        jPanel2.add(jPanel3);

        deviceChoice1.setChoiceItems(new String[] {"INTERNAL", "EXTERNAL"});
        deviceChoice1.setIdentifier("");
        deviceChoice1.setLabelString("Clock Mode: ");
        deviceChoice1.setOffsetNid(338);
        deviceChoice1.setUpdateIdentifier("");
        jPanel4.add(deviceChoice1);

        deviceField4.setIdentifier("");
        deviceField4.setLabelString("Frequency: ");
        deviceField4.setNumCols(20);
        deviceField4.setOffsetNid(337);
        jPanel4.add(deviceField4);

        deviceField5.setIdentifier("");
        deviceField5.setLabelString("Ext. Clock: ");
        deviceField5.setNumCols(20);
        deviceField5.setOffsetNid(339);
        jPanel4.add(deviceField5);

        jPanel2.add(jPanel4);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel5.setLayout(new java.awt.GridLayout(8, 2));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Channel 1"));

        deviceChoice2.setChoiceItems(new String[] {"ENABLED", "DISABLED"});
        deviceChoice2.setIdentifier("");
        deviceChoice2.setLabelString("State: ");
        deviceChoice2.setOffsetNid(343);
        deviceChoice2.setUpdateIdentifier("");
        jPanel6.add(deviceChoice2);

        deviceChoice3.setChoiceFloatValues(new float[] {10.0f, 5.0f, 2.0f, 1.0f});
        deviceChoice3.setChoiceItems(new String[] {"10.", "5.", "2.", "1."});
        deviceChoice3.setIdentifier("");
        deviceChoice3.setLabelString("Range(V): +/-");
        deviceChoice3.setOffsetNid(87);
        deviceChoice3.setUpdateIdentifier("");
        jPanel6.add(deviceChoice3);

        jPanel5.add(jPanel6);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Channel 2"));

        deviceChoice4.setChoiceItems(new String[] {"ENABLED", "DISABLED"});
        deviceChoice4.setIdentifier("");
        deviceChoice4.setLabelString("State: ");
        deviceChoice4.setOffsetNid(347);
        deviceChoice4.setUpdateIdentifier("");
        jPanel7.add(deviceChoice4);

        deviceChoice5.setChoiceFloatValues(new float[] {10.0f, 5.0f, 2.0f, 1.0f});
        deviceChoice5.setChoiceItems(new String[] {"10.", "5.", "2.", "1."});
        deviceChoice5.setIdentifier("");
        deviceChoice5.setLabelString("Range(V): +/-");
        deviceChoice5.setOffsetNid(103);
        deviceChoice5.setUpdateIdentifier("");
        jPanel7.add(deviceChoice5);

        jPanel5.add(jPanel7);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Channel 3"));

        deviceChoice6.setChoiceItems(new String[] {"ENABLED", "DISABLED"});
        deviceChoice6.setIdentifier("");
        deviceChoice6.setLabelString("State: ");
        deviceChoice6.setOffsetNid(351);
        deviceChoice6.setUpdateIdentifier("");
        jPanel8.add(deviceChoice6);

        deviceChoice7.setChoiceFloatValues(new float[] {10.0f, 5.0f, 2.0f, 1.0f});
        deviceChoice7.setChoiceItems(new String[] {"10.", "5.", "2.", "1."});
        deviceChoice7.setIdentifier("");
        deviceChoice7.setLabelString("Range(V): +/-");
        deviceChoice7.setOffsetNid(119);
        deviceChoice7.setUpdateIdentifier("");
        jPanel8.add(deviceChoice7);

        jPanel5.add(jPanel8);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Channel 4"));

        deviceChoice8.setChoiceItems(new String[] {"ENABLED", "DISABLED"});
        deviceChoice8.setIdentifier("");
        deviceChoice8.setLabelString("State: ");
        deviceChoice8.setOffsetNid(355);
        deviceChoice8.setUpdateIdentifier("");
        jPanel9.add(deviceChoice8);

        deviceChoice9.setChoiceFloatValues(new float[] {10.0f, 5.0f, 2.0f, 1.0f});
        deviceChoice9.setChoiceItems(new String[] {"10.", "5.", "2.", "1."});
        deviceChoice9.setIdentifier("");
        deviceChoice9.setLabelString("Range(V): +/-");
        deviceChoice9.setOffsetNid(135);
        deviceChoice9.setUpdateIdentifier("");
        jPanel9.add(deviceChoice9);

        jPanel5.add(jPanel9);

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Channel 5"));

        deviceChoice10.setChoiceItems(new String[] {"ENABLED", "DISABLED"});
        deviceChoice10.setIdentifier("");
        deviceChoice10.setLabelString("State: ");
        deviceChoice10.setOffsetNid(359);
        deviceChoice10.setUpdateIdentifier("");
        jPanel10.add(deviceChoice10);

        deviceChoice11.setChoiceFloatValues(new float[] {10.0f, 5.0f, 2.0f, 1.0f});
        deviceChoice11.setChoiceItems(new String[] {"10.", "5.", "2.", "1."});
        deviceChoice11.setIdentifier("");
        deviceChoice11.setLabelString("Range(V): +/-");
        deviceChoice11.setOffsetNid(151);
        deviceChoice11.setUpdateIdentifier("");
        jPanel10.add(deviceChoice11);

        jPanel5.add(jPanel10);

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Channel 6"));

        deviceChoice12.setChoiceItems(new String[] {"ENABLED", "DISABLED"});
        deviceChoice12.setIdentifier("");
        deviceChoice12.setLabelString("State: ");
        deviceChoice12.setOffsetNid(363);
        deviceChoice12.setUpdateIdentifier("");
        jPanel11.add(deviceChoice12);

        deviceChoice13.setChoiceFloatValues(new float[] {10.0f, 5.0f, 2.0f, 1.0f});
        deviceChoice13.setChoiceItems(new String[] {"10.", "5.", "2.", "1."});
        deviceChoice13.setIdentifier("");
        deviceChoice13.setLabelString("Range(V): +/-");
        deviceChoice13.setOffsetNid(167);
        deviceChoice13.setUpdateIdentifier("");
        jPanel11.add(deviceChoice13);

        jPanel5.add(jPanel11);

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Channel 7"));

        deviceChoice14.setChoiceItems(new String[] {"ENABLED", "DISABLED"});
        deviceChoice14.setIdentifier("");
        deviceChoice14.setLabelString("State: ");
        deviceChoice14.setOffsetNid(367);
        deviceChoice14.setUpdateIdentifier("");
        jPanel12.add(deviceChoice14);

        deviceChoice15.setChoiceFloatValues(new float[] {10.0f, 5.0f, 2.0f, 1.0f});
        deviceChoice15.setChoiceItems(new String[] {"10.", "5.", "2.", "1."});
        deviceChoice15.setIdentifier("");
        deviceChoice15.setLabelString("Range(V): +/-");
        deviceChoice15.setOffsetNid(183);
        deviceChoice15.setUpdateIdentifier("");
        jPanel12.add(deviceChoice15);

        jPanel5.add(jPanel12);

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder("Channel 8"));

        deviceChoice16.setChoiceItems(new String[] {"ENABLED", "DISABLED"});
        deviceChoice16.setIdentifier("");
        deviceChoice16.setLabelString("State: ");
        deviceChoice16.setOffsetNid(371);
        deviceChoice16.setUpdateIdentifier("");
        jPanel13.add(deviceChoice16);

        deviceChoice17.setChoiceFloatValues(new float[] {10.0f, 5.0f, 2.0f, 1.0f});
        deviceChoice17.setChoiceItems(new String[] {"10.", "5.", "2.", "1."});
        deviceChoice17.setIdentifier("");
        deviceChoice17.setLabelString("Range(V): +/-");
        deviceChoice17.setOffsetNid(199);
        deviceChoice17.setUpdateIdentifier("");
        jPanel13.add(deviceChoice17);

        jPanel5.add(jPanel13);

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder("Channel 9"));

        deviceChoice18.setChoiceItems(new String[] {"ENABLED", "DISABLED"});
        deviceChoice18.setIdentifier("");
        deviceChoice18.setLabelString("State: ");
        deviceChoice18.setOffsetNid(375);
        deviceChoice18.setUpdateIdentifier("");
        jPanel14.add(deviceChoice18);

        deviceChoice19.setChoiceFloatValues(new float[] {10.0f, 5.0f, 2.0f, 1.0f});
        deviceChoice19.setChoiceItems(new String[] {"10.", "5.", "2.", "1."});
        deviceChoice19.setIdentifier("");
        deviceChoice19.setLabelString("Range(V): +/-");
        deviceChoice19.setOffsetNid(215);
        deviceChoice19.setUpdateIdentifier("");
        jPanel14.add(deviceChoice19);

        jPanel5.add(jPanel14);

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder("Channel 10"));

        deviceChoice20.setChoiceItems(new String[] {"ENABLED", "DISABLED"});
        deviceChoice20.setIdentifier("");
        deviceChoice20.setLabelString("State: ");
        deviceChoice20.setOffsetNid(379);
        deviceChoice20.setUpdateIdentifier("");
        jPanel15.add(deviceChoice20);

        deviceChoice21.setChoiceFloatValues(new float[] {10.0f, 5.0f, 2.0f, 1.0f});
        deviceChoice21.setChoiceItems(new String[] {"10.", "5.", "2.", "1."});
        deviceChoice21.setIdentifier("");
        deviceChoice21.setLabelString("Range(V): +/-");
        deviceChoice21.setOffsetNid(231);
        deviceChoice21.setUpdateIdentifier("");
        jPanel15.add(deviceChoice21);

        jPanel5.add(jPanel15);

        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder("Channel 11"));

        deviceChoice22.setChoiceItems(new String[] {"ENABLED", "DISABLED"});
        deviceChoice22.setIdentifier("");
        deviceChoice22.setLabelString("State: ");
        deviceChoice22.setOffsetNid(383);
        deviceChoice22.setUpdateIdentifier("");
        jPanel16.add(deviceChoice22);

        deviceChoice23.setChoiceFloatValues(new float[] {10.0f, 5.0f, 2.0f, 1.0f});
        deviceChoice23.setChoiceItems(new String[] {"10.", "5.", "2.", "1."});
        deviceChoice23.setIdentifier("");
        deviceChoice23.setLabelString("Range(V): +/-");
        deviceChoice23.setOffsetNid(247);
        deviceChoice23.setUpdateIdentifier("");
        jPanel16.add(deviceChoice23);

        jPanel5.add(jPanel16);

        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder("Channel 12"));

        deviceChoice24.setChoiceItems(new String[] {"ENABLED", "DISABLED"});
        deviceChoice24.setIdentifier("");
        deviceChoice24.setLabelString("State: ");
        deviceChoice24.setOffsetNid(387);
        deviceChoice24.setUpdateIdentifier("");
        jPanel17.add(deviceChoice24);

        deviceChoice25.setChoiceFloatValues(new float[] {10.0f, 5.0f, 2.0f, 1.0f});
        deviceChoice25.setChoiceItems(new String[] {"10.", "5.", "2.", "1."});
        deviceChoice25.setIdentifier("");
        deviceChoice25.setLabelString("Range(V): +/-");
        deviceChoice25.setOffsetNid(263);
        deviceChoice25.setUpdateIdentifier("");
        jPanel17.add(deviceChoice25);

        jPanel5.add(jPanel17);

        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder("Channel 13"));

        deviceChoice26.setChoiceItems(new String[] {"ENABLED", "DISABLED"});
        deviceChoice26.setIdentifier("");
        deviceChoice26.setLabelString("State: ");
        deviceChoice26.setOffsetNid(391);
        deviceChoice26.setUpdateIdentifier("");
        jPanel18.add(deviceChoice26);

        deviceChoice27.setChoiceFloatValues(new float[] {10.0f, 5.0f, 2.0f, 1.0f});
        deviceChoice27.setChoiceItems(new String[] {"10.", "5.", "2.", "1."});
        deviceChoice27.setIdentifier("");
        deviceChoice27.setLabelString("Range(V): +/-");
        deviceChoice27.setOffsetNid(279);
        deviceChoice27.setUpdateIdentifier("");
        jPanel18.add(deviceChoice27);

        jPanel5.add(jPanel18);

        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder("Channel 14"));

        deviceChoice28.setChoiceItems(new String[] {"ENABLED", "DISABLED"});
        deviceChoice28.setIdentifier("");
        deviceChoice28.setLabelString("State: ");
        deviceChoice28.setOffsetNid(395);
        deviceChoice28.setUpdateIdentifier("");
        jPanel19.add(deviceChoice28);

        deviceChoice29.setChoiceFloatValues(new float[] {10.0f, 5.0f, 2.0f, 1.0f});
        deviceChoice29.setChoiceItems(new String[] {"10.", "5.", "2.", "1."});
        deviceChoice29.setIdentifier("");
        deviceChoice29.setLabelString("Range(V): +/-");
        deviceChoice29.setOffsetNid(295);
        deviceChoice29.setUpdateIdentifier("");
        jPanel19.add(deviceChoice29);

        jPanel5.add(jPanel19);

        jPanel20.setBorder(javax.swing.BorderFactory.createTitledBorder("Channel 15"));

        deviceChoice30.setChoiceItems(new String[] {"ENABLED", "DISABLED"});
        deviceChoice30.setIdentifier("");
        deviceChoice30.setLabelString("State: ");
        deviceChoice30.setOffsetNid(399);
        deviceChoice30.setUpdateIdentifier("");
        jPanel20.add(deviceChoice30);

        deviceChoice31.setChoiceFloatValues(new float[] {10.0f, 5.0f, 2.0f, 1.0f});
        deviceChoice31.setChoiceItems(new String[] {"10.", "5.", "2.", "1."});
        deviceChoice31.setIdentifier("");
        deviceChoice31.setLabelString("Range(V): +/-");
        deviceChoice31.setOffsetNid(311);
        deviceChoice31.setUpdateIdentifier("");
        jPanel20.add(deviceChoice31);

        jPanel5.add(jPanel20);

        jPanel21.setBorder(javax.swing.BorderFactory.createTitledBorder("Channel 16"));

        deviceChoice32.setChoiceItems(new String[] {"ENABLED", "DISABLED"});
        deviceChoice32.setIdentifier("");
        deviceChoice32.setLabelString("State: ");
        deviceChoice32.setOffsetNid(403);
        deviceChoice32.setUpdateIdentifier("");
        jPanel21.add(deviceChoice32);

        deviceChoice33.setChoiceFloatValues(new float[] {10.0f, 5.0f, 2.0f, 1.0f});
        deviceChoice33.setChoiceItems(new String[] {"10.", "5.", "2.", "1."});
        deviceChoice33.setIdentifier("");
        deviceChoice33.setLabelString("Range(V): +/-");
        deviceChoice33.setOffsetNid(327);
        deviceChoice33.setUpdateIdentifier("");
        jPanel21.add(deviceChoice33);

        jPanel5.add(jPanel21);

        jScrollPane1.setViewportView(jPanel5);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private DeviceButtons deviceButtons1;
    private DeviceChoice deviceChoice1;
    private DeviceChoice deviceChoice10;
    private DeviceChoice deviceChoice11;
    private DeviceChoice deviceChoice12;
    private DeviceChoice deviceChoice13;
    private DeviceChoice deviceChoice14;
    private DeviceChoice deviceChoice15;
    private DeviceChoice deviceChoice16;
    private DeviceChoice deviceChoice17;
    private DeviceChoice deviceChoice18;
    private DeviceChoice deviceChoice19;
    private DeviceChoice deviceChoice2;
    private DeviceChoice deviceChoice20;
    private DeviceChoice deviceChoice21;
    private DeviceChoice deviceChoice22;
    private DeviceChoice deviceChoice23;
    private DeviceChoice deviceChoice24;
    private DeviceChoice deviceChoice25;
    private DeviceChoice deviceChoice26;
    private DeviceChoice deviceChoice27;
    private DeviceChoice deviceChoice28;
    private DeviceChoice deviceChoice29;
    private DeviceChoice deviceChoice3;
    private DeviceChoice deviceChoice30;
    private DeviceChoice deviceChoice31;
    private DeviceChoice deviceChoice32;
    private DeviceChoice deviceChoice33;
    private DeviceChoice deviceChoice4;
    private DeviceChoice deviceChoice5;
    private DeviceChoice deviceChoice6;
    private DeviceChoice deviceChoice7;
    private DeviceChoice deviceChoice8;
    private DeviceChoice deviceChoice9;
    private DeviceField deviceField1;
    private DeviceField deviceField2;
    private DeviceField deviceField3;
    private DeviceField deviceField4;
    private DeviceField deviceField5;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
