/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mdsplus
 */
public class MARTE2_NI6723Setup extends DeviceSetup {

    /**
     * Creates new form MARTE2_NI6723Setup
     */
    public MARTE2_NI6723Setup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deviceButtons1 = new DeviceButtons();
        jScrollPane1 = new javax.swing.JScrollPane();
        deviceInputs1 = new DeviceInputs();
        jPanel17 = new javax.swing.JPanel();
        deviceField16 = new DeviceField();
        deviceField1 = new DeviceField();

        setDeviceProvider("localhost:8100");
        setDeviceTitle("NI6323 DAC");
        setDeviceType("MARTE2_NI6723");
        setHeight(300);
        setWidth(500);
        getContentPane().add(deviceButtons1, java.awt.BorderLayout.PAGE_END);

        deviceInputs1.setOffsetNid(8);
        jScrollPane1.setViewportView(deviceInputs1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        deviceField16.setIdentifier("");
        deviceField16.setLabelString("Address");
        deviceField16.setOffsetNid(7);
        deviceField16.setTextOnly(true);
        jPanel17.add(deviceField16);

        deviceField1.setIdentifier("");
        deviceField1.setLabelString("Timebase");
        deviceField1.setNumCols(20);
        deviceField1.setOffsetNid(3);
        jPanel17.add(deviceField1);

        getContentPane().add(jPanel17, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private DeviceButtons deviceButtons1;
    private DeviceField deviceField1;
    private DeviceField deviceField16;
    private DeviceInputs deviceInputs1;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
