/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mdsplus
 */
public class MARTE2_AD20XXDACSetup extends DeviceSetup {

    /**
     * Creates new form MARTE2_AD20XXDACSetup
     */
    public MARTE2_AD20XXDACSetup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deviceButtons1 = new DeviceButtons();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        deviceField1 = new DeviceField();
        deviceField2 = new DeviceField();
        jPanel4 = new javax.swing.JPanel();
        deviceChoice1 = new DeviceChoice();
        deviceChoice2 = new DeviceChoice();
        deviceChoice3 = new DeviceChoice();
        jPanel5 = new javax.swing.JPanel();
        deviceField3 = new DeviceField();
        deviceField4 = new DeviceField();
        deviceField5 = new DeviceField();
        deviceField6 = new DeviceField();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        deviceChoice4 = new DeviceChoice();
        deviceField7 = new DeviceField();
        jPanel8 = new javax.swing.JPanel();
        deviceChoice5 = new DeviceChoice();
        deviceField8 = new DeviceField();

        setDeviceProvider("localhost:8001");
        setDeviceTitle("AD20XX DAC");
        setDeviceType("MARTE2_AD20XXDAC");
        setHeight(400);
        setUpdateEvent("");
        setWidth(700);
        getContentPane().add(deviceButtons1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.GridLayout(3, 1));

        deviceField1.setIdentifier("");
        deviceField1.setLabelString("Timebase: ");
        deviceField1.setNumCols(25);
        deviceField1.setOffsetNid(3);
        jPanel3.add(deviceField1);

        deviceField2.setIdentifier("");
        deviceField2.setLabelString("Time div: ");
        deviceField2.setNumCols(4);
        deviceField2.setOffsetNid(72);
        jPanel3.add(deviceField2);

        jPanel2.add(jPanel3);

        deviceChoice1.setChoiceItems(new String[] {"InternalTiming", "ExTimeBase", "ExTimeBase_AFI0"});
        deviceChoice1.setIdentifier("");
        deviceChoice1.setLabelString("Clock Source: ");
        deviceChoice1.setOffsetNid(10);
        deviceChoice1.setUpdateIdentifier("");
        jPanel4.add(deviceChoice1);

        deviceChoice2.setChoiceItems(new String[] {"Slave", "Master"});
        deviceChoice2.setIdentifier("");
        deviceChoice2.setLabelString("SSI Mode: ");
        deviceChoice2.setOffsetNid(13);
        deviceChoice2.setUpdateIdentifier("");
        jPanel4.add(deviceChoice2);

        deviceChoice3.setChoiceItems(new String[] {"Internal", "ExternalEXTD", "ExternalSMB", "ExternalStar"});
        deviceChoice3.setIdentifier("");
        deviceChoice3.setLabelString("Trig. Source: ");
        deviceChoice3.setOffsetNid(16);
        deviceChoice3.setUpdateIdentifier("");
        jPanel4.add(deviceChoice3);

        jPanel2.add(jPanel4);

        deviceField3.setIdentifier("");
        deviceField3.setLabelString("Board Id: ");
        deviceField3.setNumCols(4);
        deviceField3.setOffsetNid(7);
        jPanel5.add(deviceField3);

        deviceField4.setIdentifier("");
        deviceField4.setLabelString("Clock divisor: ");
        deviceField4.setNumCols(8);
        deviceField4.setOffsetNid(22);
        jPanel5.add(deviceField4);

        deviceField5.setIdentifier("");
        deviceField5.setLabelString("Sleep time: ");
        deviceField5.setNumCols(8);
        deviceField5.setOffsetNid(25);
        jPanel5.add(deviceField5);

        deviceField6.setIdentifier("");
        deviceField6.setLabelString("Model: ");
        deviceField6.setNumCols(8);
        deviceField6.setOffsetNid(28);
        jPanel5.add(deviceField6);

        jPanel2.add(jPanel5);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridLayout(2, 1));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Chan 1"));

        deviceChoice4.setChoiceFloatValues(new float[] {10.0f, 5.0f, 2.5f});
        deviceChoice4.setChoiceItems(new String[] {"10", "5", "2.5"});
        deviceChoice4.setIdentifier("");
        deviceChoice4.setLabelString("Output Range: ");
        deviceChoice4.setOffsetNid(57);
        deviceChoice4.setUpdateIdentifier("");
        jPanel6.add(deviceChoice4);

        deviceField7.setIdentifier("");
        deviceField7.setLabelString("Samples ");
        deviceField7.setNumCols(8);
        deviceField7.setOffsetNid(48);
        jPanel6.add(deviceField7);

        jPanel1.add(jPanel6);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Chan 2"));

        deviceChoice5.setChoiceFloatValues(new float[] {10.0f, 5.0f, 2.5f});
        deviceChoice5.setChoiceItems(new String[] {"10", "5", "2.5"});
        deviceChoice5.setIdentifier("");
        deviceChoice5.setLabelString("Output Range: ");
        deviceChoice5.setOffsetNid(71);
        deviceChoice5.setUpdateIdentifier("");
        jPanel8.add(deviceChoice5);

        deviceField8.setIdentifier("");
        deviceField8.setLabelString("Samples ");
        deviceField8.setNumCols(8);
        deviceField8.setOffsetNid(62);
        jPanel8.add(deviceField8);

        jPanel1.add(jPanel8);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private DeviceButtons deviceButtons1;
    private DeviceChoice deviceChoice1;
    private DeviceChoice deviceChoice2;
    private DeviceChoice deviceChoice3;
    private DeviceChoice deviceChoice4;
    private DeviceChoice deviceChoice5;
    private DeviceField deviceField1;
    private DeviceField deviceField2;
    private DeviceField deviceField3;
    private DeviceField deviceField4;
    private DeviceField deviceField5;
    private DeviceField deviceField6;
    private DeviceField deviceField7;
    private DeviceField deviceField8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
}
