import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;

/**
 * <p>
 * Title:
 * </p>
 * <p>
 * Description:
 * </p>
 * <p>
 * Copyright: Copyright (c) 2003
 * </p>
 * <p>
 * Company:
 * </p>
 *
 * @author not attributable
 * @version 1.0
 */
public class RFXInverterSetupSetup extends DeviceSetup
{
	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	BorderLayout borderLayout1 = new BorderLayout();
	JPanel jPanel1 = new JPanel();
	DeviceField deviceField1 = new DeviceField();
	DeviceButtons deviceButtons1 = new DeviceButtons();
	JTabbedPane jTabbedPane1 = new JTabbedPane();
	DeviceChannel deviceChannel1 = new DeviceChannel();
	JPanel jPanel2 = new JPanel();
	BorderLayout borderLayout2 = new BorderLayout();
	DeviceField deviceField30 = new DeviceField();
	JPanel jPanel20 = new JPanel();
	DeviceField deviceField32 = new DeviceField();
	JPanel jPanel4 = new JPanel();
	BorderLayout borderLayout3 = new BorderLayout();
	DeviceField deviceField3 = new DeviceField();
	JLabel jLabel1 = new JLabel();
	DeviceField deviceField20 = new DeviceField();
	DeviceField deviceField4 = new DeviceField();
	DeviceField deviceField2 = new DeviceField();
	JPanel jPanel3 = new JPanel();
	DeviceWave deviceWave2 = new DeviceWave();
	JPanel jPanel5 = new JPanel();
	Border border1;
	TitledBorder titledBorder1;
	BorderLayout borderLayout4 = new BorderLayout();
	DeviceWaveDisplay deviceWaveDisplay1 = new DeviceWaveDisplay();
	DeviceWave deviceWave1 = new DeviceWave();
	DeviceField deviceField33 = new DeviceField();
	DeviceField deviceField5 = new DeviceField();
	BorderLayout borderLayout5 = new BorderLayout();
	JPanel jPanel6 = new JPanel();
	DeviceChannel deviceChannel2 = new DeviceChannel();
	JLabel jLabel2 = new JLabel();
	BorderLayout borderLayout6 = new BorderLayout();
	DeviceWave deviceWave3 = new DeviceWave();
	DeviceField deviceField6 = new DeviceField();
	JPanel jPanel7 = new JPanel();
	BorderLayout borderLayout7 = new BorderLayout();
	DeviceWave deviceWave4 = new DeviceWave();
	JPanel jPanel21 = new JPanel();
	JPanel jPanel8 = new JPanel();
	DeviceField deviceField21 = new DeviceField();
	JPanel jPanel9 = new JPanel();
	DeviceWaveDisplay deviceWaveDisplay2 = new DeviceWaveDisplay();
	DeviceField deviceField7 = new DeviceField();
	DeviceField deviceField34 = new DeviceField();
	DeviceField deviceField8 = new DeviceField();
	BorderLayout borderLayout8 = new BorderLayout();
	JPanel jPanel10 = new JPanel();
	DeviceChannel deviceChannel3 = new DeviceChannel();
	JLabel jLabel3 = new JLabel();
	BorderLayout borderLayout9 = new BorderLayout();
	DeviceWave deviceWave5 = new DeviceWave();
	DeviceField deviceField9 = new DeviceField();
	JPanel jPanel11 = new JPanel();
	BorderLayout borderLayout10 = new BorderLayout();
	DeviceWave deviceWave6 = new DeviceWave();
	JPanel jPanel22 = new JPanel();
	JPanel jPanel12 = new JPanel();
	DeviceField deviceField22 = new DeviceField();
	JPanel jPanel13 = new JPanel();
	DeviceWaveDisplay deviceWaveDisplay3 = new DeviceWaveDisplay();
	DeviceField deviceField10 = new DeviceField();
	DeviceField deviceField35 = new DeviceField();
	DeviceField deviceField11 = new DeviceField();
	BorderLayout borderLayout11 = new BorderLayout();
	JPanel jPanel14 = new JPanel();
	DeviceChannel deviceChannel4 = new DeviceChannel();
	JLabel jLabel4 = new JLabel();
	BorderLayout borderLayout12 = new BorderLayout();
	DeviceWave deviceWave7 = new DeviceWave();
	DeviceField deviceField12 = new DeviceField();
	JPanel jPanel15 = new JPanel();
	BorderLayout borderLayout13 = new BorderLayout();
	DeviceWave deviceWave8 = new DeviceWave();
	JPanel jPanel23 = new JPanel();
	JPanel jPanel16 = new JPanel();
	DeviceField deviceField23 = new DeviceField();
	JPanel jPanel17 = new JPanel();
	DeviceWaveDisplay deviceWaveDisplay4 = new DeviceWaveDisplay();
	DeviceField deviceField13 = new DeviceField();
	DeviceField deviceField36 = new DeviceField();
	DeviceField deviceField14 = new DeviceField();
	BorderLayout borderLayout14 = new BorderLayout();
	JPanel jPanel18 = new JPanel();
	DeviceChannel deviceChannel5 = new DeviceChannel();
	JLabel jLabel5 = new JLabel();
	BorderLayout borderLayout15 = new BorderLayout();
	DeviceWave deviceWave9 = new DeviceWave();
	DeviceField deviceField15 = new DeviceField();
	JPanel jPanel19 = new JPanel();
	BorderLayout borderLayout16 = new BorderLayout();
	DeviceWave deviceWave10 = new DeviceWave();
	JPanel jPanel24 = new JPanel();
	JPanel jPanel110 = new JPanel();
	DeviceField deviceField24 = new DeviceField();
	JPanel jPanel111 = new JPanel();
	DeviceWaveDisplay deviceWaveDisplay5 = new DeviceWaveDisplay();
	DeviceField deviceField16 = new DeviceField();
	DeviceField deviceField37 = new DeviceField();
	DeviceField deviceField17 = new DeviceField();
	BorderLayout borderLayout17 = new BorderLayout();
	JPanel jPanel112 = new JPanel();
	DeviceChannel deviceChannel6 = new DeviceChannel();
	JLabel jLabel6 = new JLabel();
	BorderLayout borderLayout18 = new BorderLayout();
	DeviceWave deviceWave11 = new DeviceWave();
	DeviceField deviceField18 = new DeviceField();
	JPanel jPanel113 = new JPanel();
	BorderLayout borderLayout19 = new BorderLayout();
	DeviceWave deviceWave12 = new DeviceWave();
	JPanel jPanel25 = new JPanel();
	JPanel jPanel114 = new JPanel();
	DeviceField deviceField25 = new DeviceField();
	JPanel jPanel115 = new JPanel();
	DeviceWaveDisplay deviceWaveDisplay6 = new DeviceWaveDisplay();
	DeviceField deviceField19 = new DeviceField();
	DeviceField deviceField38 = new DeviceField();
	DeviceField deviceField110 = new DeviceField();
	BorderLayout borderLayout110 = new BorderLayout();
	JPanel jPanel116 = new JPanel();
	DeviceChannel deviceChannel7 = new DeviceChannel();
	JLabel jLabel7 = new JLabel();
	BorderLayout borderLayout111 = new BorderLayout();
	DeviceWave deviceWave13 = new DeviceWave();
	DeviceField deviceField111 = new DeviceField();
	JPanel jPanel117 = new JPanel();
	BorderLayout borderLayout112 = new BorderLayout();
	DeviceWave deviceWave14 = new DeviceWave();
	JPanel jPanel26 = new JPanel();
	JPanel jPanel118 = new JPanel();
	DeviceField deviceField26 = new DeviceField();
	JPanel jPanel119 = new JPanel();
	DeviceWaveDisplay deviceWaveDisplay7 = new DeviceWaveDisplay();
	DeviceField deviceField112 = new DeviceField();
	DeviceField deviceField39 = new DeviceField();
	DeviceField deviceField113 = new DeviceField();
	BorderLayout borderLayout113 = new BorderLayout();
	JPanel jPanel1110 = new JPanel();
	DeviceChannel deviceChannel8 = new DeviceChannel();
	JLabel jLabel8 = new JLabel();
	BorderLayout borderLayout114 = new BorderLayout();
	DeviceWave deviceWave15 = new DeviceWave();
	DeviceField deviceField114 = new DeviceField();
	JPanel jPanel1111 = new JPanel();
	BorderLayout borderLayout115 = new BorderLayout();
	DeviceWave deviceWave16 = new DeviceWave();
	JPanel jPanel27 = new JPanel();
	JPanel jPanel1112 = new JPanel();
	DeviceField deviceField27 = new DeviceField();
	JPanel jPanel1113 = new JPanel();
	DeviceWaveDisplay deviceWaveDisplay8 = new DeviceWaveDisplay();
	DeviceField deviceField115 = new DeviceField();
	DeviceField deviceField310 = new DeviceField();
	DeviceField deviceField116 = new DeviceField();
	BorderLayout borderLayout116 = new BorderLayout();
	JPanel jPanel1114 = new JPanel();
	DeviceChannel deviceChannel9 = new DeviceChannel();
	JLabel jLabel9 = new JLabel();
	BorderLayout borderLayout117 = new BorderLayout();
	DeviceWave deviceWave17 = new DeviceWave();
	DeviceField deviceField117 = new DeviceField();
	JPanel jPanel1115 = new JPanel();
	BorderLayout borderLayout118 = new BorderLayout();
	DeviceWave deviceWave18 = new DeviceWave();
	JPanel jPanel28 = new JPanel();
	JPanel jPanel1116 = new JPanel();
	DeviceField deviceField28 = new DeviceField();
	JPanel jPanel1117 = new JPanel();
	DeviceWaveDisplay deviceWaveDisplay9 = new DeviceWaveDisplay();
	DeviceField deviceField118 = new DeviceField();
	DeviceField deviceField311 = new DeviceField();
	DeviceField deviceField119 = new DeviceField();
	BorderLayout borderLayout119 = new BorderLayout();
	JPanel jPanel1118 = new JPanel();
	DeviceChannel deviceChannel10 = new DeviceChannel();
	JLabel jLabel10 = new JLabel();
	BorderLayout borderLayout1110 = new BorderLayout();
	DeviceWave deviceWave19 = new DeviceWave();
	DeviceField deviceField1110 = new DeviceField();
	JPanel jPanel1119 = new JPanel();
	BorderLayout borderLayout1111 = new BorderLayout();
	DeviceWave deviceWave110 = new DeviceWave();
	JPanel jPanel29 = new JPanel();
	JPanel jPanel11110 = new JPanel();
	DeviceField deviceField29 = new DeviceField();
	JPanel jPanel11111 = new JPanel();
	DeviceWaveDisplay deviceWaveDisplay10 = new DeviceWaveDisplay();
	DeviceField deviceField1111 = new DeviceField();
	DeviceField deviceField314 = new DeviceField();
	DeviceField deviceField1118 = new DeviceField();
	BorderLayout borderLayout1118 = new BorderLayout();
	JPanel jPanel111110 = new JPanel();
	DeviceChannel deviceChannel13 = new DeviceChannel();
	JLabel jLabel13 = new JLabel();
	BorderLayout borderLayout1119 = new BorderLayout();
	DeviceWave deviceWave115 = new DeviceWave();
	DeviceField deviceField1119 = new DeviceField();
	JPanel jPanel111111 = new JPanel();
	BorderLayout borderLayout11110 = new BorderLayout();
	DeviceWave deviceWave116 = new DeviceWave();
	JPanel jPanel212 = new JPanel();
	JPanel jPanel111112 = new JPanel();
	DeviceField deviceField212 = new DeviceField();
	JPanel jPanel111113 = new JPanel();
	DeviceWaveDisplay deviceWaveDisplay13 = new DeviceWaveDisplay();
	DeviceField deviceField11110 = new DeviceField();
	DeviceField deviceField315 = new DeviceField();
	DeviceField deviceField11111 = new DeviceField();
	BorderLayout borderLayout11111 = new BorderLayout();
	JPanel jPanel111114 = new JPanel();
	DeviceChannel deviceChannel14 = new DeviceChannel();
	JLabel jLabel14 = new JLabel();
	BorderLayout borderLayout11112 = new BorderLayout();
	DeviceWave deviceWave117 = new DeviceWave();
	DeviceField deviceField11112 = new DeviceField();
	JPanel jPanel111115 = new JPanel();
	BorderLayout borderLayout11113 = new BorderLayout();
	DeviceWave deviceWave118 = new DeviceWave();
	JPanel jPanel213 = new JPanel();
	JPanel jPanel111116 = new JPanel();
	DeviceField deviceField213 = new DeviceField();
	JPanel jPanel111117 = new JPanel();
	DeviceWaveDisplay deviceWaveDisplay14 = new DeviceWaveDisplay();
	DeviceField deviceField11113 = new DeviceField();
	DeviceChoice deviceChoice1 = new DeviceChoice();

	public RFXInverterSetupSetup()
	{
		try
		{
			jbInit();
		}
		catch (final Exception e)
		{
			e.printStackTrace();
		}
	}

	private void jbInit() throws Exception
	{
		border1 = BorderFactory.createLineBorder(Color.white, 1);
		titledBorder1 = new TitledBorder(BorderFactory.createLineBorder(Color.white, 1),
				"Perturbation gain and preview");
		this.setWidth(800);
		this.setHeight(650);
		this.setDeviceType("RFXInverterSetup");
		this.setDeviceProvider("localhost");
		this.setDeviceTitle("EDA2 Inverter Setup");
		this.getContentPane().setLayout(borderLayout1);
		deviceField1.setOffsetNid(1);
		deviceField1.setTextOnly(true);
		deviceField1.setLabelString("Comment: ");
		deviceField1.setNumCols(20);
		deviceField1.setIdentifier("");
		deviceChannel1.setLabelString("On");
		deviceChannel1.setOffsetNid(5);
		deviceChannel1.setUpdateIdentifier("");
		deviceChannel1.setShowVal("");
		jPanel2.setLayout(borderLayout2);
		deviceField30.setOffsetNid(3);
		deviceField30.setTextOnly(true);
		deviceField30.setLabelString("Control");
		deviceField30.setIdentifier("");
		deviceField30.setEditable(false);
		deviceField30.setDisplayEvaluated(true);
		deviceField32.setOffsetNid(18);
		deviceField32.setLabelString("ITH_INV_END_FORCE: ");
		deviceField32.setIdentifier("");
		deviceField32.setEditable(false);
		jPanel4.setLayout(borderLayout3);
		deviceField3.setOffsetNid(22);
		deviceField3.setLabelString("Phase (rad.):");
		deviceField3.setNumCols(4);
		deviceField3.setIdentifier("");
		jLabel1.setText("Perturbation:");
		deviceField20.setOffsetNid(21);
		deviceField20.setLabelString("Freq. (Hz)");
		deviceField20.setNumCols(4);
		deviceField20.setIdentifier("");
		deviceField4.setOffsetNid(20);
		deviceField4.setLabelString("Amp.:");
		deviceField4.setNumCols(4);
		deviceField4.setIdentifier("");
		deviceField2.setOffsetNid(23);
		deviceField2.setLabelString("Start Time:");
		deviceField2.setNumCols(4);
		deviceField2.setIdentifier("");
		deviceWave2.setOffsetNid(6);
		deviceWave2.setMinYVisible(true);
		deviceWave2.setIdentifier("");
		deviceWave2.setUpdateExpression("");
		deviceWave2.setPrefHeight(100);
		jPanel5.setBorder(titledBorder1);
		jPanel5.setLayout(borderLayout4);
		deviceWaveDisplay1.setOffsetNid(17);
		deviceWave1.setOffsetNid(11);
		deviceWave1.setMaxYVisible(true);
		deviceWave1.setIdentifier("");
		deviceWave1.setUpdateExpression("");
		deviceField33.setIdentifier("");
		deviceField33.setLabelString("ITH_INV_END_FORCE: ");
		deviceField33.setOffsetNid(37);
		deviceField33.setEditable(false);
		deviceField5.setIdentifier("");
		deviceField5.setNumCols(4);
		deviceField5.setLabelString("Phase (rad.):");
		deviceField5.setOffsetNid(41);
		jPanel6.setLayout(borderLayout6);
		deviceChannel2.setLabelString("On");
		deviceChannel2.setOffsetNid(24);
		deviceChannel2.setUpdateIdentifier("");
		deviceChannel2.setShowVal("");
		jLabel2.setText("Perturbation:");
		deviceWave3.setOffsetNid(25);
		deviceWave3.setMinYVisible(true);
		deviceWave3.setIdentifier("");
		deviceWave3.setUpdateExpression("");
		deviceWave3.setPrefHeight(100);
		deviceField6.setOffsetNid(39);
		deviceField6.setLabelString("Amp.:");
		deviceField6.setNumCols(4);
		deviceField6.setIdentifier("");
		deviceWave4.setOffsetNid(30);
		deviceWave4.setMaxYVisible(true);
		deviceWave4.setIdentifier("");
		deviceWave4.setUpdateExpression("");
		jPanel8.setLayout(borderLayout5);
		deviceField21.setOffsetNid(40);
		deviceField21.setLabelString("Freq. (Hz)");
		deviceField21.setNumCols(4);
		deviceField21.setIdentifier("");
		jPanel9.setBorder(titledBorder1);
		jPanel9.setLayout(borderLayout7);
		deviceWaveDisplay2.setOffsetNid(36);
		deviceField7.setOffsetNid(42);
		deviceField7.setLabelString("Start Time:");
		deviceField7.setNumCols(4);
		deviceField7.setIdentifier("");
		deviceField34.setIdentifier("");
		deviceField34.setLabelString("ITH_INV_END_FORCE: ");
		deviceField34.setOffsetNid(56);
		deviceField34.setEditable(false);
		deviceField8.setIdentifier("");
		deviceField8.setNumCols(4);
		deviceField8.setLabelString("Phase (rad.):");
		deviceField8.setOffsetNid(60);
		jPanel10.setLayout(borderLayout9);
		deviceChannel3.setLabelString("On");
		deviceChannel3.setOffsetNid(43);
		deviceChannel3.setUpdateIdentifier("");
		deviceChannel3.setShowVal("");
		jLabel3.setText("Perturbation:");
		deviceWave5.setOffsetNid(44);
		deviceWave5.setMinYVisible(true);
		deviceWave5.setIdentifier("");
		deviceWave5.setUpdateExpression("");
		deviceWave5.setPrefHeight(100);
		deviceField9.setOffsetNid(58);
		deviceField9.setLabelString("Amp.:");
		deviceField9.setNumCols(4);
		deviceField9.setIdentifier("");
		deviceWave6.setOffsetNid(49);
		deviceWave6.setMaxYVisible(true);
		deviceWave6.setIdentifier("");
		deviceWave6.setUpdateExpression("");
		jPanel12.setLayout(borderLayout8);
		deviceField22.setOffsetNid(59);
		deviceField22.setLabelString("Freq. (Hz)");
		deviceField22.setNumCols(4);
		deviceField22.setIdentifier("");
		jPanel13.setBorder(titledBorder1);
		jPanel13.setLayout(borderLayout10);
		deviceWaveDisplay3.setOffsetNid(55);
		deviceField10.setOffsetNid(61);
		deviceField10.setLabelString("Start Time:");
		deviceField10.setNumCols(4);
		deviceField10.setIdentifier("");
		deviceField35.setIdentifier("");
		deviceField35.setLabelString("ITH_INV_END_FORCE: ");
		deviceField35.setOffsetNid(75);
		deviceField35.setEditable(false);
		deviceField11.setIdentifier("");
		deviceField11.setNumCols(4);
		deviceField11.setLabelString("Phase (rad.):");
		deviceField11.setOffsetNid(79);
		jPanel14.setLayout(borderLayout12);
		deviceChannel4.setLabelString("On");
		deviceChannel4.setOffsetNid(62);
		deviceChannel4.setUpdateIdentifier("");
		deviceChannel4.setShowVal("");
		jLabel4.setText("Perturbation:");
		deviceWave7.setOffsetNid(63);
		deviceWave7.setMinYVisible(true);
		deviceWave7.setIdentifier("");
		deviceWave7.setUpdateExpression("");
		deviceWave7.setPrefHeight(100);
		deviceField12.setOffsetNid(77);
		deviceField12.setLabelString("Amp.:");
		deviceField12.setNumCols(4);
		deviceField12.setIdentifier("");
		deviceWave8.setOffsetNid(68);
		deviceWave8.setMaxYVisible(true);
		deviceWave8.setIdentifier("");
		deviceWave8.setUpdateExpression("");
		jPanel16.setLayout(borderLayout11);
		deviceField23.setOffsetNid(78);
		deviceField23.setLabelString("Freq. (Hz)");
		deviceField23.setNumCols(4);
		deviceField23.setIdentifier("");
		jPanel17.setBorder(titledBorder1);
		jPanel17.setLayout(borderLayout13);
		deviceWaveDisplay4.setOffsetNid(74);
		deviceField13.setOffsetNid(80);
		deviceField13.setLabelString("Start Time:");
		deviceField13.setNumCols(4);
		deviceField13.setIdentifier("");
		deviceField36.setIdentifier("");
		deviceField36.setLabelString("ITH_INV_END_FORCE: ");
		deviceField36.setOffsetNid(94);
		deviceField36.setEditable(false);
		deviceField14.setIdentifier("");
		deviceField14.setNumCols(4);
		deviceField14.setLabelString("Phase (rad.):");
		deviceField14.setOffsetNid(98);
		jPanel18.setLayout(borderLayout15);
		deviceChannel5.setLabelString("On");
		deviceChannel5.setOffsetNid(81);
		deviceChannel5.setUpdateIdentifier("");
		deviceChannel5.setShowVal("");
		jLabel5.setText("Perturbation:");
		deviceWave9.setOffsetNid(82);
		deviceWave9.setMinYVisible(true);
		deviceWave9.setIdentifier("");
		deviceWave9.setUpdateExpression("");
		deviceWave9.setPrefHeight(100);
		deviceField15.setOffsetNid(96);
		deviceField15.setLabelString("Amp.:");
		deviceField15.setNumCols(4);
		deviceField15.setIdentifier("");
		deviceWave10.setOffsetNid(87);
		deviceWave10.setMaxYVisible(true);
		deviceWave10.setIdentifier("");
		deviceWave10.setUpdateExpression("");
		jPanel110.setLayout(borderLayout14);
		deviceField24.setOffsetNid(97);
		deviceField24.setLabelString("Freq. (Hz)");
		deviceField24.setNumCols(4);
		deviceField24.setIdentifier("");
		jPanel111.setBorder(titledBorder1);
		jPanel111.setLayout(borderLayout16);
		deviceWaveDisplay5.setOffsetNid(93);
		deviceField16.setOffsetNid(99);
		deviceField16.setLabelString("Start Time:");
		deviceField16.setNumCols(4);
		deviceField16.setIdentifier("");
		deviceField37.setIdentifier("");
		deviceField37.setLabelString("ITH_INV_END_FORCE: ");
		deviceField37.setOffsetNid(113);
		deviceField37.setEditable(false);
		deviceField17.setIdentifier("");
		deviceField17.setNumCols(4);
		deviceField17.setLabelString("Phase (rad.):");
		deviceField17.setOffsetNid(117);
		jPanel112.setLayout(borderLayout18);
		deviceChannel6.setLabelString("On");
		deviceChannel6.setOffsetNid(100);
		deviceChannel6.setUpdateIdentifier("");
		deviceChannel6.setShowVal("");
		jLabel6.setText("Perturbation:");
		deviceWave11.setOffsetNid(101);
		deviceWave11.setMinYVisible(true);
		deviceWave11.setIdentifier("");
		deviceWave11.setUpdateExpression("");
		deviceWave11.setPrefHeight(100);
		deviceField18.setOffsetNid(115);
		deviceField18.setLabelString("Amp.:");
		deviceField18.setNumCols(4);
		deviceField18.setIdentifier("");
		deviceWave12.setOffsetNid(106);
		deviceWave12.setMaxYVisible(true);
		deviceWave12.setIdentifier("");
		deviceWave12.setUpdateExpression("");
		jPanel114.setLayout(borderLayout17);
		deviceField25.setOffsetNid(116);
		deviceField25.setLabelString("Freq. (Hz)");
		deviceField25.setNumCols(4);
		deviceField25.setIdentifier("");
		jPanel115.setBorder(titledBorder1);
		jPanel115.setLayout(borderLayout19);
		deviceWaveDisplay6.setOffsetNid(112);
		deviceField19.setOffsetNid(118);
		deviceField19.setLabelString("Start Time:");
		deviceField19.setNumCols(4);
		deviceField19.setIdentifier("");
		deviceField38.setIdentifier("");
		deviceField38.setLabelString("ITH_INV_END_FORCE: ");
		deviceField38.setOffsetNid(132);
		deviceField38.setEditable(false);
		deviceField110.setIdentifier("");
		deviceField110.setNumCols(4);
		deviceField110.setLabelString("Phase (rad.):");
		deviceField110.setOffsetNid(136);
		jPanel116.setLayout(borderLayout111);
		deviceChannel7.setLabelString("On");
		deviceChannel7.setOffsetNid(119);
		deviceChannel7.setUpdateIdentifier("");
		deviceChannel7.setShowVal("");
		jLabel7.setText("Perturbation:");
		deviceWave13.setOffsetNid(120);
		deviceWave13.setMinYVisible(true);
		deviceWave13.setIdentifier("");
		deviceWave13.setUpdateExpression("");
		deviceWave13.setPrefHeight(100);
		deviceField111.setOffsetNid(134);
		deviceField111.setLabelString("Amp.:");
		deviceField111.setNumCols(4);
		deviceField111.setIdentifier("");
		deviceWave14.setOffsetNid(125);
		deviceWave14.setMaxYVisible(true);
		deviceWave14.setIdentifier("");
		deviceWave14.setUpdateExpression("");
		jPanel118.setLayout(borderLayout110);
		deviceField26.setOffsetNid(135);
		deviceField26.setLabelString("Freq. (Hz)");
		deviceField26.setNumCols(4);
		deviceField26.setIdentifier("");
		jPanel119.setBorder(titledBorder1);
		jPanel119.setLayout(borderLayout112);
		deviceWaveDisplay7.setOffsetNid(131);
		deviceField112.setOffsetNid(137);
		deviceField112.setLabelString("Start Time:");
		deviceField112.setNumCols(4);
		deviceField112.setIdentifier("");
		deviceField39.setIdentifier("");
		deviceField39.setLabelString("ITH_INV_END_FORCE: ");
		deviceField39.setOffsetNid(151);
		deviceField39.setEditable(false);
		deviceField113.setIdentifier("");
		deviceField113.setNumCols(4);
		deviceField113.setLabelString("Phase (rad.):");
		deviceField113.setOffsetNid(155);
		jPanel1110.setLayout(borderLayout114);
		deviceChannel8.setLabelString("On");
		deviceChannel8.setOffsetNid(138);
		deviceChannel8.setUpdateIdentifier("");
		deviceChannel8.setShowVal("");
		jLabel8.setText("Perturbation:");
		deviceWave15.setOffsetNid(139);
		deviceWave15.setMinYVisible(true);
		deviceWave15.setIdentifier("");
		deviceWave15.setUpdateExpression("");
		deviceWave15.setPrefHeight(100);
		deviceField114.setOffsetNid(153);
		deviceField114.setLabelString("Amp.:");
		deviceField114.setNumCols(4);
		deviceField114.setIdentifier("");
		deviceWave16.setOffsetNid(144);
		deviceWave16.setMaxYVisible(true);
		deviceWave16.setIdentifier("");
		deviceWave16.setUpdateExpression("");
		jPanel1112.setLayout(borderLayout113);
		deviceField27.setOffsetNid(154);
		deviceField27.setLabelString("Freq. (Hz)");
		deviceField27.setNumCols(4);
		deviceField27.setIdentifier("");
		jPanel1113.setBorder(titledBorder1);
		jPanel1113.setLayout(borderLayout115);
		deviceWaveDisplay8.setOffsetNid(150);
		deviceField115.setOffsetNid(156);
		deviceField115.setLabelString("Start Time:");
		deviceField115.setNumCols(4);
		deviceField115.setIdentifier("");
		deviceField310.setIdentifier("");
		deviceField310.setLabelString("ITH_INV_END_FORCE: ");
		deviceField310.setOffsetNid(170);
		deviceField310.setEditable(false);
		deviceField116.setIdentifier("");
		deviceField116.setNumCols(4);
		deviceField116.setLabelString("Phase (rad.):");
		deviceField116.setOffsetNid(174);
		jPanel1114.setLayout(borderLayout117);
		deviceChannel9.setLabelString("On");
		deviceChannel9.setOffsetNid(157);
		deviceChannel9.setUpdateIdentifier("");
		deviceChannel9.setShowVal("");
		jLabel9.setText("Perturbation:");
		deviceWave17.setOffsetNid(158);
		deviceWave17.setMinYVisible(true);
		deviceWave17.setIdentifier("");
		deviceWave17.setUpdateExpression("");
		deviceWave17.setPrefHeight(100);
		deviceField117.setOffsetNid(172);
		deviceField117.setLabelString("Amp.:");
		deviceField117.setNumCols(4);
		deviceField117.setIdentifier("");
		deviceWave18.setOffsetNid(163);
		deviceWave18.setMaxYVisible(true);
		deviceWave18.setIdentifier("");
		deviceWave18.setUpdateExpression("");
		jPanel1116.setLayout(borderLayout116);
		deviceField28.setOffsetNid(173);
		deviceField28.setLabelString("Freq. (Hz)");
		deviceField28.setNumCols(4);
		deviceField28.setIdentifier("");
		jPanel1117.setBorder(titledBorder1);
		jPanel1117.setLayout(borderLayout118);
		deviceWaveDisplay9.setOffsetNid(169);
		deviceField118.setOffsetNid(175);
		deviceField118.setLabelString("Start Time:");
		deviceField118.setNumCols(4);
		deviceField118.setIdentifier("");
		deviceField311.setIdentifier("");
		deviceField311.setLabelString("ITH_INV_END_FORCE: ");
		deviceField311.setOffsetNid(189);
		deviceField311.setEditable(false);
		deviceField119.setIdentifier("");
		deviceField119.setNumCols(4);
		deviceField119.setLabelString("Phase (rad.):");
		deviceField119.setOffsetNid(193);
		jPanel1118.setLayout(borderLayout1110);
		deviceChannel10.setLabelString("On");
		deviceChannel10.setOffsetNid(176);
		deviceChannel10.setUpdateIdentifier("");
		deviceChannel10.setShowVal("");
		jLabel10.setText("Perturbation:");
		deviceWave19.setOffsetNid(177);
		deviceWave19.setMinYVisible(true);
		deviceWave19.setIdentifier("");
		deviceWave19.setUpdateExpression("");
		deviceWave19.setPrefHeight(100);
		deviceField1110.setOffsetNid(191);
		deviceField1110.setLabelString("Amp.:");
		deviceField1110.setNumCols(4);
		deviceField1110.setIdentifier("");
		deviceWave110.setOffsetNid(182);
		deviceWave110.setMaxYVisible(true);
		deviceWave110.setIdentifier("");
		deviceWave110.setUpdateExpression("");
		jPanel11110.setLayout(borderLayout119);
		deviceField29.setOffsetNid(192);
		deviceField29.setLabelString("Freq. (Hz)");
		deviceField29.setNumCols(4);
		deviceField29.setIdentifier("");
		jPanel11111.setBorder(titledBorder1);
		jPanel11111.setLayout(borderLayout1111);
		deviceWaveDisplay10.setOffsetNid(188);
		deviceField1111.setOffsetNid(194);
		deviceField1111.setLabelString("Start Time:");
		deviceField1111.setNumCols(4);
		deviceField1111.setIdentifier("");
		deviceField314.setIdentifier("");
		deviceField314.setLabelString("ITH_INV_END_FORCE: ");
		deviceField314.setOffsetNid(208);
		deviceField314.setEditable(false);
		deviceField1118.setIdentifier("");
		deviceField1118.setNumCols(4);
		deviceField1118.setLabelString("Phase (rad.):");
		deviceField1118.setOffsetNid(212);
		jPanel111110.setLayout(borderLayout1119);
		deviceChannel13.setLabelString("On");
		deviceChannel13.setOffsetNid(195);
		deviceChannel13.setUpdateIdentifier("");
		deviceChannel13.setShowVal("");
		jLabel13.setText("Perturbation:");
		deviceWave115.setOffsetNid(196);
		deviceWave115.setMinYVisible(true);
		deviceWave115.setIdentifier("");
		deviceWave115.setUpdateExpression("");
		deviceWave115.setPrefHeight(100);
		deviceField1119.setOffsetNid(210);
		deviceField1119.setLabelString("Amp.:");
		deviceField1119.setNumCols(4);
		deviceField1119.setIdentifier("");
		deviceWave116.setOffsetNid(201);
		deviceWave116.setMaxYVisible(true);
		deviceWave116.setIdentifier("");
		deviceWave116.setUpdateExpression("");
		jPanel111112.setLayout(borderLayout1118);
		deviceField212.setOffsetNid(211);
		deviceField212.setLabelString("Freq. (Hz)");
		deviceField212.setNumCols(4);
		deviceField212.setIdentifier("");
		jPanel111113.setBorder(titledBorder1);
		jPanel111113.setLayout(borderLayout11110);
		deviceWaveDisplay13.setOffsetNid(207);
		deviceField11110.setOffsetNid(213);
		deviceField11110.setLabelString("Start Time:");
		deviceField11110.setNumCols(4);
		deviceField11110.setIdentifier("");
		deviceField315.setIdentifier("");
		deviceField315.setLabelString("ITH_INV_END_FORCE: ");
		deviceField315.setOffsetNid(227);
		deviceField315.setEditable(false);
		deviceField11111.setIdentifier("");
		deviceField11111.setNumCols(4);
		deviceField11111.setLabelString("Phase (rad.):");
		deviceField11111.setOffsetNid(231);
		jPanel111114.setLayout(borderLayout11112);
		deviceChannel14.setLabelString("On");
		deviceChannel14.setOffsetNid(214);
		deviceChannel14.setUpdateIdentifier("");
		deviceChannel14.setShowVal("");
		jLabel14.setText("Perturbation:");
		deviceWave117.setOffsetNid(215);
		deviceWave117.setMinYVisible(true);
		deviceWave117.setIdentifier("");
		deviceWave117.setUpdateExpression("");
		deviceWave117.setPrefHeight(215);
		deviceField11112.setOffsetNid(229);
		deviceField11112.setLabelString("Amp.:");
		deviceField11112.setNumCols(4);
		deviceField11112.setIdentifier("");
		deviceWave118.setOffsetNid(220);
		deviceWave118.setMaxYVisible(true);
		deviceWave118.setIdentifier("");
		deviceWave118.setUpdateExpression("");
		jPanel111116.setLayout(borderLayout11111);
		deviceField213.setOffsetNid(230);
		deviceField213.setLabelString("Freq. (Hz)");
		deviceField213.setNumCols(4);
		deviceField213.setIdentifier("");
		jPanel111117.setBorder(titledBorder1);
		jPanel111117.setLayout(borderLayout11113);
		deviceWaveDisplay14.setOffsetNid(226);
		deviceField11113.setOffsetNid(232);
		deviceField11113.setLabelString("Start Time:");
		deviceField11113.setNumCols(4);
		deviceField11113.setIdentifier("");
		deviceChoice1.setChoiceIntValues(new int[]
		{ 1, 2, 3, 4, 5, 6, 7, 8, 9 });
		deviceChoice1.setChoiceFloatValues(null);
		deviceChoice1.setConvert(true);
		deviceChoice1.setOffsetNid(233);
		deviceChoice1.setLabelString("Pert. Form: ");
		deviceChoice1.setChoiceItems(new String[]
		{ "COSINE", "TRIANGLE", "SQUARE", "SAWTOOTH RIGHT", "SAWTOOTH LEFT", "SAWTOOTH RIGHT UP", "SAWTOOTH LEFT UP",
				"SAWTOOTH RIGHT DOWN", "SAWTOOTH LEFT DOWN" });
		deviceChoice1.setUpdateIdentifier("");
		deviceChoice1.setIdentifier("");
		this.getContentPane().add(jPanel1, BorderLayout.NORTH);
		jPanel1.add(deviceField1, null);
		jPanel1.add(deviceField30, null);
		jPanel1.add(deviceChoice1, null);
		this.getContentPane().add(deviceButtons1, BorderLayout.SOUTH);
		this.getContentPane().add(jTabbedPane1, BorderLayout.CENTER);
		jTabbedPane1.add(deviceChannel1, "1");
		deviceChannel1.add(jPanel2, BorderLayout.CENTER);
		jPanel2.add(jPanel20, BorderLayout.NORTH);
		jPanel20.add(deviceField32, null);
		jPanel2.add(jPanel4, BorderLayout.SOUTH);
		jPanel3.add(jLabel1, null);
		jPanel3.add(deviceField4, null);
		jPanel3.add(deviceField20, null);
		jPanel3.add(deviceField3, null);
		jPanel3.add(deviceField2, null);
		jPanel4.add(deviceWave2, BorderLayout.NORTH);
		jPanel4.add(jPanel3, BorderLayout.SOUTH);
		jPanel2.add(jPanel5, BorderLayout.CENTER);
		jPanel5.add(deviceWaveDisplay1, BorderLayout.EAST);
		jPanel5.add(deviceWave1, BorderLayout.WEST);
		jTabbedPane1.add(deviceChannel2, "2");
		deviceChannel2.add(jPanel8, BorderLayout.CENTER);
		jPanel8.add(jPanel21, BorderLayout.NORTH);
		jPanel21.add(deviceField33, null);
		jPanel8.add(jPanel6, BorderLayout.SOUTH);
		jPanel6.add(deviceWave3, BorderLayout.NORTH);
		jPanel6.add(jPanel7, BorderLayout.SOUTH);
		jPanel7.add(jLabel2, null);
		jPanel7.add(deviceField6, null);
		jPanel7.add(deviceField21, null);
		jPanel7.add(deviceField5, null);
		jPanel7.add(deviceField7, null);
		jPanel8.add(jPanel9, BorderLayout.CENTER);
		jPanel9.add(deviceWaveDisplay2, BorderLayout.EAST);
		jPanel9.add(deviceWave4, BorderLayout.WEST);
		jTabbedPane1.add(deviceChannel3, "3");
		deviceChannel3.add(jPanel12, BorderLayout.CENTER);
		jPanel12.add(jPanel22, BorderLayout.NORTH);
		jPanel22.add(deviceField34, null);
		jPanel12.add(jPanel10, BorderLayout.SOUTH);
		jPanel10.add(deviceWave5, BorderLayout.NORTH);
		jPanel10.add(jPanel11, BorderLayout.SOUTH);
		jPanel11.add(jLabel3, null);
		jPanel11.add(deviceField9, null);
		jPanel11.add(deviceField22, null);
		jPanel11.add(deviceField8, null);
		jPanel11.add(deviceField10, null);
		jPanel12.add(jPanel13, BorderLayout.CENTER);
		jPanel13.add(deviceWaveDisplay3, BorderLayout.EAST);
		jPanel13.add(deviceWave6, BorderLayout.WEST);
		jTabbedPane1.add(deviceChannel4, "4");
		deviceChannel4.add(jPanel16, BorderLayout.CENTER);
		jPanel16.add(jPanel23, BorderLayout.NORTH);
		jPanel23.add(deviceField35, null);
		jPanel16.add(jPanel14, BorderLayout.SOUTH);
		jPanel14.add(deviceWave7, BorderLayout.NORTH);
		jPanel14.add(jPanel15, BorderLayout.SOUTH);
		jPanel15.add(jLabel4, null);
		jPanel15.add(deviceField12, null);
		jPanel15.add(deviceField23, null);
		jPanel15.add(deviceField11, null);
		jPanel15.add(deviceField13, null);
		jPanel16.add(jPanel17, BorderLayout.CENTER);
		jPanel17.add(deviceWaveDisplay4, BorderLayout.EAST);
		jPanel17.add(deviceWave8, BorderLayout.WEST);
		jTabbedPane1.add(deviceChannel5, "5");
		deviceChannel5.add(jPanel110, BorderLayout.CENTER);
		jPanel110.add(jPanel24, BorderLayout.NORTH);
		jPanel24.add(deviceField36, null);
		jPanel110.add(jPanel18, BorderLayout.SOUTH);
		jPanel18.add(deviceWave9, BorderLayout.NORTH);
		jPanel18.add(jPanel19, BorderLayout.SOUTH);
		jPanel19.add(jLabel5, null);
		jPanel19.add(deviceField15, null);
		jPanel19.add(deviceField24, null);
		jPanel19.add(deviceField14, null);
		jPanel19.add(deviceField16, null);
		jPanel110.add(jPanel111, BorderLayout.CENTER);
		jPanel111.add(deviceWaveDisplay5, BorderLayout.EAST);
		jPanel111.add(deviceWave10, BorderLayout.WEST);
		jTabbedPane1.add(deviceChannel6, "6");
		deviceChannel6.add(jPanel114, BorderLayout.CENTER);
		jPanel114.add(jPanel25, BorderLayout.NORTH);
		jPanel25.add(deviceField37, null);
		jPanel114.add(jPanel112, BorderLayout.SOUTH);
		jPanel112.add(deviceWave11, BorderLayout.NORTH);
		jPanel112.add(jPanel113, BorderLayout.SOUTH);
		jPanel113.add(jLabel6, null);
		jPanel113.add(deviceField18, null);
		jPanel113.add(deviceField25, null);
		jPanel113.add(deviceField17, null);
		jPanel113.add(deviceField19, null);
		jPanel114.add(jPanel115, BorderLayout.CENTER);
		jPanel115.add(deviceWaveDisplay6, BorderLayout.EAST);
		jPanel115.add(deviceWave12, BorderLayout.WEST);
		jTabbedPane1.add(deviceChannel7, "7");
		deviceChannel7.add(jPanel118, BorderLayout.CENTER);
		jPanel118.add(jPanel26, BorderLayout.NORTH);
		jPanel26.add(deviceField38, null);
		jPanel118.add(jPanel116, BorderLayout.SOUTH);
		jPanel116.add(deviceWave13, BorderLayout.NORTH);
		jPanel116.add(jPanel117, BorderLayout.SOUTH);
		jPanel117.add(jLabel7, null);
		jPanel117.add(deviceField111, null);
		jPanel117.add(deviceField26, null);
		jPanel117.add(deviceField110, null);
		jPanel117.add(deviceField112, null);
		jPanel118.add(jPanel119, BorderLayout.CENTER);
		jPanel119.add(deviceWaveDisplay7, BorderLayout.EAST);
		jPanel119.add(deviceWave14, BorderLayout.WEST);
		jTabbedPane1.add(deviceChannel8, "8");
		deviceChannel8.add(jPanel1112, BorderLayout.CENTER);
		jPanel1112.add(jPanel27, BorderLayout.NORTH);
		jPanel27.add(deviceField39, null);
		jPanel1112.add(jPanel1110, BorderLayout.SOUTH);
		jPanel1110.add(deviceWave15, BorderLayout.NORTH);
		jPanel1110.add(jPanel1111, BorderLayout.SOUTH);
		jPanel1111.add(jLabel8, null);
		jPanel1111.add(deviceField114, null);
		jPanel1111.add(deviceField27, null);
		jPanel1111.add(deviceField113, null);
		jPanel1111.add(deviceField115, null);
		jPanel1112.add(jPanel1113, BorderLayout.CENTER);
		jPanel1113.add(deviceWaveDisplay8, BorderLayout.EAST);
		jPanel1113.add(deviceWave16, BorderLayout.WEST);
		jTabbedPane1.add(deviceChannel9, "9");
		deviceChannel9.add(jPanel1116, BorderLayout.CENTER);
		jPanel1116.add(jPanel28, BorderLayout.NORTH);
		jPanel28.add(deviceField310, null);
		jPanel1116.add(jPanel1114, BorderLayout.SOUTH);
		jPanel1114.add(deviceWave17, BorderLayout.NORTH);
		jPanel1114.add(jPanel1115, BorderLayout.SOUTH);
		jPanel1115.add(jLabel9, null);
		jPanel1115.add(deviceField117, null);
		jPanel1115.add(deviceField28, null);
		jPanel1115.add(deviceField116, null);
		jPanel1115.add(deviceField118, null);
		jPanel1116.add(jPanel1117, BorderLayout.CENTER);
		jPanel1117.add(deviceWaveDisplay9, BorderLayout.EAST);
		jPanel1117.add(deviceWave18, BorderLayout.WEST);
		jTabbedPane1.add(deviceChannel10, "10");
		deviceChannel10.add(jPanel11110, BorderLayout.CENTER);
		jPanel11110.add(jPanel29, BorderLayout.NORTH);
		jPanel29.add(deviceField311, null);
		jPanel11110.add(jPanel1118, BorderLayout.SOUTH);
		jPanel1118.add(deviceWave19, BorderLayout.NORTH);
		jPanel1118.add(jPanel1119, BorderLayout.SOUTH);
		jPanel1119.add(jLabel10, null);
		jPanel1119.add(deviceField1110, null);
		jPanel1119.add(deviceField29, null);
		jPanel1119.add(deviceField119, null);
		jPanel1119.add(deviceField1111, null);
		jPanel11110.add(jPanel11111, BorderLayout.CENTER);
		jPanel11111.add(deviceWaveDisplay10, BorderLayout.EAST);
		jPanel11111.add(deviceWave110, BorderLayout.WEST);
		jTabbedPane1.add(deviceChannel13, "11");
		deviceChannel13.add(jPanel111112, BorderLayout.CENTER);
		jPanel111112.add(jPanel212, BorderLayout.NORTH);
		jPanel212.add(deviceField314, null);
		jPanel111112.add(jPanel111110, BorderLayout.SOUTH);
		jPanel111110.add(deviceWave115, BorderLayout.NORTH);
		jPanel111110.add(jPanel111111, BorderLayout.SOUTH);
		jPanel111111.add(jLabel13, null);
		jPanel111111.add(deviceField1119, null);
		jPanel111111.add(deviceField212, null);
		jPanel111111.add(deviceField1118, null);
		jPanel111111.add(deviceField11110, null);
		jPanel111112.add(jPanel111113, BorderLayout.CENTER);
		jPanel111113.add(deviceWaveDisplay13, BorderLayout.EAST);
		jPanel111113.add(deviceWave116, BorderLayout.WEST);
		jTabbedPane1.add(deviceChannel14, "12");
		deviceChannel14.add(jPanel111116, BorderLayout.CENTER);
		jPanel111116.add(jPanel213, BorderLayout.NORTH);
		jPanel213.add(deviceField315, null);
		jPanel111116.add(jPanel111114, BorderLayout.SOUTH);
		jPanel111114.add(deviceWave117, BorderLayout.NORTH);
		jPanel111114.add(jPanel111115, BorderLayout.SOUTH);
		jPanel111115.add(jLabel14, null);
		jPanel111115.add(deviceField11112, null);
		jPanel111115.add(deviceField213, null);
		jPanel111115.add(deviceField11111, null);
		jPanel111115.add(deviceField11113, null);
		jPanel111116.add(jPanel111117, BorderLayout.CENTER);
		jPanel111117.add(deviceWaveDisplay14, BorderLayout.EAST);
		jPanel111117.add(deviceWave118, BorderLayout.WEST);
	}
}
