
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SPIDERSetup.java
 *
 * Created on Feb 2, 2012, 2:19:27 PM
 */

/**
 *
 * @author manduchi
 */
public class SPIDER_SETUPSetup extends DeviceSetup {

    /** Creates new form SPIDERSetup */
    public SPIDER_SETUPSetup() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        deviceButtons1 = new DeviceButtons();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel27 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        deviceField18 = new DeviceField();
        jPanel30 = new javax.swing.JPanel();
        deviceField19 = new DeviceField();
        deviceField20 = new DeviceField();
        deviceField23 = new DeviceField();
        jPanel29 = new javax.swing.JPanel();
        deviceField13 = new DeviceField();
        deviceField17 = new DeviceField();
        jPanel47 = new javax.swing.JPanel();
        deviceField28 = new DeviceField();
        jPanel17 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        deviceChoice1 = new DeviceChoice();
        deviceField1 = new DeviceField();
        deviceField2 = new DeviceField();
        jPanel33 = new javax.swing.JPanel();
        jPanel53 = new javax.swing.JPanel();
        deviceChoice2 = new DeviceChoice();
        deviceField3 = new DeviceField();
        deviceField6 = new DeviceField();
        jPanel54 = new javax.swing.JPanel();
        deviceField29 = new DeviceField();
        deviceChoice10 = new DeviceChoice();
        jPanel52 = new javax.swing.JPanel();
        deviceField42 = new DeviceField();
        deviceField43 = new DeviceField();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel37 = new javax.swing.JPanel();
        deviceField10 = new DeviceField();
        deviceField11 = new DeviceField();
        jPanel25 = new javax.swing.JPanel();
        jPanel36 = new javax.swing.JPanel();
        deviceChoice4 = new DeviceChoice();
        jPanel35 = new javax.swing.JPanel();
        deviceChoice7 = new DeviceChoice();
        deviceChoice8 = new DeviceChoice();
        jPanel26 = new javax.swing.JPanel();
        deviceChoice5 = new DeviceChoice();
        deviceChoice6 = new DeviceChoice();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        deviceWave1 = new DeviceWave();
        jPanel8 = new javax.swing.JPanel();
        deviceWave2 = new DeviceWave();
        jPanel9 = new javax.swing.JPanel();
        deviceWave3 = new DeviceWave();
        jPanel13 = new javax.swing.JPanel();
        deviceWave6 = new DeviceWave();
        jPanel56 = new javax.swing.JPanel();
        deviceWave14 = new DeviceWave();
        jTabbedPane7 = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        deviceWave4 = new DeviceWave();
        jPanel14 = new javax.swing.JPanel();
        deviceWave7 = new DeviceWave();
        jPanel48 = new javax.swing.JPanel();
        deviceWave22 = new DeviceWave();
        jTabbedPane8 = new javax.swing.JTabbedPane();
        jPanel15 = new javax.swing.JPanel();
        deviceWave8 = new DeviceWave();
        jPanel16 = new javax.swing.JPanel();
        deviceWave9 = new DeviceWave();
        jPanel49 = new javax.swing.JPanel();
        deviceWave23 = new DeviceWave();
        jTabbedPane9 = new javax.swing.JTabbedPane();
        jPanel50 = new javax.swing.JPanel();
        deviceWave24 = new DeviceWave();
        jPanel64 = new javax.swing.JPanel();
        deviceWave25 = new DeviceWave();
        jPanel65 = new javax.swing.JPanel();
        deviceWave26 = new DeviceWave();
        jTabbedPane10 = new javax.swing.JTabbedPane();
        jPanel66 = new javax.swing.JPanel();
        deviceWave27 = new DeviceWave();
        jPanel67 = new javax.swing.JPanel();
        deviceWave28 = new DeviceWave();
        jPanel68 = new javax.swing.JPanel();
        deviceWave29 = new DeviceWave();
        jPanel12 = new javax.swing.JPanel();
        deviceWave5 = new DeviceWave();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        deviceField4 = new DeviceField();
        deviceField5 = new DeviceField();
        jPanel5 = new javax.swing.JPanel();
        deviceField7 = new DeviceField();
        deviceField8 = new DeviceField();
        deviceField9 = new DeviceField();
        jPanel11 = new javax.swing.JPanel();
        deviceField14 = new DeviceField();
        deviceField15 = new DeviceField();
        deviceField16 = new DeviceField();
        jPanel38 = new javax.swing.JPanel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel39 = new javax.swing.JPanel();
        jPanel40 = new javax.swing.JPanel();
        deviceChoice9 = new DeviceChoice();
        deviceField24 = new DeviceField();
        deviceField25 = new DeviceField();
        jPanel44 = new javax.swing.JPanel();
        jPanel45 = new javax.swing.JPanel();
        jPanel46 = new javax.swing.JPanel();
        deviceField30 = new DeviceField();
        deviceField31 = new DeviceField();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        jPanel51 = new javax.swing.JPanel();
        deviceWave13 = new DeviceWave();
        jPanel59 = new javax.swing.JPanel();
        deviceWave21 = new DeviceWave();
        jPanel60 = new javax.swing.JPanel();
        jPanel61 = new javax.swing.JPanel();
        deviceField32 = new DeviceField();
        deviceField33 = new DeviceField();
        jPanel62 = new javax.swing.JPanel();
        deviceField34 = new DeviceField();
        deviceField35 = new DeviceField();
        deviceField36 = new DeviceField();
        jPanel63 = new javax.swing.JPanel();
        deviceField37 = new DeviceField();
        deviceField38 = new DeviceField();
        deviceField39 = new DeviceField();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel41 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        deviceField12 = new DeviceField();
        jPanel43 = new javax.swing.JPanel();
        jPanel42 = new javax.swing.JPanel();
        deviceField40 = new DeviceField();
        jPanel55 = new javax.swing.JPanel();
        deviceField26 = new DeviceField();
        jLabel1 = new javax.swing.JLabel();
        deviceField27 = new DeviceField();
        jLabel2 = new javax.swing.JLabel();
        deviceChoice11 = new DeviceChoice();
        deviceChoice12 = new DeviceChoice();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel21 = new javax.swing.JPanel();
        deviceWave10 = new DeviceWave();
        jPanel22 = new javax.swing.JPanel();
        deviceWave11 = new DeviceWave();
        jPanel23 = new javax.swing.JPanel();
        deviceWave12 = new DeviceWave();
        jPanel24 = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        jPanel57 = new javax.swing.JPanel();
        jPanel84 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel85 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel58 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel69 = new javax.swing.JPanel();
        deviceField21 = new DeviceField();
        deviceField22 = new DeviceField();
        deviceField41 = new DeviceField();
        deviceField44 = new DeviceField();
        jPanel70 = new javax.swing.JPanel();
        deviceField45 = new DeviceField();
        deviceField46 = new DeviceField();
        deviceField47 = new DeviceField();
        deviceField48 = new DeviceField();
        jPanel71 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel72 = new javax.swing.JPanel();
        deviceField49 = new DeviceField();
        deviceField50 = new DeviceField();
        jLabel14 = new javax.swing.JLabel();
        deviceField51 = new DeviceField();
        deviceField52 = new DeviceField();
        jPanel73 = new javax.swing.JPanel();
        deviceField53 = new DeviceField();
        deviceField54 = new DeviceField();
        jLabel15 = new javax.swing.JLabel();
        deviceField55 = new DeviceField();
        deviceField56 = new DeviceField();
        jPanel74 = new javax.swing.JPanel();
        jPanel82 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel83 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel75 = new javax.swing.JPanel();
        deviceField57 = new DeviceField();
        deviceField58 = new DeviceField();
        jLabel18 = new javax.swing.JLabel();
        deviceField59 = new DeviceField();
        deviceField60 = new DeviceField();
        jPanel76 = new javax.swing.JPanel();
        deviceField61 = new DeviceField();
        deviceField62 = new DeviceField();
        jLabel24 = new javax.swing.JLabel();
        deviceField63 = new DeviceField();
        deviceField64 = new DeviceField();
        jPanel77 = new javax.swing.JPanel();
        deviceField65 = new DeviceField();
        deviceField66 = new DeviceField();
        jLabel20 = new javax.swing.JLabel();
        deviceField67 = new DeviceField();
        deviceField68 = new DeviceField();
        jPanel78 = new javax.swing.JPanel();
        deviceField69 = new DeviceField();
        deviceField70 = new DeviceField();
        jLabel21 = new javax.swing.JLabel();
        deviceField71 = new DeviceField();
        deviceField72 = new DeviceField();
        jPanel79 = new javax.swing.JPanel();
        jPanel80 = new javax.swing.JPanel();
        deviceField73 = new DeviceField();
        deviceField74 = new DeviceField();
        jLabel22 = new javax.swing.JLabel();
        deviceField75 = new DeviceField();
        deviceField76 = new DeviceField();
        jPanel81 = new javax.swing.JPanel();
        deviceField77 = new DeviceField();
        deviceField78 = new DeviceField();
        jLabel23 = new javax.swing.JLabel();
        deviceField79 = new DeviceField();
        deviceField80 = new DeviceField();

        setDeviceProvider("soserver.nbtf:9000");
        setDeviceTitle("SPIDER Experiment Setup");
        setDeviceType("SPIDER_SETUP");
        setHeight(650);
        setWidth(1000);

        deviceButtons1.setCheckExpressions(new String[] {});
        deviceButtons1.setCheckMessages(new String[] {});
        getContentPane().add(deviceButtons1, java.awt.BorderLayout.PAGE_END);

        jTabbedPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTabbedPane1FocusLost(evt);
            }
        });

        jPanel27.setLayout(new java.awt.BorderLayout());

        jPanel28.setLayout(new java.awt.GridLayout(4, 1));

        jPanel31.setBorder(javax.swing.BorderFactory.createTitledBorder("Times"));

        deviceField18.setIdentifier("");
        deviceField18.setLabelString("T_START_SPIDER: ");
        deviceField18.setNumCols(30);
        deviceField18.setOffsetNid(119);
        jPanel31.add(deviceField18);

        jPanel28.add(jPanel31);

        jPanel30.setBorder(javax.swing.BorderFactory.createTitledBorder("ISEPS EG and RF, AGPS AG  Enable  time Limit"));

        deviceField19.setIdentifier("");
        deviceField19.setLabelString("Start Time: ");
        deviceField19.setNumCols(18);
        deviceField19.setOffsetNid(120);
        jPanel30.add(deviceField19);

        deviceField20.setIdentifier("");
        deviceField20.setLabelString("End Time:");
        deviceField20.setNumCols(18);
        deviceField20.setOffsetNid(121);
        jPanel30.add(deviceField20);

        deviceField23.setIdentifier("");
        deviceField23.setLabelString("Frequency:");
        deviceField23.setNumCols(18);
        deviceField23.setOffsetNid(133);
        jPanel30.add(deviceField23);

        jPanel28.add(jPanel30);

        jPanel29.setBorder(javax.swing.BorderFactory.createTitledBorder("Reference Waveform Time Limit"));
        jPanel29.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPanel29FocusLost(evt);
            }
        });

        deviceField13.setIdentifier("");
        deviceField13.setLabelString("Start Time: ");
        deviceField13.setNumCols(30);
        deviceField13.setOffsetNid(122);
        deviceField13.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                deviceField13FocusLost(evt);
            }
        });
        jPanel29.add(deviceField13);

        deviceField17.setIdentifier("");
        deviceField17.setLabelString("End Time: ");
        deviceField17.setNumCols(30);
        deviceField17.setOffsetNid(123);
        deviceField17.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                deviceField17FocusLost(evt);
            }
        });
        deviceField17.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                deviceField17PropertyChange(evt);
            }
        });
        jPanel29.add(deviceField17);

        jPanel28.add(jPanel29);

        jPanel47.setBorder(javax.swing.BorderFactory.createTitledBorder("Time Of Interest"));
        jPanel47.setLayout(new java.awt.BorderLayout());

        deviceField28.setIdentifier("");
        deviceField28.setNumCols(80);
        deviceField28.setOffsetNid(211);
        jPanel47.add(deviceField28, java.awt.BorderLayout.CENTER);

        jPanel28.add(jPanel47);

        jPanel27.add(jPanel28, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("SPIDER", jPanel27);

        jPanel17.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.GridLayout(3, 0));

        jPanel32.setBorder(javax.swing.BorderFactory.createTitledBorder("EG Modulation"));

        deviceChoice1.setChoiceItems(new String[] {"DISABLED", "ENABLED"});
        deviceChoice1.setIdentifier("");
        deviceChoice1.setLabelString("State:");
        deviceChoice1.setOffsetNid(124);
        deviceChoice1.setUpdateIdentifier("");
        jPanel32.add(deviceChoice1);

        deviceField1.setIdentifier("");
        deviceField1.setLabelString("Frequency:");
        deviceField1.setOffsetNid(125);
        jPanel32.add(deviceField1);

        deviceField2.setIdentifier("");
        deviceField2.setLabelString("Duty Cycle:");
        deviceField2.setOffsetNid(126);
        jPanel32.add(deviceField2);

        jPanel3.add(jPanel32);

        jPanel33.setBorder(javax.swing.BorderFactory.createTitledBorder("RF"));
        jPanel33.setLayout(new java.awt.GridLayout(2, 0));

        deviceChoice2.setChoiceItems(new String[] {"DISABLED", "ENABLED"});
        deviceChoice2.setIdentifier("");
        deviceChoice2.setLabelString("RF Modulation State:");
        deviceChoice2.setOffsetNid(127);
        deviceChoice2.setUpdateIdentifier("");
        jPanel53.add(deviceChoice2);

        deviceField3.setIdentifier("");
        deviceField3.setLabelString("Mod. Frequency:");
        deviceField3.setOffsetNid(128);
        jPanel53.add(deviceField3);

        deviceField6.setIdentifier("");
        deviceField6.setLabelString("Mod. Duty Cycle:");
        deviceField6.setOffsetNid(129);
        jPanel53.add(deviceField6);

        jPanel33.add(jPanel53);

        deviceField29.setIdentifier("isrf_te_v");
        deviceField29.setLabelString("ISRF TE V:");
        deviceField29.setOffsetNid(323);
        jPanel54.add(deviceField29);

        deviceChoice10.setChoiceItems(new String[] {"None", "Frequency"});
        deviceChoice10.setIdentifier("");
        deviceChoice10.setLabelString("RF Control Mode:");
        deviceChoice10.setOffsetNid(324);
        deviceChoice10.setUpdateIdentifier("");
        jPanel54.add(deviceChoice10);

        jPanel33.add(jPanel54);

        jPanel3.add(jPanel33);

        jPanel52.setBorder(javax.swing.BorderFactory.createTitledBorder("Core Snubber"));

        deviceField42.setIdentifier("");
        deviceField42.setLabelString("CS1 Ref. I:");
        deviceField42.setOffsetNid(326);
        jPanel52.add(deviceField42);

        deviceField43.setIdentifier("");
        deviceField43.setLabelString("CS2 Ref. I:");
        deviceField43.setOffsetNid(327);
        jPanel52.add(deviceField43);

        jPanel3.add(jPanel52);

        jTabbedPane3.addTab("Setup", jPanel3);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel6.setLayout(new java.awt.GridLayout(2, 0));

        jPanel37.setBorder(javax.swing.BorderFactory.createTitledBorder("Breakdown Management"));

        deviceField10.setIdentifier("");
        deviceField10.setLabelString("Dead time Time: ");
        deviceField10.setNumCols(20);
        deviceField10.setOffsetNid(12);
        jPanel37.add(deviceField10);

        deviceField11.setIdentifier("");
        deviceField11.setLabelString("Recover time: ");
        deviceField11.setNumCols(20);
        deviceField11.setOffsetNid(13);
        jPanel37.add(deviceField11);

        jPanel6.add(jPanel37);

        jPanel25.setBorder(javax.swing.BorderFactory.createTitledBorder("ISSS Power Supply"));
        jPanel25.setLayout(new java.awt.GridLayout(1, 5));

        jPanel36.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 5);
        flowLayout1.setAlignOnBaseline(true);
        jPanel36.setLayout(flowLayout1);

        deviceChoice4.setChoiceItems(new String[] {"ENABLED", "DISABLED"});
        deviceChoice4.setIdentifier("");
        deviceChoice4.setLabelString("Plasma Grid:");
        deviceChoice4.setOffsetNid(134);
        deviceChoice4.setUpdateIdentifier("");
        jPanel36.add(deviceChoice4);

        jPanel25.add(jPanel36);

        jPanel35.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel35.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 5));

        deviceChoice7.setChoiceItems(new String[] {"ENABLED", "DISABLED"});
        deviceChoice7.setIdentifier("");
        deviceChoice7.setLabelString("Bias:");
        deviceChoice7.setOffsetNid(135);
        deviceChoice7.setUpdateIdentifier("");
        jPanel35.add(deviceChoice7);

        deviceChoice8.setChoiceItems(new String[] {"VOLTAGE", "CURRENT"});
        deviceChoice8.setIdentifier("bi_control");
        deviceChoice8.setLabelString("Control:");
        deviceChoice8.setOffsetNid(136);
        deviceChoice8.setUpdateIdentifier("");
        jPanel35.add(deviceChoice8);

        jPanel25.add(jPanel35);

        jPanel26.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel26.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 5));

        deviceChoice5.setChoiceItems(new String[] {"ENABLED", "DISABLED"});
        deviceChoice5.setIdentifier("");
        deviceChoice5.setLabelString("Bias Plate:");
        deviceChoice5.setOffsetNid(137);
        deviceChoice5.setUpdateIdentifier("");
        jPanel26.add(deviceChoice5);

        deviceChoice6.setChoiceItems(new String[] {"VOLTAGE", "CURRENT"});
        deviceChoice6.setIdentifier("bp_control");
        deviceChoice6.setLabelString("Control:");
        deviceChoice6.setOffsetNid(138);
        deviceChoice6.setUpdateIdentifier("");
        jPanel26.add(deviceChoice6);

        jPanel25.add(jPanel26);

        jPanel6.add(jPanel25);

        jPanel2.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        jPanel7.setLayout(new java.awt.BorderLayout());

        deviceWave1.setIdentifier("");
        deviceWave1.setOffsetNid(15);
        deviceWave1.setUpdateExpression("");
        jPanel7.add(deviceWave1, java.awt.BorderLayout.CENTER);

        jTabbedPane2.addTab("Bias Plate I / V  [A]/[V] ", jPanel7);

        jPanel8.setLayout(new java.awt.BorderLayout());

        deviceWave2.setIdentifier("");
        deviceWave2.setMaxYVisible(false);
        deviceWave2.setMinYVisible(true);
        deviceWave2.setOffsetNid(21);
        deviceWave2.setUpdateExpression("");
        jPanel8.add(deviceWave2, java.awt.BorderLayout.CENTER);

        jTabbedPane2.addTab("Extraction Grid [V]", jPanel8);

        jPanel9.setLayout(new java.awt.BorderLayout());

        deviceWave3.setIdentifier("");
        deviceWave3.setOffsetNid(27);
        deviceWave3.setUpdateExpression("");
        jPanel9.add(deviceWave3, java.awt.BorderLayout.CENTER);

        jTabbedPane2.addTab("Plasma Grid [A]", jPanel9);

        jPanel13.setLayout(new java.awt.BorderLayout());

        deviceWave6.setIdentifier("");
        deviceWave6.setOffsetNid(33);
        deviceWave6.setUpdateExpression("");
        jPanel13.add(deviceWave6, java.awt.BorderLayout.CENTER);

        jTabbedPane2.addTab("Bias I/V [A]/[V]", jPanel13);

        jPanel56.setLayout(new java.awt.BorderLayout());

        deviceWave14.setIdentifier("");
        deviceWave14.setOffsetNid(269);
        deviceWave14.setUpdateExpression("");
        jPanel56.add(deviceWave14, java.awt.BorderLayout.CENTER);

        jTabbedPane2.addTab("Filament Bias [V] ", jPanel56);

        jPanel10.setLayout(new java.awt.BorderLayout());

        deviceWave4.setIdentifier("rf1_power");
        deviceWave4.setOffsetNid(39);
        deviceWave4.setUpdateExpression("");
        jPanel10.add(deviceWave4, java.awt.BorderLayout.CENTER);

        jTabbedPane7.addTab("RF1 Power [W]", jPanel10);

        jPanel14.setLayout(new java.awt.BorderLayout());

        deviceWave7.setIdentifier("");
        deviceWave7.setOffsetNid(45);
        deviceWave7.setUpdateExpression("");
        jPanel14.add(deviceWave7, java.awt.BorderLayout.CENTER);

        jTabbedPane7.addTab("RF1 Frequeny [Hz]", jPanel14);

        jPanel48.setLayout(new java.awt.BorderLayout());

        deviceWave22.setIdentifier("");
        deviceWave22.setOffsetNid(51);
        deviceWave22.setUpdateExpression("");
        jPanel48.add(deviceWave22, java.awt.BorderLayout.CENTER);

        jTabbedPane7.addTab("RF1 Capacitance [pF]", jPanel48);

        jTabbedPane2.addTab("RF1 Setup", jTabbedPane7);

        jPanel15.setLayout(new java.awt.BorderLayout());

        deviceWave8.setIdentifier("rf2_power");
        deviceWave8.setOffsetNid(57);
        deviceWave8.setUpdateExpression("");
        jPanel15.add(deviceWave8, java.awt.BorderLayout.CENTER);

        jTabbedPane8.addTab("RF2 Power [W]", jPanel15);

        jPanel16.setLayout(new java.awt.BorderLayout());

        deviceWave9.setIdentifier("");
        deviceWave9.setOffsetNid(213);
        deviceWave9.setUpdateExpression("");
        jPanel16.add(deviceWave9, java.awt.BorderLayout.CENTER);

        jTabbedPane8.addTab("RF2 Frequeny [Hz]", jPanel16);

        jPanel49.setLayout(new java.awt.BorderLayout());

        deviceWave23.setIdentifier("");
        deviceWave23.setOffsetNid(220);
        deviceWave23.setUpdateExpression("");
        jPanel49.add(deviceWave23, java.awt.BorderLayout.CENTER);

        jTabbedPane8.addTab("RF2 Capacitance [pF]", jPanel49);

        jTabbedPane2.addTab("RF2 Setup", jTabbedPane8);

        jPanel50.setLayout(new java.awt.BorderLayout());

        deviceWave24.setIdentifier("rf3_power");
        deviceWave24.setOffsetNid(227);
        deviceWave24.setUpdateExpression("");
        jPanel50.add(deviceWave24, java.awt.BorderLayout.CENTER);

        jTabbedPane9.addTab("RF3 Power [W]", jPanel50);

        jPanel64.setLayout(new java.awt.BorderLayout());

        deviceWave25.setIdentifier("");
        deviceWave25.setOffsetNid(234);
        deviceWave25.setUpdateExpression("");
        jPanel64.add(deviceWave25, java.awt.BorderLayout.CENTER);

        jTabbedPane9.addTab("RF3 Frequeny [Hz]", jPanel64);

        jPanel65.setLayout(new java.awt.BorderLayout());

        deviceWave26.setIdentifier("");
        deviceWave26.setOffsetNid(241);
        deviceWave26.setUpdateExpression("");
        jPanel65.add(deviceWave26, java.awt.BorderLayout.CENTER);

        jTabbedPane9.addTab("RF3 Capacitance [pF]", jPanel65);

        jTabbedPane2.addTab("RF3 Setup", jTabbedPane9);

        jPanel66.setLayout(new java.awt.BorderLayout());

        deviceWave27.setIdentifier("rf4_power");
        deviceWave27.setOffsetNid(248);
        deviceWave27.setUpdateExpression("");
        jPanel66.add(deviceWave27, java.awt.BorderLayout.CENTER);

        jTabbedPane10.addTab("RF4 Power [W]", jPanel66);

        jPanel67.setLayout(new java.awt.BorderLayout());

        deviceWave28.setIdentifier("");
        deviceWave28.setOffsetNid(255);
        deviceWave28.setUpdateExpression("");
        jPanel67.add(deviceWave28, java.awt.BorderLayout.CENTER);

        jTabbedPane10.addTab("RF4 Frequeny [Hz]", jPanel67);

        jPanel68.setLayout(new java.awt.BorderLayout());

        deviceWave29.setIdentifier("");
        deviceWave29.setOffsetNid(262);
        deviceWave29.setUpdateExpression("");
        jPanel68.add(deviceWave29, java.awt.BorderLayout.CENTER);

        jTabbedPane10.addTab("RF4 Capacitance [pF]", jPanel68);

        jTabbedPane2.addTab("RF4 Setup", jTabbedPane10);

        jPanel12.setLayout(new java.awt.BorderLayout());

        deviceWave5.setIdentifier("");
        deviceWave5.setOffsetNid(63);
        deviceWave5.setUpdateExpression("");
        jPanel12.add(deviceWave5, java.awt.BorderLayout.CENTER);

        jTabbedPane2.addTab("Recover Wave", jPanel12);

        jPanel2.add(jTabbedPane2, java.awt.BorderLayout.CENTER);

        jTabbedPane3.addTab("Waveforms", jPanel2);

        jPanel1.setLayout(new java.awt.GridLayout(4, 1));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("CAEN DT5720 Timing"));

        deviceField4.setIdentifier("");
        deviceField4.setLabelString("Start Time: ");
        deviceField4.setNumCols(20);
        deviceField4.setOffsetNid(4);
        jPanel4.add(deviceField4);

        deviceField5.setIdentifier("");
        deviceField5.setLabelString("Duration: ");
        deviceField5.setNumCols(20);
        deviceField5.setOffsetNid(5);
        jPanel4.add(deviceField5);

        jPanel1.add(jPanel4);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("NI 6259 Timing"));

        deviceField7.setIdentifier("");
        deviceField7.setLabelString("Start Time: ");
        deviceField7.setNumCols(20);
        deviceField7.setOffsetNid(7);
        jPanel5.add(deviceField7);

        deviceField8.setIdentifier("");
        deviceField8.setLabelString("Duration");
        deviceField8.setNumCols(20);
        deviceField8.setOffsetNid(8);
        jPanel5.add(deviceField8);

        deviceField9.setIdentifier("");
        deviceField9.setLabelString("Frequency: ");
        deviceField9.setNumCols(20);
        deviceField9.setOffsetNid(6);
        jPanel5.add(deviceField9);

        jPanel1.add(jPanel5);

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("NI 6368 Timing"));

        deviceField14.setIdentifier("");
        deviceField14.setLabelString("Start Time: ");
        deviceField14.setNumCols(20);
        deviceField14.setOffsetNid(10);
        jPanel11.add(deviceField14);

        deviceField15.setIdentifier("");
        deviceField15.setLabelString("Duration");
        deviceField15.setNumCols(20);
        deviceField15.setOffsetNid(11);
        jPanel11.add(deviceField15);

        deviceField16.setIdentifier("");
        deviceField16.setLabelString("Frequency: ");
        deviceField16.setNumCols(20);
        deviceField16.setOffsetNid(9);
        jPanel11.add(deviceField16);

        jPanel1.add(jPanel11);

        jTabbedPane3.addTab("Data Acquisition", jPanel1);

        jPanel17.add(jTabbedPane3, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("ISEPS ", jPanel17);

        jPanel38.setLayout(new java.awt.BorderLayout());

        jPanel39.setLayout(new java.awt.GridLayout(3, 0));

        jPanel40.setBorder(javax.swing.BorderFactory.createTitledBorder("AG  Modulation"));

        deviceChoice9.setChoiceItems(new String[] {"DISABLED", "ENABLED"});
        deviceChoice9.setIdentifier("");
        deviceChoice9.setLabelString("State:");
        deviceChoice9.setOffsetNid(152);
        deviceChoice9.setUpdateIdentifier("");
        jPanel40.add(deviceChoice9);

        deviceField24.setIdentifier("");
        deviceField24.setLabelString("Frequency:");
        deviceField24.setOffsetNid(153);
        jPanel40.add(deviceField24);

        deviceField25.setIdentifier("");
        deviceField25.setLabelString("Duty Cycle:");
        deviceField25.setOffsetNid(154);
        jPanel40.add(deviceField25);

        jPanel39.add(jPanel40);

        jTabbedPane5.addTab("Setup", jPanel39);

        jPanel44.setLayout(new java.awt.BorderLayout());

        jPanel45.setLayout(new java.awt.GridLayout(1, 0));

        jPanel46.setBorder(javax.swing.BorderFactory.createTitledBorder("Breakdown Management"));

        deviceField30.setIdentifier("");
        deviceField30.setLabelString("Dead time Time: ");
        deviceField30.setNumCols(20);
        deviceField30.setOffsetNid(150);
        jPanel46.add(deviceField30);

        deviceField31.setIdentifier("");
        deviceField31.setLabelString("Recover time: ");
        deviceField31.setNumCols(20);
        deviceField31.setOffsetNid(151);
        jPanel46.add(deviceField31);

        jPanel45.add(jPanel46);

        jPanel44.add(jPanel45, java.awt.BorderLayout.PAGE_START);

        jPanel51.setLayout(new java.awt.BorderLayout());

        deviceWave13.setIdentifier("");
        deviceWave13.setMaxYVisible(false);
        deviceWave13.setMinYVisible(true);
        deviceWave13.setOffsetNid(156);
        deviceWave13.setUpdateExpression("");
        jPanel51.add(deviceWave13, java.awt.BorderLayout.CENTER);

        jTabbedPane6.addTab("Acceleration Grid  [V]", jPanel51);

        jPanel59.setLayout(new java.awt.BorderLayout());

        deviceWave21.setIdentifier("");
        deviceWave21.setOffsetNid(204);
        deviceWave21.setUpdateExpression("");
        jPanel59.add(deviceWave21, java.awt.BorderLayout.CENTER);

        jTabbedPane6.addTab("Recover Wave", jPanel59);

        jPanel44.add(jTabbedPane6, java.awt.BorderLayout.CENTER);

        jTabbedPane5.addTab("Waveforms", jPanel44);

        jPanel60.setLayout(new java.awt.GridLayout(4, 1));

        jPanel61.setBorder(javax.swing.BorderFactory.createTitledBorder("CAEN DT5720 Timing"));

        deviceField32.setIdentifier("");
        deviceField32.setLabelString("Start Time: ");
        deviceField32.setNumCols(20);
        deviceField32.setOffsetNid(142);
        jPanel61.add(deviceField32);

        deviceField33.setIdentifier("");
        deviceField33.setLabelString("Duration: ");
        deviceField33.setNumCols(20);
        deviceField33.setOffsetNid(143);
        jPanel61.add(deviceField33);

        jPanel60.add(jPanel61);

        jPanel62.setBorder(javax.swing.BorderFactory.createTitledBorder("NI 6259 Timing"));

        deviceField34.setIdentifier("");
        deviceField34.setLabelString("Start Time: ");
        deviceField34.setNumCols(20);
        deviceField34.setOffsetNid(145);
        jPanel62.add(deviceField34);

        deviceField35.setIdentifier("");
        deviceField35.setLabelString("Duration");
        deviceField35.setNumCols(20);
        deviceField35.setOffsetNid(146);
        jPanel62.add(deviceField35);

        deviceField36.setIdentifier("");
        deviceField36.setLabelString("Frequency: ");
        deviceField36.setNumCols(20);
        deviceField36.setOffsetNid(144);
        jPanel62.add(deviceField36);

        jPanel60.add(jPanel62);

        jPanel63.setBorder(javax.swing.BorderFactory.createTitledBorder("NI 6368 Timing"));

        deviceField37.setIdentifier("");
        deviceField37.setLabelString("Start Time: ");
        deviceField37.setNumCols(20);
        deviceField37.setOffsetNid(148);
        jPanel63.add(deviceField37);

        deviceField38.setIdentifier("");
        deviceField38.setLabelString("Duration");
        deviceField38.setNumCols(20);
        deviceField38.setOffsetNid(149);
        jPanel63.add(deviceField38);

        deviceField39.setIdentifier("");
        deviceField39.setLabelString("Frequency: ");
        deviceField39.setNumCols(20);
        deviceField39.setOffsetNid(147);
        jPanel63.add(deviceField39);

        jPanel60.add(jPanel63);

        jTabbedPane5.addTab("Data Acquisition", jPanel60);

        jPanel38.add(jTabbedPane5, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("AGPS", jPanel38);

        jPanel18.setLayout(new java.awt.BorderLayout());

        jPanel19.setLayout(new java.awt.BorderLayout());

        jPanel41.setLayout(new java.awt.GridLayout(2, 0));

        jPanel20.setBorder(javax.swing.BorderFactory.createTitledBorder("Gas And Vacuum Timing"));

        deviceField12.setIdentifier("");
        deviceField12.setLabelString("Trigger Source: ");
        deviceField12.setNumCols(30);
        deviceField12.setOffsetNid(69);
        jPanel20.add(deviceField12);

        jPanel41.add(jPanel20);

        jPanel43.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 5));

        jPanel42.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        deviceField40.setIdentifier("");
        deviceField40.setLabelString("Pre Set Press. [barG]:");
        deviceField40.setNumCols(5);
        deviceField40.setOffsetNid(320);
        jPanel42.add(deviceField40);

        jPanel43.add(jPanel42);

        jPanel55.setBorder(javax.swing.BorderFactory.createTitledBorder("GVS Configuration"));

        deviceField26.setIdentifier("");
        deviceField26.setLabelString("VC3001 Turns:");
        deviceField26.setNumCols(5);
        deviceField26.setOffsetNid(209);
        jPanel55.add(deviceField26);

        jLabel1.setText("/25      ");
        jPanel55.add(jLabel1);

        deviceField27.setIdentifier("");
        deviceField27.setLabelString("VC3002 Turns: ");
        deviceField27.setNumCols(5);
        deviceField27.setOffsetNid(210);
        jPanel55.add(deviceField27);

        jLabel2.setText("/25   ");
        jLabel2.setToolTipText("");
        jPanel55.add(jLabel2);

        deviceChoice11.setChoiceItems(new String[] {"3000", "3090"});
        deviceChoice11.setIdentifier("");
        deviceChoice11.setLabelString("Tank");
        deviceChoice11.setOffsetNid(321);
        deviceChoice11.setUpdateIdentifier("");
        jPanel55.add(deviceChoice11);

        deviceChoice12.setChoiceItems(new String[] {"H2", "D2"});
        deviceChoice12.setIdentifier("");
        deviceChoice12.setLabelString("Gas Type:");
        deviceChoice12.setOffsetNid(322);
        deviceChoice12.setUpdateIdentifier("");
        jPanel55.add(deviceChoice12);

        jPanel43.add(jPanel55);

        jPanel41.add(jPanel43);

        jPanel19.add(jPanel41, java.awt.BorderLayout.NORTH);

        jPanel21.setLayout(new java.awt.BorderLayout());

        deviceWave10.setIdentifier("");
        deviceWave10.setOffsetNid(71);
        deviceWave10.setUpdateExpression("");
        jPanel21.add(deviceWave10, java.awt.BorderLayout.CENTER);

        jTabbedPane4.addTab("Pressure Modulation %", jPanel21);

        jPanel22.setLayout(new java.awt.BorderLayout());

        deviceWave11.setIdentifier("");
        deviceWave11.setMaxYVisible(false);
        deviceWave11.setOffsetNid(77);
        deviceWave11.setUpdateExpression("");
        jPanel22.add(deviceWave11, java.awt.BorderLayout.CENTER);

        jTabbedPane4.addTab("VG-3011 Open(1) / Close(0) ", jPanel22);

        jPanel23.setLayout(new java.awt.BorderLayout());

        deviceWave12.setIdentifier("");
        deviceWave12.setMaxYVisible(false);
        deviceWave12.setOffsetNid(83);
        deviceWave12.setUpdateExpression("");
        jPanel23.add(deviceWave12, java.awt.BorderLayout.CENTER);

        jTabbedPane4.addTab("VG-3012 Open(1) / Close(0) ", jPanel23);

        jPanel19.add(jTabbedPane4, java.awt.BorderLayout.CENTER);

        jPanel18.add(jPanel19, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("GVS", jPanel18);

        jPanel24.setLayout(new java.awt.BorderLayout());

        jPanel34.setLayout(new java.awt.GridLayout(15, 0, 0, -5));

        jPanel57.setLayout(new java.awt.GridLayout(1, 0, 0, 2));

        jPanel84.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("AGPS");
        jPanel84.add(jLabel3);

        jPanel57.add(jPanel84);

        jPanel85.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("GVS");
        jPanel85.add(jLabel4);

        jPanel57.add(jPanel85);

        jPanel34.add(jPanel57);

        java.awt.GridBagLayout jPanel58Layout = new java.awt.GridBagLayout();
        jPanel58Layout.columnWeights = new double[] {0.4, 0.2, 0.3, 0.2};
        jPanel58.setLayout(jPanel58Layout);

        jLabel6.setText("Session Limits");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel58.add(jLabel6, gridBagConstraints);

        jLabel9.setText(" Nominal Limit");
        jPanel58.add(jLabel9, new java.awt.GridBagConstraints());

        jLabel8.setText("Session Limits");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel58.add(jLabel8, gridBagConstraints);

        jLabel10.setText(" Nominal Limit");
        jPanel58.add(jLabel10, new java.awt.GridBagConstraints());

        jPanel34.add(jPanel58);

        java.awt.GridBagLayout jPanel69Layout = new java.awt.GridBagLayout();
        jPanel69Layout.columnWeights = new double[] {0.4, 0.2, 0.4, 0.2};
        jPanel69.setLayout(jPanel69Layout);

        deviceField21.setEditable(false);
        deviceField21.setIdentifier("");
        deviceField21.setLabelString("Output Voltage [kV] (Plasma)");
        deviceField21.setOffsetNid(330);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel69.add(deviceField21, gridBagConstraints);

        deviceField22.setEditable(false);
        deviceField22.setIdentifier("");
        deviceField22.setOffsetNid(352);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel69.add(deviceField22, gridBagConstraints);

        deviceField41.setEditable(false);
        deviceField41.setLabelString("Preset Pressure (min) [BarG]");
        deviceField41.setOffsetNid(331);
        jPanel69.add(deviceField41, new java.awt.GridBagConstraints());

        deviceField44.setEditable(false);
        deviceField44.setOffsetNid(353);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel69.add(deviceField44, gridBagConstraints);

        jPanel34.add(jPanel69);

        java.awt.GridBagLayout jPanel70Layout = new java.awt.GridBagLayout();
        jPanel70Layout.columnWeights = new double[] {0.4, 0.2, 0.4, 0.2};
        jPanel70.setLayout(jPanel70Layout);

        deviceField45.setEditable(false);
        deviceField45.setIdentifier("");
        deviceField45.setLabelString("Output Voltage [kV] (Vacuum)");
        deviceField45.setOffsetNid(346);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel70.add(deviceField45, gridBagConstraints);

        deviceField46.setEditable(false);
        deviceField46.setIdentifier("");
        deviceField46.setOffsetNid(368);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel70.add(deviceField46, gridBagConstraints);

        deviceField47.setEditable(false);
        deviceField47.setLabelString("Preset Pressure (max) [BarG]");
        deviceField47.setOffsetNid(332);
        jPanel70.add(deviceField47, new java.awt.GridBagConstraints());

        deviceField48.setEditable(false);
        deviceField48.setIdentifier("");
        deviceField48.setOffsetNid(354);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel70.add(deviceField48, gridBagConstraints);

        jPanel34.add(jPanel70);

        jPanel71.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("---------------------------- ISEPS ---------------------------");
        jPanel71.add(jLabel13);

        jPanel34.add(jPanel71);

        deviceField49.setEditable(false);
        deviceField49.setLabelString("ISEG Output Voltage [V]     ");
        deviceField49.setOffsetNid(333);
        jPanel72.add(deviceField49);

        deviceField50.setEditable(false);
        deviceField50.setOffsetNid(355);
        jPanel72.add(deviceField50);

        jLabel14.setText("              ");
        jPanel72.add(jLabel14);

        deviceField51.setEditable(false);
        deviceField51.setLabelString("ISSS Output Current [A]");
        deviceField51.setOffsetNid(335);
        jPanel72.add(deviceField51);

        deviceField52.setEditable(false);
        deviceField52.setOffsetNid(357);
        jPanel72.add(deviceField52);

        jPanel34.add(jPanel72);

        deviceField53.setEditable(false);
        deviceField53.setLabelString("ISRF-TE Output Voltage [V]");
        deviceField53.setOffsetNid(334);
        jPanel73.add(deviceField53);

        deviceField54.setEditable(false);
        deviceField54.setOffsetNid(356);
        jPanel73.add(deviceField54);

        jLabel15.setText("               ");
        jPanel73.add(jLabel15);

        deviceField55.setEditable(false);
        deviceField55.setLabelString("ISPG Output Current [A]");
        deviceField55.setOffsetNid(336);
        jPanel73.add(deviceField55);

        deviceField56.setEditable(false);
        deviceField56.setOffsetNid(358);
        jPanel73.add(deviceField56);

        jPanel34.add(jPanel73);

        jPanel74.setLayout(new java.awt.GridLayout(1, 0, 0, 2));

        jPanel82.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 20));

        jLabel7.setText(" Vacuum");
        jPanel82.add(jLabel7);

        jPanel74.add(jPanel82);

        jPanel83.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 20));

        jLabel17.setText(" With Plasma");
        jPanel83.add(jLabel17);

        jPanel74.add(jPanel83);

        jPanel34.add(jPanel74);

        deviceField57.setEditable(false);
        deviceField57.setIdentifier("");
        deviceField57.setLabelString("ISRF1 - Output Power [kV] ");
        deviceField57.setOffsetNid(347);
        jPanel75.add(deviceField57);

        deviceField58.setEditable(false);
        deviceField58.setOffsetNid(369);
        jPanel75.add(deviceField58);

        jLabel18.setText("               ");
        jPanel75.add(jLabel18);

        deviceField59.setEditable(false);
        deviceField59.setLabelString("ISRF1 - Output Power [kV] ");
        deviceField59.setOffsetNid(337);
        jPanel75.add(deviceField59);

        deviceField60.setEditable(false);
        deviceField60.setOffsetNid(359);
        jPanel75.add(deviceField60);

        jPanel34.add(jPanel75);

        deviceField61.setEditable(false);
        deviceField61.setLabelString("ISRF2 - Output Power [kV] ");
        deviceField61.setOffsetNid(348);
        jPanel76.add(deviceField61);

        deviceField62.setEditable(false);
        deviceField62.setOffsetNid(370);
        jPanel76.add(deviceField62);

        jLabel24.setText("               ");
        jPanel76.add(jLabel24);

        deviceField63.setEditable(false);
        deviceField63.setLabelString("ISRF2 - Output Power [kV] ");
        deviceField63.setOffsetNid(338);
        jPanel76.add(deviceField63);

        deviceField64.setEditable(false);
        deviceField64.setOffsetNid(360);
        jPanel76.add(deviceField64);

        jPanel34.add(jPanel76);

        deviceField65.setEditable(false);
        deviceField65.setLabelString("ISRF3 - Output Power [kV] ");
        deviceField65.setOffsetNid(349);
        jPanel77.add(deviceField65);

        deviceField66.setEditable(false);
        deviceField66.setOffsetNid(371);
        jPanel77.add(deviceField66);

        jLabel20.setText("              ");
        jPanel77.add(jLabel20);

        deviceField67.setEditable(false);
        deviceField67.setLabelString("ISRF3 - Output Power [kV] ");
        deviceField67.setOffsetNid(339);
        jPanel77.add(deviceField67);

        deviceField68.setEditable(false);
        deviceField68.setOffsetNid(361);
        jPanel77.add(deviceField68);

        jPanel34.add(jPanel77);

        deviceField69.setEditable(false);
        deviceField69.setLabelString("ISRF4 - Output Power [kV] ");
        deviceField69.setOffsetNid(350);
        jPanel78.add(deviceField69);

        deviceField70.setEditable(false);
        deviceField70.setOffsetNid(372);
        jPanel78.add(deviceField70);

        jLabel21.setText("              ");
        jPanel78.add(jLabel21);

        deviceField71.setEditable(false);
        deviceField71.setLabelString("ISRF4 - Output Power [kV] ");
        deviceField71.setOffsetNid(340);
        jPanel78.add(deviceField71);

        deviceField72.setEditable(false);
        deviceField72.setOffsetNid(362);
        jPanel78.add(deviceField72);

        jPanel34.add(jPanel78);
        jPanel34.add(jPanel79);

        deviceField73.setEditable(false);
        deviceField73.setLabelString("ISBI - Output Voltage [V] ");
        deviceField73.setOffsetNid(341);
        jPanel80.add(deviceField73);

        deviceField74.setEditable(false);
        deviceField74.setOffsetNid(363);
        jPanel80.add(deviceField74);

        jLabel22.setText("                ");
        jPanel80.add(jLabel22);

        deviceField75.setEditable(false);
        deviceField75.setLabelString("ISBI - Output Current [A]");
        deviceField75.setOffsetNid(343);
        jPanel80.add(deviceField75);

        deviceField76.setEditable(false);
        deviceField76.setOffsetNid(365);
        jPanel80.add(deviceField76);

        jPanel34.add(jPanel80);

        deviceField77.setEditable(false);
        deviceField77.setLabelString("ISBP - Output Voltage [V]");
        deviceField77.setOffsetNid(342);
        jPanel81.add(deviceField77);

        deviceField78.setEditable(false);
        deviceField78.setOffsetNid(364);
        jPanel81.add(deviceField78);

        jLabel23.setText("         '       ");
        jPanel81.add(jLabel23);

        deviceField79.setEditable(false);
        deviceField79.setLabelString("ISBP - Output Current [A]");
        deviceField79.setOffsetNid(344);
        jPanel81.add(deviceField79);

        deviceField80.setEditable(false);
        deviceField80.setIdentifier("");
        deviceField80.setOffsetNid(366);
        jPanel81.add(deviceField80);

        jPanel34.add(jPanel81);

        jPanel24.add(jPanel34, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Safety Parameters - Annex B", jPanel24);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void deviceField17PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_deviceField17PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_deviceField17PropertyChange

    
    private void updateWaves()
    {
        float maxX = 0, minX = 0;
        try {
            //Data data = this.deviceField13.getData();
            //minX = (subtree.evaluateData(subtree.dataFromExpr("FLOAT(" + subtree.dataToString(data) + ")"), 0)).getFloat();
            minX = subtree.getFloat(this.deviceField13.getData());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(SPIDER_SETUPSetup.this,
                "The value on the file Start Time in the Reference Wave Time Limit pannel isn't a valid float value or mdsplus expression.",
                "Incorret Start Time Reference wave limits", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            //Data data = this.deviceField17.getData();
            //maxX = (subtree.evaluateData(subtree.dataFromExpr("FLOAT(" + subtree.dataToString(data) + ")"), 0)).getFloat();
            maxX = subtree.getFloat(this.deviceField17.getData());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(SPIDER_SETUPSetup.this,
                "The value on the file Stop Time in the Reference Wave Time Limit pannel isn't a valid float value or mdsplus expression.",
                "Incorret Start Time Reference wave limits", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        /*
        System.out.println("UPDATE");
        java.awt.Container con = null;
        for( con = this.getParent(); con != null && !(con instanceof DeviceSetup); con=con.getParent() );
        if(con != null)
        {
            con.getComponents();
        }
        */
        
        deviceWave1.updateXLimit(minX, maxX);
        deviceWave2.updateXLimit(minX, maxX);
        deviceWave3.updateXLimit(minX, maxX);
        deviceWave4.updateXLimit(minX, maxX);
        //deviceWave5.updateXLimit(minX, maxX); Reconnect Wave x limit fixed from 0 to 1
        deviceWave6.updateXLimit(minX, maxX);
        deviceWave7.updateXLimit(minX, maxX);
        deviceWave8.updateXLimit(minX, maxX);
        deviceWave9.updateXLimit(minX, maxX);
        deviceWave10.updateXLimit(minX, maxX);
        deviceWave11.updateXLimit(minX, maxX);
        deviceWave12.updateXLimit(minX, maxX);
        deviceWave13.updateXLimit(minX, maxX);
        deviceWave14.updateXLimit(minX, maxX);        
        //deviceWave21.updateXLimit(minX, maxX); Reconnect Wave x limit fixed from 0 to 1
        deviceWave22.updateXLimit(minX, maxX);
        deviceWave23.updateXLimit(minX, maxX);
        deviceWave24.updateXLimit(minX, maxX);
        deviceWave25.updateXLimit(minX, maxX);
        deviceWave26.updateXLimit(minX, maxX);
        deviceWave27.updateXLimit(minX, maxX);
        deviceWave28.updateXLimit(minX, maxX);
        deviceWave29.updateXLimit(minX, maxX);        
    }
    
    private void deviceField17FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_deviceField17FocusLost
        // TODO add your handling code here:
        System.out.println("FOCUS Lost deviceField17");
        updateWaves();
    }//GEN-LAST:event_deviceField17FocusLost

    private void jTabbedPane1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPane1FocusLost
        // TODO add your handling code here:
        updateWaves();
    }//GEN-LAST:event_jTabbedPane1FocusLost

    private void deviceField13FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_deviceField13FocusLost
        // TODO add your handling code here:
        System.out.println("FOCUS Lost deviceField13");
        updateWaves();    
    }//GEN-LAST:event_deviceField13FocusLost

    private void jPanel29FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel29FocusLost
        // TODO add your handling code here:
        System.out.println("FOCUS Lost jPanel29");
        updateWaves();    
    }//GEN-LAST:event_jPanel29FocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private DeviceButtons deviceButtons1;
    private DeviceChoice deviceChoice1;
    private DeviceChoice deviceChoice10;
    private DeviceChoice deviceChoice11;
    private DeviceChoice deviceChoice12;
    private DeviceChoice deviceChoice2;
    private DeviceChoice deviceChoice4;
    private DeviceChoice deviceChoice5;
    private DeviceChoice deviceChoice6;
    private DeviceChoice deviceChoice7;
    private DeviceChoice deviceChoice8;
    private DeviceChoice deviceChoice9;
    private DeviceField deviceField1;
    private DeviceField deviceField10;
    private DeviceField deviceField11;
    private DeviceField deviceField12;
    private DeviceField deviceField13;
    private DeviceField deviceField14;
    private DeviceField deviceField15;
    private DeviceField deviceField16;
    private DeviceField deviceField17;
    private DeviceField deviceField18;
    private DeviceField deviceField19;
    private DeviceField deviceField2;
    private DeviceField deviceField20;
    private DeviceField deviceField21;
    private DeviceField deviceField22;
    private DeviceField deviceField23;
    private DeviceField deviceField24;
    private DeviceField deviceField25;
    private DeviceField deviceField26;
    private DeviceField deviceField27;
    private DeviceField deviceField28;
    private DeviceField deviceField29;
    private DeviceField deviceField3;
    private DeviceField deviceField30;
    private DeviceField deviceField31;
    private DeviceField deviceField32;
    private DeviceField deviceField33;
    private DeviceField deviceField34;
    private DeviceField deviceField35;
    private DeviceField deviceField36;
    private DeviceField deviceField37;
    private DeviceField deviceField38;
    private DeviceField deviceField39;
    private DeviceField deviceField4;
    private DeviceField deviceField40;
    private DeviceField deviceField41;
    private DeviceField deviceField42;
    private DeviceField deviceField43;
    private DeviceField deviceField44;
    private DeviceField deviceField45;
    private DeviceField deviceField46;
    private DeviceField deviceField47;
    private DeviceField deviceField48;
    private DeviceField deviceField49;
    private DeviceField deviceField5;
    private DeviceField deviceField50;
    private DeviceField deviceField51;
    private DeviceField deviceField52;
    private DeviceField deviceField53;
    private DeviceField deviceField54;
    private DeviceField deviceField55;
    private DeviceField deviceField56;
    private DeviceField deviceField57;
    private DeviceField deviceField58;
    private DeviceField deviceField59;
    private DeviceField deviceField6;
    private DeviceField deviceField60;
    private DeviceField deviceField61;
    private DeviceField deviceField62;
    private DeviceField deviceField63;
    private DeviceField deviceField64;
    private DeviceField deviceField65;
    private DeviceField deviceField66;
    private DeviceField deviceField67;
    private DeviceField deviceField68;
    private DeviceField deviceField69;
    private DeviceField deviceField7;
    private DeviceField deviceField70;
    private DeviceField deviceField71;
    private DeviceField deviceField72;
    private DeviceField deviceField73;
    private DeviceField deviceField74;
    private DeviceField deviceField75;
    private DeviceField deviceField76;
    private DeviceField deviceField77;
    private DeviceField deviceField78;
    private DeviceField deviceField79;
    private DeviceField deviceField8;
    private DeviceField deviceField80;
    private DeviceField deviceField9;
    private DeviceWave deviceWave1;
    private DeviceWave deviceWave10;
    private DeviceWave deviceWave11;
    private DeviceWave deviceWave12;
    private DeviceWave deviceWave13;
    private DeviceWave deviceWave14;
    private DeviceWave deviceWave2;
    private DeviceWave deviceWave21;
    private DeviceWave deviceWave22;
    private DeviceWave deviceWave23;
    private DeviceWave deviceWave24;
    private DeviceWave deviceWave25;
    private DeviceWave deviceWave26;
    private DeviceWave deviceWave27;
    private DeviceWave deviceWave28;
    private DeviceWave deviceWave29;
    private DeviceWave deviceWave3;
    private DeviceWave deviceWave4;
    private DeviceWave deviceWave5;
    private DeviceWave deviceWave6;
    private DeviceWave deviceWave7;
    private DeviceWave deviceWave8;
    private DeviceWave deviceWave9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel50;
    private javax.swing.JPanel jPanel51;
    private javax.swing.JPanel jPanel52;
    private javax.swing.JPanel jPanel53;
    private javax.swing.JPanel jPanel54;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JPanel jPanel56;
    private javax.swing.JPanel jPanel57;
    private javax.swing.JPanel jPanel58;
    private javax.swing.JPanel jPanel59;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel60;
    private javax.swing.JPanel jPanel61;
    private javax.swing.JPanel jPanel62;
    private javax.swing.JPanel jPanel63;
    private javax.swing.JPanel jPanel64;
    private javax.swing.JPanel jPanel65;
    private javax.swing.JPanel jPanel66;
    private javax.swing.JPanel jPanel67;
    private javax.swing.JPanel jPanel68;
    private javax.swing.JPanel jPanel69;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel70;
    private javax.swing.JPanel jPanel71;
    private javax.swing.JPanel jPanel72;
    private javax.swing.JPanel jPanel73;
    private javax.swing.JPanel jPanel74;
    private javax.swing.JPanel jPanel75;
    private javax.swing.JPanel jPanel76;
    private javax.swing.JPanel jPanel77;
    private javax.swing.JPanel jPanel78;
    private javax.swing.JPanel jPanel79;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel80;
    private javax.swing.JPanel jPanel81;
    private javax.swing.JPanel jPanel82;
    private javax.swing.JPanel jPanel83;
    private javax.swing.JPanel jPanel84;
    private javax.swing.JPanel jPanel85;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane10;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTabbedPane jTabbedPane7;
    private javax.swing.JTabbedPane jTabbedPane8;
    private javax.swing.JTabbedPane jTabbedPane9;
    // End of variables declaration//GEN-END:variables

}
