#ifndef _TDISHR_H
#define _TDISHR_H
                  
#include <mdsdescrip.h>
#include <mdstypes.h>
#include <status.h>
#include <tdishr_messages.h>

extern int TdiGetLong(struct descriptor *indsc, int *out_int);
extern int TdiGetFloat(struct descriptor *index, float *out_float);
extern int TdiConvert();
extern int TdiIntrinsic(
    opcode_t opcode,
    int narg,
    struct descriptor *list[],
    struct descriptor_xd *out_ptr
);
extern int _TdiIntrinsic(
    void **ctx,
    opcode_t opcode,
    int narg,
    struct descriptor *list[],
    struct descriptor_xd *out_ptr
);
extern int CvtConvertFloat(
    void *invalue,
    uint32_t indtype,
    void *outvalue,
    uint32_t outdtype,
    uint32_t options
);

extern const opcode_t Opcdollar;
extern const opcode_t OpcA0;
extern const opcode_t OpcAlpha;
extern const opcode_t OpcAmu;
extern const opcode_t OpcC;
extern const opcode_t OpcCal;
extern const opcode_t OpcDegree;
extern const opcode_t OpcEv;
extern const opcode_t OpcFalse;
extern const opcode_t OpcFaraday;
extern const opcode_t OpcG;
extern const opcode_t OpcGas;
extern const opcode_t OpcH;
extern const opcode_t OpcHbar;
extern const opcode_t OpcI;
extern const opcode_t OpcK;
extern const opcode_t OpcMe;
extern const opcode_t OpcMissing;
extern const opcode_t OpcMp;
extern const opcode_t OpcN0;
extern const opcode_t OpcNa;
extern const opcode_t OpcP0;
extern const opcode_t OpcPi;
extern const opcode_t OpcQe;
extern const opcode_t OpcRe;
extern const opcode_t OpcRoprand;
extern const opcode_t OpcRydberg;
extern const opcode_t OpcT0;
extern const opcode_t OpcTorr;
extern const opcode_t OpcTrue;
extern const opcode_t OpcValue;
extern const opcode_t OpcAbort;
extern const opcode_t OpcAbs;
extern const opcode_t OpcAbs1;
extern const opcode_t OpcAbsSq;
extern const opcode_t OpcAchar;
extern const opcode_t OpcAcos;
extern const opcode_t OpcAcosd;
extern const opcode_t OpcAdd;
extern const opcode_t OpcAdjustl;
extern const opcode_t OpcAdjustr;
extern const opcode_t OpcAimag;
extern const opcode_t OpcAint;
extern const opcode_t OpcAll;
extern const opcode_t OpcAllocated;
extern const opcode_t OpcAnd;
extern const opcode_t OpcAndNot;
extern const opcode_t OpcAnint;
extern const opcode_t OpcAny;
extern const opcode_t OpcArg;
extern const opcode_t OpcArgd;
extern const opcode_t OpcArgOf;
extern const opcode_t OpcArray;
extern const opcode_t OpcAsin;
extern const opcode_t OpcAsind;
extern const opcode_t OpcAsIs;
extern const opcode_t OpcAtan;
extern const opcode_t OpcAtan2;
extern const opcode_t OpcAtan2d;
extern const opcode_t OpcAtand;
extern const opcode_t OpcAtanh;
extern const opcode_t OpcAxisOf;
extern const opcode_t OpcBackspace;
extern const opcode_t OpcIbclr;
extern const opcode_t OpcBeginOf;
extern const opcode_t OpcIbits;
extern const opcode_t OpcBreak;
extern const opcode_t OpcBsearch;
extern const opcode_t OpcIbset;
extern const opcode_t OpcBtest;
extern const opcode_t OpcBuildAction;
extern const opcode_t OpcBuildCondition;
extern const opcode_t OpcBuildConglom;
extern const opcode_t OpcBuildDependency;
extern const opcode_t OpcBuildDim;
extern const opcode_t OpcBuildDispatch;
extern const opcode_t OpcBuildEvent;
extern const opcode_t OpcBuildFunction;
extern const opcode_t OpcBuildMethod;
extern const opcode_t OpcBuildParam;
extern const opcode_t OpcBuildPath;
extern const opcode_t OpcBuildProcedure;
extern const opcode_t OpcBuildProgram;
extern const opcode_t OpcBuildRange;
extern const opcode_t OpcBuildRoutine;
extern const opcode_t OpcBuildSignal;
extern const opcode_t OpcBuildSlope;
extern const opcode_t OpcBuildWindow;
extern const opcode_t OpcBuildWithUnits;
extern const opcode_t OpcBuiltinOpcode;
extern const opcode_t OpcByte;
extern const opcode_t OpcByteUnsigned;
extern const opcode_t OpcCase;
extern const opcode_t OpcCeiling;
extern const opcode_t OpcChar;
extern const opcode_t OpcClass;
extern const opcode_t OpcFclose;
extern const opcode_t OpcCmplx;
extern const opcode_t OpcComma;
extern const opcode_t OpcCompile;
extern const opcode_t OpcCompletionOf;
extern const opcode_t OpcConcat;
extern const opcode_t OpcConditional;
extern const opcode_t OpcConjg;
extern const opcode_t OpcContinue;
extern const opcode_t OpcConvolve;
extern const opcode_t OpcCos;
extern const opcode_t OpcCosd;
extern const opcode_t OpcCosh;
extern const opcode_t OpcCount;
extern const opcode_t OpcCshift;
extern const opcode_t OpcCvt;
extern const opcode_t OpcData;
extern const opcode_t OpcDateAndTime;
extern const opcode_t OpcDateTime;
extern const opcode_t OpcDble;
extern const opcode_t OpcDeallocate;
extern const opcode_t OpcDebug;
extern const opcode_t OpcDecode;
extern const opcode_t OpcDecompile;
extern const opcode_t OpcDecompress;
extern const opcode_t OpcDefault;
extern const opcode_t OpcDerivative;
extern const opcode_t OpcDescr;
extern const opcode_t OpcDiagonal;
extern const opcode_t OpcDigits;
extern const opcode_t OpcDim;
extern const opcode_t OpcDimOf;
extern const opcode_t OpcDispatchOf;
extern const opcode_t OpcDivide;
extern const opcode_t OpcLbound;
extern const opcode_t OpcDo;
extern const opcode_t OpcDotProduct;
extern const opcode_t OpcDprod;
extern const opcode_t OpcDscptr;
extern const opcode_t OpcShape;
extern const opcode_t OpcSize;
extern const opcode_t OpcKind;
extern const opcode_t OpcUbound;
extern const opcode_t OpcDComplex;
extern const opcode_t OpcDFloat;
extern const opcode_t OpcRange;
extern const opcode_t OpcPrecision;
extern const opcode_t OpcElbound;
extern const opcode_t OpcElse;
extern const opcode_t OpcElsewhere;
extern const opcode_t OpcEncode;
extern const opcode_t OpcEndfile;
extern const opcode_t OpcEndOf;
extern const opcode_t OpcEoshift;
extern const opcode_t OpcEpsilon;
extern const opcode_t OpcEq;
extern const opcode_t OpcEquals;
extern const opcode_t OpcEqualsFirst;
extern const opcode_t OpcEqv;
extern const opcode_t OpcEshape;
extern const opcode_t OpcEsize;
extern const opcode_t OpcEubound;
extern const opcode_t OpcEvaluate;
extern const opcode_t OpcExecute;
extern const opcode_t OpcExp;
extern const opcode_t OpcExponent;
extern const opcode_t OpcExtFunction;
extern const opcode_t OpcFft;
extern const opcode_t OpcFirstLoc;
extern const opcode_t OpcFit;
extern const opcode_t OpcFixRoprand;
extern const opcode_t OpcFloat;
extern const opcode_t OpcFloor;
extern const opcode_t OpcFor;
extern const opcode_t OpcFraction;
extern const opcode_t OpcFun;
extern const opcode_t OpcFComplex;
extern const opcode_t OpcFFloat;
extern const opcode_t OpcGe;
extern const opcode_t OpcGetNci;
extern const opcode_t OpcGoto;
extern const opcode_t OpcGt;
extern const opcode_t OpcGComplex;
extern const opcode_t OpcGFloat;
extern const opcode_t OpcHelpOf;
extern const opcode_t OpcHuge;
extern const opcode_t OpcHComplex;
extern const opcode_t OpcHFloat;
extern const opcode_t OpcIachar;
extern const opcode_t OpcIand;
extern const opcode_t OpcIandNot;
extern const opcode_t OpcIchar;
extern const opcode_t OpcIdentOf;
extern const opcode_t OpcIf;
extern const opcode_t OpcIfError;
extern const opcode_t OpcImageOf;
extern const opcode_t OpcIn;
extern const opcode_t OpcInand;
extern const opcode_t OpcInandNot;
extern const opcode_t OpcIndex;
extern const opcode_t OpcInor;
extern const opcode_t OpcInorNot;
extern const opcode_t OpcInot;
extern const opcode_t OpcInOut;
extern const opcode_t OpcInquire;
extern const opcode_t OpcInt;
extern const opcode_t OpcIntegral;
extern const opcode_t OpcInterpol;
extern const opcode_t OpcIntersect;
extern const opcode_t OpcIntUnsigned;
extern const opcode_t OpcInverse;
extern const opcode_t OpcIor;
extern const opcode_t OpcIorNot;
extern const opcode_t OpcIsIn;
extern const opcode_t OpcIeor;
extern const opcode_t OpcIeorNot;
extern const opcode_t OpcLabel;
extern const opcode_t OpcLaminate;
extern const opcode_t OpcLanguageOf;
extern const opcode_t OpcLastLoc;
extern const opcode_t OpcLe;
extern const opcode_t OpcLen;
extern const opcode_t OpcLenTrim;
extern const opcode_t OpcLge;
extern const opcode_t OpcLgt;
extern const opcode_t OpcLle;
extern const opcode_t OpcLlt;
extern const opcode_t OpcLog;
extern const opcode_t OpcLog10;
extern const opcode_t OpcLog2;
extern const opcode_t OpcLogical;
extern const opcode_t OpcLong;
extern const opcode_t OpcLongUnsigned;
extern const opcode_t OpcLt;
extern const opcode_t OpcMatmul;
extern const opcode_t OpcMatRot;
extern const opcode_t OpcMatRotInt;
extern const opcode_t OpcMax;
extern const opcode_t OpcMaxExponent;
extern const opcode_t OpcMaxLoc;
extern const opcode_t OpcMaxVal;
extern const opcode_t OpcMean;
extern const opcode_t OpcMedian;
extern const opcode_t OpcMerge;
extern const opcode_t OpcMethodOf;
extern const opcode_t OpcMin;
extern const opcode_t OpcMinExponent;
extern const opcode_t OpcMinLoc;
extern const opcode_t OpcMinVal;
extern const opcode_t OpcMod;
extern const opcode_t OpcModelOf;
extern const opcode_t OpcMultiply;
extern const opcode_t OpcNameOf;
extern const opcode_t OpcNand;
extern const opcode_t OpcNandNot;
extern const opcode_t OpcNdesc;
extern const opcode_t OpcNe;
extern const opcode_t OpcNearest;
extern const opcode_t OpcNeqv;
extern const opcode_t OpcNint;
extern const opcode_t OpcNor;
extern const opcode_t OpcNorNot;
extern const opcode_t OpcNot;
extern const opcode_t OpcObjectOf;
extern const opcode_t OpcOctaword;
extern const opcode_t OpcOctawordUnsigned;
extern const opcode_t OpcOnError;
extern const opcode_t OpcOpcodeBuiltin;
extern const opcode_t OpcOpcodeString;
extern const opcode_t OpcFopen;
extern const opcode_t OpcOptional;
extern const opcode_t OpcOr;
extern const opcode_t OpcOrNot;
extern const opcode_t OpcOut;
extern const opcode_t OpcPack;
extern const opcode_t OpcPhaseOf;
extern const opcode_t OpcPostDec;
extern const opcode_t OpcPostInc;
extern const opcode_t OpcPower;
extern const opcode_t OpcPresent;
extern const opcode_t OpcPreDec;
extern const opcode_t OpcPreInc;
extern const opcode_t OpcPrivate;
extern const opcode_t OpcProcedureOf;
extern const opcode_t OpcProduct;
extern const opcode_t OpcProgramOf;
extern const opcode_t OpcProject;
extern const opcode_t OpcPromote;
extern const opcode_t OpcPublic;
extern const opcode_t OpcQuadword;
extern const opcode_t OpcQuadwordUnsigned;
extern const opcode_t OpcQualifiersOf;
extern const opcode_t OpcRadix;
extern const opcode_t OpcRamp;
extern const opcode_t OpcRandom;
extern const opcode_t OpcRandomSeed;
extern const opcode_t OpcDtypeRange;
extern const opcode_t OpcRank;
extern const opcode_t OpcRawOf;
extern const opcode_t OpcRead;
extern const opcode_t OpcReal;
extern const opcode_t OpcRebin;
extern const opcode_t OpcRef;
extern const opcode_t OpcRepeat;
extern const opcode_t OpcReplicate;
extern const opcode_t OpcReshape;
extern const opcode_t OpcReturn;
extern const opcode_t OpcRewind;
extern const opcode_t OpcRms;
extern const opcode_t OpcRoutineOf;
extern const opcode_t OpcRrSpacing;
extern const opcode_t OpcScale;
extern const opcode_t OpcScan;
extern const opcode_t OpcFseek;
extern const opcode_t OpcSetExponent;
extern const opcode_t OpcSetRange;
extern const opcode_t OpcIshft;
extern const opcode_t OpcIshftc;
extern const opcode_t OpcShiftLeft;
extern const opcode_t OpcShiftRight;
extern const opcode_t OpcSign;
extern const opcode_t OpcSigned;
extern const opcode_t OpcSin;
extern const opcode_t OpcSind;
extern const opcode_t OpcSinh;
extern const opcode_t OpcSizeOf;
extern const opcode_t OpcSlopeOf;
extern const opcode_t OpcSmooth;
extern const opcode_t OpcSolve;
extern const opcode_t OpcSortVal;
extern const opcode_t OpcSpacing;
extern const opcode_t OpcSpawn;
extern const opcode_t OpcSpread;
extern const opcode_t OpcSqrt;
extern const opcode_t OpcSquare;
extern const opcode_t OpcStatement;
extern const opcode_t OpcStdDev;
extern const opcode_t OpcString;
extern const opcode_t OpcStringOpcode;
extern const opcode_t OpcSubscript;
extern const opcode_t OpcSubtract;
extern const opcode_t OpcSum;
extern const opcode_t OpcSwitch;
extern const opcode_t OpcSystemClock;
extern const opcode_t OpcTan;
extern const opcode_t OpcTand;
extern const opcode_t OpcTanh;
extern const opcode_t OpcTaskOf;
extern const opcode_t OpcText;
extern const opcode_t OpcTimeoutOf;
extern const opcode_t OpcTiny;
extern const opcode_t OpcTransfer;
extern const opcode_t OpcTranspose_;
extern const opcode_t OpcTrim;
extern const opcode_t OpcUnaryMinus;
extern const opcode_t OpcUnaryPlus;
extern const opcode_t OpcUnion;
extern const opcode_t OpcUnits;
extern const opcode_t OpcUnitsOf;
extern const opcode_t OpcUnpack;
extern const opcode_t OpcUnsigned;
extern const opcode_t OpcVal;
extern const opcode_t OpcValidationOf;
extern const opcode_t OpcValueOf;
extern const opcode_t OpcVar;
extern const opcode_t OpcVector;
extern const opcode_t OpcVerify;
extern const opcode_t OpcWait;
extern const opcode_t OpcWhenOf;
extern const opcode_t OpcWhere;
extern const opcode_t OpcWhile;
extern const opcode_t OpcWindowOf;
extern const opcode_t OpcWord;
extern const opcode_t OpcWordUnsigned;
extern const opcode_t OpcWrite;
extern const opcode_t OpcZero;
extern const opcode_t Opc2Pi;
extern const opcode_t OpcNarg;
extern const opcode_t OpcElement;
extern const opcode_t OpcRcDroop;
extern const opcode_t OpcResetPrivate;
extern const opcode_t OpcResetPublic;
extern const opcode_t OpcShowPrivate;
extern const opcode_t OpcShowPublic;
extern const opcode_t OpcShowVm;
extern const opcode_t OpcTranslate;
extern const opcode_t OpcTransposeMul;
extern const opcode_t OpcUpcase;
extern const opcode_t OpcUsing;
extern const opcode_t OpcValidation;
extern const opcode_t OpcMdsDefault;
extern const opcode_t OpcExpt;
extern const opcode_t OpcShot;
extern const opcode_t OpcGetDbi;
extern const opcode_t OpcCull;
extern const opcode_t OpcExtend;
extern const opcode_t OpcItoX;
extern const opcode_t OpcXtoI;
extern const opcode_t OpcMap;
extern const opcode_t OpcCompileDependency;
extern const opcode_t OpcDecompileDependency;
extern const opcode_t OpcBuildCall;
extern const opcode_t OpcErrorlogsOf;
extern const opcode_t OpcPerformanceOf;
extern const opcode_t OpcXd;
extern const opcode_t OpcConditionOf;
extern const opcode_t OpcSort;
extern const opcode_t OpcThis;
extern const opcode_t OpcDataWithUnits;
extern const opcode_t OpcAtm;
extern const opcode_t OpcEpsilon0;
extern const opcode_t OpcGn;
extern const opcode_t OpcMu0;
extern const opcode_t OpcExtract;
extern const opcode_t OpcFinite;
extern const opcode_t OpcBitSize;
extern const opcode_t OpcModulo;
extern const opcode_t OpcSelectedIntKind;
extern const opcode_t OpcSelectedRealKind;
extern const opcode_t OpcDsql;
extern const opcode_t OpcIsql;
extern const opcode_t OpcFtell;
extern const opcode_t OpcMakeAction;
extern const opcode_t OpcMakeCondition;
extern const opcode_t OpcMakeConglom;
extern const opcode_t OpcMakeDependency;
extern const opcode_t OpcMakeDim;
extern const opcode_t OpcMakeDispatch;
extern const opcode_t OpcMakeFunction;
extern const opcode_t OpcMakeMethod;
extern const opcode_t OpcMakeParam;
extern const opcode_t OpcMakeProcedure;
extern const opcode_t OpcMakeProgram;
extern const opcode_t OpcMakeRange;
extern const opcode_t OpcMakeRoutine;
extern const opcode_t OpcMakeSignal;
extern const opcode_t OpcMakeWindow;
extern const opcode_t OpcMakeWithUnits;
extern const opcode_t OpcMakeCall;
extern const opcode_t OpcClassOf;
extern const opcode_t OpcDscptrOf;
extern const opcode_t OpcKindOf;
extern const opcode_t OpcNdescOf;
extern const opcode_t OpcAccumulate;
extern const opcode_t OpcMakeSlope;
extern const opcode_t OpcRem;
extern const opcode_t OpcCompletionMessageOf;
extern const opcode_t OpcInterruptOf;
extern const opcode_t OpcShotname;
extern const opcode_t OpcBuildWithError;
extern const opcode_t OpcErrorOf;
extern const opcode_t OpcMakeWithError;
extern const opcode_t OpcDoTask;
extern const opcode_t OpcIsqlSet;
extern const opcode_t OpcFS_float;
extern const opcode_t OpcFS_complex;
extern const opcode_t OpcFT_float;
extern const opcode_t OpcFT_complex;
extern const opcode_t OpcBuildOpaque;
extern const opcode_t OpcMakeOpaque;
extern const opcode_t OpcDict;
extern const opcode_t OpcTuple;
extern const opcode_t OpcList;
extern const opcode_t OpcSqueeze;
extern const opcode_t OpcFlatten;

extern int Tdidollar(struct descriptor *first, ...);
extern int TdiA0(struct descriptor *first, ...);
extern int TdiAlpha(struct descriptor *first, ...);
extern int TdiAmu(struct descriptor *first, ...);
extern int TdiC(struct descriptor *first, ...);
extern int TdiCal(struct descriptor *first, ...);
extern int TdiDegree(struct descriptor *first, ...);
extern int TdiEv(struct descriptor *first, ...);
extern int TdiFalse(struct descriptor *first, ...);
extern int TdiFaraday(struct descriptor *first, ...);
extern int TdiG(struct descriptor *first, ...);
extern int TdiGas(struct descriptor *first, ...);
extern int TdiH(struct descriptor *first, ...);
extern int TdiHbar(struct descriptor *first, ...);
extern int TdiI(struct descriptor *first, ...);
extern int TdiK(struct descriptor *first, ...);
extern int TdiMe(struct descriptor *first, ...);
extern int TdiMissing(struct descriptor *first, ...);
extern int TdiMp(struct descriptor *first, ...);
extern int TdiN0(struct descriptor *first, ...);
extern int TdiNa(struct descriptor *first, ...);
extern int TdiP0(struct descriptor *first, ...);
extern int TdiPi(struct descriptor *first, ...);
extern int TdiQe(struct descriptor *first, ...);
extern int TdiRe(struct descriptor *first, ...);
extern int TdiRoprand(struct descriptor *first, ...);
extern int TdiRydberg(struct descriptor *first, ...);
extern int TdiT0(struct descriptor *first, ...);
extern int TdiTorr(struct descriptor *first, ...);
extern int TdiTrue(struct descriptor *first, ...);
extern int TdiValue(struct descriptor *first, ...);
extern int TdiAbort(struct descriptor *first, ...);
extern int TdiAbs(struct descriptor *first, ...);
extern int TdiAbs1(struct descriptor *first, ...);
extern int TdiAbsSq(struct descriptor *first, ...);
extern int TdiAchar(struct descriptor *first, ...);
extern int TdiAcos(struct descriptor *first, ...);
extern int TdiAcosd(struct descriptor *first, ...);
extern int TdiAdd(struct descriptor *first, ...);
extern int TdiAdjustl(struct descriptor *first, ...);
extern int TdiAdjustr(struct descriptor *first, ...);
extern int TdiAimag(struct descriptor *first, ...);
extern int TdiAint(struct descriptor *first, ...);
extern int TdiAll(struct descriptor *first, ...);
extern int TdiAllocated(struct descriptor *first, ...);
extern int TdiAnd(struct descriptor *first, ...);
extern int TdiAndNot(struct descriptor *first, ...);
extern int TdiAnint(struct descriptor *first, ...);
extern int TdiAny(struct descriptor *first, ...);
extern int TdiArg(struct descriptor *first, ...);
extern int TdiArgd(struct descriptor *first, ...);
extern int TdiArgOf(struct descriptor *first, ...);
extern int TdiArray(struct descriptor *first, ...);
extern int TdiAsin(struct descriptor *first, ...);
extern int TdiAsind(struct descriptor *first, ...);
extern int TdiAsIs(struct descriptor *first, ...);
extern int TdiAtan(struct descriptor *first, ...);
extern int TdiAtan2(struct descriptor *first, ...);
extern int TdiAtan2d(struct descriptor *first, ...);
extern int TdiAtand(struct descriptor *first, ...);
extern int TdiAtanh(struct descriptor *first, ...);
extern int TdiAxisOf(struct descriptor *first, ...);
extern int TdiBackspace(struct descriptor *first, ...);
extern int TdiIbclr(struct descriptor *first, ...);
extern int TdiBeginOf(struct descriptor *first, ...);
extern int TdiIbits(struct descriptor *first, ...);
extern int TdiBreak(struct descriptor *first, ...);
extern int TdiBsearch(struct descriptor *first, ...);
extern int TdiIbset(struct descriptor *first, ...);
extern int TdiBtest(struct descriptor *first, ...);
extern int TdiBuildAction(struct descriptor *first, ...);
extern int TdiBuildCondition(struct descriptor *first, ...);
extern int TdiBuildConglom(struct descriptor *first, ...);
extern int TdiBuildDependency(struct descriptor *first, ...);
extern int TdiBuildDim(struct descriptor *first, ...);
extern int TdiBuildDispatch(struct descriptor *first, ...);
extern int TdiBuildEvent(struct descriptor *first, ...);
extern int TdiBuildFunction(struct descriptor *first, ...);
extern int TdiBuildMethod(struct descriptor *first, ...);
extern int TdiBuildParam(struct descriptor *first, ...);
extern int TdiBuildPath(struct descriptor *first, ...);
extern int TdiBuildProcedure(struct descriptor *first, ...);
extern int TdiBuildProgram(struct descriptor *first, ...);
extern int TdiBuildRange(struct descriptor *first, ...);
extern int TdiBuildRoutine(struct descriptor *first, ...);
extern int TdiBuildSignal(struct descriptor *first, ...);
extern int TdiBuildSlope(struct descriptor *first, ...);
extern int TdiBuildWindow(struct descriptor *first, ...);
extern int TdiBuildWithUnits(struct descriptor *first, ...);
extern int TdiBuiltinOpcode(struct descriptor *first, ...);
extern int TdiByte(struct descriptor *first, ...);
extern int TdiByteUnsigned(struct descriptor *first, ...);
extern int TdiCase(struct descriptor *first, ...);
extern int TdiCeiling(struct descriptor *first, ...);
extern int TdiChar(struct descriptor *first, ...);
extern int TdiClass(struct descriptor *first, ...);
extern int TdiFclose(struct descriptor *first, ...);
extern int TdiCmplx(struct descriptor *first, ...);
extern int TdiComma(struct descriptor *first, ...);
extern int TdiCompile(struct descriptor *first, ...);
extern int TdiCompletionOf(struct descriptor *first, ...);
extern int TdiConcat(struct descriptor *first, ...);
extern int TdiConditional(struct descriptor *first, ...);
extern int TdiConjg(struct descriptor *first, ...);
extern int TdiContinue(struct descriptor *first, ...);
extern int TdiConvolve(struct descriptor *first, ...);
extern int TdiCos(struct descriptor *first, ...);
extern int TdiCosd(struct descriptor *first, ...);
extern int TdiCosh(struct descriptor *first, ...);
extern int TdiCount(struct descriptor *first, ...);
extern int TdiCshift(struct descriptor *first, ...);
extern int TdiCvt(struct descriptor *first, ...);
extern int TdiData(struct descriptor *first, ...);
extern int TdiDateAndTime(struct descriptor *first, ...);
extern int TdiDateTime(struct descriptor *first, ...);
extern int TdiDble(struct descriptor *first, ...);
extern int TdiDeallocate(struct descriptor *first, ...);
extern int TdiDebug(struct descriptor *first, ...);
extern int TdiDecode(struct descriptor *first, ...);
extern int TdiDecompile(struct descriptor *first, ...);
extern int TdiDecompress(struct descriptor *first, ...);
extern int TdiDefault(struct descriptor *first, ...);
extern int TdiDerivative(struct descriptor *first, ...);
extern int TdiDescr(struct descriptor *first, ...);
extern int TdiDiagonal(struct descriptor *first, ...);
extern int TdiDigits(struct descriptor *first, ...);
extern int TdiDim(struct descriptor *first, ...);
extern int TdiDimOf(struct descriptor *first, ...);
extern int TdiDispatchOf(struct descriptor *first, ...);
extern int TdiDivide(struct descriptor *first, ...);
extern int TdiLbound(struct descriptor *first, ...);
extern int TdiDo(struct descriptor *first, ...);
extern int TdiDotProduct(struct descriptor *first, ...);
extern int TdiDprod(struct descriptor *first, ...);
extern int TdiDscptr(struct descriptor *first, ...);
extern int TdiShape(struct descriptor *first, ...);
extern int TdiSize(struct descriptor *first, ...);
extern int TdiKind(struct descriptor *first, ...);
extern int TdiUbound(struct descriptor *first, ...);
extern int TdiDComplex(struct descriptor *first, ...);
extern int TdiDFloat(struct descriptor *first, ...);
extern int TdiRange(struct descriptor *first, ...);
extern int TdiPrecision(struct descriptor *first, ...);
extern int TdiElbound(struct descriptor *first, ...);
extern int TdiElse(struct descriptor *first, ...);
extern int TdiElsewhere(struct descriptor *first, ...);
extern int TdiEncode(struct descriptor *first, ...);
extern int TdiEndfile(struct descriptor *first, ...);
extern int TdiEndOf(struct descriptor *first, ...);
extern int TdiEoshift(struct descriptor *first, ...);
extern int TdiEpsilon(struct descriptor *first, ...);
extern int TdiEq(struct descriptor *first, ...);
extern int TdiEquals(struct descriptor *first, ...);
extern int TdiEqualsFirst(struct descriptor *first, ...);
extern int TdiEqv(struct descriptor *first, ...);
extern int TdiEshape(struct descriptor *first, ...);
extern int TdiEsize(struct descriptor *first, ...);
extern int TdiEubound(struct descriptor *first, ...);
extern int TdiEvaluate(struct descriptor *first, ...);
extern int TdiExecute(struct descriptor *first, ...);
extern int TdiExp(struct descriptor *first, ...);
extern int TdiExponent(struct descriptor *first, ...);
extern int TdiExtFunction(struct descriptor *first, ...);
extern int TdiFft(struct descriptor *first, ...);
extern int TdiFirstLoc(struct descriptor *first, ...);
extern int TdiFit(struct descriptor *first, ...);
extern int TdiFixRoprand(struct descriptor *first, ...);
extern int TdiFloat(struct descriptor *first, ...);
extern int TdiFloor(struct descriptor *first, ...);
extern int TdiFor(struct descriptor *first, ...);
extern int TdiFraction(struct descriptor *first, ...);
extern int TdiFun(struct descriptor *first, ...);
extern int TdiFComplex(struct descriptor *first, ...);
extern int TdiFFloat(struct descriptor *first, ...);
extern int TdiGe(struct descriptor *first, ...);
extern int TdiGetNci(struct descriptor *first, ...);
extern int TdiGoto(struct descriptor *first, ...);
extern int TdiGt(struct descriptor *first, ...);
extern int TdiGComplex(struct descriptor *first, ...);
extern int TdiGFloat(struct descriptor *first, ...);
extern int TdiHelpOf(struct descriptor *first, ...);
extern int TdiHuge(struct descriptor *first, ...);
extern int TdiHComplex(struct descriptor *first, ...);
extern int TdiHFloat(struct descriptor *first, ...);
extern int TdiIachar(struct descriptor *first, ...);
extern int TdiIand(struct descriptor *first, ...);
extern int TdiIandNot(struct descriptor *first, ...);
extern int TdiIchar(struct descriptor *first, ...);
extern int TdiIdentOf(struct descriptor *first, ...);
extern int TdiIf(struct descriptor *first, ...);
extern int TdiIfError(struct descriptor *first, ...);
extern int TdiImageOf(struct descriptor *first, ...);
extern int TdiIn(struct descriptor *first, ...);
extern int TdiInand(struct descriptor *first, ...);
extern int TdiInandNot(struct descriptor *first, ...);
extern int TdiIndex(struct descriptor *first, ...);
extern int TdiInor(struct descriptor *first, ...);
extern int TdiInorNot(struct descriptor *first, ...);
extern int TdiInot(struct descriptor *first, ...);
extern int TdiInOut(struct descriptor *first, ...);
extern int TdiInquire(struct descriptor *first, ...);
extern int TdiInt(struct descriptor *first, ...);
extern int TdiIntegral(struct descriptor *first, ...);
extern int TdiInterpol(struct descriptor *first, ...);
extern int TdiIntersect(struct descriptor *first, ...);
extern int TdiIntUnsigned(struct descriptor *first, ...);
extern int TdiInverse(struct descriptor *first, ...);
extern int TdiIor(struct descriptor *first, ...);
extern int TdiIorNot(struct descriptor *first, ...);
extern int TdiIsIn(struct descriptor *first, ...);
extern int TdiIeor(struct descriptor *first, ...);
extern int TdiIeorNot(struct descriptor *first, ...);
extern int TdiLabel(struct descriptor *first, ...);
extern int TdiLaminate(struct descriptor *first, ...);
extern int TdiLanguageOf(struct descriptor *first, ...);
extern int TdiLastLoc(struct descriptor *first, ...);
extern int TdiLe(struct descriptor *first, ...);
extern int TdiLen(struct descriptor *first, ...);
extern int TdiLenTrim(struct descriptor *first, ...);
extern int TdiLge(struct descriptor *first, ...);
extern int TdiLgt(struct descriptor *first, ...);
extern int TdiLle(struct descriptor *first, ...);
extern int TdiLlt(struct descriptor *first, ...);
extern int TdiLog(struct descriptor *first, ...);
extern int TdiLog10(struct descriptor *first, ...);
extern int TdiLog2(struct descriptor *first, ...);
extern int TdiLogical(struct descriptor *first, ...);
extern int TdiLong(struct descriptor *first, ...);
extern int TdiLongUnsigned(struct descriptor *first, ...);
extern int TdiLt(struct descriptor *first, ...);
extern int TdiMatmul(struct descriptor *first, ...);
extern int TdiMatRot(struct descriptor *first, ...);
extern int TdiMatRotInt(struct descriptor *first, ...);
extern int TdiMax(struct descriptor *first, ...);
extern int TdiMaxExponent(struct descriptor *first, ...);
extern int TdiMaxLoc(struct descriptor *first, ...);
extern int TdiMaxVal(struct descriptor *first, ...);
extern int TdiMean(struct descriptor *first, ...);
extern int TdiMedian(struct descriptor *first, ...);
extern int TdiMerge(struct descriptor *first, ...);
extern int TdiMethodOf(struct descriptor *first, ...);
extern int TdiMin(struct descriptor *first, ...);
extern int TdiMinExponent(struct descriptor *first, ...);
extern int TdiMinLoc(struct descriptor *first, ...);
extern int TdiMinVal(struct descriptor *first, ...);
extern int TdiMod(struct descriptor *first, ...);
extern int TdiModelOf(struct descriptor *first, ...);
extern int TdiMultiply(struct descriptor *first, ...);
extern int TdiNameOf(struct descriptor *first, ...);
extern int TdiNand(struct descriptor *first, ...);
extern int TdiNandNot(struct descriptor *first, ...);
extern int TdiNdesc(struct descriptor *first, ...);
extern int TdiNe(struct descriptor *first, ...);
extern int TdiNearest(struct descriptor *first, ...);
extern int TdiNeqv(struct descriptor *first, ...);
extern int TdiNint(struct descriptor *first, ...);
extern int TdiNor(struct descriptor *first, ...);
extern int TdiNorNot(struct descriptor *first, ...);
extern int TdiNot(struct descriptor *first, ...);
extern int TdiObjectOf(struct descriptor *first, ...);
extern int TdiOctaword(struct descriptor *first, ...);
extern int TdiOctawordUnsigned(struct descriptor *first, ...);
extern int TdiOnError(struct descriptor *first, ...);
extern int TdiOpcodeBuiltin(struct descriptor *first, ...);
extern int TdiOpcodeString(struct descriptor *first, ...);
extern int TdiFopen(struct descriptor *first, ...);
extern int TdiOptional(struct descriptor *first, ...);
extern int TdiOr(struct descriptor *first, ...);
extern int TdiOrNot(struct descriptor *first, ...);
extern int TdiOut(struct descriptor *first, ...);
extern int TdiPack(struct descriptor *first, ...);
extern int TdiPhaseOf(struct descriptor *first, ...);
extern int TdiPostDec(struct descriptor *first, ...);
extern int TdiPostInc(struct descriptor *first, ...);
extern int TdiPower(struct descriptor *first, ...);
extern int TdiPresent(struct descriptor *first, ...);
extern int TdiPreDec(struct descriptor *first, ...);
extern int TdiPreInc(struct descriptor *first, ...);
extern int TdiPrivate(struct descriptor *first, ...);
extern int TdiProcedureOf(struct descriptor *first, ...);
extern int TdiProduct(struct descriptor *first, ...);
extern int TdiProgramOf(struct descriptor *first, ...);
extern int TdiProject(struct descriptor *first, ...);
extern int TdiPromote(struct descriptor *first, ...);
extern int TdiPublic(struct descriptor *first, ...);
extern int TdiQuadword(struct descriptor *first, ...);
extern int TdiQuadwordUnsigned(struct descriptor *first, ...);
extern int TdiQualifiersOf(struct descriptor *first, ...);
extern int TdiRadix(struct descriptor *first, ...);
extern int TdiRamp(struct descriptor *first, ...);
extern int TdiRandom(struct descriptor *first, ...);
extern int TdiRandomSeed(struct descriptor *first, ...);
extern int TdiDtypeRange(struct descriptor *first, ...);
extern int TdiRank(struct descriptor *first, ...);
extern int TdiRawOf(struct descriptor *first, ...);
extern int TdiRead(struct descriptor *first, ...);
extern int TdiReal(struct descriptor *first, ...);
extern int TdiRebin(struct descriptor *first, ...);
extern int TdiRef(struct descriptor *first, ...);
extern int TdiRepeat(struct descriptor *first, ...);
extern int TdiReplicate(struct descriptor *first, ...);
extern int TdiReshape(struct descriptor *first, ...);
extern int TdiReturn(struct descriptor *first, ...);
extern int TdiRewind(struct descriptor *first, ...);
extern int TdiRms(struct descriptor *first, ...);
extern int TdiRoutineOf(struct descriptor *first, ...);
extern int TdiRrSpacing(struct descriptor *first, ...);
extern int TdiScale(struct descriptor *first, ...);
extern int TdiScan(struct descriptor *first, ...);
extern int TdiFseek(struct descriptor *first, ...);
extern int TdiSetExponent(struct descriptor *first, ...);
extern int TdiSetRange(struct descriptor *first, ...);
extern int TdiIshft(struct descriptor *first, ...);
extern int TdiIshftc(struct descriptor *first, ...);
extern int TdiShiftLeft(struct descriptor *first, ...);
extern int TdiShiftRight(struct descriptor *first, ...);
extern int TdiSign(struct descriptor *first, ...);
extern int TdiSigned(struct descriptor *first, ...);
extern int TdiSin(struct descriptor *first, ...);
extern int TdiSind(struct descriptor *first, ...);
extern int TdiSinh(struct descriptor *first, ...);
extern int TdiSizeOf(struct descriptor *first, ...);
extern int TdiSlopeOf(struct descriptor *first, ...);
extern int TdiSmooth(struct descriptor *first, ...);
extern int TdiSolve(struct descriptor *first, ...);
extern int TdiSortVal(struct descriptor *first, ...);
extern int TdiSpacing(struct descriptor *first, ...);
extern int TdiSpawn(struct descriptor *first, ...);
extern int TdiSpread(struct descriptor *first, ...);
extern int TdiSqrt(struct descriptor *first, ...);
extern int TdiSquare(struct descriptor *first, ...);
extern int TdiStatement(struct descriptor *first, ...);
extern int TdiStdDev(struct descriptor *first, ...);
extern int TdiString(struct descriptor *first, ...);
extern int TdiStringOpcode(struct descriptor *first, ...);
extern int TdiSubscript(struct descriptor *first, ...);
extern int TdiSubtract(struct descriptor *first, ...);
extern int TdiSum(struct descriptor *first, ...);
extern int TdiSwitch(struct descriptor *first, ...);
extern int TdiSystemClock(struct descriptor *first, ...);
extern int TdiTan(struct descriptor *first, ...);
extern int TdiTand(struct descriptor *first, ...);
extern int TdiTanh(struct descriptor *first, ...);
extern int TdiTaskOf(struct descriptor *first, ...);
extern int TdiText(struct descriptor *first, ...);
extern int TdiTimeoutOf(struct descriptor *first, ...);
extern int TdiTiny(struct descriptor *first, ...);
extern int TdiTransfer(struct descriptor *first, ...);
extern int TdiTranspose_(struct descriptor *first, ...);
extern int TdiTrim(struct descriptor *first, ...);
extern int TdiUnaryMinus(struct descriptor *first, ...);
extern int TdiUnaryPlus(struct descriptor *first, ...);
extern int TdiUnion(struct descriptor *first, ...);
extern int TdiUnits(struct descriptor *first, ...);
extern int TdiUnitsOf(struct descriptor *first, ...);
extern int TdiUnpack(struct descriptor *first, ...);
extern int TdiUnsigned(struct descriptor *first, ...);
extern int TdiVal(struct descriptor *first, ...);
extern int TdiValidationOf(struct descriptor *first, ...);
extern int TdiValueOf(struct descriptor *first, ...);
extern int TdiVar(struct descriptor *first, ...);
extern int TdiVector(struct descriptor *first, ...);
extern int TdiVerify(struct descriptor *first, ...);
extern int TdiWait(struct descriptor *first, ...);
extern int TdiWhenOf(struct descriptor *first, ...);
extern int TdiWhere(struct descriptor *first, ...);
extern int TdiWhile(struct descriptor *first, ...);
extern int TdiWindowOf(struct descriptor *first, ...);
extern int TdiWord(struct descriptor *first, ...);
extern int TdiWordUnsigned(struct descriptor *first, ...);
extern int TdiWrite(struct descriptor *first, ...);
extern int TdiZero(struct descriptor *first, ...);
extern int Tdi2Pi(struct descriptor *first, ...);
extern int TdiNarg(struct descriptor *first, ...);
extern int TdiElement(struct descriptor *first, ...);
extern int TdiRcDroop(struct descriptor *first, ...);
extern int TdiResetPrivate(struct descriptor *first, ...);
extern int TdiResetPublic(struct descriptor *first, ...);
extern int TdiShowPrivate(struct descriptor *first, ...);
extern int TdiShowPublic(struct descriptor *first, ...);
extern int TdiShowVm(struct descriptor *first, ...);
extern int TdiTranslate(struct descriptor *first, ...);
extern int TdiTransposeMul(struct descriptor *first, ...);
extern int TdiUpcase(struct descriptor *first, ...);
extern int TdiUsing(struct descriptor *first, ...);
extern int TdiValidation(struct descriptor *first, ...);
extern int TdiMdsDefault(struct descriptor *first, ...);
extern int TdiExpt(struct descriptor *first, ...);
extern int TdiShot(struct descriptor *first, ...);
extern int TdiGetDbi(struct descriptor *first, ...);
extern int TdiCull(struct descriptor *first, ...);
extern int TdiExtend(struct descriptor *first, ...);
extern int TdiItoX(struct descriptor *first, ...);
extern int TdiXtoI(struct descriptor *first, ...);
extern int TdiMap(struct descriptor *first, ...);
extern int TdiCompileDependency(struct descriptor *first, ...);
extern int TdiDecompileDependency(struct descriptor *first, ...);
extern int TdiBuildCall(struct descriptor *first, ...);
extern int TdiErrorlogsOf(struct descriptor *first, ...);
extern int TdiPerformanceOf(struct descriptor *first, ...);
extern int TdiXd(struct descriptor *first, ...);
extern int TdiConditionOf(struct descriptor *first, ...);
extern int TdiSort(struct descriptor *first, ...);
extern int TdiThis(struct descriptor *first, ...);
extern int TdiDataWithUnits(struct descriptor *first, ...);
extern int TdiAtm(struct descriptor *first, ...);
extern int TdiEpsilon0(struct descriptor *first, ...);
extern int TdiGn(struct descriptor *first, ...);
extern int TdiMu0(struct descriptor *first, ...);
extern int TdiExtract(struct descriptor *first, ...);
extern int TdiFinite(struct descriptor *first, ...);
extern int TdiBitSize(struct descriptor *first, ...);
extern int TdiModulo(struct descriptor *first, ...);
extern int TdiSelectedIntKind(struct descriptor *first, ...);
extern int TdiSelectedRealKind(struct descriptor *first, ...);
extern int TdiDsql(struct descriptor *first, ...);
extern int TdiIsql(struct descriptor *first, ...);
extern int TdiFtell(struct descriptor *first, ...);
extern int TdiMakeAction(struct descriptor *first, ...);
extern int TdiMakeCondition(struct descriptor *first, ...);
extern int TdiMakeConglom(struct descriptor *first, ...);
extern int TdiMakeDependency(struct descriptor *first, ...);
extern int TdiMakeDim(struct descriptor *first, ...);
extern int TdiMakeDispatch(struct descriptor *first, ...);
extern int TdiMakeFunction(struct descriptor *first, ...);
extern int TdiMakeMethod(struct descriptor *first, ...);
extern int TdiMakeParam(struct descriptor *first, ...);
extern int TdiMakeProcedure(struct descriptor *first, ...);
extern int TdiMakeProgram(struct descriptor *first, ...);
extern int TdiMakeRange(struct descriptor *first, ...);
extern int TdiMakeRoutine(struct descriptor *first, ...);
extern int TdiMakeSignal(struct descriptor *first, ...);
extern int TdiMakeWindow(struct descriptor *first, ...);
extern int TdiMakeWithUnits(struct descriptor *first, ...);
extern int TdiMakeCall(struct descriptor *first, ...);
extern int TdiClassOf(struct descriptor *first, ...);
extern int TdiDscptrOf(struct descriptor *first, ...);
extern int TdiKindOf(struct descriptor *first, ...);
extern int TdiNdescOf(struct descriptor *first, ...);
extern int TdiAccumulate(struct descriptor *first, ...);
extern int TdiMakeSlope(struct descriptor *first, ...);
extern int TdiRem(struct descriptor *first, ...);
extern int TdiCompletionMessageOf(struct descriptor *first, ...);
extern int TdiInterruptOf(struct descriptor *first, ...);
extern int TdiShotname(struct descriptor *first, ...);
extern int TdiBuildWithError(struct descriptor *first, ...);
extern int TdiErrorOf(struct descriptor *first, ...);
extern int TdiMakeWithError(struct descriptor *first, ...);
extern int TdiDoTask(struct descriptor *first, ...);
extern int TdiIsqlSet(struct descriptor *first, ...);
extern int TdiFS_float(struct descriptor *first, ...);
extern int TdiFS_complex(struct descriptor *first, ...);
extern int TdiFT_float(struct descriptor *first, ...);
extern int TdiFT_complex(struct descriptor *first, ...);
extern int TdiBuildOpaque(struct descriptor *first, ...);
extern int TdiMakeOpaque(struct descriptor *first, ...);
extern int TdiDict(struct descriptor *first, ...);
extern int TdiTuple(struct descriptor *first, ...);
extern int TdiList(struct descriptor *first, ...);
extern int TdiSqueeze(struct descriptor *first, ...);
extern int TdiFlatten(struct descriptor *first, ...);

extern int _Tdidollar(void **ctx, struct descriptor *first, ...);
extern int _TdiA0(void **ctx, struct descriptor *first, ...);
extern int _TdiAlpha(void **ctx, struct descriptor *first, ...);
extern int _TdiAmu(void **ctx, struct descriptor *first, ...);
extern int _TdiC(void **ctx, struct descriptor *first, ...);
extern int _TdiCal(void **ctx, struct descriptor *first, ...);
extern int _TdiDegree(void **ctx, struct descriptor *first, ...);
extern int _TdiEv(void **ctx, struct descriptor *first, ...);
extern int _TdiFalse(void **ctx, struct descriptor *first, ...);
extern int _TdiFaraday(void **ctx, struct descriptor *first, ...);
extern int _TdiG(void **ctx, struct descriptor *first, ...);
extern int _TdiGas(void **ctx, struct descriptor *first, ...);
extern int _TdiH(void **ctx, struct descriptor *first, ...);
extern int _TdiHbar(void **ctx, struct descriptor *first, ...);
extern int _TdiI(void **ctx, struct descriptor *first, ...);
extern int _TdiK(void **ctx, struct descriptor *first, ...);
extern int _TdiMe(void **ctx, struct descriptor *first, ...);
extern int _TdiMissing(void **ctx, struct descriptor *first, ...);
extern int _TdiMp(void **ctx, struct descriptor *first, ...);
extern int _TdiN0(void **ctx, struct descriptor *first, ...);
extern int _TdiNa(void **ctx, struct descriptor *first, ...);
extern int _TdiP0(void **ctx, struct descriptor *first, ...);
extern int _TdiPi(void **ctx, struct descriptor *first, ...);
extern int _TdiQe(void **ctx, struct descriptor *first, ...);
extern int _TdiRe(void **ctx, struct descriptor *first, ...);
extern int _TdiRoprand(void **ctx, struct descriptor *first, ...);
extern int _TdiRydberg(void **ctx, struct descriptor *first, ...);
extern int _TdiT0(void **ctx, struct descriptor *first, ...);
extern int _TdiTorr(void **ctx, struct descriptor *first, ...);
extern int _TdiTrue(void **ctx, struct descriptor *first, ...);
extern int _TdiValue(void **ctx, struct descriptor *first, ...);
extern int _TdiAbort(void **ctx, struct descriptor *first, ...);
extern int _TdiAbs(void **ctx, struct descriptor *first, ...);
extern int _TdiAbs1(void **ctx, struct descriptor *first, ...);
extern int _TdiAbsSq(void **ctx, struct descriptor *first, ...);
extern int _TdiAchar(void **ctx, struct descriptor *first, ...);
extern int _TdiAcos(void **ctx, struct descriptor *first, ...);
extern int _TdiAcosd(void **ctx, struct descriptor *first, ...);
extern int _TdiAdd(void **ctx, struct descriptor *first, ...);
extern int _TdiAdjustl(void **ctx, struct descriptor *first, ...);
extern int _TdiAdjustr(void **ctx, struct descriptor *first, ...);
extern int _TdiAimag(void **ctx, struct descriptor *first, ...);
extern int _TdiAint(void **ctx, struct descriptor *first, ...);
extern int _TdiAll(void **ctx, struct descriptor *first, ...);
extern int _TdiAllocated(void **ctx, struct descriptor *first, ...);
extern int _TdiAnd(void **ctx, struct descriptor *first, ...);
extern int _TdiAndNot(void **ctx, struct descriptor *first, ...);
extern int _TdiAnint(void **ctx, struct descriptor *first, ...);
extern int _TdiAny(void **ctx, struct descriptor *first, ...);
extern int _TdiArg(void **ctx, struct descriptor *first, ...);
extern int _TdiArgd(void **ctx, struct descriptor *first, ...);
extern int _TdiArgOf(void **ctx, struct descriptor *first, ...);
extern int _TdiArray(void **ctx, struct descriptor *first, ...);
extern int _TdiAsin(void **ctx, struct descriptor *first, ...);
extern int _TdiAsind(void **ctx, struct descriptor *first, ...);
extern int _TdiAsIs(void **ctx, struct descriptor *first, ...);
extern int _TdiAtan(void **ctx, struct descriptor *first, ...);
extern int _TdiAtan2(void **ctx, struct descriptor *first, ...);
extern int _TdiAtan2d(void **ctx, struct descriptor *first, ...);
extern int _TdiAtand(void **ctx, struct descriptor *first, ...);
extern int _TdiAtanh(void **ctx, struct descriptor *first, ...);
extern int _TdiAxisOf(void **ctx, struct descriptor *first, ...);
extern int _TdiBackspace(void **ctx, struct descriptor *first, ...);
extern int _TdiIbclr(void **ctx, struct descriptor *first, ...);
extern int _TdiBeginOf(void **ctx, struct descriptor *first, ...);
extern int _TdiIbits(void **ctx, struct descriptor *first, ...);
extern int _TdiBreak(void **ctx, struct descriptor *first, ...);
extern int _TdiBsearch(void **ctx, struct descriptor *first, ...);
extern int _TdiIbset(void **ctx, struct descriptor *first, ...);
extern int _TdiBtest(void **ctx, struct descriptor *first, ...);
extern int _TdiBuildAction(void **ctx, struct descriptor *first, ...);
extern int _TdiBuildCondition(void **ctx, struct descriptor *first, ...);
extern int _TdiBuildConglom(void **ctx, struct descriptor *first, ...);
extern int _TdiBuildDependency(void **ctx, struct descriptor *first, ...);
extern int _TdiBuildDim(void **ctx, struct descriptor *first, ...);
extern int _TdiBuildDispatch(void **ctx, struct descriptor *first, ...);
extern int _TdiBuildEvent(void **ctx, struct descriptor *first, ...);
extern int _TdiBuildFunction(void **ctx, struct descriptor *first, ...);
extern int _TdiBuildMethod(void **ctx, struct descriptor *first, ...);
extern int _TdiBuildParam(void **ctx, struct descriptor *first, ...);
extern int _TdiBuildPath(void **ctx, struct descriptor *first, ...);
extern int _TdiBuildProcedure(void **ctx, struct descriptor *first, ...);
extern int _TdiBuildProgram(void **ctx, struct descriptor *first, ...);
extern int _TdiBuildRange(void **ctx, struct descriptor *first, ...);
extern int _TdiBuildRoutine(void **ctx, struct descriptor *first, ...);
extern int _TdiBuildSignal(void **ctx, struct descriptor *first, ...);
extern int _TdiBuildSlope(void **ctx, struct descriptor *first, ...);
extern int _TdiBuildWindow(void **ctx, struct descriptor *first, ...);
extern int _TdiBuildWithUnits(void **ctx, struct descriptor *first, ...);
extern int _TdiBuiltinOpcode(void **ctx, struct descriptor *first, ...);
extern int _TdiByte(void **ctx, struct descriptor *first, ...);
extern int _TdiByteUnsigned(void **ctx, struct descriptor *first, ...);
extern int _TdiCase(void **ctx, struct descriptor *first, ...);
extern int _TdiCeiling(void **ctx, struct descriptor *first, ...);
extern int _TdiChar(void **ctx, struct descriptor *first, ...);
extern int _TdiClass(void **ctx, struct descriptor *first, ...);
extern int _TdiFclose(void **ctx, struct descriptor *first, ...);
extern int _TdiCmplx(void **ctx, struct descriptor *first, ...);
extern int _TdiComma(void **ctx, struct descriptor *first, ...);
extern int _TdiCompile(void **ctx, struct descriptor *first, ...);
extern int _TdiCompletionOf(void **ctx, struct descriptor *first, ...);
extern int _TdiConcat(void **ctx, struct descriptor *first, ...);
extern int _TdiConditional(void **ctx, struct descriptor *first, ...);
extern int _TdiConjg(void **ctx, struct descriptor *first, ...);
extern int _TdiContinue(void **ctx, struct descriptor *first, ...);
extern int _TdiConvolve(void **ctx, struct descriptor *first, ...);
extern int _TdiCos(void **ctx, struct descriptor *first, ...);
extern int _TdiCosd(void **ctx, struct descriptor *first, ...);
extern int _TdiCosh(void **ctx, struct descriptor *first, ...);
extern int _TdiCount(void **ctx, struct descriptor *first, ...);
extern int _TdiCshift(void **ctx, struct descriptor *first, ...);
extern int _TdiCvt(void **ctx, struct descriptor *first, ...);
extern int _TdiData(void **ctx, struct descriptor *first, ...);
extern int _TdiDateAndTime(void **ctx, struct descriptor *first, ...);
extern int _TdiDateTime(void **ctx, struct descriptor *first, ...);
extern int _TdiDble(void **ctx, struct descriptor *first, ...);
extern int _TdiDeallocate(void **ctx, struct descriptor *first, ...);
extern int _TdiDebug(void **ctx, struct descriptor *first, ...);
extern int _TdiDecode(void **ctx, struct descriptor *first, ...);
extern int _TdiDecompile(void **ctx, struct descriptor *first, ...);
extern int _TdiDecompress(void **ctx, struct descriptor *first, ...);
extern int _TdiDefault(void **ctx, struct descriptor *first, ...);
extern int _TdiDerivative(void **ctx, struct descriptor *first, ...);
extern int _TdiDescr(void **ctx, struct descriptor *first, ...);
extern int _TdiDiagonal(void **ctx, struct descriptor *first, ...);
extern int _TdiDigits(void **ctx, struct descriptor *first, ...);
extern int _TdiDim(void **ctx, struct descriptor *first, ...);
extern int _TdiDimOf(void **ctx, struct descriptor *first, ...);
extern int _TdiDispatchOf(void **ctx, struct descriptor *first, ...);
extern int _TdiDivide(void **ctx, struct descriptor *first, ...);
extern int _TdiLbound(void **ctx, struct descriptor *first, ...);
extern int _TdiDo(void **ctx, struct descriptor *first, ...);
extern int _TdiDotProduct(void **ctx, struct descriptor *first, ...);
extern int _TdiDprod(void **ctx, struct descriptor *first, ...);
extern int _TdiDscptr(void **ctx, struct descriptor *first, ...);
extern int _TdiShape(void **ctx, struct descriptor *first, ...);
extern int _TdiSize(void **ctx, struct descriptor *first, ...);
extern int _TdiKind(void **ctx, struct descriptor *first, ...);
extern int _TdiUbound(void **ctx, struct descriptor *first, ...);
extern int _TdiDComplex(void **ctx, struct descriptor *first, ...);
extern int _TdiDFloat(void **ctx, struct descriptor *first, ...);
extern int _TdiRange(void **ctx, struct descriptor *first, ...);
extern int _TdiPrecision(void **ctx, struct descriptor *first, ...);
extern int _TdiElbound(void **ctx, struct descriptor *first, ...);
extern int _TdiElse(void **ctx, struct descriptor *first, ...);
extern int _TdiElsewhere(void **ctx, struct descriptor *first, ...);
extern int _TdiEncode(void **ctx, struct descriptor *first, ...);
extern int _TdiEndfile(void **ctx, struct descriptor *first, ...);
extern int _TdiEndOf(void **ctx, struct descriptor *first, ...);
extern int _TdiEoshift(void **ctx, struct descriptor *first, ...);
extern int _TdiEpsilon(void **ctx, struct descriptor *first, ...);
extern int _TdiEq(void **ctx, struct descriptor *first, ...);
extern int _TdiEquals(void **ctx, struct descriptor *first, ...);
extern int _TdiEqualsFirst(void **ctx, struct descriptor *first, ...);
extern int _TdiEqv(void **ctx, struct descriptor *first, ...);
extern int _TdiEshape(void **ctx, struct descriptor *first, ...);
extern int _TdiEsize(void **ctx, struct descriptor *first, ...);
extern int _TdiEubound(void **ctx, struct descriptor *first, ...);
extern int _TdiEvaluate(void **ctx, struct descriptor *first, ...);
extern int _TdiExecute(void **ctx, struct descriptor *first, ...);
extern int _TdiExp(void **ctx, struct descriptor *first, ...);
extern int _TdiExponent(void **ctx, struct descriptor *first, ...);
extern int _TdiExtFunction(void **ctx, struct descriptor *first, ...);
extern int _TdiFft(void **ctx, struct descriptor *first, ...);
extern int _TdiFirstLoc(void **ctx, struct descriptor *first, ...);
extern int _TdiFit(void **ctx, struct descriptor *first, ...);
extern int _TdiFixRoprand(void **ctx, struct descriptor *first, ...);
extern int _TdiFloat(void **ctx, struct descriptor *first, ...);
extern int _TdiFloor(void **ctx, struct descriptor *first, ...);
extern int _TdiFor(void **ctx, struct descriptor *first, ...);
extern int _TdiFraction(void **ctx, struct descriptor *first, ...);
extern int _TdiFun(void **ctx, struct descriptor *first, ...);
extern int _TdiFComplex(void **ctx, struct descriptor *first, ...);
extern int _TdiFFloat(void **ctx, struct descriptor *first, ...);
extern int _TdiGe(void **ctx, struct descriptor *first, ...);
extern int _TdiGetNci(void **ctx, struct descriptor *first, ...);
extern int _TdiGoto(void **ctx, struct descriptor *first, ...);
extern int _TdiGt(void **ctx, struct descriptor *first, ...);
extern int _TdiGComplex(void **ctx, struct descriptor *first, ...);
extern int _TdiGFloat(void **ctx, struct descriptor *first, ...);
extern int _TdiHelpOf(void **ctx, struct descriptor *first, ...);
extern int _TdiHuge(void **ctx, struct descriptor *first, ...);
extern int _TdiHComplex(void **ctx, struct descriptor *first, ...);
extern int _TdiHFloat(void **ctx, struct descriptor *first, ...);
extern int _TdiIachar(void **ctx, struct descriptor *first, ...);
extern int _TdiIand(void **ctx, struct descriptor *first, ...);
extern int _TdiIandNot(void **ctx, struct descriptor *first, ...);
extern int _TdiIchar(void **ctx, struct descriptor *first, ...);
extern int _TdiIdentOf(void **ctx, struct descriptor *first, ...);
extern int _TdiIf(void **ctx, struct descriptor *first, ...);
extern int _TdiIfError(void **ctx, struct descriptor *first, ...);
extern int _TdiImageOf(void **ctx, struct descriptor *first, ...);
extern int _TdiIn(void **ctx, struct descriptor *first, ...);
extern int _TdiInand(void **ctx, struct descriptor *first, ...);
extern int _TdiInandNot(void **ctx, struct descriptor *first, ...);
extern int _TdiIndex(void **ctx, struct descriptor *first, ...);
extern int _TdiInor(void **ctx, struct descriptor *first, ...);
extern int _TdiInorNot(void **ctx, struct descriptor *first, ...);
extern int _TdiInot(void **ctx, struct descriptor *first, ...);
extern int _TdiInOut(void **ctx, struct descriptor *first, ...);
extern int _TdiInquire(void **ctx, struct descriptor *first, ...);
extern int _TdiInt(void **ctx, struct descriptor *first, ...);
extern int _TdiIntegral(void **ctx, struct descriptor *first, ...);
extern int _TdiInterpol(void **ctx, struct descriptor *first, ...);
extern int _TdiIntersect(void **ctx, struct descriptor *first, ...);
extern int _TdiIntUnsigned(void **ctx, struct descriptor *first, ...);
extern int _TdiInverse(void **ctx, struct descriptor *first, ...);
extern int _TdiIor(void **ctx, struct descriptor *first, ...);
extern int _TdiIorNot(void **ctx, struct descriptor *first, ...);
extern int _TdiIsIn(void **ctx, struct descriptor *first, ...);
extern int _TdiIeor(void **ctx, struct descriptor *first, ...);
extern int _TdiIeorNot(void **ctx, struct descriptor *first, ...);
extern int _TdiLabel(void **ctx, struct descriptor *first, ...);
extern int _TdiLaminate(void **ctx, struct descriptor *first, ...);
extern int _TdiLanguageOf(void **ctx, struct descriptor *first, ...);
extern int _TdiLastLoc(void **ctx, struct descriptor *first, ...);
extern int _TdiLe(void **ctx, struct descriptor *first, ...);
extern int _TdiLen(void **ctx, struct descriptor *first, ...);
extern int _TdiLenTrim(void **ctx, struct descriptor *first, ...);
extern int _TdiLge(void **ctx, struct descriptor *first, ...);
extern int _TdiLgt(void **ctx, struct descriptor *first, ...);
extern int _TdiLle(void **ctx, struct descriptor *first, ...);
extern int _TdiLlt(void **ctx, struct descriptor *first, ...);
extern int _TdiLog(void **ctx, struct descriptor *first, ...);
extern int _TdiLog10(void **ctx, struct descriptor *first, ...);
extern int _TdiLog2(void **ctx, struct descriptor *first, ...);
extern int _TdiLogical(void **ctx, struct descriptor *first, ...);
extern int _TdiLong(void **ctx, struct descriptor *first, ...);
extern int _TdiLongUnsigned(void **ctx, struct descriptor *first, ...);
extern int _TdiLt(void **ctx, struct descriptor *first, ...);
extern int _TdiMatmul(void **ctx, struct descriptor *first, ...);
extern int _TdiMatRot(void **ctx, struct descriptor *first, ...);
extern int _TdiMatRotInt(void **ctx, struct descriptor *first, ...);
extern int _TdiMax(void **ctx, struct descriptor *first, ...);
extern int _TdiMaxExponent(void **ctx, struct descriptor *first, ...);
extern int _TdiMaxLoc(void **ctx, struct descriptor *first, ...);
extern int _TdiMaxVal(void **ctx, struct descriptor *first, ...);
extern int _TdiMean(void **ctx, struct descriptor *first, ...);
extern int _TdiMedian(void **ctx, struct descriptor *first, ...);
extern int _TdiMerge(void **ctx, struct descriptor *first, ...);
extern int _TdiMethodOf(void **ctx, struct descriptor *first, ...);
extern int _TdiMin(void **ctx, struct descriptor *first, ...);
extern int _TdiMinExponent(void **ctx, struct descriptor *first, ...);
extern int _TdiMinLoc(void **ctx, struct descriptor *first, ...);
extern int _TdiMinVal(void **ctx, struct descriptor *first, ...);
extern int _TdiMod(void **ctx, struct descriptor *first, ...);
extern int _TdiModelOf(void **ctx, struct descriptor *first, ...);
extern int _TdiMultiply(void **ctx, struct descriptor *first, ...);
extern int _TdiNameOf(void **ctx, struct descriptor *first, ...);
extern int _TdiNand(void **ctx, struct descriptor *first, ...);
extern int _TdiNandNot(void **ctx, struct descriptor *first, ...);
extern int _TdiNdesc(void **ctx, struct descriptor *first, ...);
extern int _TdiNe(void **ctx, struct descriptor *first, ...);
extern int _TdiNearest(void **ctx, struct descriptor *first, ...);
extern int _TdiNeqv(void **ctx, struct descriptor *first, ...);
extern int _TdiNint(void **ctx, struct descriptor *first, ...);
extern int _TdiNor(void **ctx, struct descriptor *first, ...);
extern int _TdiNorNot(void **ctx, struct descriptor *first, ...);
extern int _TdiNot(void **ctx, struct descriptor *first, ...);
extern int _TdiObjectOf(void **ctx, struct descriptor *first, ...);
extern int _TdiOctaword(void **ctx, struct descriptor *first, ...);
extern int _TdiOctawordUnsigned(void **ctx, struct descriptor *first, ...);
extern int _TdiOnError(void **ctx, struct descriptor *first, ...);
extern int _TdiOpcodeBuiltin(void **ctx, struct descriptor *first, ...);
extern int _TdiOpcodeString(void **ctx, struct descriptor *first, ...);
extern int _TdiFopen(void **ctx, struct descriptor *first, ...);
extern int _TdiOptional(void **ctx, struct descriptor *first, ...);
extern int _TdiOr(void **ctx, struct descriptor *first, ...);
extern int _TdiOrNot(void **ctx, struct descriptor *first, ...);
extern int _TdiOut(void **ctx, struct descriptor *first, ...);
extern int _TdiPack(void **ctx, struct descriptor *first, ...);
extern int _TdiPhaseOf(void **ctx, struct descriptor *first, ...);
extern int _TdiPostDec(void **ctx, struct descriptor *first, ...);
extern int _TdiPostInc(void **ctx, struct descriptor *first, ...);
extern int _TdiPower(void **ctx, struct descriptor *first, ...);
extern int _TdiPresent(void **ctx, struct descriptor *first, ...);
extern int _TdiPreDec(void **ctx, struct descriptor *first, ...);
extern int _TdiPreInc(void **ctx, struct descriptor *first, ...);
extern int _TdiPrivate(void **ctx, struct descriptor *first, ...);
extern int _TdiProcedureOf(void **ctx, struct descriptor *first, ...);
extern int _TdiProduct(void **ctx, struct descriptor *first, ...);
extern int _TdiProgramOf(void **ctx, struct descriptor *first, ...);
extern int _TdiProject(void **ctx, struct descriptor *first, ...);
extern int _TdiPromote(void **ctx, struct descriptor *first, ...);
extern int _TdiPublic(void **ctx, struct descriptor *first, ...);
extern int _TdiQuadword(void **ctx, struct descriptor *first, ...);
extern int _TdiQuadwordUnsigned(void **ctx, struct descriptor *first, ...);
extern int _TdiQualifiersOf(void **ctx, struct descriptor *first, ...);
extern int _TdiRadix(void **ctx, struct descriptor *first, ...);
extern int _TdiRamp(void **ctx, struct descriptor *first, ...);
extern int _TdiRandom(void **ctx, struct descriptor *first, ...);
extern int _TdiRandomSeed(void **ctx, struct descriptor *first, ...);
extern int _TdiDtypeRange(void **ctx, struct descriptor *first, ...);
extern int _TdiRank(void **ctx, struct descriptor *first, ...);
extern int _TdiRawOf(void **ctx, struct descriptor *first, ...);
extern int _TdiRead(void **ctx, struct descriptor *first, ...);
extern int _TdiReal(void **ctx, struct descriptor *first, ...);
extern int _TdiRebin(void **ctx, struct descriptor *first, ...);
extern int _TdiRef(void **ctx, struct descriptor *first, ...);
extern int _TdiRepeat(void **ctx, struct descriptor *first, ...);
extern int _TdiReplicate(void **ctx, struct descriptor *first, ...);
extern int _TdiReshape(void **ctx, struct descriptor *first, ...);
extern int _TdiReturn(void **ctx, struct descriptor *first, ...);
extern int _TdiRewind(void **ctx, struct descriptor *first, ...);
extern int _TdiRms(void **ctx, struct descriptor *first, ...);
extern int _TdiRoutineOf(void **ctx, struct descriptor *first, ...);
extern int _TdiRrSpacing(void **ctx, struct descriptor *first, ...);
extern int _TdiScale(void **ctx, struct descriptor *first, ...);
extern int _TdiScan(void **ctx, struct descriptor *first, ...);
extern int _TdiFseek(void **ctx, struct descriptor *first, ...);
extern int _TdiSetExponent(void **ctx, struct descriptor *first, ...);
extern int _TdiSetRange(void **ctx, struct descriptor *first, ...);
extern int _TdiIshft(void **ctx, struct descriptor *first, ...);
extern int _TdiIshftc(void **ctx, struct descriptor *first, ...);
extern int _TdiShiftLeft(void **ctx, struct descriptor *first, ...);
extern int _TdiShiftRight(void **ctx, struct descriptor *first, ...);
extern int _TdiSign(void **ctx, struct descriptor *first, ...);
extern int _TdiSigned(void **ctx, struct descriptor *first, ...);
extern int _TdiSin(void **ctx, struct descriptor *first, ...);
extern int _TdiSind(void **ctx, struct descriptor *first, ...);
extern int _TdiSinh(void **ctx, struct descriptor *first, ...);
extern int _TdiSizeOf(void **ctx, struct descriptor *first, ...);
extern int _TdiSlopeOf(void **ctx, struct descriptor *first, ...);
extern int _TdiSmooth(void **ctx, struct descriptor *first, ...);
extern int _TdiSolve(void **ctx, struct descriptor *first, ...);
extern int _TdiSortVal(void **ctx, struct descriptor *first, ...);
extern int _TdiSpacing(void **ctx, struct descriptor *first, ...);
extern int _TdiSpawn(void **ctx, struct descriptor *first, ...);
extern int _TdiSpread(void **ctx, struct descriptor *first, ...);
extern int _TdiSqrt(void **ctx, struct descriptor *first, ...);
extern int _TdiSquare(void **ctx, struct descriptor *first, ...);
extern int _TdiStatement(void **ctx, struct descriptor *first, ...);
extern int _TdiStdDev(void **ctx, struct descriptor *first, ...);
extern int _TdiString(void **ctx, struct descriptor *first, ...);
extern int _TdiStringOpcode(void **ctx, struct descriptor *first, ...);
extern int _TdiSubscript(void **ctx, struct descriptor *first, ...);
extern int _TdiSubtract(void **ctx, struct descriptor *first, ...);
extern int _TdiSum(void **ctx, struct descriptor *first, ...);
extern int _TdiSwitch(void **ctx, struct descriptor *first, ...);
extern int _TdiSystemClock(void **ctx, struct descriptor *first, ...);
extern int _TdiTan(void **ctx, struct descriptor *first, ...);
extern int _TdiTand(void **ctx, struct descriptor *first, ...);
extern int _TdiTanh(void **ctx, struct descriptor *first, ...);
extern int _TdiTaskOf(void **ctx, struct descriptor *first, ...);
extern int _TdiText(void **ctx, struct descriptor *first, ...);
extern int _TdiTimeoutOf(void **ctx, struct descriptor *first, ...);
extern int _TdiTiny(void **ctx, struct descriptor *first, ...);
extern int _TdiTransfer(void **ctx, struct descriptor *first, ...);
extern int _TdiTranspose_(void **ctx, struct descriptor *first, ...);
extern int _TdiTrim(void **ctx, struct descriptor *first, ...);
extern int _TdiUnaryMinus(void **ctx, struct descriptor *first, ...);
extern int _TdiUnaryPlus(void **ctx, struct descriptor *first, ...);
extern int _TdiUnion(void **ctx, struct descriptor *first, ...);
extern int _TdiUnits(void **ctx, struct descriptor *first, ...);
extern int _TdiUnitsOf(void **ctx, struct descriptor *first, ...);
extern int _TdiUnpack(void **ctx, struct descriptor *first, ...);
extern int _TdiUnsigned(void **ctx, struct descriptor *first, ...);
extern int _TdiVal(void **ctx, struct descriptor *first, ...);
extern int _TdiValidationOf(void **ctx, struct descriptor *first, ...);
extern int _TdiValueOf(void **ctx, struct descriptor *first, ...);
extern int _TdiVar(void **ctx, struct descriptor *first, ...);
extern int _TdiVector(void **ctx, struct descriptor *first, ...);
extern int _TdiVerify(void **ctx, struct descriptor *first, ...);
extern int _TdiWait(void **ctx, struct descriptor *first, ...);
extern int _TdiWhenOf(void **ctx, struct descriptor *first, ...);
extern int _TdiWhere(void **ctx, struct descriptor *first, ...);
extern int _TdiWhile(void **ctx, struct descriptor *first, ...);
extern int _TdiWindowOf(void **ctx, struct descriptor *first, ...);
extern int _TdiWord(void **ctx, struct descriptor *first, ...);
extern int _TdiWordUnsigned(void **ctx, struct descriptor *first, ...);
extern int _TdiWrite(void **ctx, struct descriptor *first, ...);
extern int _TdiZero(void **ctx, struct descriptor *first, ...);
extern int _Tdi2Pi(void **ctx, struct descriptor *first, ...);
extern int _TdiNarg(void **ctx, struct descriptor *first, ...);
extern int _TdiElement(void **ctx, struct descriptor *first, ...);
extern int _TdiRcDroop(void **ctx, struct descriptor *first, ...);
extern int _TdiResetPrivate(void **ctx, struct descriptor *first, ...);
extern int _TdiResetPublic(void **ctx, struct descriptor *first, ...);
extern int _TdiShowPrivate(void **ctx, struct descriptor *first, ...);
extern int _TdiShowPublic(void **ctx, struct descriptor *first, ...);
extern int _TdiShowVm(void **ctx, struct descriptor *first, ...);
extern int _TdiTranslate(void **ctx, struct descriptor *first, ...);
extern int _TdiTransposeMul(void **ctx, struct descriptor *first, ...);
extern int _TdiUpcase(void **ctx, struct descriptor *first, ...);
extern int _TdiUsing(void **ctx, struct descriptor *first, ...);
extern int _TdiValidation(void **ctx, struct descriptor *first, ...);
extern int _TdiMdsDefault(void **ctx, struct descriptor *first, ...);
extern int _TdiExpt(void **ctx, struct descriptor *first, ...);
extern int _TdiShot(void **ctx, struct descriptor *first, ...);
extern int _TdiGetDbi(void **ctx, struct descriptor *first, ...);
extern int _TdiCull(void **ctx, struct descriptor *first, ...);
extern int _TdiExtend(void **ctx, struct descriptor *first, ...);
extern int _TdiItoX(void **ctx, struct descriptor *first, ...);
extern int _TdiXtoI(void **ctx, struct descriptor *first, ...);
extern int _TdiMap(void **ctx, struct descriptor *first, ...);
extern int _TdiCompileDependency(void **ctx, struct descriptor *first, ...);
extern int _TdiDecompileDependency(void **ctx, struct descriptor *first, ...);
extern int _TdiBuildCall(void **ctx, struct descriptor *first, ...);
extern int _TdiErrorlogsOf(void **ctx, struct descriptor *first, ...);
extern int _TdiPerformanceOf(void **ctx, struct descriptor *first, ...);
extern int _TdiXd(void **ctx, struct descriptor *first, ...);
extern int _TdiConditionOf(void **ctx, struct descriptor *first, ...);
extern int _TdiSort(void **ctx, struct descriptor *first, ...);
extern int _TdiThis(void **ctx, struct descriptor *first, ...);
extern int _TdiDataWithUnits(void **ctx, struct descriptor *first, ...);
extern int _TdiAtm(void **ctx, struct descriptor *first, ...);
extern int _TdiEpsilon0(void **ctx, struct descriptor *first, ...);
extern int _TdiGn(void **ctx, struct descriptor *first, ...);
extern int _TdiMu0(void **ctx, struct descriptor *first, ...);
extern int _TdiExtract(void **ctx, struct descriptor *first, ...);
extern int _TdiFinite(void **ctx, struct descriptor *first, ...);
extern int _TdiBitSize(void **ctx, struct descriptor *first, ...);
extern int _TdiModulo(void **ctx, struct descriptor *first, ...);
extern int _TdiSelectedIntKind(void **ctx, struct descriptor *first, ...);
extern int _TdiSelectedRealKind(void **ctx, struct descriptor *first, ...);
extern int _TdiDsql(void **ctx, struct descriptor *first, ...);
extern int _TdiIsql(void **ctx, struct descriptor *first, ...);
extern int _TdiFtell(void **ctx, struct descriptor *first, ...);
extern int _TdiMakeAction(void **ctx, struct descriptor *first, ...);
extern int _TdiMakeCondition(void **ctx, struct descriptor *first, ...);
extern int _TdiMakeConglom(void **ctx, struct descriptor *first, ...);
extern int _TdiMakeDependency(void **ctx, struct descriptor *first, ...);
extern int _TdiMakeDim(void **ctx, struct descriptor *first, ...);
extern int _TdiMakeDispatch(void **ctx, struct descriptor *first, ...);
extern int _TdiMakeFunction(void **ctx, struct descriptor *first, ...);
extern int _TdiMakeMethod(void **ctx, struct descriptor *first, ...);
extern int _TdiMakeParam(void **ctx, struct descriptor *first, ...);
extern int _TdiMakeProcedure(void **ctx, struct descriptor *first, ...);
extern int _TdiMakeProgram(void **ctx, struct descriptor *first, ...);
extern int _TdiMakeRange(void **ctx, struct descriptor *first, ...);
extern int _TdiMakeRoutine(void **ctx, struct descriptor *first, ...);
extern int _TdiMakeSignal(void **ctx, struct descriptor *first, ...);
extern int _TdiMakeWindow(void **ctx, struct descriptor *first, ...);
extern int _TdiMakeWithUnits(void **ctx, struct descriptor *first, ...);
extern int _TdiMakeCall(void **ctx, struct descriptor *first, ...);
extern int _TdiClassOf(void **ctx, struct descriptor *first, ...);
extern int _TdiDscptrOf(void **ctx, struct descriptor *first, ...);
extern int _TdiKindOf(void **ctx, struct descriptor *first, ...);
extern int _TdiNdescOf(void **ctx, struct descriptor *first, ...);
extern int _TdiAccumulate(void **ctx, struct descriptor *first, ...);
extern int _TdiMakeSlope(void **ctx, struct descriptor *first, ...);
extern int _TdiRem(void **ctx, struct descriptor *first, ...);
extern int _TdiCompletionMessageOf(void **ctx, struct descriptor *first, ...);
extern int _TdiInterruptOf(void **ctx, struct descriptor *first, ...);
extern int _TdiShotname(void **ctx, struct descriptor *first, ...);
extern int _TdiBuildWithError(void **ctx, struct descriptor *first, ...);
extern int _TdiErrorOf(void **ctx, struct descriptor *first, ...);
extern int _TdiMakeWithError(void **ctx, struct descriptor *first, ...);
extern int _TdiDoTask(void **ctx, struct descriptor *first, ...);
extern int _TdiIsqlSet(void **ctx, struct descriptor *first, ...);
extern int _TdiFS_float(void **ctx, struct descriptor *first, ...);
extern int _TdiFS_complex(void **ctx, struct descriptor *first, ...);
extern int _TdiFT_float(void **ctx, struct descriptor *first, ...);
extern int _TdiFT_complex(void **ctx, struct descriptor *first, ...);
extern int _TdiBuildOpaque(void **ctx, struct descriptor *first, ...);
extern int _TdiMakeOpaque(void **ctx, struct descriptor *first, ...);
extern int _TdiDict(void **ctx, struct descriptor *first, ...);
extern int _TdiTuple(void **ctx, struct descriptor *first, ...);
extern int _TdiList(void **ctx, struct descriptor *first, ...);
extern int _TdiSqueeze(void **ctx, struct descriptor *first, ...);
extern int _TdiFlatten(void **ctx, struct descriptor *first, ...);

#endif
