#!/bin/bash
flavor=$1
pkg=$2
version=$3
release=$4
dist=$5
rm -Rf ${WORKSPACE}/debian/${pkg}
for f in `awk '{if (substr($1,1,1) == "%") {if ($1=="%files" || substr($1,1,5)=="%defa") F=1; else F=0;}; if (F==1 && substr($1,1,1) == "/") print $1}' ${WORKSPACE}/rpm/subpackages/${pkg}`
do 
    mkdir -p ${WORKSPACE}/debian/${pkg}$(dirname ${f})
    rsync -a ${WORKSPACE}/BUILDROOT${f} ${WORKSPACE}/debian/${pkg}$(dirname ${f})
done
for f in `awk '{if (substr($1,1,1) == "%") {if ($1=="%exclude") print $2;}}' ${WORKSPACE}/rpm/subpackages/${pkg}`
do
    rm -Rf ${WORKSPACE}/debian/${pkg}${f}
done
mkdir -p ${WORKSPACE}/debian/${pkg}/DEBIAN
if [ $(uname -p) == "x86_64" ]
then
  arch="amd64"
else
  arch="i686"
fi
if [ $flavor == "stable" ]
then
  debflavor=""
else
  debflavor="-${flavor}"
fi
sed s/--FLAVOR--/${debflavor}/g ${WORKSPACE}/rpm/debian_packages/${pkg} | \
sed s/--VERSION--/${version}/g | \
sed s/--RELEASE--/${release}/g | \
sed s/--ARCH--/${arch}/g > ${WORKSPACE}/debian/${pkg}/DEBIAN/control
mkdir ${WORKSPACE}/DEBS/$(uname -p) -p
dpkg-deb --build ${WORKSPACE}/debian/${pkg} ${WORKSPACE}/DEBS/$(uname -p)/mdsplus${debflavor}-${pkg}-${version}-${release}.${dist}.$(uname -p).deb


