#!/bin/sh
#
tag=`devscripts/GetRelease`
version=`devscripts/GetRelease version $tag`
release=`devscripts/GetRelease release $tag`
vername="mdsplus-${version}"
kitname="mdsplus-${version}"
if !(grep topdir $HOME/.rpmmacros >/dev/null 2>&1)
then
  echo "%_topdir $HOME/rpm" > $HOME/.rpmmacros
  mkdir -p $HOME/rpm/BUILD
  mkdir -p $HOME/rpm/RPMS
  mkdir -p $HOME/rpm/SOURCES
  mkdir -p $HOME/rpm/SPECS
  mkdir -p $HOME/rpm/SRPMS
fi
rm -Rf $HOME/rpm/BUILD/*
tdir=$(mktemp -d -p $HOME)
if [ -z "$tdir" ]
then
  echo "Error creating temporary directory"
  exit
fi
cp rpm/mdsplus-part1.spec $tdir/${kitname}.spec
for i in `ls rpm/subpackages | grep -v '~'`
do
  echo "requires: mdsplus-${i}" >> $tdir/${kitname}.spec
done
cat rpm/mdsplus-part2.spec >> $tdir/${kitname}.spec
for i in `ls rpm/subpackages | grep -v '~'`
do
  cat rpm/subpackages/${i} >> $tdir/${kitname}.spec
done
pushd $tdir
cvs -d :pserver:MDSguest@www.mdsplus.org:/mdsplus/repos -Q checkout -r $tag mdsplus
mv mdsplus $vername
tar zcf $HOME/rpm/SOURCES/${kitname}.tar.gz --exclude CVS $vername
rm -Rf ${vername}
if [ -z $1 ]
then
  rpmbuild --define="mdsver $version" \
           --define="mdsrel $release" \
           --define="kitname $kitname" \
           -ba ${kitname}.spec 
else
  rpmbuild --define="mdsver $version" \
           --define="mdsrel $release" \
           --define="kitname $kitname" \
           --target=$2 -ba ${kitname}.spec
fi
rm ${kitname}.spec
cd ..
rmdir $tdir
popd
if [ -z $1 ]
then
  $0 i686-linux
fi

