#!/bin/bash
if [ "$1" == "copy_it" ]
then
  ddn=${WORKSPACE}/$4/solaris/$2
  fn=${3:1}
  arch=$4
  dn=$(dirname $fn)
  mkdir -p ${ddn}${dn}
  rsync -a ${WORKSPACE}/$arch/BUILDROOT${fn} ${ddn}${dn}
else
  flavor=$1
  pkg=$2
  version=$3
  release=$4
  arch=$5
  dist=$6
  repo=$7
  debug=$8
  if [ $flavor == "stable" ]
  then
    pkgflavor=""
  else
    pkgflavor="-${flavor}"
  fi
  if [ -z "$debug" ]
  then
  if [ ! -r ~/.gnupg ]
  then
    rsync -a alchome:/mnt/scratch/mdsplus/rpm-signing-keys.tgz ~
    tar zxfC ~/rpm-signing-keys.tgz ~/
  fi
  rm -Rf ${WORKSPACE}/$arch/solaris/${pkg}
  rm -Rf ${WORKSPACE}/$arch/solaris/${pkg}-tmp
  mkdir -p ${WORKSPACE}/$arch/solaris/${pkg}
  mkdir -p ${WORKSPACE}/$arch/solaris/${pkg}-tmp
  echo Making: ${WORKSPACE}/PKGS/${arch}/mdsplus${pkgflavor}-${pkg}_${version}-${release}_${dist}.$(uname -m).${arch}.pkg 
  if [ ! "${pkg}" == "all" ]
  then
    gawk '{ if (substr($1,1,1) == "%") {   \
              if ($1=="%files" || substr($1,1,5)=="%defa") F=1; else F=0; \
            };  \
            if (F==1 && substr($1,1,1) == "/") {  \
              system("cd ${WORKSPACE}/'$arch'/BUILDROOT/; gfind . -wholename \"*" $1 "*\" \
              -exec '$0' copy_it '$pkg' {} '$arch' \\;");
           }  \
          }' ${WORKSPACE}/x86_64/mdsplus/rpm/subpackages/${pkg}
    for f in $(gawk '{if (substr($1,1,1) == "%") {if ($1=="%exclude") print "'${WORKSPACE}/$arch/solaris/${pkg}'" $2;}}' ${WORKSPACE}/x86_64/mdsplus/rpm/subpackages/${pkg})
    do
      rm -Rf ${f}
    done
  fi
  fi
  if [ ! -d $repo ]
  then
    mkdir -p $repo
    cat - > $repo/pkg5.repository << EOF
[publisher]
prefix = www.mdsplus.org

[CONFIGURATION]
version = 4

[repository]
version = 4

EOF
  fi
  cd ${WORKSPACE}/$arch/solaris
  echo "set name=pkg.fmri value=pkg://www.mdsplus.org/mdsplus${pkgflavor}-${pkg}@${version}.${release}" > ./${pkg}-tmp/manifest
  pkgsend generate ./$pkg >> ./${pkg}-tmp/manifest
  pkgdepend generate -md ./${pkg} ./${pkg}-tmp/manifest > ./${pkg}-tmp/manifest.1
  pkgdepend resolve -m ./${pkg}-tmp/manifest.1
  pkgmogrify -O ./${pkg}-tmp/manifest ./${pkg}-tmp/manifest.1.res /dev/stdin <<EOF
<transform dir path=usr$ -> drop>
<transform dir file link -> edit path usr/local/mdsplus/lib32 usr/local/mdsplus/lib>
<transform dir file link -> edit path usr/local/mdsplus/lib64 usr/local/mdsplus/lib/amd64>
<transform dir file link -> edit path usr/local/mdsplus/bin32 usr/local/mdsplus/bin>
<transform dir file link -> edit path usr/local/mdsplus/bin64 usr/local/mdsplus/bin/amd64>
EOF
  pkgrepo remove -s $repo mdsplus${pkgflavor}-${pkg}@${version}.${release}
  pkgsend -s $repo publish -d ./${pkg} ./${pkg}-tmp/manifest
fi
