#!/bin/sh
#
tag=`devscripts/GetRelease`
version=`devscripts/GetRelease version $tag`
release=`devscripts/GetRelease release $tag`
if (test "$XIO" = "")
then
    if (test "$GLOBUS_LOCATION" = "")
	then
	globuskit=
	enableglobus=
    else
	globuskit=-globus
	enableglobus=--enable-globus
    fi
else
    globuskit=-xio
    enableglobus=--with-xio=$GLOBUS_LOCATION\:$GLOBUS_FLAVOR
fi
mkdir mdskit$globuskit
cd mdskit$globuskit
cvs -d :pserver:`whoami`@www.mdsplus.org:/mdsplus/repos -Q checkout -r $tag mdsplus
mv mdsplus mdsplus$globuskit-$version-$release
find . -name CVS -exec rm -Rf {} \; > /dev/null 2> /dev/null
tar cf $HOME/rpm/SOURCES/mdsplus$globuskit-$version-$release.tar mdsplus$globuskit-$version-$release 
gzip -f $HOME/rpm/SOURCES/mdsplus$globuskit-$version-$release.tar
echo "s/#GLOBUS#/$globuskit/g" > tmp.sed
echo "s+#ENABLEGLOBUS#+$enableglobus+g" >> tmp.sed
echo "s/#VERSION#/$version/g" >> tmp.sed
echo "s/#RELEASE#/$release/g" >> tmp.sed
cat tmp.sed
sed -f tmp.sed mdsplus$globuskit-$version-$release/rpm/rpm.spec > rpm.spec 
rpmbuild -ba rpm.spec
cd ..
rm -Rf mdskit$globuskit
