#!/bin/bash
if [ "$1" == "copy_it" ]
then
  ddn=${WORKSPACE}/debian/$2
  fn=${3:1}
  dn=$(dirname $fn)
  mkdir -p ${ddn}${dn}
  rsync -a ${WORKSPACE}/BUILDROOT${fn} ${ddn}${dn}
else
  flavor=$1
  pkg=$2
  version=$3
  release=$4
  rm -Rf ${WORKSPACE}/debian/${pkg}
  mkdir -p ${WORKSPACE}/debian/${pkg}/DEBIAN
  if [ $(uname -p) == "x86_64" ]
  then
    arch="amd64"
  else
    arch="i386"
  fi
  if [ $flavor == "stable" ]
  then
    debflavor=""
  else
    debflavor="-${flavor}"
  fi
  if [ ! "${pkg}" == "all" ]
  then
    awk '{if (substr($1,1,1) == "%") {if ($1=="%files" || substr($1,1,5)=="%defa") F=1; else F=0;}; if (F==1 && substr($1,1,1) == "/") {system("cd ${WORKSPACE}/BUILDROOT; find . -wholename \"*" $1 "*\" -exec '$0' copy_it '$pkg' {} \;");}}' ${WORKSPACE}/rpm/subpackages/${pkg}
    for f in `awk '{if (substr($1,1,1) == "%") {if ($1=="%exclude") print $2;}}' ${WORKSPACE}/rpm/subpackages/${pkg}`
    do
      rm -Rf ${WORKSPACE}/debian/${pkg}${f}
    done
  fi
  sed s/--FLAVOR--/${debflavor}/g ${WORKSPACE}/rpm/debian_packages/${pkg} | \
  sed s/--VERSION--/${version}/g | \
  sed s/--RELEASE--/${release}/g | \
  sed s/--ARCH--/${arch}/g > ${WORKSPACE}/debian/${pkg}/DEBIAN/control
  mkdir ${repodir}/{conf,pool,dists} -p
  cat <<EOF > ${repodir}/conf/distributions
Origin: MDSplus Development Team
Label: MDSplus
Codename: MDSplus
Version: 1.0
Architectures: i386 amd64 source
Components: alpha beta stable
Description: MDSplus packages
SignWith: MDSplus
EOF
  for f in $(ls ${WORKSPACE}/rpm/debian_packages/${pkg}.* 2>/dev/null)
  do
    chmod a+rx $f
    file=$(echo $(basename $f) | awk -F. '{print $2}')
    rsync -a $f ${WORKSPACE}/debian/${pkg}/DEBIAN/${file}
  done
  DEB="${WORKSPACE}/DEBS/${arch}/mdsplus${debflavor}-${pkg}-${version}.${release}_${arch}.deb"
  mkdir ${WORKSPACE}/DEBS/${arch} -p
  dpkg-deb --build ${WORKSPACE}/debian/${pkg} ${DEB}
  if [ ! -r ~/.gnupg ]
  then
    rsync -a alchome:/mnt/scratch/mdsplus/rpm-signing-keys.tgz ~
    tar zxfC ~/rpm-signing-keys.tgz ~/
  fi
fi
