#!/bin/sh
filelist=/tmp/python_installed_files
if [ "$1" == "install" ]
then
  cd /usr/local/mdsplus/mdsobjects/python
  python setup.py install --record=$filelist >/dev/null 2>&1
  exit $?
else
  echo got here
  gawk '{system("rm -f \""$0"\"")}' $filelist
  gawk -F/ '{dir=""; for (i=2;i<NF-1;i++) {dir=dir "/" $i;} system("gfind " dir " -type d -empty -delete");exit}' $filelist
  rm -f $filelist
fi

