#!/bin/sh
#
svccfg -s application/pkg/server add mdsplus-repo-x86_64
svccfg -s application/pkg/server add mdsplus-repo-i686
svccfg -s application/pkg/server:mdsplus-repo-x86_64 addpg pkg application
svccfg -s application/pkg/server:mdsplus-repo-i686 addpg pkg application
svccfg -s application/pkg/server:mdsplus-repo-x86_64 setprop pkg/inst_root=/home/twf/mdsplus-repo-x86_64
svccfg -s application/pkg/server:mdsplus-repo-x86_64 setprop pkg/readonly=true
svccfg -s application/pkg/server:mdsplus-repo-x86_64 setprop pkg/port=82
svccfg -s application/pkg/server:mdsplus-repo-x86_64 addpg general framework
svccfg -s application/pkg/server:mdsplus-repo-x86_64 addpropvalue general/complete astring: MDSplusX86_64
svccfg -s application/pkg/server:mdsplus-repo-x86_64 addpropvalue general/enabled boolean: true
svcadm refresh application/pkg/server:mdsplus-repo-x86_64
svcadm enable application/pkg/server:mdsplus-repo-x86_64
svccfg -s application/pkg/server:mdsplus-repo-i686 setprop pkg/inst_root=/home/twf/mdsplus-repo-i686
svccfg -s application/pkg/server:mdsplus-repo-i686 setprop pkg/readonly=true
svccfg -s application/pkg/server:mdsplus-repo-i686 setprop pkg/port=81
svccfg -s application/pkg/server:mdsplus-repo-i686 addpg general framework
svccfg -s application/pkg/server:mdsplus-repo-i686 addpropvalue general/complete astring: MDSplusI686
svccfg -s application/pkg/server:mdsplus-repo-i686 addpropvalue general/enabled boolean: true
svcadm refresh application/pkg/server:mdsplus-repo-i686
svcadm enable application/pkg/server:mdsplus-repo-i686

