#!/bin/sh
#
#
if [ "$1" = "alpha" ]
then
  branch=""
else
  branch="-F $1"
fi
cd $(dirname $0)/..
rm -f ChangeLog
touch ChangeLog
devscripts/cvs2cl.pl --prune --accum --separate-header $branch -r -b 2> /dev/null
cvs commit -m "" ChangeLog

