

import java.awt.*;
import javax.swing.*;
/**
 * <p>Title: </p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2003</p>
 * <p>Company: </p>
 * @author not attributable
 * @version 1.0
 */

public class BUILD_VERSIONSetup extends DeviceSetup {
  BorderLayout borderLayout1 = new BorderLayout();
  DeviceButtons deviceButtons1 = new DeviceButtons();
  JPanel jPanel1 = new JPanel();
  GridLayout gridLayout1 = new GridLayout();
  JPanel jPanel2 = new JPanel();
  DeviceField deviceField1 = new DeviceField();
  FlowLayout flowLayout1 = new FlowLayout();
  FlowLayout flowLayout2 = new FlowLayout();
  DeviceField deviceField2 = new DeviceField();
  JPanel jPanel3 = new JPanel();
  DeviceField deviceField3 = new DeviceField();
  JPanel jPanel4 = new JPanel();
  JTabbedPane jTabbedPane1 = new JTabbedPane();
  BorderLayout borderLayout2 = new BorderLayout();
  JPanel jPanel5 = new JPanel();
  GridLayout gridLayout2 = new GridLayout();
  DeviceChannel deviceChannel1 = new DeviceChannel();
  JPanel jPanel20 = new JPanel();
  BorderLayout borderLayout3 = new BorderLayout();
  FlowLayout flowLayout3 = new FlowLayout();
  DeviceField deviceField5 = new DeviceField();
  JPanel jPanel6 = new JPanel();
  DeviceField deviceField4 = new DeviceField();
  DeviceField deviceField6 = new DeviceField();
  FlowLayout flowLayout4 = new FlowLayout();
  JPanel jPanel7 = new JPanel();
  GridLayout gridLayout10 = new GridLayout();
  FlowLayout flowLayout5 = new FlowLayout();
  DeviceField deviceField7 = new DeviceField();
  JPanel jPanel8 = new JPanel();
  GridLayout gridLayout11 = new GridLayout();
  JPanel jPanel21 = new JPanel();
  DeviceChannel deviceChannel2 = new DeviceChannel();
  DeviceField deviceField8 = new DeviceField();
  FlowLayout flowLayout6 = new FlowLayout();
  GridLayout gridLayout3 = new GridLayout();
  BorderLayout borderLayout4 = new BorderLayout();
  JPanel jPanel9 = new JPanel();
  JPanel jPanel10 = new JPanel();
  DeviceField deviceField9 = new DeviceField();
  FlowLayout flowLayout7 = new FlowLayout();
  DeviceField deviceField10 = new DeviceField();
  JPanel jPanel11 = new JPanel();
  GridLayout gridLayout12 = new GridLayout();
  JPanel jPanel22 = new JPanel();
  DeviceChannel deviceChannel3 = new DeviceChannel();
  DeviceField deviceField11 = new DeviceField();
  FlowLayout flowLayout8 = new FlowLayout();
  GridLayout gridLayout4 = new GridLayout();
  BorderLayout borderLayout5 = new BorderLayout();
  JPanel jPanel12 = new JPanel();
  JPanel jPanel13 = new JPanel();
  DeviceField deviceField12 = new DeviceField();
  FlowLayout flowLayout9 = new FlowLayout();
  DeviceField deviceField13 = new DeviceField();
  JPanel jPanel14 = new JPanel();
  GridLayout gridLayout13 = new GridLayout();
  JPanel jPanel23 = new JPanel();
  DeviceChannel deviceChannel4 = new DeviceChannel();
  DeviceField deviceField14 = new DeviceField();
  FlowLayout flowLayout10 = new FlowLayout();
  GridLayout gridLayout5 = new GridLayout();
  BorderLayout borderLayout6 = new BorderLayout();
  JPanel jPanel15 = new JPanel();
  JPanel jPanel16 = new JPanel();
  DeviceField deviceField15 = new DeviceField();
  FlowLayout flowLayout11 = new FlowLayout();
  DeviceField deviceField16 = new DeviceField();
  JPanel jPanel17 = new JPanel();
  GridLayout gridLayout14 = new GridLayout();
  JPanel jPanel24 = new JPanel();
  DeviceChannel deviceChannel5 = new DeviceChannel();
  DeviceField deviceField17 = new DeviceField();
  FlowLayout flowLayout12 = new FlowLayout();
  GridLayout gridLayout6 = new GridLayout();
  BorderLayout borderLayout7 = new BorderLayout();
  JPanel jPanel18 = new JPanel();
  JPanel jPanel19 = new JPanel();
  FlowLayout flowLayout13 = new FlowLayout();
  DeviceField deviceField19 = new DeviceField();
  JPanel jPanel110 = new JPanel();
  GridLayout gridLayout15 = new GridLayout();
  JPanel jPanel25 = new JPanel();
  DeviceChannel deviceChannel6 = new DeviceChannel();
  DeviceField deviceField110 = new DeviceField();
  FlowLayout flowLayout14 = new FlowLayout();
  GridLayout gridLayout7 = new GridLayout();
  BorderLayout borderLayout8 = new BorderLayout();
  JPanel jPanel111 = new JPanel();
  JPanel jPanel112 = new JPanel();
  DeviceField deviceField111 = new DeviceField();
  FlowLayout flowLayout15 = new FlowLayout();
  DeviceField deviceField112 = new DeviceField();
  JPanel jPanel113 = new JPanel();
  GridLayout gridLayout16 = new GridLayout();
  JPanel jPanel26 = new JPanel();
  DeviceChannel deviceChannel7 = new DeviceChannel();
  DeviceField deviceField113 = new DeviceField();
  FlowLayout flowLayout16 = new FlowLayout();
  GridLayout gridLayout8 = new GridLayout();
  BorderLayout borderLayout9 = new BorderLayout();
  JPanel jPanel114 = new JPanel();
  JPanel jPanel115 = new JPanel();
  DeviceField deviceField114 = new DeviceField();
  FlowLayout flowLayout17 = new FlowLayout();
  DeviceField deviceField115 = new DeviceField();
  JPanel jPanel116 = new JPanel();
  GridLayout gridLayout17 = new GridLayout();
  JPanel jPanel27 = new JPanel();
  DeviceChannel deviceChannel8 = new DeviceChannel();
  DeviceField deviceField116 = new DeviceField();
  FlowLayout flowLayout18 = new FlowLayout();
  GridLayout gridLayout9 = new GridLayout();
  BorderLayout borderLayout10 = new BorderLayout();
  JPanel jPanel117 = new JPanel();
  JPanel jPanel118 = new JPanel();
  DeviceField deviceField117 = new DeviceField();
  DeviceField deviceField18 = new DeviceField();
  public BUILD_VERSIONSetup() {
    try {
      jbInit();
    }
    catch(Exception e) {
      e.printStackTrace();
    }
  }
  private void jbInit() throws Exception {
    this.setWidth(700);
    this.setHeight(250);
    this.setDeviceType("BUILD_VERSION");
    this.setDeviceProvider("150.178.3.33");
    this.setDeviceTitle("Build new RFX experiment version ");
    this.getContentPane().setLayout(borderLayout1);
    jPanel1.setLayout(gridLayout1);
    gridLayout1.setRows(2);
    deviceField1.setOffsetNid(1);
    deviceField1.setTextOnly(true);
    deviceField1.setLabelString("Comment");
    deviceField1.setNumCols(50);
    deviceField1.setIdentifier("");
    jPanel2.setLayout(flowLayout1);
    flowLayout1.setAlignment(FlowLayout.LEFT);
    flowLayout2.setAlignment(FlowLayout.LEFT);
    deviceField2.setOffsetNid(3);
    deviceField2.setTextOnly(false);
    deviceField2.setLabelString("Shots: ");
    deviceField2.setNumCols(20);
    deviceField2.setIdentifier("");
    jPanel3.setLayout(flowLayout2);
    deviceField3.setNumCols(10);
    deviceField3.setIdentifier("");
    deviceField3.setLabelString("Version: ");
    deviceField3.setOffsetNid(2);
    deviceField3.setTextOnly(false);
    jPanel4.setLayout(borderLayout2);
    jPanel5.setLayout(gridLayout2);
    deviceButtons1.setMethods(new String[] {"start"});
    deviceChannel1.setLabelString("");
    deviceChannel1.setOffsetNid(4);
    deviceChannel1.setInSameLine(true);
    deviceChannel1.setUpdateIdentifier("");
    deviceChannel1.setShowVal("");
    deviceChannel1.setLayout(borderLayout3);
    jPanel20.setLayout(gridLayout10);
    flowLayout3.setAlignment(FlowLayout.LEFT);
    deviceField5.setOffsetNid(6);
    deviceField5.setTextOnly(true);
    deviceField5.setLabelString("Experiment");
    deviceField5.setIdentifier("");
    deviceField5.setEditable(false);
    jPanel6.setLayout(flowLayout3);
    deviceField4.setNumCols(25);
    deviceField4.setIdentifier("");
    deviceField4.setLabelString("Comment");
    deviceField4.setTextOnly(true);
    deviceField4.setOffsetNid(5);
    deviceField6.setOffsetNid(7);
    deviceField6.setTextOnly(false);
    deviceField6.setLabelString("Programs:");
    deviceField6.setNumCols(50);
    deviceField6.setIdentifier("");
    flowLayout4.setAlignment(FlowLayout.LEFT);
    jPanel7.setLayout(flowLayout4);
    gridLayout10.setRows(2);
    flowLayout5.setAlignment(FlowLayout.LEFT);
    deviceField7.setIdentifier("");
    deviceField7.setEditable(true);
    deviceField7.setLabelString("Experiment");
    deviceField7.setTextOnly(true);
    deviceField7.setOffsetNid(10);
    jPanel8.setLayout(flowLayout5);
    gridLayout11.setRows(2);
    jPanel21.setLayout(gridLayout11);
    deviceChannel2.setLabelString("");
    deviceChannel2.setOffsetNid(8);
    deviceChannel2.setInSameLine(true);
    deviceChannel2.setUpdateIdentifier("");
    deviceChannel2.setShowVal("");
    deviceChannel2.setLayout(borderLayout4);
    deviceField8.setOffsetNid(11);
    deviceField8.setTextOnly(false);
    deviceField8.setLabelString("Programs:");
    deviceField8.setNumCols(50);
    deviceField8.setIdentifier("");
    flowLayout6.setAlignment(FlowLayout.LEFT);
    jPanel9.setLayout(gridLayout3);
    jPanel10.setLayout(flowLayout6);
    deviceField9.setNumCols(25);
    deviceField9.setIdentifier("");
    deviceField9.setLabelString("Comment");
    deviceField9.setTextOnly(true);
    deviceField9.setOffsetNid(9);
    flowLayout7.setAlignment(FlowLayout.LEFT);
    deviceField10.setIdentifier("");
    deviceField10.setEditable(true);
    deviceField10.setLabelString("Experiment");
    deviceField10.setTextOnly(true);
    deviceField10.setOffsetNid(14);
    jPanel11.setLayout(flowLayout7);
    gridLayout12.setRows(2);
    jPanel22.setLayout(gridLayout12);
    deviceChannel3.setLabelString("");
    deviceChannel3.setOffsetNid(12);
    deviceChannel3.setInSameLine(true);
    deviceChannel3.setUpdateIdentifier("");
    deviceChannel3.setShowVal("");
    deviceChannel3.setLayout(borderLayout5);
    deviceField11.setOffsetNid(15);
    deviceField11.setTextOnly(false);
    deviceField11.setLabelString("Programs:");
    deviceField11.setNumCols(50);
    deviceField11.setIdentifier("");
    flowLayout8.setAlignment(FlowLayout.LEFT);
    jPanel12.setLayout(gridLayout4);
    jPanel13.setLayout(flowLayout8);
    deviceField12.setNumCols(25);
    deviceField12.setIdentifier("");
    deviceField12.setLabelString("Comment");
    deviceField12.setTextOnly(true);
    deviceField12.setOffsetNid(13);
    flowLayout9.setAlignment(FlowLayout.LEFT);
    deviceField13.setIdentifier("");
    deviceField13.setEditable(true);
    deviceField13.setLabelString("Experiment");
    deviceField13.setTextOnly(true);
    deviceField13.setOffsetNid(18);
    jPanel14.setLayout(flowLayout9);
    gridLayout13.setRows(2);
    jPanel23.setLayout(gridLayout13);
    deviceChannel4.setLabelString("");
    deviceChannel4.setOffsetNid(16);
    deviceChannel4.setInSameLine(true);
    deviceChannel4.setUpdateIdentifier("");
    deviceChannel4.setShowVal("");
    deviceChannel4.setLayout(borderLayout6);
    deviceField14.setOffsetNid(19);
    deviceField14.setTextOnly(false);
    deviceField14.setLabelString("Programs:");
    deviceField14.setNumCols(50);
    deviceField14.setIdentifier("");
    flowLayout10.setAlignment(FlowLayout.LEFT);
    jPanel15.setLayout(gridLayout5);
    jPanel16.setLayout(flowLayout10);
    deviceField15.setNumCols(25);
    deviceField15.setIdentifier("");
    deviceField15.setLabelString("Comment");
    deviceField15.setTextOnly(true);
    deviceField15.setOffsetNid(17);
    flowLayout11.setAlignment(FlowLayout.LEFT);
    deviceField16.setIdentifier("");
    deviceField16.setEditable(true);
    deviceField16.setLabelString("Experiment");
    deviceField16.setTextOnly(true);
    deviceField16.setOffsetNid(10);
    jPanel17.setLayout(flowLayout11);
    gridLayout14.setRows(2);
    jPanel24.setLayout(gridLayout14);
    deviceChannel5.setLabelString("");
    deviceChannel5.setOffsetNid(20);
    deviceChannel5.setInSameLine(true);
    deviceChannel5.setUpdateIdentifier("");
    deviceChannel5.setShowVal("");
    deviceChannel5.setLayout(borderLayout7);
    deviceField17.setOffsetNid(23);
    deviceField17.setTextOnly(false);
    deviceField17.setLabelString("Programs:");
    deviceField17.setNumCols(50);
    deviceField17.setIdentifier("");
    flowLayout12.setAlignment(FlowLayout.LEFT);
    jPanel18.setLayout(gridLayout6);
    jPanel19.setLayout(flowLayout12);
    flowLayout13.setAlignment(FlowLayout.LEFT);
    deviceField19.setIdentifier("");
    deviceField19.setEditable(true);
    deviceField19.setLabelString("Experiment");
    deviceField19.setTextOnly(true);
    deviceField19.setOffsetNid(26);
    jPanel110.setLayout(flowLayout13);
    gridLayout15.setRows(2);
    jPanel25.setLayout(gridLayout15);
    deviceChannel6.setLabelString("");
    deviceChannel6.setOffsetNid(24);
    deviceChannel6.setInSameLine(true);
    deviceChannel6.setUpdateIdentifier("");
    deviceChannel6.setShowVal("");
    deviceChannel6.setLayout(borderLayout8);
    deviceField110.setOffsetNid(27);
    deviceField110.setTextOnly(false);
    deviceField110.setLabelString("Programs:");
    deviceField110.setNumCols(50);
    deviceField110.setIdentifier("");
    flowLayout14.setAlignment(FlowLayout.LEFT);
    jPanel111.setLayout(gridLayout7);
    jPanel112.setLayout(flowLayout14);
    deviceField111.setNumCols(25);
    deviceField111.setIdentifier("");
    deviceField111.setLabelString("Comment");
    deviceField111.setTextOnly(true);
    deviceField111.setOffsetNid(25);
    flowLayout15.setAlignment(FlowLayout.LEFT);
    deviceField112.setIdentifier("");
    deviceField112.setEditable(true);
    deviceField112.setLabelString("Experiment");
    deviceField112.setTextOnly(true);
    deviceField112.setOffsetNid(30);
    jPanel113.setLayout(flowLayout15);
    gridLayout16.setRows(2);
    jPanel26.setLayout(gridLayout16);
    deviceChannel7.setLabelString("");
    deviceChannel7.setOffsetNid(28);
    deviceChannel7.setInSameLine(true);
    deviceChannel7.setUpdateIdentifier("");
    deviceChannel7.setShowVal("");
    deviceChannel7.setLayout(borderLayout9);
    deviceField113.setOffsetNid(31);
    deviceField113.setTextOnly(false);
    deviceField113.setLabelString("Programs:");
    deviceField113.setNumCols(50);
    deviceField113.setIdentifier("");
    flowLayout16.setAlignment(FlowLayout.LEFT);
    jPanel114.setLayout(gridLayout8);
    jPanel115.setLayout(flowLayout16);
    deviceField114.setNumCols(25);
    deviceField114.setIdentifier("");
    deviceField114.setLabelString("Comment");
    deviceField114.setTextOnly(true);
    deviceField114.setOffsetNid(29);
    flowLayout17.setAlignment(FlowLayout.LEFT);
    deviceField115.setIdentifier("");
    deviceField115.setLabelString("Experiment");
    deviceField115.setTextOnly(true);
    deviceField115.setOffsetNid(34);
    jPanel116.setLayout(flowLayout17);
    gridLayout17.setRows(2);
    jPanel27.setLayout(gridLayout17);
    deviceChannel8.setLabelString("");
    deviceChannel8.setOffsetNid(32);
    deviceChannel8.setInSameLine(true);
    deviceChannel8.setUpdateIdentifier("");
    deviceChannel8.setShowVal("");
    deviceChannel8.setLayout(borderLayout10);
    deviceField116.setOffsetNid(35);
    deviceField116.setTextOnly(false);
    deviceField116.setLabelString("Programs:");
    deviceField116.setNumCols(50);
    deviceField116.setIdentifier("");
    flowLayout18.setAlignment(FlowLayout.LEFT);
    jPanel117.setLayout(gridLayout9);
    jPanel118.setLayout(flowLayout18);
    deviceField117.setNumCols(25);
    deviceField117.setIdentifier("");
    deviceField117.setLabelString("Comment");
    deviceField117.setTextOnly(true);
    deviceField117.setOffsetNid(33);
    deviceField18.setNumCols(25);
    deviceField18.setIdentifier("");
    deviceField18.setLabelString("Comment");
    deviceField18.setTextOnly(true);
    deviceField18.setOffsetNid(21);
    this.getContentPane().add(deviceButtons1, BorderLayout.SOUTH);
    this.getContentPane().add(jPanel1,  BorderLayout.NORTH);
    jPanel1.add(jPanel2, null);
    jPanel2.add(deviceField1, null);
    jPanel1.add(jPanel3, null);
    jPanel3.add(deviceField3, null);
    jPanel3.add(deviceField2, null);
    this.getContentPane().add(jPanel4,  BorderLayout.CENTER);
    jPanel4.add(jTabbedPane1,  BorderLayout.CENTER);
    jTabbedPane1.add(jPanel5,      "Sub-tree A");
    jPanel5.add(deviceChannel1, null);
    deviceChannel1.add(jPanel20, BorderLayout.CENTER);
    jPanel20.add(jPanel6, null);
    jPanel6.add(deviceField4, null);
    jPanel6.add(deviceField5, null);
    jPanel20.add(jPanel7, null);
    jPanel7.add(deviceField6, null);
    jTabbedPane1.add(jPanel9,   "Sub-tree 2");
    jPanel9.add(deviceChannel2, null);
    deviceChannel2.add(jPanel21, BorderLayout.CENTER);
    jPanel8.add(deviceField8, null);
    jPanel21.add(jPanel10, null);
    jPanel10.add(deviceField9, null);
    jPanel10.add(deviceField7, null);
    jTabbedPane1.add(jPanel12,   "Sub-tree 3");
    jPanel12.add(deviceChannel3, null);
    deviceChannel3.add(jPanel22, BorderLayout.CENTER);
    jPanel11.add(deviceField11, null);
    jPanel22.add(jPanel13, null);
    jPanel13.add(deviceField12, null);
    jPanel13.add(deviceField10, null);
    jTabbedPane1.add(jPanel15,   "Sub-tree 4");
    jPanel15.add(deviceChannel4, null);
    deviceChannel4.add(jPanel23, BorderLayout.CENTER);
    jPanel14.add(deviceField14, null);
    jPanel23.add(jPanel16, null);
    jPanel16.add(deviceField15, null);
    jPanel16.add(deviceField13, null);
    jTabbedPane1.add(jPanel18,   "Sub-tree 5");
    jPanel18.add(deviceChannel5, null);
    deviceChannel5.add(jPanel24, BorderLayout.CENTER);
    jPanel17.add(deviceField17, null);
    jPanel24.add(jPanel19, null);
    jPanel19.add(deviceField18, null);
    jPanel19.add(deviceField16, null);
    jTabbedPane1.add(jPanel111,   "Sub-tree 6");
    jPanel111.add(deviceChannel6, null);
    deviceChannel6.add(jPanel25, BorderLayout.CENTER);
    jPanel110.add(deviceField110, null);
    jPanel25.add(jPanel112, null);
    jPanel112.add(deviceField111, null);
    jPanel112.add(deviceField19, null);
    jTabbedPane1.add(jPanel114,   "Sub-tree 7");
    jPanel114.add(deviceChannel7, null);
    deviceChannel7.add(jPanel26, BorderLayout.CENTER);
    jPanel113.add(deviceField113, null);
    jPanel26.add(jPanel115, null);
    jPanel115.add(deviceField114, null);
    jPanel115.add(deviceField112, null);
    jTabbedPane1.add(jPanel117,   "Sub-tree 8");
    jPanel117.add(deviceChannel8, null);
    deviceChannel8.add(jPanel27, BorderLayout.CENTER);
    jPanel116.add(deviceField116, null);
    jPanel27.add(jPanel118, null);
    jPanel118.add(deviceField117, null);
    jPanel118.add(deviceField115, null);
    jPanel27.add(jPanel116, null);
    jPanel26.add(jPanel113, null);
    jPanel25.add(jPanel110, null);
    jPanel24.add(jPanel17, null);
    jPanel23.add(jPanel14, null);
    jPanel22.add(jPanel11, null);
    jPanel21.add(jPanel8, null);
  }

}