/*
 * DEMOADCSetup.java
 *
 * Created on 16 marzo 2009, 9.13
 */



/**
 *
 * @author  manduchi
 */
public class DEMOADCSetup extends DeviceSetup {

    /** Creates new form BeanForm */
    public DEMOADCSetup() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deviceChannel1 = new DeviceChannel();
        jPanel1 = new javax.swing.JPanel();
        deviceChannel2 = new DeviceChannel();

        getContentPane().add(deviceChannel1, java.awt.BorderLayout.CENTER);

        jPanel1.add(deviceChannel2);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private DeviceChannel deviceChannel1;
    private DeviceChannel deviceChannel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
