

import java.awt.*;
import javax.swing.*;
/**
 * <p>Title: </p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2003</p>
 * <p>Company: </p>
 * @author not attributable
 * @version 1.0
 */

public class ISIS_GAINSetup extends DeviceSetup {
  BorderLayout borderLayout1 = new BorderLayout();
  DeviceButtons deviceButtons1 = new DeviceButtons();
  JPanel jPanel1 = new JPanel();
  JPanel jPanel2 = new JPanel();
  GridLayout gridLayout1 = new GridLayout();
  DeviceField deviceField1 = new DeviceField();
  DeviceDispatch deviceDispatch1 = new DeviceDispatch();
  FlowLayout flowLayout1 = new FlowLayout();
  JPanel jPanel3 = new JPanel();
  DeviceField deviceField2 = new DeviceField();
  FlowLayout flowLayout2 = new FlowLayout();
  JLabel jLabel1 = new JLabel();
  JScrollPane jScrollPane1 = new JScrollPane();
  JPanel jPanel4 = new JPanel();
  GridLayout gridLayout2 = new GridLayout();
  DeviceChannel deviceChannel1 = new DeviceChannel();
  FlowLayout flowLayout3 = new FlowLayout();
  JPanel jPanel5 = new JPanel();
  FlowLayout flowLayout4 = new FlowLayout();
  DeviceChoice deviceChoice1 = new DeviceChoice();
  DeviceField deviceField3 = new DeviceField();
  DeviceField deviceField4 = new DeviceField();
  DeviceChoice deviceChoice2 = new DeviceChoice();
  DeviceField deviceField5 = new DeviceField();
  DeviceField deviceField6 = new DeviceField();
  FlowLayout flowLayout5 = new FlowLayout();
  DeviceField deviceField7 = new DeviceField();
  DeviceField deviceField8 = new DeviceField();
  DeviceChoice deviceChoice3 = new DeviceChoice();
  DeviceChannel deviceChannel2 = new DeviceChannel();
  DeviceField deviceField9 = new DeviceField();
  FlowLayout flowLayout6 = new FlowLayout();
  JPanel jPanel6 = new JPanel();
  DeviceChoice deviceChoice4 = new DeviceChoice();
  DeviceField deviceField10 = new DeviceField();
  FlowLayout flowLayout7 = new FlowLayout();
  DeviceField deviceField11 = new DeviceField();
  DeviceField deviceField12 = new DeviceField();
  DeviceChoice deviceChoice5 = new DeviceChoice();
  DeviceChannel deviceChannel3 = new DeviceChannel();
  DeviceField deviceField13 = new DeviceField();
  FlowLayout flowLayout8 = new FlowLayout();
  JPanel jPanel7 = new JPanel();
  DeviceChoice deviceChoice6 = new DeviceChoice();
  DeviceField deviceField14 = new DeviceField();
  FlowLayout flowLayout9 = new FlowLayout();
  DeviceField deviceField15 = new DeviceField();
  DeviceField deviceField16 = new DeviceField();
  DeviceChoice deviceChoice7 = new DeviceChoice();
  DeviceChannel deviceChannel4 = new DeviceChannel();
  DeviceField deviceField17 = new DeviceField();
  FlowLayout flowLayout10 = new FlowLayout();
  JPanel jPanel8 = new JPanel();
  DeviceChoice deviceChoice8 = new DeviceChoice();
  DeviceField deviceField18 = new DeviceField();
  FlowLayout flowLayout11 = new FlowLayout();
  DeviceField deviceField19 = new DeviceField();
  DeviceField deviceField110 = new DeviceField();
  DeviceChoice deviceChoice9 = new DeviceChoice();
  DeviceChannel deviceChannel5 = new DeviceChannel();
  DeviceField deviceField111 = new DeviceField();
  FlowLayout flowLayout12 = new FlowLayout();
  JPanel jPanel9 = new JPanel();
  DeviceChoice deviceChoice10 = new DeviceChoice();
  DeviceField deviceField112 = new DeviceField();
  FlowLayout flowLayout13 = new FlowLayout();
  DeviceField deviceField113 = new DeviceField();
  DeviceField deviceField114 = new DeviceField();
  DeviceChoice deviceChoice11 = new DeviceChoice();
  DeviceChannel deviceChannel6 = new DeviceChannel();
  DeviceField deviceField115 = new DeviceField();
  FlowLayout flowLayout14 = new FlowLayout();
  JPanel jPanel10 = new JPanel();
  DeviceChoice deviceChoice12 = new DeviceChoice();
  DeviceField deviceField116 = new DeviceField();
  FlowLayout flowLayout15 = new FlowLayout();
  DeviceField deviceField117 = new DeviceField();
  DeviceField deviceField118 = new DeviceField();
  DeviceChoice deviceChoice13 = new DeviceChoice();
  DeviceChannel deviceChannel7 = new DeviceChannel();
  DeviceField deviceField119 = new DeviceField();
  FlowLayout flowLayout16 = new FlowLayout();
  JPanel jPanel11 = new JPanel();
  DeviceChoice deviceChoice14 = new DeviceChoice();
  DeviceField deviceField1110 = new DeviceField();
  FlowLayout flowLayout17 = new FlowLayout();
  DeviceField deviceField1111 = new DeviceField();
  DeviceField deviceField1112 = new DeviceField();
  DeviceChoice deviceChoice15 = new DeviceChoice();
  DeviceChannel deviceChannel8 = new DeviceChannel();
  DeviceField deviceField1113 = new DeviceField();
  FlowLayout flowLayout18 = new FlowLayout();
  JPanel jPanel12 = new JPanel();
  DeviceChoice deviceChoice16 = new DeviceChoice();
  DeviceField deviceField1114 = new DeviceField();
  FlowLayout flowLayout19 = new FlowLayout();
  DeviceField deviceField1115 = new DeviceField();
  DeviceField deviceField1116 = new DeviceField();
  DeviceChoice deviceChoice17 = new DeviceChoice();
  DeviceChannel deviceChannel9 = new DeviceChannel();
  DeviceField deviceField1117 = new DeviceField();
  FlowLayout flowLayout110 = new FlowLayout();
  JPanel jPanel13 = new JPanel();
  DeviceChoice deviceChoice18 = new DeviceChoice();
  DeviceField deviceField1118 = new DeviceField();
  FlowLayout flowLayout111 = new FlowLayout();
  DeviceField deviceField1119 = new DeviceField();
  DeviceField deviceField11110 = new DeviceField();
  DeviceChoice deviceChoice19 = new DeviceChoice();
  DeviceChannel deviceChannel10 = new DeviceChannel();
  DeviceField deviceField11111 = new DeviceField();
  FlowLayout flowLayout112 = new FlowLayout();
  JPanel jPanel14 = new JPanel();
  DeviceChoice deviceChoice110 = new DeviceChoice();
  DeviceField deviceField11112 = new DeviceField();
  FlowLayout flowLayout113 = new FlowLayout();
  DeviceField deviceField11113 = new DeviceField();
  DeviceField deviceField11114 = new DeviceField();
  DeviceChoice deviceChoice111 = new DeviceChoice();
  DeviceChannel deviceChannel11 = new DeviceChannel();
  DeviceField deviceField11115 = new DeviceField();
  FlowLayout flowLayout114 = new FlowLayout();
  JPanel jPanel15 = new JPanel();
  DeviceChoice deviceChoice112 = new DeviceChoice();
  DeviceField deviceField11116 = new DeviceField();
  FlowLayout flowLayout115 = new FlowLayout();
  DeviceField deviceField11117 = new DeviceField();
  DeviceField deviceField11118 = new DeviceField();
  DeviceChoice deviceChoice113 = new DeviceChoice();
  DeviceChannel deviceChannel12 = new DeviceChannel();
  DeviceField deviceField11119 = new DeviceField();
  FlowLayout flowLayout116 = new FlowLayout();
  JPanel jPanel16 = new JPanel();
  DeviceChoice deviceChoice114 = new DeviceChoice();
  DeviceField deviceField111110 = new DeviceField();
  FlowLayout flowLayout117 = new FlowLayout();
  DeviceField deviceField111111 = new DeviceField();
  DeviceField deviceField111112 = new DeviceField();
  DeviceChoice deviceChoice115 = new DeviceChoice();
  DeviceChannel deviceChannel13 = new DeviceChannel();
  DeviceField deviceField111113 = new DeviceField();
  FlowLayout flowLayout118 = new FlowLayout();
  JPanel jPanel17 = new JPanel();
  DeviceChoice deviceChoice116 = new DeviceChoice();
  DeviceField deviceField111114 = new DeviceField();
  FlowLayout flowLayout119 = new FlowLayout();
  DeviceField deviceField111115 = new DeviceField();
  DeviceField deviceField111116 = new DeviceField();
  DeviceChoice deviceChoice117 = new DeviceChoice();
  DeviceChannel deviceChannel14 = new DeviceChannel();
  DeviceField deviceField111117 = new DeviceField();
  FlowLayout flowLayout1110 = new FlowLayout();
  JPanel jPanel18 = new JPanel();
  DeviceChoice deviceChoice118 = new DeviceChoice();
  DeviceField deviceField111118 = new DeviceField();
  FlowLayout flowLayout1111 = new FlowLayout();
  DeviceField deviceField111119 = new DeviceField();
  DeviceField deviceField1111110 = new DeviceField();
  DeviceChoice deviceChoice119 = new DeviceChoice();
  DeviceChannel deviceChannel15 = new DeviceChannel();
  DeviceField deviceField1111111 = new DeviceField();
  FlowLayout flowLayout1112 = new FlowLayout();
  JPanel jPanel19 = new JPanel();
  DeviceChoice deviceChoice1110 = new DeviceChoice();
  DeviceField deviceField1111112 = new DeviceField();
  FlowLayout flowLayout1113 = new FlowLayout();
  DeviceField deviceField1111113 = new DeviceField();
  DeviceField deviceField1111114 = new DeviceField();
  DeviceChoice deviceChoice1111 = new DeviceChoice();
  DeviceChannel deviceChannel16 = new DeviceChannel();
  DeviceField deviceField1111115 = new DeviceField();
  FlowLayout flowLayout1114 = new FlowLayout();
  JPanel jPanel110 = new JPanel();
  DeviceChoice deviceChoice1112 = new DeviceChoice();
  DeviceField deviceField1111116 = new DeviceField();
  FlowLayout flowLayout1115 = new FlowLayout();
  DeviceField deviceField1111117 = new DeviceField();
  DeviceField deviceField1111118 = new DeviceField();
  DeviceChoice deviceChoice1113 = new DeviceChoice();
  DeviceChannel deviceChannel17 = new DeviceChannel();
  DeviceField deviceField1111119 = new DeviceField();
  FlowLayout flowLayout1116 = new FlowLayout();
  JPanel jPanel111 = new JPanel();
  DeviceChoice deviceChoice1114 = new DeviceChoice();
  DeviceField deviceField11111110 = new DeviceField();
  FlowLayout flowLayout1117 = new FlowLayout();
  DeviceField deviceField11111111 = new DeviceField();
  DeviceField deviceField11111112 = new DeviceField();
  DeviceChoice deviceChoice1115 = new DeviceChoice();
  DeviceChannel deviceChannel18 = new DeviceChannel();
  DeviceField deviceField11111113 = new DeviceField();
  FlowLayout flowLayout1118 = new FlowLayout();
  JPanel jPanel112 = new JPanel();
  DeviceChoice deviceChoice1116 = new DeviceChoice();
  DeviceField deviceField11111114 = new DeviceField();
  public ISIS_GAINSetup() {
    try {
      jbInit();
    }
    catch(Exception e) {
      e.printStackTrace();
    }
  }
  private void jbInit() throws Exception {
    this.setWidth(850);
    this.setHeight(900);
    this.setDeviceType("ISIS_GAIN");
    this.setDeviceProvider("150.178.3.33");
    this.setDeviceTitle("ISIS Front End Gains");
    this.getContentPane().setLayout(borderLayout1);
    jPanel1.setLayout(gridLayout1);
    gridLayout1.setRows(3);
    deviceField1.setOffsetNid(1);
    deviceField1.setLabelString("Comment: ");
    deviceField1.setNumCols(30);
    deviceField1.setIdentifier("");
    jPanel2.setLayout(flowLayout1);
    flowLayout1.setAlignment(FlowLayout.LEFT);
    deviceField2.setOffsetNid(2);
    deviceField2.setLabelString("IP address: ");
    deviceField2.setNumCols(20);
    deviceField2.setIdentifier("");
    jPanel3.setLayout(flowLayout2);
    flowLayout2.setAlignment(FlowLayout.LEFT);
    jLabel1.setText("  CARD                                   NAME                    " +
    "                      CALIB                GAIN                  " +
    "                 NAME                                    CALIB   " +
    "                   GAIN");
    jPanel4.setLayout(gridLayout2);
    gridLayout2.setRows(18);
    gridLayout2.setVgap(0);
    deviceChannel1.setLayout(flowLayout3);
    deviceChannel1.setLabelString("01");
    deviceChannel1.setOffsetNid(4);
    deviceChannel1.setInSameLine(true);
    deviceChannel1.setUpdateIdentifier("");
    deviceChannel1.setShowVal("");
    jPanel5.setLayout(flowLayout4);
    deviceField6.setOffsetNid(5);
    deviceField6.setTextOnly(true);
    deviceField6.setNumCols(15);
    deviceField6.setIdentifier("");
    deviceField6.setEditable(false);
    deviceField4.setOffsetNid(10);
    deviceField4.setTextOnly(true);
    deviceField4.setNumCols(15);
    deviceField4.setIdentifier("");
    deviceField4.setEditable(false);
    deviceChoice2.setChoiceIntValues(new int[] {(int)1,(int)2,(int)5,(int)10});
    deviceChoice2.setChoiceFloatValues(null);
    deviceChoice2.setOffsetNid(7);
    deviceChoice2.setLabelString(" ");
    deviceChoice2.setChoiceItems(new String[] {"1", "2", "5", "10"});
    deviceChoice2.setUpdateIdentifier("");
    deviceChoice2.setIdentifier("");
    deviceChoice1.setChoiceIntValues(new int[] {(int)1,(int)2,(int)5,(int)10});
    deviceChoice1.setChoiceFloatValues(null);
    deviceChoice1.setOffsetNid(12);
    deviceChoice1.setLabelString(" ");
    deviceChoice1.setChoiceItems(new String[] {"1", "2", "5", "10"});
    deviceChoice1.setUpdateIdentifier("");
    deviceChoice1.setIdentifier("");
    deviceField5.setOffsetNid(6);
    deviceField5.setIdentifier("");
    deviceField3.setOffsetNid(11);
    deviceField3.setIdentifier("");
    deviceField7.setIdentifier("");
    deviceField7.setOffsetNid(193);
    deviceField8.setIdentifier("");
    deviceField8.setOffsetNid(198);
    deviceChoice3.setIdentifier("");
    deviceChoice3.setUpdateIdentifier("");
    deviceChoice3.setChoiceItems(new String[] {"1", "2", "5", "10"});
    deviceChoice3.setLabelString("");
    deviceChoice3.setOffsetNid(194);
    deviceChoice3.setChoiceFloatValues(null);
    deviceChoice3.setChoiceIntValues(new int[] {(int)1,(int)2,(int)5,(int)10});
    deviceChannel2.setShowVal("");
    deviceChannel2.setUpdateIdentifier("");
    deviceChannel2.setInSameLine(true);
    deviceChannel2.setOffsetNid(191);
    deviceChannel2.setLabelString("18");
    deviceChannel2.setLayout(flowLayout5);
    deviceField9.setOffsetNid(192);
    deviceField9.setTextOnly(true);
    deviceField9.setNumCols(15);
    deviceField9.setIdentifier("");
    deviceField9.setEditable(false);
    jPanel6.setLayout(flowLayout6);
    deviceChoice4.setChoiceIntValues(new int[] {(int)1,(int)2,(int)5,(int)10});
    deviceChoice4.setChoiceFloatValues(null);
    deviceChoice4.setOffsetNid(199);
    deviceChoice4.setLabelString(" ");
    deviceChoice4.setChoiceItems(new String[] {"1", "2", "5", "10"});
    deviceChoice4.setUpdateIdentifier("");
    deviceChoice4.setIdentifier("");
    deviceField10.setOffsetNid(197);
    deviceField10.setTextOnly(true);
    deviceField10.setNumCols(15);
    deviceField10.setIdentifier("");
    deviceField10.setEditable(false);
    deviceField11.setIdentifier("");
    deviceField11.setOffsetNid(182);
    deviceField12.setIdentifier("");
    deviceField12.setOffsetNid(187);
    deviceChoice5.setIdentifier("");
    deviceChoice5.setUpdateIdentifier("");
    deviceChoice5.setChoiceItems(new String[] {"1", "2", "5", "10"});
    deviceChoice5.setLabelString(" ");
    deviceChoice5.setOffsetNid(183);
    deviceChoice5.setChoiceFloatValues(null);
    deviceChoice5.setChoiceIntValues(new int[] {(int)1,(int)2,(int)5,(int)10});
    deviceChannel3.setShowVal("");
    deviceChannel3.setUpdateIdentifier("");
    deviceChannel3.setInSameLine(true);
    deviceChannel3.setOffsetNid(180);
    deviceChannel3.setLabelString("17");
    deviceChannel3.setLayout(flowLayout7);
    deviceField13.setOffsetNid(181);
    deviceField13.setTextOnly(true);
    deviceField13.setNumCols(15);
    deviceField13.setIdentifier("");
    deviceField13.setEditable(false);
    jPanel7.setLayout(flowLayout8);
    deviceChoice6.setChoiceIntValues(new int[] {(int)1,(int)2,(int)5,(int)10});
    deviceChoice6.setChoiceFloatValues(null);
    deviceChoice6.setOffsetNid(188);
    deviceChoice6.setLabelString(" ");
    deviceChoice6.setChoiceItems(new String[] {"1", "2", "5", "10"});
    deviceChoice6.setUpdateIdentifier("");
    deviceChoice6.setIdentifier("");
    deviceField14.setOffsetNid(186);
    deviceField14.setTextOnly(true);
    deviceField14.setNumCols(15);
    deviceField14.setIdentifier("");
    deviceField14.setEditable(false);
    deviceField15.setIdentifier("");
    deviceField15.setOffsetNid(171);
    deviceField16.setIdentifier("");
    deviceField16.setOffsetNid(176);
    deviceChoice7.setIdentifier("");
    deviceChoice7.setUpdateIdentifier("");
    deviceChoice7.setChoiceItems(new String[] {"1", "2", "5", "10"});
    deviceChoice7.setLabelString(" ");
    deviceChoice7.setOffsetNid(172);
    deviceChoice7.setChoiceFloatValues(null);
    deviceChoice7.setChoiceIntValues(new int[] {(int)1,(int)2,(int)5,(int)10});
    deviceChannel4.setShowVal("");
    deviceChannel4.setUpdateIdentifier("");
    deviceChannel4.setInSameLine(true);
    deviceChannel4.setOffsetNid(169);
    deviceChannel4.setLabelString("16");
    deviceChannel4.setLayout(flowLayout9);
    deviceField17.setOffsetNid(170);
    deviceField17.setTextOnly(true);
    deviceField17.setNumCols(15);
    deviceField17.setIdentifier("");
    deviceField17.setEditable(false);
    jPanel8.setLayout(flowLayout10);
    deviceChoice8.setChoiceIntValues(new int[] {(int)1,(int)2,(int)5,(int)10});
    deviceChoice8.setChoiceFloatValues(null);
    deviceChoice8.setOffsetNid(177);
    deviceChoice8.setLabelString(" ");
    deviceChoice8.setChoiceItems(new String[] {"1", "2", "5", "10"});
    deviceChoice8.setUpdateIdentifier("");
    deviceChoice8.setIdentifier("");
    deviceField18.setOffsetNid(175);
    deviceField18.setTextOnly(true);
    deviceField18.setNumCols(15);
    deviceField18.setIdentifier("");
    deviceField18.setEditable(false);
    deviceField19.setIdentifier("");
    deviceField19.setOffsetNid(160);
    deviceField110.setIdentifier("");
    deviceField110.setOffsetNid(165);
    deviceChoice9.setIdentifier("");
    deviceChoice9.setUpdateIdentifier("");
    deviceChoice9.setChoiceItems(new String[] {"1", "2", "5", "10"});
    deviceChoice9.setLabelString(" ");
    deviceChoice9.setOffsetNid(161);
    deviceChoice9.setChoiceFloatValues(null);
    deviceChoice9.setChoiceIntValues(new int[] {(int)1,(int)2,(int)5,(int)10});
    deviceChannel5.setShowVal("");
    deviceChannel5.setUpdateIdentifier("");
    deviceChannel5.setInSameLine(true);
    deviceChannel5.setOffsetNid(158);
    deviceChannel5.setLabelString("15");
    deviceChannel5.setLayout(flowLayout11);
    deviceField111.setOffsetNid(159);
    deviceField111.setTextOnly(true);
    deviceField111.setNumCols(15);
    deviceField111.setIdentifier("");
    deviceField111.setEditable(false);
    jPanel9.setLayout(flowLayout12);
    deviceChoice10.setChoiceIntValues(new int[] {(int)1,(int)2,(int)5,(int)10});
    deviceChoice10.setChoiceFloatValues(null);
    deviceChoice10.setOffsetNid(166);
    deviceChoice10.setLabelString(" ");
    deviceChoice10.setChoiceItems(new String[] {"1", "2", "5", "10"});
    deviceChoice10.setUpdateIdentifier("");
    deviceChoice10.setIdentifier("");
    deviceField112.setOffsetNid(164);
    deviceField112.setTextOnly(true);
    deviceField112.setNumCols(15);
    deviceField112.setIdentifier("");
    deviceField112.setEditable(false);
    deviceField113.setIdentifier("");
    deviceField113.setOffsetNid(149);
    deviceField114.setIdentifier("");
    deviceField114.setOffsetNid(154);
    deviceChoice11.setIdentifier("");
    deviceChoice11.setUpdateIdentifier("");
    deviceChoice11.setChoiceItems(new String[] {"1", "2", "5", "10"});
    deviceChoice11.setLabelString(" ");
    deviceChoice11.setOffsetNid(150);
    deviceChoice11.setChoiceFloatValues(null);
    deviceChoice11.setChoiceIntValues(new int[] {(int)1,(int)2,(int)5,(int)10});
    deviceChannel6.setShowVal("");
    deviceChannel6.setUpdateIdentifier("");
    deviceChannel6.setInSameLine(true);
    deviceChannel6.setOffsetNid(147);
    deviceChannel6.setLabelString("14");
    deviceChannel6.setLayout(flowLayout13);
    deviceField115.setOffsetNid(148);
    deviceField115.setTextOnly(true);
    deviceField115.setNumCols(15);
    deviceField115.setIdentifier("");
    deviceField115.setEditable(false);
    jPanel10.setLayout(flowLayout14);
    deviceChoice12.setChoiceIntValues(new int[] {(int)1,(int)2,(int)5,(int)10});
    deviceChoice12.setChoiceFloatValues(null);
    deviceChoice12.setOffsetNid(155);
    deviceChoice12.setLabelString(" ");
    deviceChoice12.setChoiceItems(new String[] {"1", "2", "5", "10"});
    deviceChoice12.setUpdateIdentifier("");
    deviceChoice12.setIdentifier("");
    deviceField116.setOffsetNid(153);
    deviceField116.setTextOnly(true);
    deviceField116.setNumCols(15);
    deviceField116.setIdentifier("");
    deviceField116.setEditable(false);
    deviceField117.setIdentifier("");
    deviceField117.setOffsetNid(138);
    deviceField118.setIdentifier("");
    deviceField118.setOffsetNid(143);
    deviceChoice13.setIdentifier("");
    deviceChoice13.setUpdateIdentifier("");
    deviceChoice13.setChoiceItems(new String[] {"1", "2", "5", "10"});
    deviceChoice13.setLabelString(" ");
    deviceChoice13.setOffsetNid(139);
    deviceChoice13.setChoiceFloatValues(null);
    deviceChoice13.setChoiceIntValues(new int[] {(int)1,(int)2,(int)5,(int)10});
    deviceChannel7.setShowVal("");
    deviceChannel7.setUpdateIdentifier("");
    deviceChannel7.setInSameLine(true);
    deviceChannel7.setOffsetNid(136);
    deviceChannel7.setLabelString("13");
    deviceChannel7.setLayout(flowLayout15);
    deviceField119.setOffsetNid(137);
    deviceField119.setTextOnly(true);
    deviceField119.setNumCols(15);
    deviceField119.setIdentifier("");
    deviceField119.setEditable(false);
    jPanel11.setLayout(flowLayout16);
    deviceChoice14.setChoiceIntValues(new int[] {(int)1,(int)2,(int)5,(int)10});
    deviceChoice14.setChoiceFloatValues(null);
    deviceChoice14.setOffsetNid(144);
    deviceChoice14.setLabelString("");
    deviceChoice14.setChoiceItems(new String[] {"1", "2", "5", "10"});
    deviceChoice14.setUpdateIdentifier("");
    deviceChoice14.setIdentifier("");
    deviceField1110.setOffsetNid(142);
    deviceField1110.setTextOnly(true);
    deviceField1110.setNumCols(15);
    deviceField1110.setIdentifier("");
    deviceField1110.setEditable(false);
    deviceField1111.setIdentifier("");
    deviceField1111.setOffsetNid(127);
    deviceField1112.setIdentifier("");
    deviceField1112.setOffsetNid(132);
    deviceChoice15.setIdentifier("");
    deviceChoice15.setUpdateIdentifier("");
    deviceChoice15.setChoiceItems(new String[] {"1", "2", "5", "10"});
    deviceChoice15.setLabelString(" ");
    deviceChoice15.setOffsetNid(128);
    deviceChoice15.setChoiceFloatValues(null);
    deviceChoice15.setChoiceIntValues(new int[] {(int)1,(int)2,(int)5,(int)10});
    deviceChannel8.setShowVal("");
    deviceChannel8.setUpdateIdentifier("");
    deviceChannel8.setInSameLine(true);
    deviceChannel8.setOffsetNid(125);
    deviceChannel8.setLabelString("12");
    deviceChannel8.setLayout(flowLayout17);
    deviceField1113.setOffsetNid(126);
    deviceField1113.setTextOnly(true);
    deviceField1113.setNumCols(15);
    deviceField1113.setIdentifier("");
    deviceField1113.setEditable(false);
    jPanel12.setLayout(flowLayout18);
    deviceChoice16.setChoiceIntValues(new int[] {(int)1,(int)2,(int)5,(int)10});
    deviceChoice16.setChoiceFloatValues(null);
    deviceChoice16.setOffsetNid(133);
    deviceChoice16.setLabelString(" ");
    deviceChoice16.setChoiceItems(new String[] {"1", "2", "5", "10"});
    deviceChoice16.setUpdateIdentifier("");
    deviceChoice16.setIdentifier("");
    deviceField1114.setOffsetNid(131);
    deviceField1114.setTextOnly(true);
    deviceField1114.setNumCols(15);
    deviceField1114.setIdentifier("");
    deviceField1114.setEditable(false);
    deviceField1115.setIdentifier("");
    deviceField1115.setOffsetNid(116);
    deviceField1116.setIdentifier("");
    deviceField1116.setOffsetNid(121);
    deviceChoice17.setIdentifier("");
    deviceChoice17.setUpdateIdentifier("");
    deviceChoice17.setChoiceItems(new String[] {"1", "2", "5", "10"});
    deviceChoice17.setLabelString(" ");
    deviceChoice17.setOffsetNid(117);
    deviceChoice17.setChoiceFloatValues(null);
    deviceChoice17.setChoiceIntValues(new int[] {(int)1,(int)2,(int)5,(int)10});
    deviceChannel9.setShowVal("");
    deviceChannel9.setUpdateIdentifier("");
    deviceChannel9.setInSameLine(true);
    deviceChannel9.setOffsetNid(114);
    deviceChannel9.setLabelString("11");
    deviceChannel9.setLayout(flowLayout19);
    deviceField1117.setOffsetNid(115);
    deviceField1117.setTextOnly(true);
    deviceField1117.setNumCols(15);
    deviceField1117.setIdentifier("");
    deviceField1117.setEditable(false);
    jPanel13.setLayout(flowLayout110);
    deviceChoice18.setChoiceIntValues(new int[] {(int)1,(int)2,(int)5,(int)10});
    deviceChoice18.setChoiceFloatValues(null);
    deviceChoice18.setOffsetNid(122);
    deviceChoice18.setLabelString(" ");
    deviceChoice18.setChoiceItems(new String[] {"1", "2", "5", "10"});
    deviceChoice18.setUpdateIdentifier("");
    deviceChoice18.setIdentifier("");
    deviceField1118.setOffsetNid(120);
    deviceField1118.setTextOnly(true);
    deviceField1118.setNumCols(15);
    deviceField1118.setIdentifier("");
    deviceField1118.setEditable(false);
    deviceField1119.setIdentifier("");
    deviceField1119.setOffsetNid(105);
    deviceField11110.setIdentifier("");
    deviceField11110.setOffsetNid(110);
    deviceChoice19.setIdentifier("");
    deviceChoice19.setUpdateIdentifier("");
    deviceChoice19.setChoiceItems(new String[] {"1", "2", "5", "10"});
    deviceChoice19.setLabelString(" ");
    deviceChoice19.setOffsetNid(106);
    deviceChoice19.setChoiceFloatValues(null);
    deviceChoice19.setChoiceIntValues(new int[] {(int)1,(int)2,(int)5,(int)10});
    deviceChannel10.setShowVal("");
    deviceChannel10.setUpdateIdentifier("");
    deviceChannel10.setInSameLine(true);
    deviceChannel10.setOffsetNid(103);
    deviceChannel10.setLabelString("10");
    deviceChannel10.setLayout(flowLayout111);
    deviceField11111.setOffsetNid(104);
    deviceField11111.setTextOnly(true);
    deviceField11111.setNumCols(15);
    deviceField11111.setIdentifier("");
    deviceField11111.setEditable(false);
    jPanel14.setLayout(flowLayout112);
    deviceChoice110.setChoiceIntValues(new int[] {(int)1,(int)2,(int)5,(int)10});
    deviceChoice110.setChoiceFloatValues(null);
    deviceChoice110.setOffsetNid(111);
    deviceChoice110.setLabelString(" ");
    deviceChoice110.setChoiceItems(new String[] {"1", "2", "5", "10"});
    deviceChoice110.setUpdateIdentifier("");
    deviceChoice110.setIdentifier("");
    deviceField11112.setOffsetNid(109);
    deviceField11112.setTextOnly(true);
    deviceField11112.setNumCols(15);
    deviceField11112.setIdentifier("");
    deviceField11112.setEditable(false);
    deviceField11113.setIdentifier("");
    deviceField11113.setOffsetNid(94);
    deviceField11114.setIdentifier("");
    deviceField11114.setOffsetNid(99);
    deviceChoice111.setIdentifier("");
    deviceChoice111.setUpdateIdentifier("");
    deviceChoice111.setChoiceItems(new String[] {"1", "2", "5", "10"});
    deviceChoice111.setLabelString("");
    deviceChoice111.setOffsetNid(95);
    deviceChoice111.setChoiceFloatValues(null);
    deviceChoice111.setChoiceIntValues(new int[] {(int)1,(int)2,(int)5,(int)10});
    deviceChannel11.setShowVal("");
    deviceChannel11.setUpdateIdentifier("");
    deviceChannel11.setInSameLine(true);
    deviceChannel11.setOffsetNid(92);
    deviceChannel11.setLabelString("09");
    deviceChannel11.setLayout(flowLayout113);
    deviceField11115.setOffsetNid(93);
    deviceField11115.setTextOnly(true);
    deviceField11115.setNumCols(15);
    deviceField11115.setIdentifier("");
    deviceField11115.setEditable(false);
    jPanel15.setLayout(flowLayout114);
    deviceChoice112.setChoiceIntValues(new int[] {(int)1,(int)2,(int)5,(int)10});
    deviceChoice112.setChoiceFloatValues(null);
    deviceChoice112.setOffsetNid(100);
    deviceChoice112.setLabelString(" ");
    deviceChoice112.setChoiceItems(new String[] {"1", "2", "5", "10"});
    deviceChoice112.setUpdateIdentifier("");
    deviceChoice112.setIdentifier("");
    deviceField11116.setOffsetNid(98);
    deviceField11116.setTextOnly(true);
    deviceField11116.setNumCols(15);
    deviceField11116.setIdentifier("");
    deviceField11116.setEditable(false);
    deviceField11117.setIdentifier("");
    deviceField11117.setOffsetNid(83);
    deviceField11118.setIdentifier("");
    deviceField11118.setOffsetNid(88);
    deviceChoice113.setIdentifier("");
    deviceChoice113.setUpdateIdentifier("");
    deviceChoice113.setChoiceItems(new String[] {"1", "2", "5", "10"});
    deviceChoice113.setLabelString(" ");
    deviceChoice113.setOffsetNid(84);
    deviceChoice113.setChoiceFloatValues(null);
    deviceChoice113.setChoiceIntValues(new int[] {(int)1,(int)2,(int)5,(int)10});
    deviceChannel12.setShowVal("");
    deviceChannel12.setUpdateIdentifier("");
    deviceChannel12.setInSameLine(true);
    deviceChannel12.setOffsetNid(81);
    deviceChannel12.setLabelString("08");
    deviceChannel12.setLayout(flowLayout115);
    deviceField11119.setOffsetNid(82);
    deviceField11119.setTextOnly(true);
    deviceField11119.setNumCols(15);
    deviceField11119.setIdentifier("");
    deviceField11119.setEditable(false);
    jPanel16.setLayout(flowLayout116);
    deviceChoice114.setChoiceIntValues(new int[] {(int)1,(int)2,(int)5,(int)10});
    deviceChoice114.setChoiceFloatValues(null);
    deviceChoice114.setOffsetNid(89);
    deviceChoice114.setLabelString(" ");
    deviceChoice114.setChoiceItems(new String[] {"1", "2", "5", "10"});
    deviceChoice114.setUpdateIdentifier("");
    deviceChoice114.setIdentifier("");
    deviceField111110.setOffsetNid(87);
    deviceField111110.setTextOnly(true);
    deviceField111110.setNumCols(15);
    deviceField111110.setIdentifier("");
    deviceField111110.setEditable(false);
    deviceField111111.setIdentifier("");
    deviceField111111.setOffsetNid(72);
    deviceField111112.setIdentifier("");
    deviceField111112.setOffsetNid(77);
    deviceChoice115.setIdentifier("");
    deviceChoice115.setUpdateIdentifier("");
    deviceChoice115.setChoiceItems(new String[] {"1", "2", "5", "10"});
    deviceChoice115.setLabelString(" ");
    deviceChoice115.setOffsetNid(73);
    deviceChoice115.setChoiceFloatValues(null);
    deviceChoice115.setChoiceIntValues(new int[] {(int)1,(int)2,(int)5,(int)10});
    deviceChannel13.setShowVal("");
    deviceChannel13.setUpdateIdentifier("");
    deviceChannel13.setInSameLine(true);
    deviceChannel13.setOffsetNid(70);
    deviceChannel13.setLabelString("07");
    deviceChannel13.setLayout(flowLayout117);
    deviceField111113.setOffsetNid(71);
    deviceField111113.setTextOnly(true);
    deviceField111113.setNumCols(15);
    deviceField111113.setIdentifier("");
    deviceField111113.setEditable(false);
    jPanel17.setLayout(flowLayout118);
    deviceChoice116.setChoiceIntValues(new int[] {(int)1,(int)2,(int)5,(int)10});
    deviceChoice116.setChoiceFloatValues(null);
    deviceChoice116.setOffsetNid(78);
    deviceChoice116.setLabelString(" ");
    deviceChoice116.setChoiceItems(new String[] {"1", "2", "5", "10"});
    deviceChoice116.setUpdateIdentifier("");
    deviceChoice116.setIdentifier("");
    deviceField111114.setOffsetNid(76);
    deviceField111114.setTextOnly(true);
    deviceField111114.setNumCols(15);
    deviceField111114.setIdentifier("");
    deviceField111114.setEditable(false);
    deviceField111115.setIdentifier("");
    deviceField111115.setOffsetNid(61);
    deviceField111116.setIdentifier("");
    deviceField111116.setOffsetNid(66);
    deviceChoice117.setIdentifier("");
    deviceChoice117.setUpdateIdentifier("");
    deviceChoice117.setChoiceItems(new String[] {"1", "2", "5", "10"});
    deviceChoice117.setLabelString(" ");
    deviceChoice117.setOffsetNid(62);
    deviceChoice117.setChoiceFloatValues(null);
    deviceChoice117.setChoiceIntValues(new int[] {(int)1,(int)2,(int)5,(int)10});
    deviceChannel14.setShowVal("");
    deviceChannel14.setUpdateIdentifier("");
    deviceChannel14.setInSameLine(true);
    deviceChannel14.setOffsetNid(59);
    deviceChannel14.setLabelString("06");
    deviceChannel14.setLayout(flowLayout119);
    deviceField111117.setOffsetNid(60);
    deviceField111117.setTextOnly(true);
    deviceField111117.setNumCols(15);
    deviceField111117.setIdentifier("");
    deviceField111117.setEditable(false);
    jPanel18.setLayout(flowLayout1110);
    deviceChoice118.setChoiceIntValues(new int[] {(int)1,(int)2,(int)5,(int)10});
    deviceChoice118.setChoiceFloatValues(null);
    deviceChoice118.setOffsetNid(67);
    deviceChoice118.setLabelString(" ");
    deviceChoice118.setChoiceItems(new String[] {"1", "2", "5", "10"});
    deviceChoice118.setUpdateIdentifier("");
    deviceChoice118.setIdentifier("");
    deviceField111118.setOffsetNid(65);
    deviceField111118.setTextOnly(true);
    deviceField111118.setNumCols(15);
    deviceField111118.setIdentifier("");
    deviceField111118.setEditable(false);
    deviceField111119.setIdentifier("");
    deviceField111119.setOffsetNid(50);
    deviceField1111110.setIdentifier("");
    deviceField1111110.setOffsetNid(55);
    deviceChoice119.setIdentifier("");
    deviceChoice119.setUpdateIdentifier("");
    deviceChoice119.setChoiceItems(new String[] {"1", "2", "5", "10"});
    deviceChoice119.setLabelString(" ");
    deviceChoice119.setOffsetNid(51);
    deviceChoice119.setChoiceFloatValues(null);
    deviceChoice119.setChoiceIntValues(new int[] {(int)1,(int)2,(int)5,(int)10});
    deviceChannel15.setShowVal("");
    deviceChannel15.setUpdateIdentifier("");
    deviceChannel15.setInSameLine(true);
    deviceChannel15.setOffsetNid(48);
    deviceChannel15.setLabelString("05");
    deviceChannel15.setLayout(flowLayout1111);
    deviceField1111111.setOffsetNid(49);
    deviceField1111111.setTextOnly(true);
    deviceField1111111.setNumCols(15);
    deviceField1111111.setIdentifier("");
    deviceField1111111.setEditable(false);
    jPanel19.setLayout(flowLayout1112);
    deviceChoice1110.setChoiceIntValues(new int[] {(int)1,(int)2,(int)5,(int)10});
    deviceChoice1110.setChoiceFloatValues(null);
    deviceChoice1110.setOffsetNid(56);
    deviceChoice1110.setLabelString("");
    deviceChoice1110.setChoiceItems(new String[] {"1", "2", "5", "10"});
    deviceChoice1110.setUpdateIdentifier("");
    deviceChoice1110.setIdentifier("");
    deviceField1111112.setOffsetNid(54);
    deviceField1111112.setTextOnly(true);
    deviceField1111112.setNumCols(15);
    deviceField1111112.setIdentifier("");
    deviceField1111112.setEditable(false);
    deviceField1111113.setIdentifier("");
    deviceField1111113.setOffsetNid(39);
    deviceField1111114.setIdentifier("");
    deviceField1111114.setOffsetNid(44);
    deviceChoice1111.setIdentifier("");
    deviceChoice1111.setUpdateIdentifier("");
    deviceChoice1111.setChoiceItems(new String[] {"1", "2", "5", "10"});
    deviceChoice1111.setLabelString(" ");
    deviceChoice1111.setOffsetNid(40);
    deviceChoice1111.setChoiceFloatValues(null);
    deviceChoice1111.setChoiceIntValues(new int[] {(int)1,(int)2,(int)5,(int)10});
    deviceChannel16.setShowVal("");
    deviceChannel16.setUpdateIdentifier("");
    deviceChannel16.setInSameLine(true);
    deviceChannel16.setOffsetNid(37);
    deviceChannel16.setLabelString("04");
    deviceChannel16.setLayout(flowLayout1113);
    deviceField1111115.setOffsetNid(38);
    deviceField1111115.setTextOnly(true);
    deviceField1111115.setNumCols(15);
    deviceField1111115.setIdentifier("");
    deviceField1111115.setEditable(false);
    jPanel110.setLayout(flowLayout1114);
    deviceChoice1112.setChoiceIntValues(new int[] {(int)1,(int)2,(int)5,(int)10});
    deviceChoice1112.setChoiceFloatValues(null);
    deviceChoice1112.setOffsetNid(45);
    deviceChoice1112.setLabelString(" ");
    deviceChoice1112.setChoiceItems(new String[] {"1", "2", "5", "10"});
    deviceChoice1112.setUpdateIdentifier("");
    deviceChoice1112.setIdentifier("");
    deviceField1111116.setOffsetNid(43);
    deviceField1111116.setTextOnly(true);
    deviceField1111116.setNumCols(15);
    deviceField1111116.setIdentifier("");
    deviceField1111116.setEditable(false);
    deviceField1111117.setIdentifier("");
    deviceField1111117.setOffsetNid(28);
    deviceField1111118.setIdentifier("");
    deviceField1111118.setOffsetNid(33);
    deviceChoice1113.setIdentifier("");
    deviceChoice1113.setUpdateIdentifier("");
    deviceChoice1113.setChoiceItems(new String[] {"1", "2", "5", "10"});
    deviceChoice1113.setLabelString("");
    deviceChoice1113.setOffsetNid(29);
    deviceChoice1113.setChoiceFloatValues(null);
    deviceChoice1113.setChoiceIntValues(new int[] {(int)1,(int)2,(int)5,(int)10});
    deviceChannel17.setShowVal("");
    deviceChannel17.setUpdateIdentifier("");
    deviceChannel17.setInSameLine(true);
    deviceChannel17.setOffsetNid(26);
    deviceChannel17.setLabelString("03");
    deviceChannel17.setLayout(flowLayout1115);
    deviceField1111119.setOffsetNid(27);
    deviceField1111119.setTextOnly(true);
    deviceField1111119.setNumCols(15);
    deviceField1111119.setIdentifier("");
    deviceField1111119.setEditable(false);
    jPanel111.setLayout(flowLayout1116);
    deviceChoice1114.setChoiceIntValues(new int[] {(int)1,(int)2,(int)5,(int)10});
    deviceChoice1114.setChoiceFloatValues(null);
    deviceChoice1114.setOffsetNid(34);
    deviceChoice1114.setLabelString(" ");
    deviceChoice1114.setChoiceItems(new String[] {"1", "2", "5", "10"});
    deviceChoice1114.setUpdateIdentifier("");
    deviceChoice1114.setIdentifier("");
    deviceField11111110.setOffsetNid(32);
    deviceField11111110.setTextOnly(true);
    deviceField11111110.setNumCols(15);
    deviceField11111110.setIdentifier("");
    deviceField11111110.setEditable(false);
    deviceField11111111.setIdentifier("");
    deviceField11111111.setOffsetNid(17);
    deviceField11111112.setIdentifier("");
    deviceField11111112.setOffsetNid(22);
    deviceChoice1115.setIdentifier("");
    deviceChoice1115.setUpdateIdentifier("");
    deviceChoice1115.setChoiceItems(new String[] {"1", "2", "5", "10"});
    deviceChoice1115.setLabelString(" ");
    deviceChoice1115.setOffsetNid(18);
    deviceChoice1115.setChoiceFloatValues(null);
    deviceChoice1115.setChoiceIntValues(new int[] {(int)1,(int)2,(int)5,(int)10});
    deviceChannel18.setShowVal("");
    deviceChannel18.setUpdateIdentifier("");
    deviceChannel18.setInSameLine(true);
    deviceChannel18.setOffsetNid(15);
    deviceChannel18.setLabelString("02");
    deviceChannel18.setLayout(flowLayout1117);
    deviceField11111113.setOffsetNid(16);
    deviceField11111113.setTextOnly(true);
    deviceField11111113.setNumCols(15);
    deviceField11111113.setIdentifier("");
    deviceField11111113.setEditable(false);
    jPanel112.setLayout(flowLayout1118);
    deviceChoice1116.setChoiceIntValues(new int[] {(int)1,(int)2,(int)5,(int)10});
    deviceChoice1116.setChoiceFloatValues(null);
    deviceChoice1116.setOffsetNid(23);
    deviceChoice1116.setLabelString(" ");
    deviceChoice1116.setChoiceItems(new String[] {"1", "2", "5", "10"});
    deviceChoice1116.setUpdateIdentifier("");
    deviceChoice1116.setIdentifier("");
    deviceField11111114.setOffsetNid(21);
    deviceField11111114.setTextOnly(true);
    deviceField11111114.setNumCols(15);
    deviceField11111114.setIdentifier("");
    deviceField11111114.setEditable(false);
    jPanel19.setAlignmentY((float) 0.5);
    deviceButtons1.setMethods(new String[] {"init"});
    flowLayout1113.setVgap(0);
    flowLayout3.setVgap(5);
    flowLayout4.setVgap(5);
    flowLayout1117.setVgap(5);
    flowLayout1118.setVgap(5);
    this.getContentPane().add(deviceButtons1, BorderLayout.SOUTH);
    this.getContentPane().add(jPanel1, BorderLayout.NORTH);
    jPanel1.add(jPanel2, null);
    jPanel2.add(deviceField1, null);
    jPanel2.add(deviceDispatch1, null);
    jPanel1.add(jPanel3, null);
    jPanel3.add(deviceField2, null);
    jPanel1.add(jLabel1, null);
    this.getContentPane().add(jScrollPane1, BorderLayout.CENTER);
    jScrollPane1.getViewport().add(jPanel4, null);
    jPanel4.add(deviceChannel1, null);
    deviceChannel1.add(jPanel5, null);
    jPanel5.add(deviceField6, null);
    jPanel5.add(deviceField5, null);
    jPanel5.add(deviceChoice2, null);
    jPanel5.add(deviceField4, null);
    jPanel5.add(deviceField3, null);
    jPanel5.add(deviceChoice1, null);
    jPanel4.add(deviceChannel18, null);
    deviceChannel18.add(jPanel112, null);
    jPanel112.add(deviceField11111113, null);
    jPanel112.add(deviceField11111111, null);
    jPanel112.add(deviceChoice1115, null);
    jPanel112.add(deviceField11111114, null);
    jPanel112.add(deviceField11111112, null);
    jPanel112.add(deviceChoice1116, null);
    jPanel4.add(deviceChannel17, null);
    deviceChannel17.add(jPanel111, null);
    jPanel111.add(deviceField1111119, null);
    jPanel111.add(deviceField1111117, null);
    jPanel111.add(deviceChoice1113, null);
    jPanel111.add(deviceField11111110, null);
    jPanel111.add(deviceField1111118, null);
    jPanel111.add(deviceChoice1114, null);
    jPanel4.add(deviceChannel16, null);
    deviceChannel16.add(jPanel110, null);
    jPanel110.add(deviceField1111115, null);
    jPanel110.add(deviceField1111113, null);
    jPanel110.add(deviceChoice1111, null);
    jPanel110.add(deviceField1111116, null);
    jPanel110.add(deviceField1111114, null);
    jPanel110.add(deviceChoice1112, null);
    jPanel4.add(deviceChannel15, null);
    deviceChannel15.add(jPanel19, null);
    jPanel19.add(deviceField1111111, null);
    jPanel19.add(deviceField111119, null);
    jPanel19.add(deviceChoice119, null);
    jPanel19.add(deviceField1111112, null);
    jPanel19.add(deviceField1111110, null);
    jPanel19.add(deviceChoice1110, null);
    jPanel4.add(deviceChannel14, null);
    deviceChannel14.add(jPanel18, null);
    jPanel18.add(deviceField111117, null);
    jPanel18.add(deviceField111115, null);
    jPanel18.add(deviceChoice117, null);
    jPanel18.add(deviceField111118, null);
    jPanel18.add(deviceField111116, null);
    jPanel18.add(deviceChoice118, null);
    jPanel4.add(deviceChannel13, null);
    deviceChannel13.add(jPanel17, null);
    jPanel17.add(deviceField111113, null);
    jPanel17.add(deviceField111111, null);
    jPanel17.add(deviceChoice115, null);
    jPanel17.add(deviceField111114, null);
    jPanel17.add(deviceField111112, null);
    jPanel17.add(deviceChoice116, null);
    jPanel4.add(deviceChannel12, null);
    deviceChannel12.add(jPanel16, null);
    jPanel16.add(deviceField11119, null);
    jPanel16.add(deviceField11117, null);
    jPanel16.add(deviceChoice113, null);
    jPanel16.add(deviceField111110, null);
    jPanel16.add(deviceField11118, null);
    jPanel16.add(deviceChoice114, null);
    jPanel4.add(deviceChannel11, null);
    deviceChannel11.add(jPanel15, null);
    jPanel15.add(deviceField11115, null);
    jPanel15.add(deviceField11113, null);
    jPanel15.add(deviceChoice111, null);
    jPanel15.add(deviceField11116, null);
    jPanel15.add(deviceField11114, null);
    jPanel15.add(deviceChoice112, null);
    jPanel4.add(deviceChannel10, null);
    deviceChannel10.add(jPanel14, null);
    jPanel14.add(deviceField11111, null);
    jPanel14.add(deviceField1119, null);
    jPanel14.add(deviceChoice19, null);
    jPanel14.add(deviceField11112, null);
    jPanel14.add(deviceField11110, null);
    jPanel14.add(deviceChoice110, null);
    jPanel4.add(deviceChannel9, null);
    deviceChannel9.add(jPanel13, null);
    jPanel13.add(deviceField1117, null);
    jPanel13.add(deviceField1115, null);
    jPanel13.add(deviceChoice17, null);
    jPanel13.add(deviceField1118, null);
    jPanel13.add(deviceField1116, null);
    jPanel13.add(deviceChoice18, null);
    jPanel4.add(deviceChannel8, null);
    deviceChannel8.add(jPanel12, null);
    jPanel12.add(deviceField1113, null);
    jPanel12.add(deviceField1111, null);
    jPanel12.add(deviceChoice15, null);
    jPanel12.add(deviceField1114, null);
    jPanel12.add(deviceField1112, null);
    jPanel12.add(deviceChoice16, null);
    jPanel4.add(deviceChannel7, null);
    deviceChannel7.add(jPanel11, null);
    jPanel11.add(deviceField119, null);
    jPanel11.add(deviceField117, null);
    jPanel11.add(deviceChoice13, null);
    jPanel11.add(deviceField1110, null);
    jPanel11.add(deviceField118, null);
    jPanel11.add(deviceChoice14, null);
    jPanel4.add(deviceChannel6, null);
    deviceChannel6.add(jPanel10, null);
    jPanel10.add(deviceField115, null);
    jPanel10.add(deviceField113, null);
    jPanel10.add(deviceChoice11, null);
    jPanel10.add(deviceField116, null);
    jPanel10.add(deviceField114, null);
    jPanel10.add(deviceChoice12, null);
    jPanel4.add(deviceChannel5, null);
    deviceChannel5.add(jPanel9, null);
    jPanel9.add(deviceField111, null);
    jPanel9.add(deviceField19, null);
    jPanel9.add(deviceChoice9, null);
    jPanel9.add(deviceField112, null);
    jPanel9.add(deviceField110, null);
    jPanel9.add(deviceChoice10, null);
    jPanel4.add(deviceChannel4, null);
    deviceChannel4.add(jPanel8, null);
    jPanel8.add(deviceField17, null);
    jPanel8.add(deviceField15, null);
    jPanel8.add(deviceChoice7, null);
    jPanel8.add(deviceField18, null);
    jPanel8.add(deviceField16, null);
    jPanel8.add(deviceChoice8, null);
    jPanel4.add(deviceChannel3, null);
    deviceChannel3.add(jPanel7, null);
    jPanel7.add(deviceField13, null);
    jPanel7.add(deviceField11, null);
    jPanel7.add(deviceChoice5, null);
    jPanel7.add(deviceField14, null);
    jPanel7.add(deviceField12, null);
    jPanel7.add(deviceChoice6, null);
    jPanel4.add(deviceChannel2, null);
    deviceChannel2.add(jPanel6, null);
    jPanel6.add(deviceField9, null);
    jPanel6.add(deviceField7, null);
    jPanel6.add(deviceChoice3, null);
    jPanel6.add(deviceField10, null);
    jPanel6.add(deviceField8, null);
    jPanel6.add(deviceChoice4, null);
  }

}