
import java.awt.*;
import javax.swing.*;
import javax.swing.border.Border;
import javax.swing.border.TitledBorder;
public class K3115Setup extends DeviceSetup {
  DeviceField deviceField1 = new DeviceField();
  DeviceField deviceField2 = new DeviceField();
  DeviceChoice deviceChoice1 = new DeviceChoice();
  DeviceField deviceField3 = new DeviceField();
  DeviceChoice deviceChoice2 = new DeviceChoice();
  DeviceChoice deviceChoice3 = new DeviceChoice();
  DeviceChoice deviceChoice4 = new DeviceChoice();
  JTabbedPane jTabbedPane1 = new JTabbedPane();
  JPanel jPanel1 = new JPanel();
  BorderLayout borderLayout1 = new BorderLayout();
  DeviceChannel deviceChannel1 = new DeviceChannel();
  JPanel jPanel2 = new JPanel();
  GridLayout gridLayout1 = new GridLayout();
  JPanel jPanel3 = new JPanel();
  JPanel jPanel4 = new JPanel();
  JPanel jPanel5 = new JPanel();
  DeviceField deviceField4 = new DeviceField();
  DeviceChoice deviceChoice5 = new DeviceChoice();
  DeviceChoice deviceChoice6 = new DeviceChoice();
  DeviceChoice deviceChoice7 = new DeviceChoice();
  DeviceField deviceField5 = new DeviceField();
  DeviceField deviceField6 = new DeviceField();
  JPanel jPanel6 = new JPanel();
  JPanel jPanel7 = new JPanel();
  JPanel jPanel8 = new JPanel();
  JPanel jPanel9 = new JPanel();
  BorderLayout borderLayout2 = new BorderLayout();
  DeviceButtons deviceButtons1 = new DeviceButtons();
  DeviceField deviceField7 = new DeviceField();
  DeviceField deviceField8 = new DeviceField();
  DeviceField deviceField9 = new DeviceField();
  BorderLayout borderLayout3 = new BorderLayout();
  DeviceChannel deviceChannel2 = new DeviceChannel();
  JPanel jPanel10 = new JPanel();
  DeviceChoice deviceChoice8 = new DeviceChoice();
  JPanel jPanel11 = new JPanel();
  JPanel jPanel12 = new JPanel();
  GridLayout gridLayout2 = new GridLayout();
  JPanel jPanel13 = new JPanel();
  JPanel jPanel14 = new JPanel();
  DeviceChoice deviceChoice9 = new DeviceChoice();
  DeviceChoice deviceChoice10 = new DeviceChoice();
  DeviceField deviceField10 = new DeviceField();
  DeviceField deviceField11 = new DeviceField();
  DeviceField deviceField12 = new DeviceField();
  BorderLayout borderLayout4 = new BorderLayout();
  DeviceChannel deviceChannel3 = new DeviceChannel();
  JPanel jPanel15 = new JPanel();
  DeviceChoice deviceChoice11 = new DeviceChoice();
  JPanel jPanel16 = new JPanel();
  JPanel jPanel17 = new JPanel();
  GridLayout gridLayout3 = new GridLayout();
  JPanel jPanel18 = new JPanel();
  JPanel jPanel19 = new JPanel();
  DeviceChoice deviceChoice12 = new DeviceChoice();
  DeviceChoice deviceChoice13 = new DeviceChoice();
  DeviceField deviceField13 = new DeviceField();
  DeviceField deviceField14 = new DeviceField();
  DeviceField deviceField15 = new DeviceField();
  BorderLayout borderLayout5 = new BorderLayout();
  DeviceChannel deviceChannel4 = new DeviceChannel();
  JPanel jPanel110 = new JPanel();
  DeviceChoice deviceChoice14 = new DeviceChoice();
  JPanel jPanel111 = new JPanel();
  JPanel jPanel112 = new JPanel();
  GridLayout gridLayout4 = new GridLayout();
  JPanel jPanel113 = new JPanel();
  JPanel jPanel114 = new JPanel();
  DeviceChoice deviceChoice15 = new DeviceChoice();
  DeviceChoice deviceChoice16 = new DeviceChoice();
  DeviceField deviceField16 = new DeviceField();
  DeviceField deviceField17 = new DeviceField();
  DeviceField deviceField18 = new DeviceField();
  BorderLayout borderLayout6 = new BorderLayout();
  DeviceChannel deviceChannel5 = new DeviceChannel();
  JPanel jPanel115 = new JPanel();
  DeviceChoice deviceChoice17 = new DeviceChoice();
  JPanel jPanel116 = new JPanel();
  JPanel jPanel117 = new JPanel();
  GridLayout gridLayout5 = new GridLayout();
  JPanel jPanel118 = new JPanel();
  JPanel jPanel119 = new JPanel();
  DeviceChoice deviceChoice18 = new DeviceChoice();
  DeviceChoice deviceChoice19 = new DeviceChoice();
  DeviceField deviceField19 = new DeviceField();
  DeviceField deviceField110 = new DeviceField();
  DeviceField deviceField111 = new DeviceField();
  BorderLayout borderLayout7 = new BorderLayout();
  DeviceChannel deviceChannel6 = new DeviceChannel();
  JPanel jPanel1110 = new JPanel();
  DeviceChoice deviceChoice110 = new DeviceChoice();
  JPanel jPanel1111 = new JPanel();
  JPanel jPanel1112 = new JPanel();
  GridLayout gridLayout6 = new GridLayout();
  JPanel jPanel1113 = new JPanel();
  JPanel jPanel1114 = new JPanel();
  DeviceChoice deviceChoice111 = new DeviceChoice();
  DeviceChoice deviceChoice112 = new DeviceChoice();
  DeviceDispatch deviceDispatch1 = new DeviceDispatch();


  public K3115Setup() {
    try {
      jbInit();
    }
    catch(Exception e) {
      e.printStackTrace();
    }
  }
  private void jbInit() throws Exception {
    this.getContentPane().setLayout(null);
    deviceField1.setOffsetNid(1);
    deviceField1.setTextOnly(true);
    deviceField1.setLabelString("Camac Name :");
    deviceField1.setNumCols(10);
    deviceField1.setIdentifier("");
    deviceField1.setPreferredWidth(-1);
    deviceField1.setBounds(new Rectangle(12, 15, 226, 31));
    this.setWidth(529);
    this.setHeight(529);
    this.setDeviceType("K3115");
    this.setDeviceProvider("localhost");
    this.setDeviceTitle("K3115: Six Channel Waveform Generator");
    deviceField2.setOffsetNid(2);
    deviceField2.setTextOnly(true);
    deviceField2.setLabelString("Comment :");
    deviceField2.setNumCols(33);
    deviceField2.setIdentifier("");
    deviceField2.setBounds(new Rectangle(25, 45, 472, 34));
    deviceChoice1.setChoiceIntValues(null);
    deviceChoice1.setChoiceFloatValues(null);
    deviceChoice1.setOffsetNid(3);
    deviceChoice1.setLabelString("Mode :");
    deviceChoice1.setChoiceItems(new String[] {"INTERNAL", "EXTERNAL"});
    deviceChoice1.setUpdateIdentifier("");
    deviceChoice1.setIdentifier("");
    deviceChoice1.setBounds(new Rectangle(347, 17, 145, 37));
    deviceField3.setOffsetNid(4);
    deviceField3.setLabelString("Source :");
    deviceField3.setNumCols(24);
    deviceField3.setIdentifier("");
    deviceField3.setBounds(new Rectangle(6, 16, 340, 34));
    deviceChoice2.setChoiceIntValues(null);
    deviceChoice2.setChoiceFloatValues(new float[] {(float)50.0,(float)100.0,(float)250.0,(float)500.0,(float)1000.0,(float)2500.0,(float)5000.0,(float)10000.0});
    deviceChoice2.setOffsetNid(5);
    deviceChoice2.setLabelString("Frequency (Hz) :");
    deviceChoice2.setChoiceItems(new String[] {"50", "100", "250", "500", "1E3", "2.5E3", "5E3", "10E3"});
    deviceChoice2.setUpdateIdentifier("");
    deviceChoice2.setIdentifier("");
    deviceChoice2.setBounds(new Rectangle(320, 52, 174, 35));
    deviceChoice3.setChoiceIntValues(null);
    deviceChoice3.setChoiceFloatValues(null);
    deviceChoice3.setOffsetNid(6);
    deviceChoice3.setLabelString("Control Mode :");
    deviceChoice3.setChoiceItems(new String[] {"MASTER", "SLAVE"});
    deviceChoice3.setUpdateIdentifier("");
    deviceChoice3.setIdentifier("");
    deviceChoice3.setBounds(new Rectangle(313, 16, 177, 38));
    deviceChoice4.setChoiceIntValues(null);
    deviceChoice4.setChoiceFloatValues(null);
    deviceChoice4.setOffsetNid(7);
    deviceChoice4.setLabelString("Wave Mode :");
    deviceChoice4.setChoiceItems(new String[] {"CYCLIC", "ACYCLIC"});
    deviceChoice4.setUpdateIdentifier("");
    deviceChoice4.setIdentifier("");
    deviceChoice4.setBounds(new Rectangle(13, 15, 163, 35));
    jPanel1.setLayout(borderLayout1);
    jPanel2.setLayout(gridLayout1);
    gridLayout1.setColumns(1);
    gridLayout1.setRows(3);
    deviceField4.setOffsetNid(15);
    deviceField4.setLabelString("Waveform :");
    deviceField4.setNumCols(35);
    deviceField4.setIdentifier("");
    deviceField4.setPreferredWidth(-1);
    deviceField4.setBounds(new Rectangle(5, 0, 475, 37));
    jPanel5.setLayout(null);
    jPanel3.setLayout(null);
    deviceChoice7.setChoiceIntValues(null);
    deviceChoice7.setChoiceFloatValues(null);
    deviceChoice7.setOffsetNid(12);
    deviceChoice7.setLabelString("Polarity :");
    deviceChoice7.setChoiceItems(new String[] {"UNIPOLAR", "BIPOLAR"});
    deviceChoice7.setUpdateIdentifier("");
    deviceChoice7.setIdentifier("");
    deviceChoice7.setBounds(new Rectangle(324, 0, 150, 35));
    deviceChoice6.setChoiceIntValues(null);
    deviceChoice6.setChoiceFloatValues(new float[] {(float)5.0,(float)10.0,(float)20.0});
    deviceChoice6.setOffsetNid(11);
    deviceChoice6.setLabelString("Range (V p-p) :");
    deviceChoice6.setChoiceItems(new String[] {"5", "10", "20"});
    deviceChoice6.setUpdateIdentifier("");
    deviceChoice6.setIdentifier("");
    deviceChoice6.setBounds(new Rectangle(166, 0, 149, 35));
    jPanel4.setLayout(null);
    deviceChoice5.setChoiceIntValues(null);
    deviceChoice5.setChoiceFloatValues(null);
    deviceChoice5.setOffsetNid(13);
    deviceChoice5.setLabelString("Mode :");
    deviceChoice5.setChoiceItems(new String[] {"AS IS", "VARIABLE"});
    deviceChoice5.setUpdateIdentifier("");
    deviceChoice5.setIdentifier("");
    deviceChoice5.setBounds(new Rectangle(9, 0, 135, 35));
    deviceField5.setOffsetNid(9);
    deviceField5.setLabelString("Start Time :");
    deviceField5.setNumCols(7);
    deviceField5.setIdentifier("");
    deviceField5.setBounds(new Rectangle(141, 0, 166, 31));
    deviceField6.setOffsetNid(10);
    deviceField6.setLabelString("End Time :");
    deviceField6.setNumCols(7);
    deviceField6.setIdentifier("");
    deviceField6.setBounds(new Rectangle(310, 0, 167, 38));
    jPanel1.setAlignmentX((float) 0.5);
    jPanel1.setBorder(BorderFactory.createEmptyBorder());
    deviceChannel1.setLabelString("On / Off");
    deviceChannel1.setOffsetNid(8);
    deviceChannel1.setLines(1);
    deviceChannel1.setUpdateIdentifier("");
    deviceChannel1.setShowVal("");
    jPanel6.setBorder(new TitledBorder(BorderFactory.createEtchedBorder(Color.white,new Color(142, 142, 142))," General "));
    jPanel6.setBounds(new Rectangle(12, 7, 502, 88));
    jPanel6.setLayout(null);
    jPanel7.setBorder(new TitledBorder(BorderFactory.createEtchedBorder(Color.white,new Color(142, 142, 142))," Clock "));
    jPanel7.setBounds(new Rectangle(12, 94, 503, 97));
    jPanel7.setLayout(null);
    jPanel8.setBorder(new TitledBorder(BorderFactory.createEtchedBorder(Color.white,new Color(142, 142, 142))," Other "));
    jPanel8.setBounds(new Rectangle(12, 191, 504, 64));
    jPanel8.setLayout(null);
    jPanel9.setBorder(new TitledBorder(BorderFactory.createEtchedBorder(Color.white,new Color(142, 142, 142))," Channels "));
    jPanel9.setBounds(new Rectangle(11, 255, 504, 180));
    jPanel9.setLayout(borderLayout2);
    deviceButtons1.setCheckExpressions(null);
    deviceButtons1.setCheckMessages(null);
    deviceButtons1.setMethods(new String[] {"INIT", "TRIGGER", "RESET"});
    deviceButtons1.setBounds(new Rectangle(78, 451, 362, 40));
    jTabbedPane1.setBorder(null);
    deviceField7.setBounds(new Rectangle(141, 0, 166, 31));
    deviceField7.setIdentifier("");
    deviceField7.setNumCols(7);
    deviceField7.setLabelString("Start Time :");
    deviceField7.setOffsetNid(17);
    deviceField8.setBounds(new Rectangle(5, 0, 475, 37));
    deviceField8.setPreferredWidth(-1);
    deviceField8.setIdentifier("");
    deviceField8.setNumCols(35);
    deviceField8.setLabelString("Waveform :");
    deviceField8.setOffsetNid(23);
    deviceField9.setBounds(new Rectangle(310, 0, 167, 38));
    deviceField9.setIdentifier("");
    deviceField9.setNumCols(7);
    deviceField9.setLabelString("End Time :");
    deviceField9.setOffsetNid(18);
    deviceChannel2.setLines(1);
    deviceChannel2.setUpdateIdentifier("");
    deviceChannel2.setShowVal("");
    deviceChannel2.setLabelString("On / Off");
    deviceChannel2.setOffsetNid(16);
    jPanel10.setLayout(borderLayout3);
    jPanel10.setAlignmentX((float) 0.5);
    jPanel10.setBorder(BorderFactory.createEmptyBorder());
    deviceChoice8.setChoiceIntValues(null);
    deviceChoice8.setChoiceFloatValues(new float[] {(float)5.0,(float)10.0,(float)20.0});
    deviceChoice8.setOffsetNid(19);
    deviceChoice8.setLabelString("Range (V p-p) :");
    deviceChoice8.setChoiceItems(new String[] {"5", "10", "20"});
    deviceChoice8.setUpdateIdentifier("");
    deviceChoice8.setIdentifier("");
    deviceChoice8.setBounds(new Rectangle(166, 0, 149, 35));
    jPanel11.setLayout(null);
    jPanel12.setLayout(null);
    gridLayout2.setColumns(1);
    gridLayout2.setRows(3);
    jPanel13.setLayout(gridLayout2);
    jPanel14.setLayout(null);
    deviceChoice9.setChoiceIntValues(null);
    deviceChoice9.setChoiceFloatValues(null);
    deviceChoice9.setOffsetNid(20);
    deviceChoice9.setLabelString("Polarity :");
    deviceChoice9.setChoiceItems(new String[] {"UNIPOLAR", "BIPOLAR"});
    deviceChoice9.setUpdateIdentifier("");
    deviceChoice9.setIdentifier("");
    deviceChoice9.setBounds(new Rectangle(324, 0, 150, 35));
    deviceChoice10.setChoiceIntValues(null);
    deviceChoice10.setChoiceFloatValues(null);
    deviceChoice10.setOffsetNid(21);
    deviceChoice10.setLabelString("Mode :");
    deviceChoice10.setChoiceItems(new String[] {"AS IS", "VARIABLE"});
    deviceChoice10.setUpdateIdentifier("");
    deviceChoice10.setIdentifier("");
    deviceChoice10.setBounds(new Rectangle(9, 0, 135, 35));
    deviceField10.setBounds(new Rectangle(141, 0, 166, 31));
    deviceField10.setIdentifier("");
    deviceField10.setNumCols(7);
    deviceField10.setLabelString("Start Time :");
    deviceField10.setOffsetNid(25);
    deviceField11.setBounds(new Rectangle(5, 0, 475, 37));
    deviceField11.setPreferredWidth(-1);
    deviceField11.setIdentifier("");
    deviceField11.setNumCols(35);
    deviceField11.setLabelString("Waveform :");
    deviceField11.setOffsetNid(31);
    deviceField12.setBounds(new Rectangle(310, 0, 167, 38));
    deviceField12.setIdentifier("");
    deviceField12.setNumCols(7);
    deviceField12.setLabelString("End Time :");
    deviceField12.setOffsetNid(26);
    deviceChannel3.setLines(1);
    deviceChannel3.setUpdateIdentifier("");
    deviceChannel3.setShowVal("");
    deviceChannel3.setLabelString("On / Off");
    deviceChannel3.setOffsetNid(24);
    jPanel15.setLayout(borderLayout4);
    jPanel15.setAlignmentX((float) 0.5);
    jPanel15.setBorder(BorderFactory.createEmptyBorder());
    deviceChoice11.setChoiceIntValues(null);
    deviceChoice11.setChoiceFloatValues(new float[] {(float)5.0,(float)10.0,(float)20.0});
    deviceChoice11.setOffsetNid(27);
    deviceChoice11.setLabelString("Range (V p-p) :");
    deviceChoice11.setChoiceItems(new String[] {"5", "10", "20"});
    deviceChoice11.setUpdateIdentifier("");
    deviceChoice11.setIdentifier("");
    deviceChoice11.setBounds(new Rectangle(166, 0, 149, 35));
    jPanel16.setLayout(null);
    jPanel17.setLayout(null);
    gridLayout3.setColumns(1);
    gridLayout3.setRows(3);
    jPanel18.setLayout(gridLayout3);
    jPanel19.setLayout(null);
    deviceChoice12.setChoiceIntValues(null);
    deviceChoice12.setChoiceFloatValues(null);
    deviceChoice12.setOffsetNid(28);
    deviceChoice12.setLabelString("Polarity :");
    deviceChoice12.setChoiceItems(new String[] {"UNIPOLAR", "BIPOLAR"});
    deviceChoice12.setUpdateIdentifier("");
    deviceChoice12.setIdentifier("");
    deviceChoice12.setBounds(new Rectangle(324, 0, 150, 35));
    deviceChoice13.setChoiceIntValues(null);
    deviceChoice13.setChoiceFloatValues(null);
    deviceChoice13.setOffsetNid(29);
    deviceChoice13.setLabelString("Mode :");
    deviceChoice13.setChoiceItems(new String[] {"AS IS", "VARIABLE"});
    deviceChoice13.setUpdateIdentifier("");
    deviceChoice13.setIdentifier("");
    deviceChoice13.setBounds(new Rectangle(9, 0, 135, 35));
    deviceField13.setBounds(new Rectangle(141, 0, 166, 31));
    deviceField13.setIdentifier("");
    deviceField13.setNumCols(7);
    deviceField13.setLabelString("Start Time :");
    deviceField13.setOffsetNid(33);
    deviceField14.setBounds(new Rectangle(5, 0, 475, 37));
    deviceField14.setPreferredWidth(-1);
    deviceField14.setIdentifier("");
    deviceField14.setNumCols(35);
    deviceField14.setLabelString("Waveform :");
    deviceField14.setOffsetNid(39);
    deviceField15.setBounds(new Rectangle(310, 0, 167, 38));
    deviceField15.setIdentifier("");
    deviceField15.setNumCols(7);
    deviceField15.setLabelString("End Time :");
    deviceField15.setOffsetNid(34);
    deviceChannel4.setLines(1);
    deviceChannel4.setUpdateIdentifier("");
    deviceChannel4.setShowVal("");
    deviceChannel4.setLabelString("On / Off");
    deviceChannel4.setOffsetNid(32);
    jPanel110.setLayout(borderLayout5);
    jPanel110.setAlignmentX((float) 0.5);
    jPanel110.setBorder(BorderFactory.createEmptyBorder());
    deviceChoice14.setChoiceIntValues(null);
    deviceChoice14.setChoiceFloatValues(new float[] {(float)5.0,(float)10.0,(float)20.0});
    deviceChoice14.setOffsetNid(35);
    deviceChoice14.setLabelString("Range (V p-p) :");
    deviceChoice14.setChoiceItems(new String[] {"5", "10", "20"});
    deviceChoice14.setUpdateIdentifier("");
    deviceChoice14.setIdentifier("");
    deviceChoice14.setBounds(new Rectangle(166, 0, 149, 35));
    jPanel111.setLayout(null);
    jPanel112.setLayout(null);
    gridLayout4.setColumns(1);
    gridLayout4.setRows(3);
    jPanel113.setLayout(gridLayout4);
    jPanel114.setLayout(null);
    deviceChoice15.setChoiceIntValues(null);
    deviceChoice15.setChoiceFloatValues(null);
    deviceChoice15.setOffsetNid(36);
    deviceChoice15.setLabelString("Polarity :");
    deviceChoice15.setChoiceItems(new String[] {"UNIPOLAR", "BIPOLAR"});
    deviceChoice15.setUpdateIdentifier("");
    deviceChoice15.setIdentifier("");
    deviceChoice15.setBounds(new Rectangle(324, 0, 150, 35));
    deviceChoice16.setChoiceIntValues(null);
    deviceChoice16.setChoiceFloatValues(null);
    deviceChoice16.setOffsetNid(37);
    deviceChoice16.setLabelString("Mode :");
    deviceChoice16.setChoiceItems(new String[] {"AS IS", "VARIABLE"});
    deviceChoice16.setUpdateIdentifier("");
    deviceChoice16.setIdentifier("");
    deviceChoice16.setBounds(new Rectangle(9, 0, 135, 35));
    deviceField16.setBounds(new Rectangle(141, 0, 166, 31));
    deviceField16.setIdentifier("");
    deviceField16.setNumCols(7);
    deviceField16.setLabelString("Start Time :");
    deviceField16.setOffsetNid(41);
    deviceField17.setBounds(new Rectangle(5, 0, 475, 37));
    deviceField17.setPreferredWidth(-1);
    deviceField17.setIdentifier("");
    deviceField17.setNumCols(35);
    deviceField17.setLabelString("Waveform :");
    deviceField17.setOffsetNid(47);
    deviceField18.setBounds(new Rectangle(310, 0, 167, 38));
    deviceField18.setIdentifier("");
    deviceField18.setNumCols(7);
    deviceField18.setLabelString("End Time :");
    deviceField18.setOffsetNid(42);
    deviceChannel5.setLines(1);
    deviceChannel5.setUpdateIdentifier("");
    deviceChannel5.setShowVal("");
    deviceChannel5.setLabelString("On / Off");
    deviceChannel5.setOffsetNid(40);
    jPanel115.setLayout(borderLayout6);
    jPanel115.setAlignmentX((float) 0.5);
    jPanel115.setBorder(BorderFactory.createEmptyBorder());
    deviceChoice17.setChoiceIntValues(null);
    deviceChoice17.setChoiceFloatValues(new float[] {(float)5.0,(float)10.0,(float)20.0});
    deviceChoice17.setOffsetNid(43);
    deviceChoice17.setLabelString("Range (V p-p) :");
    deviceChoice17.setChoiceItems(new String[] {"5", "10", "20"});
    deviceChoice17.setUpdateIdentifier("");
    deviceChoice17.setIdentifier("");
    deviceChoice17.setBounds(new Rectangle(166, 0, 149, 35));
    jPanel116.setLayout(null);
    jPanel117.setLayout(null);
    gridLayout5.setColumns(1);
    gridLayout5.setRows(3);
    jPanel118.setLayout(gridLayout5);
    jPanel119.setLayout(null);
    deviceChoice18.setChoiceIntValues(null);
    deviceChoice18.setChoiceFloatValues(null);
    deviceChoice18.setOffsetNid(44);
    deviceChoice18.setLabelString("Polarity :");
    deviceChoice18.setChoiceItems(new String[] {"UNIPOLAR", "BIPOLAR"});
    deviceChoice18.setUpdateIdentifier("");
    deviceChoice18.setIdentifier("");
    deviceChoice18.setBounds(new Rectangle(324, 0, 150, 35));
    deviceChoice19.setChoiceIntValues(null);
    deviceChoice19.setChoiceFloatValues(null);
    deviceChoice19.setOffsetNid(45);
    deviceChoice19.setLabelString("Mode :");
    deviceChoice19.setChoiceItems(new String[] {"AS IS", "VARIABLE"});
    deviceChoice19.setUpdateIdentifier("");
    deviceChoice19.setIdentifier("");
    deviceChoice19.setBounds(new Rectangle(9, 0, 135, 35));
    deviceField19.setBounds(new Rectangle(141, 0, 166, 31));
    deviceField19.setIdentifier("");
    deviceField19.setNumCols(7);
    deviceField19.setLabelString("Start Time :");
    deviceField19.setOffsetNid(49);
    deviceField110.setBounds(new Rectangle(5, 0, 475, 37));
    deviceField110.setPreferredWidth(-1);
    deviceField110.setIdentifier("");
    deviceField110.setNumCols(35);
    deviceField110.setLabelString("Waveform :");
    deviceField110.setOffsetNid(55);
    deviceField111.setBounds(new Rectangle(310, 0, 167, 38));
    deviceField111.setIdentifier("");
    deviceField111.setNumCols(7);
    deviceField111.setLabelString("End Time :");
    deviceField111.setOffsetNid(50);
    deviceChannel6.setLines(1);
    deviceChannel6.setUpdateIdentifier("");
    deviceChannel6.setShowVal("");
    deviceChannel6.setLabelString("On / Off");
    deviceChannel6.setOffsetNid(48);
    jPanel1110.setLayout(borderLayout7);
    jPanel1110.setAlignmentX((float) 0.5);
    jPanel1110.setBorder(BorderFactory.createEmptyBorder());
    deviceChoice110.setChoiceIntValues(null);
    deviceChoice110.setChoiceFloatValues(new float[] {(float)5.0,(float)10.0,(float)20.0});
    deviceChoice110.setOffsetNid(51);
    deviceChoice110.setLabelString("Range (V p-p) :");
    deviceChoice110.setChoiceItems(new String[] {"5", "10", "20"});
    deviceChoice110.setUpdateIdentifier("");
    deviceChoice110.setIdentifier("");
    deviceChoice110.setBounds(new Rectangle(166, 0, 149, 35));
    jPanel1111.setLayout(null);
    jPanel1112.setLayout(null);
    gridLayout6.setColumns(1);
    gridLayout6.setRows(3);
    jPanel1113.setLayout(gridLayout6);
    jPanel1114.setLayout(null);
    deviceChoice111.setChoiceIntValues(null);
    deviceChoice111.setChoiceFloatValues(null);
    deviceChoice111.setOffsetNid(52);
    deviceChoice111.setLabelString("Polarity :");
    deviceChoice111.setChoiceItems(new String[] {"UNIPOLAR", "BIPOLAR"});
    deviceChoice111.setUpdateIdentifier("");
    deviceChoice111.setIdentifier("");
    deviceChoice111.setBounds(new Rectangle(324, 0, 150, 35));
    deviceChoice112.setChoiceIntValues(null);
    deviceChoice112.setChoiceFloatValues(null);
    deviceChoice112.setOffsetNid(53);
    deviceChoice112.setLabelString("Mode :");
    deviceChoice112.setChoiceItems(new String[] {"AS IS", "VARIABLE"});
    deviceChoice112.setUpdateIdentifier("");
    deviceChoice112.setIdentifier("");
    deviceChoice112.setBounds(new Rectangle(9, 0, 135, 35));
    deviceDispatch1.setBounds(new Rectangle(352, 18, 135, 32));
    jPanel6.add(deviceField1, null);
    jPanel6.add(deviceField2, null);
    jPanel6.add(deviceDispatch1, null);
    jPanel7.add(deviceChoice2, null);
    jPanel7.add(deviceField3, null);
    jPanel7.add(deviceChoice1, null);
    this.getContentPane().add(jPanel8, null);
    this.getContentPane().add(jPanel6, null);
    jPanel8.add(deviceChoice4, null);
    jPanel8.add(deviceChoice3, null);
    this.getContentPane().add(jPanel7, null);
    this.getContentPane().add(jPanel9, null);
    jPanel9.add(jTabbedPane1, BorderLayout.CENTER);
    this.getContentPane().add(deviceButtons1, null);
    jTabbedPane1.add(jPanel1, "CH 01");
    jPanel1.add(deviceChannel1, BorderLayout.CENTER);
    deviceChannel1.add(jPanel2, BorderLayout.CENTER);




    jPanel3.add(deviceField5, null);
    jPanel3.add(deviceChoice5, null);
    jPanel3.add(deviceField6, null);
    jPanel4.add(deviceChoice7, null);
    jPanel4.add(deviceChoice6, null);
    jPanel5.add(deviceField4, null);
    jTabbedPane1.add(jPanel10,   "CH 02");
    jPanel10.add(deviceChannel2, BorderLayout.CENTER);
    deviceChannel2.add(jPanel13, BorderLayout.CENTER);
    jPanel11.add(deviceChoice9, null);
    jPanel11.add(deviceChoice8, null);

    jPanel12.add(deviceField7, null);
    jPanel12.add(deviceChoice10, null);
    jPanel12.add(deviceField9, null);

    jPanel14.add(deviceField8, null);
    jTabbedPane1.add(jPanel15,   "CH 03");
    jPanel15.add(deviceChannel3, BorderLayout.CENTER);
    deviceChannel3.add(jPanel18, BorderLayout.CENTER);
    jPanel16.add(deviceChoice12, null);
    jPanel16.add(deviceChoice11, null);

    jPanel17.add(deviceField10, null);
    jPanel17.add(deviceChoice13, null);
    jPanel17.add(deviceField12, null);

    jPanel19.add(deviceField11, null);
    jTabbedPane1.add(jPanel110,   "CH 04");
    jPanel110.add(deviceChannel4, BorderLayout.CENTER);
    deviceChannel4.add(jPanel113, BorderLayout.CENTER);
    jPanel111.add(deviceChoice15, null);
    jPanel111.add(deviceChoice14, null);

    jPanel112.add(deviceField13, null);
    jPanel112.add(deviceChoice16, null);
    jPanel112.add(deviceField15, null);

    jPanel114.add(deviceField14, null);
    jTabbedPane1.add(jPanel115,   "CH 05");
    jPanel115.add(deviceChannel5, BorderLayout.CENTER);
    deviceChannel5.add(jPanel118, BorderLayout.CENTER);
    jPanel116.add(deviceChoice18, null);
    jPanel116.add(deviceChoice17, null);

    jPanel117.add(deviceField16, null);
    jPanel117.add(deviceChoice19, null);
    jPanel117.add(deviceField18, null);

    jPanel119.add(deviceField17, null);
    jTabbedPane1.add(jPanel1110,   "CH 06");
    jPanel1110.add(deviceChannel6, BorderLayout.CENTER);
    deviceChannel6.add(jPanel1113, BorderLayout.CENTER);
    jPanel1111.add(deviceChoice111, null);
    jPanel1111.add(deviceChoice110, null);

    jPanel1112.add(deviceField19, null);
    jPanel1112.add(deviceChoice112, null);
    jPanel1112.add(deviceField111, null);

    jPanel1114.add(deviceField110, null);



    jPanel1113.add(jPanel1111, null);
    jPanel1113.add(jPanel1112, null);
    jPanel1113.add(jPanel1114, null);

    jPanel118.add(jPanel116, null);
    jPanel118.add(jPanel117, null);
    jPanel118.add(jPanel119, null);

    jPanel113.add(jPanel111, null);
    jPanel113.add(jPanel112, null);
    jPanel113.add(jPanel114, null);

    jPanel18.add(jPanel16, null);
    jPanel18.add(jPanel17, null);
    jPanel18.add(jPanel19, null);

    jPanel13.add(jPanel11, null);
    jPanel13.add(jPanel12, null);
    jPanel13.add(jPanel14, null);

    jPanel2.add(jPanel4, null);
    jPanel2.add(jPanel3, null);
    jPanel2.add(jPanel5, null);

  }

}
