/*
		A basic implementation of the DeviceSetup class.
*/

import java.awt.*;

public class RFXClockSetup extends DeviceSetup
{
	public RFXClockSetup(Frame parent)
	{
		super(parent);
		
		// This code is automatically generated by Visual Cafe when you add
		// components to the visual environment. It instantiates and initializes
		// the components. To modify the code, only use code syntax that matches
		// what Visual Cafe can generate, or Visual Cafe may be unable to back
		// parse your Java file into its visual environment.
		//{{INIT_CONTROLS
		setDeviceProvider("150.178.3.112");
		setDeviceTitle("RFX Clock generator");
		setDeviceType("RFXClock");
		getContentPane().setLayout(null);
		setSize(405,220);
		deviceField1.setNumCols(25);
		deviceField1.setTextOnly(true);
		deviceField1.setOffsetNid(1);
		deviceField1.setLabelString("Comment: ");
		getContentPane().add(deviceField1);
		deviceField1.setBounds(12,12,372,40);
		deviceField2.setNumCols(15);
		deviceField2.setOffsetNid(2);
		deviceField2.setLabelString("Decoder: ");
		getContentPane().add(deviceField2);
		deviceField2.setBounds(12,48,264,40);
		deviceField3.setNumCols(3);
		deviceField3.setOffsetNid(3);
		deviceField3.setLabelString("Channel: ");
		getContentPane().add(deviceField3);
		deviceField3.setBounds(264,48,130,40);
		deviceField4.setNumCols(20);
		deviceField4.setOffsetNid(4);
		deviceField4.setLabelString("Frequency: ");
		getContentPane().add(deviceField4);
		deviceField4.setBounds(0,84,324,40);
		deviceField5.setNumCols(8);
		deviceField5.setOffsetNid(5);
		deviceField5.setLabelString("Duty Cycle: ");
		getContentPane().add(deviceField5);
		deviceField5.setBounds(0,120,216,40);
		getContentPane().add(deviceDispatch1);
		deviceDispatch1.setBounds(240,120,131,40);
		{
			String[] tempString = new String[1];
			tempString[0] = "init";
			deviceButtons1.setMethods(tempString);
		}
		getContentPane().add(deviceButtons1);
		deviceButtons1.setBounds(72,168,281,40);
		//}}
	}

	public RFXClockSetup()
	{
		this((Frame)null);
	}

	public RFXClockSetup(String sTitle)
	{
		this();
		setTitle(sTitle);
	}

	public void setVisible(boolean b)
	{
		if (b)
			setLocation(50, 50);
		super.setVisible(b);
	}

	static public void main(String args[])
	{
		(new RFXClockSetup()).setVisible(true);
	}

	public void addNotify()
	{
		// Record the size of the window prior to calling parents addNotify.
		Dimension size = getSize();

		super.addNotify();

		if (frameSizeAdjusted)
			return;
		frameSizeAdjusted = true;

		// Adjust size of frame according to the insets
		Insets insets = getInsets();
		setSize(insets.left + insets.right + size.width, insets.top + insets.bottom + size.height);
	}

	// Used by addNotify
	boolean frameSizeAdjusted = false;

	//{{DECLARE_CONTROLS
	DeviceField deviceField1 = new DeviceField();
	DeviceField deviceField2 = new DeviceField();
	DeviceField deviceField3 = new DeviceField();
	DeviceField deviceField4 = new DeviceField();
	DeviceField deviceField5 = new DeviceField();
	DeviceDispatch deviceDispatch1 = new DeviceDispatch();
	DeviceButtons deviceButtons1 = new DeviceButtons();
	//}}

}