

import java.awt.*;
import javax.swing.*;
/**
 * <p>Title: </p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2003</p>
 * <p>Company: </p>
 * @author not attributable
 * @version 1.0
 */

public class RFXInverterSetupSetup extends DeviceSetup {
  BorderLayout borderLayout1 = new BorderLayout();
  JPanel jPanel1 = new JPanel();
  DeviceChoice deviceChoice1 = new DeviceChoice();
  DeviceField deviceField1 = new DeviceField();
  DeviceButtons deviceButtons1 = new DeviceButtons();
  JTabbedPane jTabbedPane1 = new JTabbedPane();
  DeviceChannel deviceChannel1 = new DeviceChannel();
  JPanel jPanel2 = new JPanel();
  JPanel jPanel3 = new JPanel();
  BorderLayout borderLayout2 = new BorderLayout();
  DeviceField deviceField2 = new DeviceField();
  DeviceField deviceField3 = new DeviceField();
  DeviceField deviceField4 = new DeviceField();
  DeviceWave deviceWave1 = new DeviceWave();
  DeviceField deviceField20 = new DeviceField();
  JLabel jLabel1 = new JLabel();
  DeviceField deviceField5 = new DeviceField();
  BorderLayout borderLayout3 = new BorderLayout();
  DeviceWave deviceWave2 = new DeviceWave();
  JLabel jLabel2 = new JLabel();
  DeviceChannel deviceChannel2 = new DeviceChannel();
  DeviceField deviceField21 = new DeviceField();
  JPanel jPanel4 = new JPanel();
  DeviceField deviceField6 = new DeviceField();
  DeviceField deviceField7 = new DeviceField();
  JPanel jPanel5 = new JPanel();
  DeviceField deviceField8 = new DeviceField();
  BorderLayout borderLayout4 = new BorderLayout();
  DeviceWave deviceWave3 = new DeviceWave();
  JLabel jLabel3 = new JLabel();
  DeviceChannel deviceChannel3 = new DeviceChannel();
  DeviceField deviceField22 = new DeviceField();
  JPanel jPanel6 = new JPanel();
  DeviceField deviceField9 = new DeviceField();
  DeviceField deviceField10 = new DeviceField();
  JPanel jPanel7 = new JPanel();
  DeviceField deviceField11 = new DeviceField();
  BorderLayout borderLayout5 = new BorderLayout();
  DeviceWave deviceWave4 = new DeviceWave();
  JLabel jLabel4 = new JLabel();
  DeviceChannel deviceChannel4 = new DeviceChannel();
  DeviceField deviceField23 = new DeviceField();
  JPanel jPanel8 = new JPanel();
  DeviceField deviceField12 = new DeviceField();
  DeviceField deviceField13 = new DeviceField();
  JPanel jPanel9 = new JPanel();
  DeviceField deviceField14 = new DeviceField();
  BorderLayout borderLayout6 = new BorderLayout();
  DeviceWave deviceWave5 = new DeviceWave();
  JLabel jLabel5 = new JLabel();
  DeviceChannel deviceChannel5 = new DeviceChannel();
  DeviceField deviceField24 = new DeviceField();
  JPanel jPanel10 = new JPanel();
  DeviceField deviceField15 = new DeviceField();
  DeviceField deviceField16 = new DeviceField();
  JPanel jPanel11 = new JPanel();
  DeviceField deviceField17 = new DeviceField();
  BorderLayout borderLayout7 = new BorderLayout();
  DeviceWave deviceWave6 = new DeviceWave();
  JLabel jLabel6 = new JLabel();
  DeviceChannel deviceChannel6 = new DeviceChannel();
  DeviceField deviceField25 = new DeviceField();
  JPanel jPanel12 = new JPanel();
  DeviceField deviceField18 = new DeviceField();
  DeviceField deviceField19 = new DeviceField();
  JPanel jPanel13 = new JPanel();
  DeviceField deviceField110 = new DeviceField();
  BorderLayout borderLayout8 = new BorderLayout();
  DeviceWave deviceWave7 = new DeviceWave();
  JLabel jLabel7 = new JLabel();
  DeviceChannel deviceChannel7 = new DeviceChannel();
  DeviceField deviceField26 = new DeviceField();
  JPanel jPanel14 = new JPanel();
  DeviceField deviceField111 = new DeviceField();
  DeviceField deviceField112 = new DeviceField();
  JPanel jPanel15 = new JPanel();
  DeviceField deviceField113 = new DeviceField();
  BorderLayout borderLayout9 = new BorderLayout();
  DeviceWave deviceWave8 = new DeviceWave();
  JLabel jLabel8 = new JLabel();
  DeviceChannel deviceChannel8 = new DeviceChannel();
  DeviceField deviceField27 = new DeviceField();
  JPanel jPanel16 = new JPanel();
  DeviceField deviceField114 = new DeviceField();
  DeviceField deviceField115 = new DeviceField();
  JPanel jPanel17 = new JPanel();
  DeviceField deviceField116 = new DeviceField();
  BorderLayout borderLayout10 = new BorderLayout();
  DeviceWave deviceWave9 = new DeviceWave();
  JLabel jLabel9 = new JLabel();
  DeviceChannel deviceChannel9 = new DeviceChannel();
  DeviceField deviceField28 = new DeviceField();
  JPanel jPanel18 = new JPanel();
  DeviceField deviceField117 = new DeviceField();
  DeviceField deviceField118 = new DeviceField();
  JPanel jPanel19 = new JPanel();
  DeviceField deviceField119 = new DeviceField();
  BorderLayout borderLayout11 = new BorderLayout();
  DeviceWave deviceWave10 = new DeviceWave();
  JLabel jLabel10 = new JLabel();
  DeviceChannel deviceChannel10 = new DeviceChannel();
  DeviceField deviceField29 = new DeviceField();
  JPanel jPanel110 = new JPanel();
  DeviceField deviceField1110 = new DeviceField();
  DeviceField deviceField1111 = new DeviceField();
  JPanel jPanel111 = new JPanel();
  DeviceField deviceField1112 = new DeviceField();
  BorderLayout borderLayout12 = new BorderLayout();
  DeviceWave deviceWave11 = new DeviceWave();
  JLabel jLabel11 = new JLabel();
  DeviceChannel deviceChannel11 = new DeviceChannel();
  DeviceField deviceField210 = new DeviceField();
  JPanel jPanel112 = new JPanel();
  DeviceField deviceField1113 = new DeviceField();
  DeviceField deviceField1114 = new DeviceField();
  JPanel jPanel113 = new JPanel();
  DeviceField deviceField1115 = new DeviceField();
  BorderLayout borderLayout13 = new BorderLayout();
  DeviceWave deviceWave12 = new DeviceWave();
  JLabel jLabel12 = new JLabel();
  DeviceChannel deviceChannel12 = new DeviceChannel();
  DeviceField deviceField211 = new DeviceField();
  JPanel jPanel114 = new JPanel();
  DeviceField deviceField1116 = new DeviceField();
  DeviceField deviceField1117 = new DeviceField();
  JPanel jPanel115 = new JPanel();
  public RFXInverterSetupSetup() {
    try {
      jbInit();
    }
    catch(Exception e) {
      e.printStackTrace();
    }
  }
  private void jbInit() throws Exception {
    this.setWidth(607);
    this.setHeight(550);
    this.setDeviceType("RFXInverterSetup");
    this.setDeviceProvider("localhost");
    this.setDeviceTitle("EDA2 Inverter Setup");
    this.getContentPane().setLayout(borderLayout1);
    deviceField1.setOffsetNid(1);
    deviceField1.setTextOnly(true);
    deviceField1.setLabelString("Comment: ");
    deviceField1.setNumCols(20);
    deviceField1.setIdentifier("");
    deviceChoice1.setChoiceIntValues(null);
    deviceChoice1.setChoiceFloatValues(null);
    deviceChoice1.setOffsetNid(3);
    deviceChoice1.setLabelString("Control: ");
    deviceChoice1.setChoiceItems(new String[] {"VOLTAGE", "CURRENT", "OPEN LOOP"});
    deviceChoice1.setUpdateIdentifier("");
    deviceChoice1.setIdentifier("");
    deviceChannel1.setLabelString("On");
    deviceChannel1.setOffsetNid(5);
    deviceChannel1.setUpdateIdentifier("");
    deviceChannel1.setShowVal("");
    jPanel2.setLayout(borderLayout2);
    deviceField4.setOffsetNid(11);
    deviceField4.setLabelString("Amp.:");
    deviceField4.setNumCols(4);
    deviceField4.setIdentifier("");
    deviceField3.setOffsetNid(13);
    deviceField3.setLabelString("Phase (rad.):");
    deviceField3.setNumCols(4);
    deviceField3.setIdentifier("");
    deviceField2.setOffsetNid(14);
    deviceField2.setLabelString("Start Time:");
    deviceField2.setNumCols(4);
    deviceField2.setIdentifier("");
    deviceWave1.setOffsetNid(6);
    deviceWave1.setMinYVisible(true);
    deviceWave1.setIdentifier("");
    deviceWave1.setUpdateExpression("");
    deviceField20.setOffsetNid(12);
    deviceField20.setLabelString("Freq. (Hz)");
    deviceField20.setNumCols(4);
    deviceField20.setIdentifier("");
    jLabel1.setText("Perturbation:");
    deviceField5.setIdentifier("");
    deviceField5.setNumCols(4);
    deviceField5.setLabelString("Phase (rad.):");
    deviceField5.setOffsetNid(23);
    deviceWave2.setUpdateExpression("");
    deviceWave2.setIdentifier("");
    deviceWave2.setMinYVisible(true);
    deviceWave2.setOffsetNid(16);
    jLabel2.setText("Perturbation:");
    deviceChannel2.setShowVal("");
    deviceChannel2.setUpdateIdentifier("");
    deviceChannel2.setOffsetNid(15);
    deviceChannel2.setLabelString("On");
    deviceField21.setOffsetNid(22);
    deviceField21.setLabelString("Freq. (Hz)");
    deviceField21.setNumCols(4);
    deviceField21.setIdentifier("");
    jPanel4.setLayout(borderLayout3);
    deviceField6.setOffsetNid(21);
    deviceField6.setLabelString("Amp.:");
    deviceField6.setNumCols(4);
    deviceField6.setIdentifier("");
    deviceField7.setOffsetNid(24);
    deviceField7.setLabelString("Start Time:");
    deviceField7.setNumCols(4);
    deviceField7.setIdentifier("");
    deviceField8.setIdentifier("");
    deviceField8.setNumCols(4);
    deviceField8.setLabelString("Phase (rad.):");
    deviceField8.setOffsetNid(33);
    deviceWave3.setUpdateExpression("");
    deviceWave3.setIdentifier("");
    deviceWave3.setMinYVisible(true);
    deviceWave3.setOffsetNid(26);
    jLabel3.setText("Perturbation:");
    deviceChannel3.setShowVal("");
    deviceChannel3.setUpdateIdentifier("");
    deviceChannel3.setOffsetNid(25);
    deviceChannel3.setLabelString("On");
    deviceField22.setOffsetNid(32);
    deviceField22.setLabelString("Freq. (Hz)");
    deviceField22.setNumCols(4);
    deviceField22.setIdentifier("");
    jPanel6.setLayout(borderLayout4);
    deviceField9.setOffsetNid(31);
    deviceField9.setLabelString("Amp.:");
    deviceField9.setNumCols(4);
    deviceField9.setIdentifier("");
    deviceField10.setOffsetNid(34);
    deviceField10.setLabelString("Start Time:");
    deviceField10.setNumCols(4);
    deviceField10.setIdentifier("");
    deviceField11.setIdentifier("");
    deviceField11.setNumCols(4);
    deviceField11.setLabelString("Phase (rad.):");
    deviceField11.setOffsetNid(43);
    deviceWave4.setUpdateExpression("");
    deviceWave4.setIdentifier("");
    deviceWave4.setMinYVisible(true);
    deviceWave4.setOffsetNid(36);
    jLabel4.setText("Perturbation:");
    deviceChannel4.setShowVal("");
    deviceChannel4.setUpdateIdentifier("");
    deviceChannel4.setOffsetNid(35);
    deviceChannel4.setLabelString("On");
    deviceField23.setOffsetNid(42);
    deviceField23.setLabelString("Freq. (Hz)");
    deviceField23.setNumCols(4);
    deviceField23.setIdentifier("");
    jPanel8.setLayout(borderLayout5);
    deviceField12.setOffsetNid(41);
    deviceField12.setLabelString("Amp.:");
    deviceField12.setNumCols(4);
    deviceField12.setIdentifier("");
    deviceField13.setOffsetNid(44);
    deviceField13.setLabelString("Start Time:");
    deviceField13.setNumCols(4);
    deviceField13.setIdentifier("");
    deviceField14.setIdentifier("");
    deviceField14.setNumCols(4);
    deviceField14.setLabelString("Phase (rad.):");
    deviceField14.setOffsetNid(53);
    deviceWave5.setUpdateExpression("");
    deviceWave5.setIdentifier("");
    deviceWave5.setMinYVisible(true);
    deviceWave5.setOffsetNid(46);
    jLabel5.setText("Perturbation:");
    deviceChannel5.setShowVal("");
    deviceChannel5.setUpdateIdentifier("");
    deviceChannel5.setOffsetNid(45);
    deviceChannel5.setLabelString("On");
    deviceField24.setOffsetNid(52);
    deviceField24.setLabelString("Freq. (Hz)");
    deviceField24.setNumCols(4);
    deviceField24.setIdentifier("");
    jPanel10.setLayout(borderLayout6);
    deviceField15.setOffsetNid(51);
    deviceField15.setLabelString("Amp.:");
    deviceField15.setNumCols(4);
    deviceField15.setIdentifier("");
    deviceField16.setOffsetNid(54);
    deviceField16.setLabelString("Start Time:");
    deviceField16.setNumCols(4);
    deviceField16.setIdentifier("");
    deviceField17.setIdentifier("");
    deviceField17.setNumCols(4);
    deviceField17.setLabelString("Phase (rad.):");
    deviceField17.setOffsetNid(63);
    deviceWave6.setUpdateExpression("");
    deviceWave6.setIdentifier("");
    deviceWave6.setMinYVisible(true);
    deviceWave6.setOffsetNid(56);
    jLabel6.setText("Perturbation:");
    deviceChannel6.setShowVal("");
    deviceChannel6.setUpdateIdentifier("");
    deviceChannel6.setOffsetNid(55);
    deviceChannel6.setLabelString("On");
    deviceField25.setOffsetNid(62);
    deviceField25.setLabelString("Freq. (Hz)");
    deviceField25.setNumCols(4);
    deviceField25.setIdentifier("");
    jPanel12.setLayout(borderLayout7);
    deviceField18.setOffsetNid(61);
    deviceField18.setLabelString("Amp.:");
    deviceField18.setNumCols(4);
    deviceField18.setIdentifier("");
    deviceField19.setOffsetNid(64);
    deviceField19.setLabelString("Start Time:");
    deviceField19.setNumCols(4);
    deviceField19.setIdentifier("");
    deviceField110.setIdentifier("");
    deviceField110.setNumCols(4);
    deviceField110.setLabelString("Phase (rad.):");
    deviceField110.setOffsetNid(73);
    deviceWave7.setUpdateExpression("");
    deviceWave7.setIdentifier("");
    deviceWave7.setMinYVisible(true);
    deviceWave7.setOffsetNid(66);
    jLabel7.setText("Perturbation:");
    deviceChannel7.setShowVal("");
    deviceChannel7.setUpdateIdentifier("");
    deviceChannel7.setOffsetNid(65);
    deviceChannel7.setLabelString("On");
    deviceField26.setOffsetNid(72);
    deviceField26.setLabelString("Freq. (Hz)");
    deviceField26.setNumCols(4);
    deviceField26.setIdentifier("");
    jPanel14.setLayout(borderLayout8);
    deviceField111.setOffsetNid(71);
    deviceField111.setLabelString("Amp.:");
    deviceField111.setNumCols(4);
    deviceField111.setIdentifier("");
    deviceField112.setOffsetNid(74);
    deviceField112.setLabelString("Start Time:");
    deviceField112.setNumCols(4);
    deviceField112.setIdentifier("");
    deviceField113.setIdentifier("");
    deviceField113.setNumCols(4);
    deviceField113.setLabelString("Phase (rad.):");
    deviceField113.setOffsetNid(83);
    deviceWave8.setUpdateExpression("");
    deviceWave8.setIdentifier("");
    deviceWave8.setMinYVisible(true);
    deviceWave8.setOffsetNid(76);
    jLabel8.setText("Perturbation:");
    deviceChannel8.setShowVal("");
    deviceChannel8.setUpdateIdentifier("");
    deviceChannel8.setOffsetNid(75);
    deviceChannel8.setLabelString("On");
    deviceField27.setOffsetNid(82);
    deviceField27.setLabelString("Freq. (Hz)");
    deviceField27.setNumCols(4);
    deviceField27.setIdentifier("");
    jPanel16.setLayout(borderLayout9);
    deviceField114.setOffsetNid(81);
    deviceField114.setLabelString("Amp.:");
    deviceField114.setNumCols(4);
    deviceField114.setIdentifier("");
    deviceField115.setOffsetNid(84);
    deviceField115.setLabelString("Start Time:");
    deviceField115.setNumCols(4);
    deviceField115.setIdentifier("");
    deviceField116.setIdentifier("");
    deviceField116.setNumCols(4);
    deviceField116.setLabelString("Phase (rad.):");
    deviceField116.setOffsetNid(93);
    deviceWave9.setUpdateExpression("");
    deviceWave9.setIdentifier("");
    deviceWave9.setMinYVisible(true);
    deviceWave9.setOffsetNid(86);
    jLabel9.setText("Perturbation:");
    deviceChannel9.setShowVal("");
    deviceChannel9.setUpdateIdentifier("");
    deviceChannel9.setOffsetNid(85);
    deviceChannel9.setLabelString("On");
    deviceField28.setOffsetNid(92);
    deviceField28.setLabelString("Freq. (Hz)");
    deviceField28.setNumCols(4);
    deviceField28.setIdentifier("");
    jPanel18.setLayout(borderLayout10);
    deviceField117.setOffsetNid(91);
    deviceField117.setLabelString("Amp.:");
    deviceField117.setNumCols(4);
    deviceField117.setIdentifier("");
    deviceField118.setOffsetNid(94);
    deviceField118.setLabelString("Start Time:");
    deviceField118.setNumCols(4);
    deviceField118.setIdentifier("");
    deviceField119.setIdentifier("");
    deviceField119.setNumCols(4);
    deviceField119.setLabelString("Phase (rad.):");
    deviceField119.setOffsetNid(103);
    deviceWave10.setUpdateExpression("");
    deviceWave10.setIdentifier("");
    deviceWave10.setMinYVisible(true);
    deviceWave10.setOffsetNid(96);
    jLabel10.setText("Perturbation:");
    deviceChannel10.setShowVal("");
    deviceChannel10.setUpdateIdentifier("");
    deviceChannel10.setOffsetNid(95);
    deviceChannel10.setLabelString("On");
    deviceField29.setOffsetNid(102);
    deviceField29.setLabelString("Freq. (Hz)");
    deviceField29.setNumCols(4);
    deviceField29.setIdentifier("");
    jPanel110.setLayout(borderLayout11);
    deviceField1110.setOffsetNid(101);
    deviceField1110.setLabelString("Amp.:");
    deviceField1110.setNumCols(4);
    deviceField1110.setIdentifier("");
    deviceField1111.setOffsetNid(104);
    deviceField1111.setLabelString("Start Time:");
    deviceField1111.setNumCols(4);
    deviceField1111.setIdentifier("");
    deviceField1112.setIdentifier("");
    deviceField1112.setNumCols(4);
    deviceField1112.setLabelString("Phase (rad.):");
    deviceField1112.setOffsetNid(113);
    deviceWave11.setUpdateExpression("");
    deviceWave11.setIdentifier("");
    deviceWave11.setMinYVisible(true);
    deviceWave11.setOffsetNid(106);
    jLabel11.setText("Perturbation:");
    deviceChannel11.setShowVal("");
    deviceChannel11.setUpdateIdentifier("");
    deviceChannel11.setOffsetNid(105);
    deviceChannel11.setLabelString("On");
    deviceField210.setOffsetNid(112);
    deviceField210.setLabelString("Freq. (Hz)");
    deviceField210.setNumCols(4);
    deviceField210.setIdentifier("");
    jPanel112.setLayout(borderLayout12);
    deviceField1113.setOffsetNid(111);
    deviceField1113.setLabelString("Amp.:");
    deviceField1113.setNumCols(4);
    deviceField1113.setIdentifier("");
    deviceField1114.setOffsetNid(114);
    deviceField1114.setLabelString("Start Time:");
    deviceField1114.setNumCols(4);
    deviceField1114.setIdentifier("");
    deviceField1115.setIdentifier("");
    deviceField1115.setNumCols(4);
    deviceField1115.setLabelString("Phase (rad.):");
    deviceField1115.setOffsetNid(123);
    deviceWave12.setUpdateExpression("");
    deviceWave12.setIdentifier("");
    deviceWave12.setMinYVisible(true);
    deviceWave12.setOffsetNid(116);
    jLabel12.setText("Perturbation:");
    deviceChannel12.setShowVal("");
    deviceChannel12.setUpdateIdentifier("");
    deviceChannel12.setOffsetNid(115);
    deviceChannel12.setLabelString("On");
    deviceField211.setOffsetNid(122);
    deviceField211.setLabelString("Freq. (Hz)");
    deviceField211.setNumCols(4);
    deviceField211.setIdentifier("");
    jPanel114.setLayout(borderLayout13);
    deviceField1116.setOffsetNid(121);
    deviceField1116.setLabelString("Amp.:");
    deviceField1116.setNumCols(4);
    deviceField1116.setIdentifier("");
    deviceField1117.setOffsetNid(124);
    deviceField1117.setLabelString("Start Time:");
    deviceField1117.setNumCols(4);
    deviceField1117.setIdentifier("");
    this.getContentPane().add(jPanel1, BorderLayout.NORTH);
    jPanel1.add(deviceField1, null);
    jPanel1.add(deviceChoice1, null);
    this.getContentPane().add(deviceButtons1, BorderLayout.SOUTH);
    this.getContentPane().add(jTabbedPane1, BorderLayout.CENTER);
    jTabbedPane1.add(deviceChannel1,   "1");
    deviceChannel1.add(jPanel2,  BorderLayout.CENTER);
    jPanel2.add(jPanel3,  BorderLayout.SOUTH);
    jPanel3.add(jLabel1, null);
    jPanel3.add(deviceField4, null);
    jPanel3.add(deviceField20, null);
    jPanel3.add(deviceField3, null);
    jPanel3.add(deviceField2, null);
    jPanel2.add(deviceWave1, BorderLayout.CENTER);
    jTabbedPane1.add(deviceChannel2,   "2");
    deviceChannel2.add(jPanel4, BorderLayout.CENTER);
    jPanel5.add(jLabel2, null);
    jPanel5.add(deviceField6, null);
    jPanel5.add(deviceField21, null);
    jPanel5.add(deviceField5, null);
    jPanel5.add(deviceField7, null);
    jPanel4.add(deviceWave2, BorderLayout.CENTER);
    jTabbedPane1.add(deviceChannel3,   "3");
    deviceChannel3.add(jPanel6, BorderLayout.CENTER);
    jPanel7.add(jLabel3, null);
    jPanel7.add(deviceField9, null);
    jPanel7.add(deviceField22, null);
    jPanel7.add(deviceField8, null);
    jPanel7.add(deviceField10, null);
    jPanel6.add(deviceWave3, BorderLayout.CENTER);
    jTabbedPane1.add(deviceChannel4,   "4");
    deviceChannel4.add(jPanel8, BorderLayout.CENTER);
    jPanel9.add(jLabel4, null);
    jPanel9.add(deviceField12, null);
    jPanel9.add(deviceField23, null);
    jPanel9.add(deviceField11, null);
    jPanel9.add(deviceField13, null);
    jPanel8.add(deviceWave4, BorderLayout.CENTER);
    jTabbedPane1.add(deviceChannel5,   "5");
    deviceChannel5.add(jPanel10, BorderLayout.CENTER);
    jPanel11.add(jLabel5, null);
    jPanel11.add(deviceField15, null);
    jPanel11.add(deviceField24, null);
    jPanel11.add(deviceField14, null);
    jPanel11.add(deviceField16, null);
    jPanel10.add(deviceWave5, BorderLayout.CENTER);
    jTabbedPane1.add(deviceChannel6,   "6");
    deviceChannel6.add(jPanel12, BorderLayout.CENTER);
    jPanel13.add(jLabel6, null);
    jPanel13.add(deviceField18, null);
    jPanel13.add(deviceField25, null);
    jPanel13.add(deviceField17, null);
    jPanel13.add(deviceField19, null);
    jPanel12.add(deviceWave6, BorderLayout.CENTER);
    jTabbedPane1.add(deviceChannel7,   "7");
    deviceChannel7.add(jPanel14, BorderLayout.CENTER);
    jPanel15.add(jLabel7, null);
    jPanel15.add(deviceField111, null);
    jPanel15.add(deviceField26, null);
    jPanel15.add(deviceField110, null);
    jPanel15.add(deviceField112, null);
    jPanel14.add(deviceWave7, BorderLayout.CENTER);
    jTabbedPane1.add(deviceChannel8,   "8");
    deviceChannel8.add(jPanel16, BorderLayout.CENTER);
    jPanel17.add(jLabel8, null);
    jPanel17.add(deviceField114, null);
    jPanel17.add(deviceField27, null);
    jPanel17.add(deviceField113, null);
    jPanel17.add(deviceField115, null);
    jPanel16.add(deviceWave8, BorderLayout.CENTER);
    jTabbedPane1.add(deviceChannel9,   "9");
    deviceChannel9.add(jPanel18, BorderLayout.CENTER);
    jPanel19.add(jLabel9, null);
    jPanel19.add(deviceField117, null);
    jPanel19.add(deviceField28, null);
    jPanel19.add(deviceField116, null);
    jPanel19.add(deviceField118, null);
    jPanel18.add(deviceWave9, BorderLayout.CENTER);
    jTabbedPane1.add(deviceChannel10,   "10");
    deviceChannel10.add(jPanel110, BorderLayout.CENTER);
    jPanel111.add(jLabel10, null);
    jPanel111.add(deviceField1110, null);
    jPanel111.add(deviceField29, null);
    jPanel111.add(deviceField119, null);
    jPanel111.add(deviceField1111, null);
    jPanel110.add(deviceWave10, BorderLayout.CENTER);
    jTabbedPane1.add(deviceChannel11,   "11");
    deviceChannel11.add(jPanel112, BorderLayout.CENTER);
    jPanel113.add(jLabel11, null);
    jPanel113.add(deviceField1113, null);
    jPanel113.add(deviceField210, null);
    jPanel113.add(deviceField1112, null);
    jPanel113.add(deviceField1114, null);
    jPanel112.add(deviceWave11, BorderLayout.CENTER);
    jTabbedPane1.add(deviceChannel12,   "12");
    deviceChannel12.add(jPanel114, BorderLayout.CENTER);
    jPanel115.add(jLabel12, null);
    jPanel115.add(deviceField1116, null);
    jPanel115.add(deviceField211, null);
    jPanel115.add(deviceField1115, null);
    jPanel115.add(deviceField1117, null);
    jPanel114.add(deviceWave12, BorderLayout.CENTER);
    jPanel114.add(jPanel115, BorderLayout.SOUTH);
    jPanel112.add(jPanel113, BorderLayout.SOUTH);
    jPanel110.add(jPanel111, BorderLayout.SOUTH);
    jPanel18.add(jPanel19, BorderLayout.SOUTH);
    jPanel16.add(jPanel17, BorderLayout.SOUTH);
    jPanel14.add(jPanel15, BorderLayout.SOUTH);
    jPanel12.add(jPanel13, BorderLayout.SOUTH);
    jPanel10.add(jPanel11, BorderLayout.SOUTH);
    jPanel8.add(jPanel9, BorderLayout.SOUTH);
    jPanel6.add(jPanel7, BorderLayout.SOUTH);
    jPanel4.add(jPanel5, BorderLayout.SOUTH);
  }

}