

import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
/**
 * <p>Title: </p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2003</p>
 * <p>Company: </p>
 * @author not attributable
 * @version 1.0
 */

public class RFXMHDSetup extends DeviceSetup {
  DeviceButtons deviceButtons1 = new DeviceButtons();
  JPanel jPanel9 = new JPanel();
  BorderLayout borderLayout1 = new BorderLayout();
  JPanel jPanel33 = new JPanel();
  BorderLayout borderLayout2 = new BorderLayout();
  JTabbedPane jTabbedPane1 = new JTabbedPane();
  JScrollPane jScrollPane4 = new JScrollPane();
  DeviceField deviceField25 = new DeviceField();
  DeviceField deviceField2111 = new DeviceField();
  DeviceField deviceField212 = new DeviceField();
  DeviceField deviceField2110 = new DeviceField();
  DeviceField deviceField210 = new DeviceField();
  DeviceField deviceField31 = new DeviceField();
  DeviceField deviceField30 = new DeviceField();
  DeviceField deviceField20 = new DeviceField();
  DeviceField deviceField21 = new DeviceField();
  DeviceField deviceField211 = new DeviceField();
  DeviceField deviceField22 = new DeviceField();
  JPanel jPanel24 = new JPanel();
  DeviceField deviceField2113 = new DeviceField();
  DeviceField deviceField2112 = new DeviceField();
  JPanel jPanel23 = new JPanel();
  DeviceField deviceField24 = new DeviceField();
  DeviceField deviceField23 = new DeviceField();
  JPanel jPanel6 = new JPanel();
  DeviceField deviceField213 = new DeviceField();
  DeviceField deviceField32 = new DeviceField();
  DeviceField deviceField33 = new DeviceField();
  FlowLayout flowLayout5 = new FlowLayout();
  DeviceField deviceField214 = new DeviceField();
  FlowLayout flowLayout7 = new FlowLayout();
  FlowLayout flowLayout8 = new FlowLayout();
  FlowLayout flowLayout6 = new FlowLayout();
  JPanel jPanel7 = new JPanel();
  JPanel jPanel5 = new JPanel();
  GridLayout gridLayout5 = new GridLayout();
  DeviceField deviceField215 = new DeviceField();
  DeviceField deviceField216 = new DeviceField();
  DeviceField deviceField219 = new DeviceField();
  DeviceField deviceField218 = new DeviceField();
  DeviceField deviceField217 = new DeviceField();
  DeviceField deviceField29 = new DeviceField();
  DeviceField deviceField26 = new DeviceField();
  DeviceField deviceField28 = new DeviceField();
  DeviceField deviceField27 = new DeviceField();
  JPanel jPanel40 = new JPanel();
  GridLayout gridLayout8 = new GridLayout();
  DeviceChoice deviceChoice2 = new DeviceChoice();
  JPanel jPanel27 = new JPanel();
  BorderLayout borderLayout3 = new BorderLayout();
    JScrollPane jScrollPane5 = new JScrollPane();
  DeviceTable deviceTable7 = new DeviceTable();
  DeviceField deviceField34 = new DeviceField();
  BorderLayout borderLayout5 = new BorderLayout();
  GridLayout gridLayout10 = new GridLayout();
  JPanel jPanel47 = new JPanel();
  JPanel jPanel42 = new JPanel();
  DeviceChoice deviceChoice5 = new DeviceChoice();
  JPanel jPanel44 = new JPanel();
  DeviceTable deviceTable11 = new DeviceTable();
  DeviceField deviceField35 = new DeviceField();
  JScrollPane jScrollPane14 = new JScrollPane();
  JPanel jPanel415 = new JPanel();
  DeviceChoice deviceChoice6 = new DeviceChoice();
  DeviceTable deviceTable13 = new DeviceTable();
  DeviceField deviceField37 = new DeviceField();
  JPanel jPanel46 = new JPanel();
  DeviceTable deviceTable8 = new DeviceTable();
  DeviceField deviceField36 = new DeviceField();
  BorderLayout borderLayout6 = new BorderLayout();
  GridLayout gridLayout11 = new GridLayout();
  JPanel jPanel45 = new JPanel();
  JScrollPane jScrollPane7 = new JScrollPane();
  JPanel jPanel417 = new JPanel();
  DeviceTable deviceTable15 = new DeviceTable();
  DeviceField deviceField38 = new DeviceField();
  JPanel jPanel418 = new JPanel();
  JPanel jPanel416 = new JPanel();
  GridLayout gridLayout12 = new GridLayout();
  BorderLayout borderLayout7 = new BorderLayout();
  DeviceChoice deviceChoice7 = new DeviceChoice();
  DeviceField deviceField39 = new DeviceField();
  DeviceTable deviceTable9 = new DeviceTable();
  JScrollPane jScrollPane8 = new JScrollPane();
  DeviceField deviceField311 = new DeviceField();
  GridLayout gridLayout13 = new GridLayout();
  JPanel jPanel419 = new JPanel();
  JPanel jPanel4110 = new JPanel();
  DeviceTable deviceTable18 = new DeviceTable();
  BorderLayout borderLayout8 = new BorderLayout();
  DeviceChoice deviceChoice8 = new DeviceChoice();
  JPanel jPanel4111 = new JPanel();
  DeviceField deviceField310 = new DeviceField();
  DeviceTable deviceTable16 = new DeviceTable();
  Border border1;
  TitledBorder titledBorder1;
  TitledBorder titledBorder2;
  Border border2;
  TitledBorder titledBorder3;
  Border border3;
  TitledBorder titledBorder4;
  Border border4;
  TitledBorder titledBorder5;
  Border border5;
  TitledBorder titledBorder6;
  Border border6;
  TitledBorder titledBorder7;
    JScrollPane jScrollPane15 = new JScrollPane();
    JPanel jPanel54 = new JPanel();
    DeviceTable deviceTable21 = new DeviceTable();
    GridLayout gridLayout9 = new GridLayout();
    DeviceTable deviceTable23 = new DeviceTable();
    DeviceTable deviceTable24 = new DeviceTable();
    DeviceField deviceField16 = new DeviceField();
    DeviceField deviceField40 = new DeviceField();
    DeviceField deviceField41 = new DeviceField();
    DeviceField deviceField42 = new DeviceField();
    JScrollPane jScrollPane9 = new JScrollPane();
    JPanel jPanel55 = new JPanel();
    DeviceTable deviceTable22 = new DeviceTable();
    BorderLayout borderLayout9 = new BorderLayout();
    JPanel jPanel56 = new JPanel();
    DeviceField deviceField43 = new DeviceField();
    DeviceField deviceField44 = new DeviceField();
    JScrollPane jScrollPane10 = new JScrollPane();
    JScrollPane jScrollPane11 = new JScrollPane();
    BorderLayout borderLayout10 = new BorderLayout();
    DeviceField deviceField45 = new DeviceField();
    JPanel jPanel58 = new JPanel();
    JPanel jPanel57 = new JPanel();
    DeviceTable deviceTable25 = new DeviceTable();
    DeviceField deviceField46 = new DeviceField();
    DeviceTable deviceTable26 = new DeviceTable();
    JPanel jPanel59 = new JPanel();
    DeviceField deviceField48 = new DeviceField();
    JPanel jPanel510 = new JPanel();
    BorderLayout borderLayout11 = new BorderLayout();
    DeviceField deviceField47 = new DeviceField();
    JPanel jPanel10 = new JPanel();
    DeviceField deviceField1 = new DeviceField();
    DeviceTable deviceTable27 = new DeviceTable();
    DeviceTable deviceTable28 = new DeviceTable();
    DeviceTable deviceTable29 = new DeviceTable();
  public RFXMHDSetup() {
    try {
      jbInit();
    }
    catch(Exception e) {
      e.printStackTrace();
    }
  }
  private void jbInit() throws Exception {
    border1 = new EtchedBorder(EtchedBorder.RAISED,Color.white,new Color(148, 145, 140));
    titledBorder1 = new TitledBorder(BorderFactory.createLineBorder(Color.black,1),"Output 4");
    titledBorder2 = new TitledBorder("");
    border2 = BorderFactory.createLineBorder(Color.black,2);
    titledBorder3 = new TitledBorder(border2,"Output 3");
    border3 = BorderFactory.createLineBorder(Color.black,1);
    titledBorder4 = new TitledBorder(border3,"Output 1");
    border4 = BorderFactory.createLineBorder(Color.black,1);
    titledBorder5 = new TitledBorder(border4,"Output 2");
    border5 = BorderFactory.createLineBorder(Color.black,2);
    titledBorder6 = new TitledBorder(border5,"Output 3");
    border6 = BorderFactory.createLineBorder(Color.black,1);
    titledBorder7 = new TitledBorder(border6,"Output 4");
    this.setWidth(736);
    this.setHeight(736);
    this.setDeviceType("RFXControl");
    this.setDeviceProvider("");
    this.setDeviceTitle("MHD Control Setup");
    this.getContentPane().setLayout(borderLayout1);
    jPanel9.setLayout(borderLayout3);
    jPanel9.setDebugGraphicsOptions(0);
    jPanel33.setLayout(borderLayout2);
    deviceField25.setOffsetNid(1037);
    deviceField25.setLabelString("Rot. Phase(Rad):");
    deviceField25.setNumCols(4);
    deviceField25.setIdentifier("");
    deviceField2111.setOffsetNid(1039);
    deviceField2111.setLabelString("N2: ");
    deviceField2111.setNumCols(2);
    deviceField2111.setIdentifier("");
    deviceField212.setIdentifier("");
    deviceField212.setNumCols(4);
    deviceField212.setLabelString("Rot. Phase(Rad):");
    deviceField212.setOffsetNid(1065);
    deviceField2110.setOffsetNid(1045);
    deviceField2110.setLabelString("Start:");
    deviceField2110.setNumCols(4);
    deviceField2110.setIdentifier("");
    deviceField210.setOffsetNid(1075);
    deviceField210.setLabelString("End:");
    deviceField210.setNumCols(4);
    deviceField210.setIdentifier("");
    deviceField31.setOffsetNid(1041);
    deviceField31.setLabelString("M2:");
    deviceField31.setNumCols(2);
    deviceField30.setOffsetNid(1027);
    deviceField30.setLabelString("M1:");
    deviceField30.setNumCols(2);
    deviceField30.setIdentifier("");
    deviceField20.setOffsetNid(1025);
    deviceField20.setLabelString("N1: ");
    deviceField20.setNumCols(2);
    deviceField20.setIdentifier("");
    deviceField21.setOffsetNid(1029);
    deviceField21.setLabelString("Amp.:");
    deviceField21.setNumCols(4);
    deviceField21.setIdentifier("");
    deviceField211.setOffsetNid(1071);
    deviceField211.setLabelString("Amp.:");
    deviceField211.setNumCols(4);
    deviceField211.setIdentifier("");
    deviceField22.setOffsetNid(1031);
    deviceField22.setLabelString("Start:");
    deviceField22.setNumCols(4);
    deviceField22.setIdentifier("");
    jPanel24.setLayout(flowLayout6);
    deviceField2113.setOffsetNid(1043);
    deviceField2113.setLabelString("Amp.:");
    deviceField2113.setNumCols(4);
    deviceField2113.setIdentifier("");
    deviceField2112.setOffsetNid(1047);
    deviceField2112.setLabelString("End:");
    deviceField2112.setNumCols(4);
    deviceField2112.setIdentifier("");
    jPanel23.setLayout(flowLayout7);
    deviceField24.setOffsetNid(1035);
    deviceField24.setLabelString("Rot. Freq. (Hz):");
    deviceField24.setNumCols(4);
    deviceField24.setIdentifier("");
    deviceField23.setOffsetNid(1033);
    deviceField23.setLabelString("End:");
    deviceField23.setNumCols(4);
    deviceField23.setIdentifier("");
    jPanel6.setLayout(flowLayout5);
    deviceField213.setIdentifier("");
    deviceField213.setNumCols(4);
    deviceField213.setLabelString("Rot. Freq. (Hz):");
    deviceField213.setOffsetNid(1063);
    deviceField32.setOffsetNid(1055);
    deviceField32.setLabelString("M3:");
    deviceField32.setNumCols(2);
    deviceField33.setOffsetNid(1069);
    deviceField33.setLabelString("M4:");
    deviceField33.setNumCols(2);
    deviceField214.setOffsetNid(1059);
    deviceField214.setLabelString("Start:");
    deviceField214.setNumCols(4);
    deviceField214.setIdentifier("");
    jPanel7.setLayout(flowLayout8);
    jPanel5.setLayout(gridLayout5);
    gridLayout5.setRows(4);
    gridLayout5.setVgap(-5);
    deviceField215.setOffsetNid(1053);
    deviceField215.setLabelString("N3: ");
    deviceField215.setNumCols(2);
    deviceField215.setIdentifier("");
    deviceField216.setOffsetNid(1061);
    deviceField216.setLabelString("End:");
    deviceField216.setNumCols(4);
    deviceField216.setIdentifier("");
    deviceField219.setIdentifier("");
    deviceField219.setNumCols(4);
    deviceField219.setLabelString("Rot. Freq. (Hz):");
    deviceField219.setOffsetNid(1049);
    deviceField218.setIdentifier("");
    deviceField218.setNumCols(4);
    deviceField218.setLabelString("Rot. Phase(Rad):");
    deviceField218.setOffsetNid(1051);
    deviceField217.setOffsetNid(1057);
    deviceField217.setLabelString("Amp.:");
    deviceField217.setNumCols(4);
    deviceField217.setIdentifier("");
    deviceField29.setOffsetNid(1067);
    deviceField29.setLabelString("N4: ");
    deviceField29.setNumCols(2);
    deviceField29.setIdentifier("");
    deviceField26.setIdentifier("");
    deviceField26.setNumCols(4);
    deviceField26.setLabelString("Rot. Phase(Rad):");
    deviceField26.setOffsetNid(1079);
    deviceField28.setOffsetNid(1073);
    deviceField28.setLabelString("Start:");
    deviceField28.setNumCols(4);
    deviceField28.setIdentifier("");
    deviceField27.setIdentifier("");
    deviceField27.setNumCols(4);
    deviceField27.setLabelString("Rot. Freq. (Hz):");
    deviceField27.setOffsetNid(1077);
        jPanel40.setLayout(gridLayout8);
    gridLayout8.setColumns(1);
    gridLayout8.setHgap(0);
    gridLayout8.setRows(2);
    gridLayout8.setVgap(-2);
    deviceChoice2.setChoiceIntValues(new int[] {(int)3,(int)4,(int)9,(int)10,(int)11,(int)12,(int)15,(int)16});
    deviceChoice2.setChoiceFloatValues(null);
    deviceChoice2.setConvert(true);
    deviceChoice2.setOffsetNid(7);
    deviceChoice2.setLabelString("Trig1 control: ");
    deviceChoice2.setChoiceItems(new String[] {"ROT.PERTURBATION", "MODE CONTROL", "MODE CONTROL+ROT.PERT.", "VIRTUAL SHELL", "VS+ROT.PERT.(FEEDBACK)", "VS+ROT.PERT.(FEEDFORW)",
        "Closer VS", "Closer VS+Rot.Pert."});
    deviceChoice2.setUpdateIdentifier("");
    deviceChoice2.setIdentifier("");
        deviceTable7.setOffsetNid(1229);
    deviceTable7.setLabelString("Gain Module:");
    deviceTable7.setNumCols(48);
    deviceTable7.setNumRows(1);
    deviceTable7.setIdentifier("");
    deviceTable7.setColumnNames(new String[] {"0", "-1", "-2", "-3", "-4", "-5", "-6", "-7", "-8", "-9", "-10", "-11", "-12", "-13", "-14", "-15", "-16", "-17", "-18", "-19", "-20", "-21", "-22", "-23", "-24", "23", "22", "21", "20", "19", "18", "17", "16", "15", "14", "13", "12", "11", "10", "9",
        "8", "7", "6", "5", "4", "3", "2", "1"});
    deviceTable7.setRowNames(null);
    deviceField34.setOffsetNid(1227);
    deviceField34.setLabelString("End Time(s): ");
    deviceField34.setIdentifier("");
    gridLayout10.setColumns(1);
    gridLayout10.setRows(2);
    jPanel47.setLayout(gridLayout10);
    jPanel42.setLayout(borderLayout5);
    deviceChoice5.setChoiceIntValues(new int[] {(int)0,(int)1});
    deviceChoice5.setChoiceFloatValues(null);
    deviceChoice5.setConvert(true);
    deviceChoice5.setOffsetNid(1233);
    deviceChoice5.setLabelString("Mode: ");
    deviceChoice5.setChoiceItems(new String[] {"M1->M1", "M0->M0"});
    deviceChoice5.setUpdateIdentifier("");
    deviceChoice5.setIdentifier("");
    deviceTable11.setRowNames(null);
    deviceTable11.setColumnNames(new String[] {"0", "-1", "-2", "-3", "-4", "-5", "-6", "-7", "-8", "-9", "-10", "-11", "-12", "-13", "-14", "-15", "-16", "-17", "-18", "-19", "-20", "-21", "-22", "-23", "-24", "23", "22", "21", "20", "19", "18", "17", "16", "15", "14", "13", "12", "11", "10", "9",
        "8", "7", "6", "5", "4", "3", "2", "1"});
    deviceTable11.setIdentifier("");
    deviceTable11.setNumRows(1);
    deviceTable11.setNumCols(48);
    deviceTable11.setLabelString("Gain Phase (Rad):");
    deviceTable11.setOffsetNid(1231);
    deviceField35.setOffsetNid(1225);
    deviceField35.setLabelString("Start Time(s): ");
    deviceField35.setIdentifier("");
    jPanel415.setLayout(gridLayout11);
    deviceChoice6.setChoiceIntValues(new int[] {(int)0,(int)1});
    deviceChoice6.setChoiceFloatValues(null);
    deviceChoice6.setConvert(true);
    deviceChoice6.setOffsetNid(1243);
    deviceChoice6.setLabelString("Mode: ");
    deviceChoice6.setChoiceItems(new String[] {"M1->M1", "M0->M0"});
    deviceChoice6.setUpdateIdentifier("");
    deviceChoice6.setIdentifier("");
    deviceTable13.setRowNames(null);
    deviceTable13.setColumnNames(new String[] {"0", "-1", "-2", "-3", "-4", "-5", "-6", "-7", "-8", "-9", "-10", "-11", "-12", "-13", "-14", "-15", "-16", "-17", "-18", "-19", "-20", "-21", "-22", "-23", "-24", "23", "22", "21", "20", "19", "18", "17", "16", "15", "14", "13", "12", "11", "10", "9",
        "8", "7", "6", "5", "4", "3", "2", "16<NL>5<NL>4<NL>3<NL>2<NL>1<NL>"});
    deviceTable13.setIdentifier("");
    deviceTable13.setNumRows(1);
    deviceTable13.setNumCols(48);
    deviceTable13.setLabelString("Gain Phase (Rad):");
    deviceTable13.setOffsetNid(1241);
    deviceField37.setOffsetNid(1235);
    deviceField37.setLabelString("Start Time(s): ");
    deviceField37.setIdentifier("");
    deviceTable8.setRowNames(null);
    deviceTable8.setColumnNames(new String[] {"0", "-1", "-2", "-3", "-4", "-5", "-6", "-7", "-8", "-9", "-10", "-11", "-12", "-13", "-14", "-15", "-16", "-17", "-18", "-19", "-20", "-21", "-22", "-23", "-24", "23", "22", "21", "20", "19", "18", "17", "16", "15", "14", "13", "12", "11", "10", "9",
        "8", "7", "6", "5", "4", "3", "2", "1"});
    deviceTable8.setIdentifier("");
    deviceTable8.setNumRows(1);
    deviceTable8.setNumCols(48);
    deviceTable8.setLabelString("Gain Module:");
    deviceTable8.setOffsetNid(1239);
    deviceField36.setIdentifier("");
    deviceField36.setLabelString("End Time(s): ");
    deviceField36.setOffsetNid(1237);
    gridLayout11.setRows(2);
    gridLayout11.setColumns(1);
    jPanel45.setLayout(borderLayout6);
    jPanel417.setLayout(borderLayout7);
    deviceTable15.setRowNames(null);
    deviceTable15.setColumnNames(new String[] {"0", "-1", "-2", "-3", "-4", "-5", "-6", "-7", "-8", "-9", "-10", "-11", "-12", "-13", "-14", "-15", "-16", "-17", "-18", "-19", "-20", "-21", "-22", "-23", "-24", "23", "22", "21", "20", "19", "18", "17", "16", "15", "14", "13", "12", "11", "10", "9",
        "8", "7", "6", "5", "4", "3", "2", "1"});
    deviceTable15.setIdentifier("");
    deviceTable15.setNumRows(1);
    deviceTable15.setNumCols(48);
    deviceTable15.setLabelString("Gain Phase (Rad):");
    deviceTable15.setOffsetNid(1251);
    deviceField38.setIdentifier("");
    deviceField38.setLabelString("End Time(s): ");
    deviceField38.setOffsetNid(1247);
    jPanel416.setLayout(gridLayout12);
    gridLayout12.setRows(2);
    gridLayout12.setColumns(1);
    deviceChoice7.setChoiceIntValues(new int[] {(int)0,(int)1});
    deviceChoice7.setChoiceFloatValues(null);
    deviceChoice7.setConvert(true);
    deviceChoice7.setOffsetNid(1253);
    deviceChoice7.setLabelString("Mode: ");
    deviceChoice7.setChoiceItems(new String[] {"M1->M1", "M0->M0"});
    deviceChoice7.setUpdateIdentifier("");
    deviceChoice7.setIdentifier("");
    deviceField39.setOffsetNid(1245);
    deviceField39.setLabelString("Start Time(s): ");
    deviceField39.setIdentifier("");
    deviceTable9.setRowNames(null);
    deviceTable9.setColumnNames(new String[] {"0", "-1", "-2", "-3", "-4", "-5", "-6", "-7", "-8", "-9", "-10", "-11", "-12", "-13", "-14", "-15", "-16", "-17", "-18", "-19", "-20", "-21", "-22", "-23", "-24", "23", "22", "21", "20", "19", "18", "17", "16", "15", "14", "13", "12", "11", "10", "9",
        "8", "7", "6", "5", "4", "3", "2", "1"});
    deviceTable9.setIdentifier("");
    deviceTable9.setNumRows(1);
    deviceTable9.setNumCols(48);
    deviceTable9.setLabelString("Gain Module:");
    deviceTable9.setOffsetNid(1249);
    deviceField311.setOffsetNid(1255);
    deviceField311.setLabelString("Start Time(s): ");
    deviceField311.setIdentifier("");
    gridLayout13.setRows(2);
    gridLayout13.setColumns(1);
    jPanel419.setLayout(gridLayout13);
    jPanel4110.setLayout(borderLayout8);
    deviceTable18.setRowNames(null);
    deviceTable18.setColumnNames(new String[] {"0", "-1", "-2", "-3", "-4", "-5", "-6", "-7", "-8", "-9", "-10", "-11", "-12", "-13", "-14", "-15", "-16", "-17", "-18", "-19", "-20", "-21", "-22", "-23", "-24", "23", "22", "21", "20", "19", "18", "17", "16", "15", "14", "13", "12", "11", "10", "9",
        "8", "7", "6", "5", "4", "3", "2", "1"});
    deviceTable18.setIdentifier("");
    deviceTable18.setNumRows(1);
    deviceTable18.setNumCols(48);
    deviceTable18.setLabelString("Gain Phase (Rad):");
    deviceTable18.setOffsetNid(1261);
    deviceChoice8.setChoiceIntValues(new int[] {(int)0,(int)1});
    deviceChoice8.setChoiceFloatValues(null);
    deviceChoice8.setConvert(true);
    deviceChoice8.setOffsetNid(1263);
    deviceChoice8.setLabelString("Mode: ");
    deviceChoice8.setChoiceItems(new String[] {"M1->M1", "M0->M0"});
    deviceChoice8.setUpdateIdentifier("");
    deviceChoice8.setIdentifier("");
    deviceField310.setIdentifier("");
    deviceField310.setLabelString("End Time(s): ");
    deviceField310.setOffsetNid(1257);
    deviceTable16.setRowNames(null);
    deviceTable16.setColumnNames(new String[] {"0", "-1", "-2", "-3", "-4", "-5", "-6", "-7", "-8", "-9", "-10", "-11", "-12", "-13", "-14", "-15", "-16", "-17", "-18", "-19", "-20", "-21", "-22", "-23", "-24", "23", "22", "21", "20", "19", "18", "17", "16", "15", "14", "13", "12", "11", "10", "9",
        "8", "7", "6", "5", "4", "3", "2", "1"});
    deviceTable16.setIdentifier("");
    deviceTable16.setNumRows(1);
    deviceTable16.setNumCols(48);
    deviceTable16.setLabelString("Gain Module:");
    deviceTable16.setOffsetNid(1259);
    jPanel54.setLayout(gridLayout9);
        gridLayout9.setColumns(1);
        gridLayout9.setRows(4);
        deviceTable21.setOffsetNid(1081);
        deviceTable21.setLabelString("Kp");
        deviceTable21.setNumCols(48);
        deviceTable21.setNumRows(4);
        deviceTable21.setIdentifier("");
        deviceTable21.setColumnNames(new String[] {"1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48"});
        deviceTable21.setRowNames(null);
        deviceTable21.setDisplayRowNumber(true);
        deviceTable23.setDisplayRowNumber(true);
        deviceTable23.setRowNames(null);
        deviceTable23.setColumnNames(new String[] {"1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48"});
        deviceTable23.setIdentifier("");
        deviceTable23.setNumRows(4);
        deviceTable23.setNumCols(48);
        deviceTable23.setLabelString("Kd");
        deviceTable23.setOffsetNid(1085);
        deviceTable24.setDisplayRowNumber(true);
        deviceTable24.setRowNames(null);
        deviceTable24.setColumnNames(new String[] {"1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48"});
        deviceTable24.setIdentifier("");
        deviceTable24.setNumRows(4);
        deviceTable24.setNumCols(48);
        deviceTable24.setLabelString("Ki");
        deviceTable24.setOffsetNid(1083);
        deviceField16.setOffsetNid(1295);
        deviceField16.setLabelString("Rise time(s):");
        deviceField16.setNumCols(4);
        deviceField16.setIdentifier("");
        deviceField40.setOffsetNid(1297);
        deviceField40.setLabelString("Rise time(s): ");
        deviceField40.setNumCols(4);
        deviceField40.setIdentifier("");
        deviceField41.setOffsetNid(1299);
        deviceField41.setLabelString("Rise time(s):");
        deviceField41.setNumCols(4);
        deviceField41.setIdentifier("");
        deviceField42.setOffsetNid(1301);
        deviceField42.setLabelString("Rise time(s):");
        deviceField42.setNumCols(4);
        deviceField42.setIdentifier("");
        jPanel55.setLayout(borderLayout9);
        deviceTable22.setDisplayRowNumber(true);
        deviceTable22.setRowNames(new String[] {"0", "1", "2", "3"});
        deviceTable22.setBinary(false);
        deviceTable22.setColumnNames(new String[] {"0", "-1", "-2", "-3", "-4", "-5", "-6", "-7", "-8", "-9", "-10", "-11", "-12", "-13", "-14", "-15", "-16", "-17", "-18", "-19", "-20", "-21", "-22", "-23", "-24", "23", "22", "21", "20", "19", "18", "17", "16", "15", "14", "13", "12", "11", "10", "9",
        "8", "7", "6", "5", "4", "3", "2", "1"});
        deviceTable22.setIdentifier("");
        deviceTable22.setNumRows(4);
        deviceTable22.setNumCols(48);
        deviceTable22.setLabelString("Mode Gains (Module)");
        deviceTable22.setOffsetNid(1269);
        deviceField44.setOffsetNid(1265);
        deviceField44.setLabelString("Start time: ");
        deviceField44.setNumCols(5);
        deviceField44.setIdentifier("");
        deviceField43.setOffsetNid(1267);
        deviceField43.setLabelString("End time: ");
        deviceField43.setNumCols(5);
        deviceField43.setIdentifier("");
        deviceField45.setIdentifier("");
        deviceField45.setNumCols(5);
        deviceField45.setLabelString("End time: ");
        deviceField45.setOffsetNid(1277);
        jPanel57.setLayout(borderLayout10);
        deviceTable25.setDisplayRowNumber(true);
        deviceTable25.setRowNames(new String[] {"0", "1", "2", "3"});
        deviceTable25.setBinary(false);
        deviceTable25.setColumnNames(new String[] {"0", "-1", "-2", "-3", "-4", "-5", "-6", "-7", "-8", "-9", "-10", "-11", "-12", "-13", "-14", "-15", "-16", "-17", "-18", "-19", "-20", "-21", "-22", "-23", "-24", "23", "22", "21", "20", "19", "18", "17", "16", "15", "14", "13", "12", "11", "10", "9",
        "8", "7", "6", "5", "4", "3", "2", "1"});
        deviceTable25.setIdentifier("");
        deviceTable25.setNumRows(4);
        deviceTable25.setNumCols(48);
        deviceTable25.setLabelString("Mode Gains (Module)");
        deviceTable25.setOffsetNid(1279);
        deviceField46.setOffsetNid(1275);
        deviceField46.setLabelString("Start time: ");
        deviceField46.setNumCols(5);
        deviceField46.setIdentifier("");
        deviceTable26.setDisplayRowNumber(true);
        deviceTable26.setRowNames(new String[] {"0", "1", "2", "3"});
        deviceTable26.setBinary(false);
        deviceTable26.setColumnNames(new String[] {"0", "-1", "-2", "-3", "-4", "-5", "-6", "-7", "-8", "-9", "-10", "-11", "-12", "-13", "-14", "-15", "-16", "-17", "-18", "-19", "-20", "-21", "-22", "-23", "-24", "23", "22", "21", "20", "19", "18", "17", "16", "15", "14", "13", "12", "11", "10", "9",
        "8", "7", "6", "5", "4", "3", "2", "1"});
        deviceTable26.setIdentifier("");
        deviceTable26.setNumRows(4);
        deviceTable26.setNumCols(48);
        deviceTable26.setLabelString("Mode Gains (Module)");
        deviceTable26.setOffsetNid(1289);
        jPanel59.setLayout(borderLayout11);
        deviceField48.setOffsetNid(1285);
        deviceField48.setLabelString("Start time: ");
        deviceField48.setNumCols(5);
        deviceField48.setIdentifier("");
        deviceField47.setIdentifier("");
        deviceField47.setNumCols(5);
        deviceField47.setLabelString("End time: ");
        deviceField47.setOffsetNid(1287);
        deviceField1.setOffsetNid(1);
        deviceField1.setTextOnly(true);
        deviceField1.setLabelString("Comment: ");
        deviceField1.setNumCols(30);
        deviceField1.setIdentifier("");
    deviceTable27.setOffsetNid(1271);
        deviceTable27.setLabelString("Mode Gains (Phase, Rad)");
        deviceTable27.setNumCols(48);
        deviceTable27.setNumRows(4);
        deviceTable27.setIdentifier("");
        deviceTable27.setColumnNames(new String[] {"0", "-1", "-2", "-3", "-4", "-5", "-6", "-7", "-8", "-9", "-10", "-11", "-12", "-13", "-14", "-15", "-16", "-17", "-18", "-19", "-20", "-21", "-22", "-23", "-24", "23", "22", "21", "20", "19", "18", "17", "16", "15", "14", "13", "12", "11", "10", "9",
        "8", "7", "6", "5", "4", "3", "2", "1"});
        deviceTable27.setBinary(false);
        deviceTable27.setRowNames(new String[] {"0", "1", "2", "3"});
        deviceTable27.setDisplayRowNumber(true);
        deviceTable28.setOffsetNid(1281);
        deviceTable28.setLabelString("Mode Gains (Phase, Rad)");
        deviceTable28.setNumCols(48);
        deviceTable28.setNumRows(4);
        deviceTable28.setIdentifier("");
        deviceTable28.setColumnNames(new String[] {"0", "-1", "-2", "-3", "-4", "-5", "-6", "-7", "-8", "-9", "-10", "-11", "-12", "-13", "-14", "-15", "-16", "-17", "-18", "-19", "-20", "-21", "-22", "-23", "-24", "23", "22", "21", "20", "19", "18", "17", "16", "15", "14", "13", "12", "11", "10", "9",
        "8", "7", "6", "5", "4", "3", "2", "1"});
        deviceTable28.setBinary(false);
        deviceTable28.setRowNames(new String[] {"0", "1", "2", "3"});
        deviceTable28.setDisplayRowNumber(true);
        deviceTable29.setOffsetNid(1291);
        deviceTable29.setLabelString("Mode Gains (Phase, Rad)");
        deviceTable29.setNumCols(48);
        deviceTable29.setNumRows(4);
        deviceTable29.setIdentifier("");
        deviceTable29.setColumnNames(new String[] {"0", "-1", "-2", "-3", "-4", "-5", "-6", "-7", "-8", "-9", "-10", "-11", "-12", "-13", "-14", "-15", "-16", "-17", "-18", "-19", "-20", "-21", "-22", "-23", "-24", "23", "22", "21", "20", "19", "18", "17", "16", "15", "14", "13", "12", "11", "10", "9",
        "8", "7", "6", "5", "4", "3", "2", "1"});
        deviceTable29.setBinary(false);
        deviceTable29.setRowNames(new String[] {"0", "1", "2", "3"});
        deviceTable29.setDisplayRowNumber(true);
        this.getContentPane().add(jPanel9,  BorderLayout.NORTH);
    jPanel9.add(jPanel40, BorderLayout.CENTER);
    jPanel40.add(jPanel10, null);
        jPanel10.add(deviceField1, null);
        jPanel40.add(jPanel27, null);
    jPanel27.add(deviceChoice2, null);
    this.getContentPane().add(jPanel33,  BorderLayout.CENTER);
    jPanel33.add(jTabbedPane1,  BorderLayout.CENTER);
    jTabbedPane1.add(jScrollPane4,  "Rot. Perturbation");
    jScrollPane4.getViewport().add(jPanel5, null);
        jPanel24.add(deviceField2111, null);
    jPanel24.add(deviceField31, null);
    jPanel24.add(deviceField2113, null);
    jPanel24.add(deviceField2110, null);
    jPanel24.add(deviceField2112, null);
    jPanel24.add(deviceField219, null);
    jPanel24.add(deviceField218, null);
        jPanel24.add(deviceField40, null);
    jPanel5.add(jPanel6, null);
    jPanel5.add(jPanel24, null);
        jPanel6.add(deviceField20, null);
    jPanel6.add(deviceField30, null);
    jPanel6.add(deviceField21, null);
    jPanel6.add(deviceField22, null);
    jPanel6.add(deviceField23, null);
    jPanel6.add(deviceField24, null);
    jPanel6.add(deviceField25, null);
        jPanel6.add(deviceField16, null);
    jPanel5.add(jPanel23, null);
        jPanel23.add(deviceField215, null);
    jPanel23.add(deviceField32, null);
    jPanel23.add(deviceField217, null);
    jPanel23.add(deviceField214, null);
    jPanel23.add(deviceField216, null);
    jPanel23.add(deviceField213, null);
    jPanel23.add(deviceField212, null);
    jPanel5.add(jPanel7, null);
    jPanel7.add(deviceField29, null);
    jPanel7.add(deviceField33, null);
    jPanel7.add(deviceField211, null);
    jPanel7.add(deviceField28, null);
    jPanel7.add(deviceField210, null);
    jPanel7.add(deviceField27, null);
    jPanel7.add(deviceField26, null);
        jTabbedPane1.add(jScrollPane5,   "Mode Control 1");
    jScrollPane5.getViewport().add(jPanel42, null);
    jPanel44.add(deviceField35, null);
    jPanel44.add(deviceField34, null);
    jPanel44.add(deviceChoice5, null);
    jPanel42.add(jPanel47, BorderLayout.CENTER);
    jPanel42.add(jPanel44, BorderLayout.NORTH);
    jPanel47.add(deviceTable7, null);
    jPanel47.add(deviceTable11, null);
    jTabbedPane1.add(jScrollPane14,  "Mode Control 2");
    jTabbedPane1.add(jScrollPane7,  "Mode Control 3");
    jTabbedPane1.add(jScrollPane8,  "Mode Control 4");
        jTabbedPane1.add(jScrollPane15,   "Virtual Shell: PID Parameters");
        jTabbedPane1.add(jScrollPane9,   "Virtual Shell: Input Config. 1");
        jTabbedPane1.add(jScrollPane10,   "Virtual Shell: Input Config. 2");
        jScrollPane10.getViewport().add(jPanel57, null);
        jPanel57.add(deviceTable25, BorderLayout.CENTER);
        jPanel57.add(jPanel58, BorderLayout.NORTH);
        jPanel58.add(deviceField46, null);
        jPanel58.add(deviceField45, null);
        jPanel57.add(deviceTable28,  BorderLayout.SOUTH);
        jTabbedPane1.add(jScrollPane11,    "Virtual Shell: Input Config. 3");
        jScrollPane11.getViewport().add(jPanel59, null);
        jPanel59.add(deviceTable26,  BorderLayout.CENTER);
        jPanel59.add(jPanel510, BorderLayout.NORTH);
        jPanel510.add(deviceField48, null);
        jPanel510.add(deviceField47, null);
        jPanel59.add(deviceTable29,  BorderLayout.SOUTH);
        jScrollPane9.getViewport().add(jPanel55, null);
        jPanel55.add(deviceTable22, BorderLayout.CENTER);
        jPanel55.add(jPanel56, BorderLayout.NORTH);
        jPanel56.add(deviceField44, null);
        jPanel56.add(deviceField43, null);
        jPanel55.add(deviceTable27,  BorderLayout.SOUTH);
        jScrollPane15.getViewport().add(jPanel54, null);
        jPanel54.add(deviceTable21, null);
        jPanel54.add(deviceTable24, null);
        jPanel54.add(deviceTable23, null);
    jScrollPane8.getViewport().add(jPanel4110, null);
    jPanel419.add(deviceTable16, null);
    jPanel419.add(deviceTable18, null);
    jPanel4110.add(jPanel4111, BorderLayout.NORTH);
    jPanel4110.add(jPanel419, BorderLayout.CENTER);
    jPanel4111.add(deviceField311, null);
    jPanel4111.add(deviceField310, null);
    jPanel4111.add(deviceChoice8, null);
    jScrollPane7.getViewport().add(jPanel417, null);
    jPanel416.add(deviceTable9, null);
    jPanel416.add(deviceTable15, null);
    jPanel417.add(jPanel418, BorderLayout.NORTH);
    jPanel417.add(jPanel416, BorderLayout.CENTER);
    jPanel418.add(deviceField39, null);
    jPanel418.add(deviceField38, null);
    jPanel418.add(deviceChoice7, null);
    jScrollPane14.getViewport().add(jPanel45, null);
    jPanel415.add(deviceTable8, null);
    jPanel415.add(deviceTable13, null);
    jPanel45.add(jPanel46, BorderLayout.NORTH);
    jPanel45.add(jPanel415, BorderLayout.CENTER);
    jPanel46.add(deviceField37, null);
    jPanel46.add(deviceField36, null);
    jPanel46.add(deviceChoice6, null);
    this.getContentPane().add(deviceButtons1, BorderLayout.SOUTH);
        jPanel23.add(deviceField41, null);
        jPanel7.add(deviceField42, null);
  }

}
