

import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
/**
 * <p>Title: </p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2003</p>
 * <p>Company: </p>
 * @author not attributable
 * @version 1.0
 */

public class RFXTorControlSetup extends DeviceSetup {
  DeviceButtons deviceButtons1 = new DeviceButtons();
  JPanel jPanel9 = new JPanel();
  BorderLayout borderLayout1 = new BorderLayout();
  JPanel jPanel33 = new JPanel();
  BorderLayout borderLayout2 = new BorderLayout();
  JTabbedPane jTabbedPane1 = new JTabbedPane();
  JScrollPane jScrollPane4 = new JScrollPane();
  DeviceField deviceField25 = new DeviceField();
  DeviceField deviceField2111 = new DeviceField();
  DeviceField deviceField212 = new DeviceField();
  DeviceField deviceField2110 = new DeviceField();
  DeviceField deviceField210 = new DeviceField();
  DeviceField deviceField31 = new DeviceField();
  DeviceField deviceField30 = new DeviceField();
  DeviceField deviceField20 = new DeviceField();
  DeviceField deviceField21 = new DeviceField();
  DeviceField deviceField211 = new DeviceField();
  DeviceField deviceField22 = new DeviceField();
  JPanel jPanel24 = new JPanel();
  DeviceField deviceField2113 = new DeviceField();
  DeviceField deviceField2112 = new DeviceField();
  JPanel jPanel23 = new JPanel();
  DeviceField deviceField24 = new DeviceField();
  DeviceField deviceField23 = new DeviceField();
  JPanel jPanel6 = new JPanel();
  DeviceField deviceField213 = new DeviceField();
  DeviceField deviceField32 = new DeviceField();
  DeviceField deviceField33 = new DeviceField();
  FlowLayout flowLayout5 = new FlowLayout();
  DeviceField deviceField214 = new DeviceField();
  FlowLayout flowLayout7 = new FlowLayout();
  FlowLayout flowLayout8 = new FlowLayout();
  FlowLayout flowLayout6 = new FlowLayout();
  JPanel jPanel7 = new JPanel();
  JPanel jPanel5 = new JPanel();
  GridLayout gridLayout5 = new GridLayout();
  DeviceField deviceField215 = new DeviceField();
  DeviceField deviceField216 = new DeviceField();
  DeviceField deviceField219 = new DeviceField();
  DeviceField deviceField218 = new DeviceField();
  DeviceField deviceField217 = new DeviceField();
  DeviceField deviceField29 = new DeviceField();
  DeviceField deviceField26 = new DeviceField();
  DeviceField deviceField28 = new DeviceField();
  DeviceField deviceField27 = new DeviceField();
  JPanel jPanel40 = new JPanel();
  GridLayout gridLayout8 = new GridLayout();
  JPanel jPanel10 = new JPanel();
  DeviceField deviceField1 = new DeviceField();
  DeviceChoice deviceChoice2 = new DeviceChoice();
  JPanel jPanel27 = new JPanel();
  BorderLayout borderLayout3 = new BorderLayout();
  JScrollPane jScrollPane6 = new JScrollPane();
  JPanel jPanel410 = new JPanel();
    DeviceTable deviceTable4 = new DeviceTable();
    JPanel jPanel41 = new JPanel();
    GridLayout gridLayout2 = new GridLayout();
    DeviceField deviceField417 = new DeviceField();
    DeviceField deviceField415 = new DeviceField();
    DeviceField deviceField320 = new DeviceField();
    JPanel jPanel411 = new JPanel();
    DeviceField deviceField416 = new DeviceField();
    DeviceField deviceField419 = new DeviceField();
    DeviceField deviceField318 = new DeviceField();
    JPanel jPanel414 = new JPanel();
    DeviceField deviceField423 = new DeviceField();
    DeviceField deviceField420 = new DeviceField();
    DeviceField deviceField4112 = new DeviceField();
    DeviceField deviceField314 = new DeviceField();
    JPanel jPanel412 = new JPanel();
    DeviceField deviceField4113 = new DeviceField();
    DeviceField deviceField422 = new DeviceField();
    DeviceField deviceField3110 = new DeviceField();
    JPanel jPanel48 = new JPanel();
    DeviceField deviceField418 = new DeviceField();
    DeviceField deviceField4111 = new DeviceField();
    DeviceField deviceField4110 = new DeviceField();
    BorderLayout borderLayout4 = new BorderLayout();
  DeviceField deviceField424 = new DeviceField();
  DeviceField deviceField3111 = new DeviceField();
  DeviceField deviceField421 = new DeviceField();
  DeviceField deviceField425 = new DeviceField();
  JPanel jPanel413 = new JPanel();
  DeviceField deviceField316 = new DeviceField();
  JPanel jPanel49 = new JPanel();
  DeviceField deviceField321 = new DeviceField();
  DeviceField deviceField319 = new DeviceField();
  DeviceField deviceField315 = new DeviceField();
  DeviceField deviceField317 = new DeviceField();
    JScrollPane jScrollPane5 = new JScrollPane();
  DeviceTable deviceTable7 = new DeviceTable();
  DeviceField deviceField34 = new DeviceField();
  BorderLayout borderLayout5 = new BorderLayout();
  GridLayout gridLayout10 = new GridLayout();
  JPanel jPanel47 = new JPanel();
  JPanel jPanel42 = new JPanel();
  DeviceChoice deviceChoice5 = new DeviceChoice();
  JPanel jPanel44 = new JPanel();
  DeviceTable deviceTable11 = new DeviceTable();
  DeviceField deviceField35 = new DeviceField();
  JScrollPane jScrollPane14 = new JScrollPane();
  JPanel jPanel415 = new JPanel();
  DeviceChoice deviceChoice6 = new DeviceChoice();
  DeviceTable deviceTable13 = new DeviceTable();
  DeviceField deviceField37 = new DeviceField();
  JPanel jPanel46 = new JPanel();
  DeviceTable deviceTable8 = new DeviceTable();
  DeviceField deviceField36 = new DeviceField();
  BorderLayout borderLayout6 = new BorderLayout();
  GridLayout gridLayout11 = new GridLayout();
  JPanel jPanel45 = new JPanel();
  JScrollPane jScrollPane7 = new JScrollPane();
  JPanel jPanel417 = new JPanel();
  DeviceTable deviceTable15 = new DeviceTable();
  DeviceField deviceField38 = new DeviceField();
  JPanel jPanel418 = new JPanel();
  JPanel jPanel416 = new JPanel();
  GridLayout gridLayout12 = new GridLayout();
  BorderLayout borderLayout7 = new BorderLayout();
  DeviceChoice deviceChoice7 = new DeviceChoice();
  DeviceField deviceField39 = new DeviceField();
  DeviceTable deviceTable9 = new DeviceTable();
  JScrollPane jScrollPane8 = new JScrollPane();
  DeviceField deviceField311 = new DeviceField();
  GridLayout gridLayout13 = new GridLayout();
  JPanel jPanel419 = new JPanel();
  JPanel jPanel4110 = new JPanel();
  DeviceTable deviceTable18 = new DeviceTable();
  BorderLayout borderLayout8 = new BorderLayout();
  DeviceChoice deviceChoice8 = new DeviceChoice();
  JPanel jPanel4111 = new JPanel();
  DeviceField deviceField310 = new DeviceField();
  DeviceTable deviceTable16 = new DeviceTable();
  Border border1;
  TitledBorder titledBorder1;
  TitledBorder titledBorder2;
  Border border2;
  TitledBorder titledBorder3;
  Border border3;
  TitledBorder titledBorder4;
  Border border4;
  TitledBorder titledBorder5;
  Border border5;
  TitledBorder titledBorder6;
  Border border6;
  TitledBorder titledBorder7;
    DeviceField deviceField16 = new DeviceField();
    DeviceField deviceField40 = new DeviceField();
    DeviceField deviceField41 = new DeviceField();
    DeviceField deviceField42 = new DeviceField();
    JPanel jPanel60 = new JPanel();
    GridLayout gridLayout14 = new GridLayout();
    JPanel jPanel61 = new JPanel();
    JPanel jPanel62 = new JPanel();
    DeviceField deviceField49 = new DeviceField();
    DeviceField deviceField50 = new DeviceField();
    DeviceField deviceField51 = new DeviceField();
    DeviceField deviceField52 = new DeviceField();
    DeviceField deviceField53 = new DeviceField();
    JPanel jPanel63 = new JPanel();
    DeviceField deviceField54 = new DeviceField();
    DeviceField deviceField55 = new DeviceField();
    JPanel jPanel64 = new JPanel();
    DeviceField deviceField410 = new DeviceField();
    GridLayout gridLayout15 = new GridLayout();
    DeviceField deviceField56 = new DeviceField();
    DeviceField deviceField57 = new DeviceField();
    JPanel jPanel65 = new JPanel();
    JPanel jPanel66 = new JPanel();
    DeviceField deviceField58 = new DeviceField();
    JPanel jPanel67 = new JPanel();
    DeviceField deviceField59 = new DeviceField();
    JPanel jPanel68 = new JPanel();
    DeviceField deviceField60 = new DeviceField();
    JPanel jPanel69 = new JPanel();
    DeviceField deviceField61 = new DeviceField();
  public RFXTorControlSetup() {
    try {
      jbInit();
    }
    catch(Exception e) {
      e.printStackTrace();
    }
  }
  private void jbInit() throws Exception {
    border1 = new EtchedBorder(EtchedBorder.RAISED,Color.white,new Color(148, 145, 140));
    titledBorder1 = new TitledBorder(BorderFactory.createLineBorder(Color.black,1),"Output 4");
    titledBorder2 = new TitledBorder("");
    border2 = BorderFactory.createLineBorder(Color.black,2);
    titledBorder3 = new TitledBorder(border2,"Output 3");
    border3 = BorderFactory.createLineBorder(Color.black,1);
    titledBorder4 = new TitledBorder(border3,"Output 1");
    border4 = BorderFactory.createLineBorder(Color.black,1);
    titledBorder5 = new TitledBorder(border4,"Output 2");
    border5 = BorderFactory.createLineBorder(Color.black,2);
    titledBorder6 = new TitledBorder(border5,"Output 3");
    border6 = BorderFactory.createLineBorder(Color.black,1);
    titledBorder7 = new TitledBorder(border6,"Output 4");
    this.setWidth(813);
    this.setHeight(813);
    this.setDeviceType("RFXControl");
    this.setDeviceProvider("");
    this.setDeviceTitle("RFX Control Setup");
    this.getContentPane().setLayout(borderLayout1);
    jPanel9.setLayout(borderLayout3);
    jPanel9.setDebugGraphicsOptions(0);
    jPanel33.setLayout(borderLayout2);
    deviceField25.setOffsetNid(1037);
    deviceField25.setLabelString("Rot. Phase(Rad):");
    deviceField25.setNumCols(4);
    deviceField25.setIdentifier("");
    deviceField2111.setOffsetNid(1039);
    deviceField2111.setLabelString("N2: ");
    deviceField2111.setNumCols(2);
    deviceField2111.setIdentifier("");
    deviceField212.setIdentifier("");
    deviceField212.setNumCols(4);
    deviceField212.setLabelString("Rot. Phase(Rad):");
    deviceField212.setOffsetNid(1065);
    deviceField2110.setOffsetNid(1045);
    deviceField2110.setLabelString("Start:");
    deviceField2110.setNumCols(4);
    deviceField2110.setIdentifier("");
    deviceField210.setOffsetNid(1075);
    deviceField210.setLabelString("End:");
    deviceField210.setNumCols(4);
    deviceField210.setIdentifier("");
    deviceField31.setOffsetNid(1041);
    deviceField31.setLabelString("M2:");
    deviceField31.setNumCols(2);
    deviceField30.setOffsetNid(1027);
    deviceField30.setLabelString("M1:");
    deviceField30.setNumCols(2);
    deviceField30.setIdentifier("");
    deviceField20.setOffsetNid(1025);
    deviceField20.setLabelString("N1: ");
    deviceField20.setNumCols(2);
    deviceField20.setIdentifier("");
    deviceField21.setOffsetNid(1029);
    deviceField21.setLabelString("Amp.:");
    deviceField21.setNumCols(4);
    deviceField21.setIdentifier("");
    deviceField211.setOffsetNid(1071);
    deviceField211.setLabelString("Amp.:");
    deviceField211.setNumCols(4);
    deviceField211.setIdentifier("");
    deviceField22.setOffsetNid(1031);
    deviceField22.setLabelString("Start:");
    deviceField22.setNumCols(4);
    deviceField22.setIdentifier("");
    jPanel24.setLayout(flowLayout6);
    deviceField2113.setOffsetNid(1043);
    deviceField2113.setLabelString("Amp.:");
    deviceField2113.setNumCols(4);
    deviceField2113.setIdentifier("");
    deviceField2112.setOffsetNid(1047);
    deviceField2112.setLabelString("End:");
    deviceField2112.setNumCols(4);
    deviceField2112.setIdentifier("");
    jPanel23.setLayout(flowLayout7);
    deviceField24.setOffsetNid(1035);
    deviceField24.setLabelString("Rot. Freq. (Hz):");
    deviceField24.setNumCols(4);
    deviceField24.setIdentifier("");
    deviceField23.setOffsetNid(1033);
    deviceField23.setLabelString("End:");
    deviceField23.setNumCols(4);
    deviceField23.setIdentifier("");
    jPanel6.setLayout(flowLayout5);
    deviceField213.setIdentifier("");
    deviceField213.setNumCols(4);
    deviceField213.setLabelString("Rot. Freq. (Hz):");
    deviceField213.setOffsetNid(1063);
    deviceField32.setOffsetNid(1055);
    deviceField32.setLabelString("M3:");
    deviceField32.setNumCols(2);
    deviceField33.setOffsetNid(1069);
    deviceField33.setLabelString("M4:");
    deviceField33.setNumCols(2);
    deviceField214.setOffsetNid(1059);
    deviceField214.setLabelString("Start:");
    deviceField214.setNumCols(4);
    deviceField214.setIdentifier("");
    jPanel7.setLayout(flowLayout8);
    jPanel5.setLayout(gridLayout5);
    gridLayout5.setRows(4);
    gridLayout5.setVgap(-5);
    deviceField215.setOffsetNid(1053);
    deviceField215.setLabelString("N3: ");
    deviceField215.setNumCols(2);
    deviceField215.setIdentifier("");
    deviceField216.setOffsetNid(1061);
    deviceField216.setLabelString("End:");
    deviceField216.setNumCols(4);
    deviceField216.setIdentifier("");
    deviceField219.setIdentifier("");
    deviceField219.setNumCols(4);
    deviceField219.setLabelString("Rot. Freq. (Hz):");
    deviceField219.setOffsetNid(1049);
    deviceField218.setIdentifier("");
    deviceField218.setNumCols(4);
    deviceField218.setLabelString("Rot. Phase(Rad):");
    deviceField218.setOffsetNid(1051);
    deviceField217.setOffsetNid(1057);
    deviceField217.setLabelString("Amp.:");
    deviceField217.setNumCols(4);
    deviceField217.setIdentifier("");
    deviceField29.setOffsetNid(1067);
    deviceField29.setLabelString("N4: ");
    deviceField29.setNumCols(2);
    deviceField29.setIdentifier("");
    deviceField26.setIdentifier("");
    deviceField26.setNumCols(4);
    deviceField26.setLabelString("Rot. Phase(Rad):");
    deviceField26.setOffsetNid(1079);
    deviceField28.setOffsetNid(1073);
    deviceField28.setLabelString("Start:");
    deviceField28.setNumCols(4);
    deviceField28.setIdentifier("");
    deviceField27.setIdentifier("");
    deviceField27.setNumCols(4);
    deviceField27.setLabelString("Rot. Freq. (Hz):");
    deviceField27.setOffsetNid(1077);
        jPanel40.setLayout(gridLayout8);
    gridLayout8.setColumns(1);
    gridLayout8.setHgap(0);
    gridLayout8.setRows(2);
    gridLayout8.setVgap(-2);
    deviceField1.setOffsetNid(1);
    deviceField1.setTextOnly(true);
    deviceField1.setLabelString("Comment: ");
    deviceField1.setNumCols(20);
    deviceField1.setIdentifier("");
    deviceChoice2.setChoiceIntValues(new int[] {(int)3,(int)8,(int)4,(int)9,(int)13,(int)14,(int)15});
    deviceChoice2.setChoiceFloatValues(null);
    deviceChoice2.setConvert(true);
    deviceChoice2.setOffsetNid(7);
    deviceChoice2.setLabelString("Trig1 control: ");
    deviceChoice2.setChoiceItems(new String[] {"ROT.PERTURBATION", "LOCK CONTROL", "MODE CONTROL", "MODE CONTROL+ROT.PERT.", "Bt CONTROL", "F CONTROL", "Closer VS"});
    deviceChoice2.setUpdateIdentifier("");
    deviceChoice2.setIdentifier("");
    jPanel410.setLayout(borderLayout4);
    deviceTable4.setOffsetNid(1223);
        deviceTable4.setLabelString("Pert. Values");
        deviceTable4.setNumCols(14);
        deviceTable4.setNumRows(1);
        deviceTable4.setIdentifier("");
        deviceTable4.setColumnNames(new String[] {"-6", "-5", "-4", "-3", "-2", "-1", "1", "2", "3", "4", "5", "6", "DeltaPhi(Rad)", "Rot.Freq.(Hz)"});
        deviceTable4.setRowNames(null);
        jPanel41.setLayout(gridLayout2);
        gridLayout2.setRows(6);
        deviceField417.setOffsetNid(1217);
        deviceField417.setLabelString("Delta Phi(Rad): ");
        deviceField417.setNumCols(4);
        deviceField417.setIdentifier("");
        deviceField415.setOffsetNid(1215);
        deviceField415.setLabelString("N: ");
        deviceField415.setNumCols(4);
        deviceField415.setIdentifier("");
        deviceField320.setOffsetNid(1221);
        deviceField320.setLabelString("Rot. Frequency (Hz): ");
        deviceField320.setNumCols(4);
        deviceField320.setIdentifier("");
        deviceField416.setOffsetNid(1219);
        deviceField416.setLabelString("Amplitude: ");
        deviceField416.setNumCols(4);
        deviceField416.setIdentifier("");
        deviceField419.setOffsetNid(1203);
        deviceField419.setLabelString("Amplitude: ");
        deviceField419.setNumCols(4);
        deviceField419.setIdentifier("");
        deviceField318.setOffsetNid(1205);
        deviceField318.setLabelString("Rot. Frequency (Hz): ");
        deviceField318.setNumCols(4);
        deviceField318.setIdentifier("");
        deviceField423.setOffsetNid(1201);
        deviceField423.setLabelString("Delta Phi(Rad): ");
        deviceField423.setNumCols(4);
        deviceField423.setIdentifier("");
        deviceField420.setOffsetNid(1199);
        deviceField420.setLabelString("N: ");
        deviceField420.setNumCols(4);
        deviceField420.setIdentifier("");
        deviceField4112.setOffsetNid(1191);
        deviceField4112.setLabelString("N: ");
        deviceField4112.setNumCols(4);
        deviceField4112.setIdentifier("");
        deviceField314.setOffsetNid(1197);
        deviceField314.setLabelString("Rot. Frequency (Hz): ");
        deviceField314.setNumCols(4);
        deviceField314.setIdentifier("");
        deviceField4113.setOffsetNid(1195);
        deviceField4113.setLabelString("Amplitude: ");
        deviceField4113.setNumCols(4);
        deviceField4113.setIdentifier("");
        deviceField422.setOffsetNid(1193);
        deviceField422.setLabelString("Delta Phi(Rad): ");
        deviceField422.setNumCols(4);
        deviceField422.setIdentifier("");
        deviceField3110.setOffsetNid(1189);
        deviceField3110.setLabelString("Rot. Frequency (Hz): ");
        deviceField3110.setNumCols(4);
        deviceField3110.setIdentifier("");
        deviceField418.setOffsetNid(1183);
        deviceField418.setLabelString("N: ");
        deviceField418.setNumCols(4);
        deviceField418.setIdentifier("");
        deviceField4111.setOffsetNid(1187);
        deviceField4111.setLabelString("Amplitude: ");
        deviceField4111.setNumCols(4);
        deviceField4111.setIdentifier("");
        deviceField4110.setOffsetNid(1185);
        deviceField4110.setLabelString("Delta Phi(Rad): ");
        deviceField4110.setNumCols(4);
        deviceField4110.setIdentifier("");
    deviceField424.setOffsetNid(1211);
    deviceField424.setLabelString("Amplitude: ");
    deviceField424.setNumCols(4);
    deviceField424.setIdentifier("");
    deviceField3111.setOffsetNid(1213);
    deviceField3111.setLabelString("Rot. Frequency (Hz): ");
    deviceField3111.setNumCols(4);
    deviceField3111.setIdentifier("");
    deviceField421.setOffsetNid(1209);
    deviceField421.setLabelString("Delta Phi(Rad): ");
    deviceField421.setNumCols(4);
    deviceField421.setIdentifier("");
    deviceField425.setOffsetNid(1207);
    deviceField425.setLabelString("N: ");
    deviceField425.setNumCols(4);
    deviceField425.setIdentifier("");
    deviceField316.setOffsetNid(1175);
    deviceField316.setLabelString("Threshold Strength: ");
    deviceField316.setNumCols(4);
    deviceField316.setIdentifier("");
    deviceField321.setOffsetNid(1177);
    deviceField321.setLabelString("Threshold time: ");
    deviceField321.setNumCols(4);
    deviceField321.setIdentifier("");
    deviceField319.setOffsetNid(1173);
    deviceField319.setLabelString("Start Control: ");
    deviceField319.setNumCols(4);
    deviceField319.setIdentifier("");
    deviceField315.setOffsetNid(1179);
    deviceField315.setLabelString("Threshold Interval(Rad): ");
    deviceField315.setNumCols(4);
    deviceField315.setIdentifier("");
    deviceField317.setOffsetNid(1181);
    deviceField317.setLabelString("Cycle Time");
    deviceField317.setNumCols(4);
    deviceField317.setIdentifier("");
        deviceTable7.setOffsetNid(1229);
    deviceTable7.setLabelString("Gain Module:");
    deviceTable7.setNumCols(48);
    deviceTable7.setNumRows(1);
    deviceTable7.setIdentifier("");
    deviceTable7.setColumnNames(new String[] {"0", "-1", "-2", "-3", "-4", "-5", "-6", "-7", "-8", "-9", "-10", "-11", "-12", "-13", "-14", "-15", "-16", "-17", "-18", "-19", "-20", "-21", "-22", "-23", "-24", "23", "22", "21", "20", "19", "18", "17", "16", "15", "14", "13", "12", "11", "10", "9",
        "8", "7", "6", "5", "4", "3", "2", "1"});
    deviceTable7.setRowNames(null);
    deviceField34.setOffsetNid(1227);
    deviceField34.setLabelString("End Time(s): ");
    deviceField34.setIdentifier("");
    gridLayout10.setColumns(1);
    gridLayout10.setRows(2);
    jPanel47.setLayout(gridLayout10);
    jPanel42.setLayout(borderLayout5);
    deviceChoice5.setChoiceIntValues(new int[] {(int)0,(int)1});
    deviceChoice5.setChoiceFloatValues(null);
    deviceChoice5.setConvert(true);
    deviceChoice5.setOffsetNid(1233);
    deviceChoice5.setLabelString("Mode: ");
    deviceChoice5.setChoiceItems(new String[] {"M1->M1", "M0->M0"});
    deviceChoice5.setUpdateIdentifier("");
    deviceChoice5.setIdentifier("");
    deviceTable11.setRowNames(null);
    deviceTable11.setColumnNames(new String[] {"0", "-1", "-2", "-3", "-4", "-5", "-6", "-7", "-8", "-9", "-10", "-11", "-12", "-13", "-14", "-15", "-16", "-17", "-18", "-19", "-20", "-21", "-22", "-23", "-24", "23", "22", "21", "20", "19", "18", "17", "16", "15", "14", "13", "12", "11", "10", "9",
        "8", "7", "6", "5", "4", "3", "2", "1"});
    deviceTable11.setIdentifier("");
    deviceTable11.setNumRows(1);
    deviceTable11.setNumCols(48);
    deviceTable11.setLabelString("Gain Phase (Rad):");
    deviceTable11.setOffsetNid(1231);
    deviceField35.setOffsetNid(1225);
    deviceField35.setLabelString("Start Time(s): ");
    deviceField35.setIdentifier("");
    jPanel415.setLayout(gridLayout11);
    deviceChoice6.setChoiceIntValues(new int[] {(int)0,(int)1});
    deviceChoice6.setChoiceFloatValues(null);
    deviceChoice6.setConvert(true);
    deviceChoice6.setOffsetNid(1243);
    deviceChoice6.setLabelString("Mode: ");
    deviceChoice6.setChoiceItems(new String[] {"M1->M1", "M0->M0"});
    deviceChoice6.setUpdateIdentifier("");
    deviceChoice6.setIdentifier("");
    deviceTable13.setRowNames(null);
    deviceTable13.setColumnNames(new String[] {"0", "-1", "-2", "-3", "-4", "-5", "-6", "-7", "-8", "-9", "-10", "-11", "-12", "-13", "-14", "-15", "-16", "-17", "-18", "-19", "-20", "-21", "-22", "-23", "-24", "23", "22", "21", "20", "19", "18", "17", "16", "15", "14", "13", "12", "11", "10", "9",
        "8", "7", "6", "5", "4", "3", "2", "16<NL>5<NL>4<NL>3<NL>2<NL>1<NL>"});
    deviceTable13.setIdentifier("");
    deviceTable13.setNumRows(1);
    deviceTable13.setNumCols(48);
    deviceTable13.setLabelString("Gain Phase (Rad):");
    deviceTable13.setOffsetNid(1241);
    deviceField37.setOffsetNid(1235);
    deviceField37.setLabelString("Start Time(s): ");
    deviceField37.setIdentifier("");
    deviceTable8.setRowNames(null);
    deviceTable8.setColumnNames(new String[] {"0", "-1", "-2", "-3", "-4", "-5", "-6", "-7", "-8", "-9", "-10", "-11", "-12", "-13", "-14", "-15", "-16", "-17", "-18", "-19", "-20", "-21", "-22", "-23", "-24", "23", "22", "21", "20", "19", "18", "17", "16", "15", "14", "13", "12", "11", "10", "9",
        "8", "7", "6", "5", "4", "3", "2", "1"});
    deviceTable8.setIdentifier("");
    deviceTable8.setNumRows(1);
    deviceTable8.setNumCols(48);
    deviceTable8.setLabelString("Gain Module:");
    deviceTable8.setOffsetNid(1239);
    deviceField36.setIdentifier("");
    deviceField36.setLabelString("End Time(s): ");
    deviceField36.setOffsetNid(1237);
    gridLayout11.setRows(2);
    gridLayout11.setColumns(1);
    jPanel45.setLayout(borderLayout6);
    jPanel417.setLayout(borderLayout7);
    deviceTable15.setRowNames(null);
    deviceTable15.setColumnNames(new String[] {"0", "-1", "-2", "-3", "-4", "-5", "-6", "-7", "-8", "-9", "-10", "-11", "-12", "-13", "-14", "-15", "-16", "-17", "-18", "-19", "-20", "-21", "-22", "-23", "-24", "23", "22", "21", "20", "19", "18", "17", "16", "15", "14", "13", "12", "11", "10", "9",
        "8", "7", "6", "5", "4", "3", "2", "1"});
    deviceTable15.setIdentifier("");
    deviceTable15.setNumRows(1);
    deviceTable15.setNumCols(48);
    deviceTable15.setLabelString("Gain Phase (Rad):");
    deviceTable15.setOffsetNid(1251);
    deviceField38.setIdentifier("");
    deviceField38.setLabelString("End Time(s): ");
    deviceField38.setOffsetNid(1247);
    jPanel416.setLayout(gridLayout12);
    gridLayout12.setRows(2);
    gridLayout12.setColumns(1);
    deviceChoice7.setChoiceIntValues(new int[] {(int)0,(int)1});
    deviceChoice7.setChoiceFloatValues(null);
    deviceChoice7.setConvert(true);
    deviceChoice7.setOffsetNid(1253);
    deviceChoice7.setLabelString("Mode: ");
    deviceChoice7.setChoiceItems(new String[] {"M1->M1", "M0->M0"});
    deviceChoice7.setUpdateIdentifier("");
    deviceChoice7.setIdentifier("");
    deviceField39.setOffsetNid(1245);
    deviceField39.setLabelString("Start Time(s): ");
    deviceField39.setIdentifier("");
    deviceTable9.setRowNames(null);
    deviceTable9.setColumnNames(new String[] {"0", "-1", "-2", "-3", "-4", "-5", "-6", "-7", "-8", "-9", "-10", "-11", "-12", "-13", "-14", "-15", "-16", "-17", "-18", "-19", "-20", "-21", "-22", "-23", "-24", "23", "22", "21", "20", "19", "18", "17", "16", "15", "14", "13", "12", "11", "10", "9",
        "8", "7", "6", "5", "4", "3", "2", "1"});
    deviceTable9.setIdentifier("");
    deviceTable9.setNumRows(1);
    deviceTable9.setNumCols(48);
    deviceTable9.setLabelString("Gain Module:");
    deviceTable9.setOffsetNid(1249);
    deviceField311.setOffsetNid(1255);
    deviceField311.setLabelString("Start Time(s): ");
    deviceField311.setIdentifier("");
    gridLayout13.setRows(2);
    gridLayout13.setColumns(1);
    jPanel419.setLayout(gridLayout13);
    jPanel4110.setLayout(borderLayout8);
    deviceTable18.setRowNames(null);
    deviceTable18.setColumnNames(new String[] {"0", "-1", "-2", "-3", "-4", "-5", "-6", "-7", "-8", "-9", "-10", "-11", "-12", "-13", "-14", "-15", "-16", "-17", "-18", "-19", "-20", "-21", "-22", "-23", "-24", "23", "22", "21", "20", "19", "18", "17", "16", "15", "14", "13", "12", "11", "10", "9",
        "8", "7", "6", "5", "4", "3", "2", "1"});
    deviceTable18.setIdentifier("");
    deviceTable18.setNumRows(1);
    deviceTable18.setNumCols(48);
    deviceTable18.setLabelString("Gain Phase (Rad):");
    deviceTable18.setOffsetNid(1261);
    deviceChoice8.setChoiceIntValues(new int[] {(int)0,(int)1});
    deviceChoice8.setChoiceFloatValues(null);
    deviceChoice8.setConvert(true);
    deviceChoice8.setOffsetNid(1263);
    deviceChoice8.setLabelString("Mode: ");
    deviceChoice8.setChoiceItems(new String[] {"M1->M1", "M0->M0"});
    deviceChoice8.setUpdateIdentifier("");
    deviceChoice8.setIdentifier("");
    deviceField310.setIdentifier("");
    deviceField310.setLabelString("End Time(s): ");
    deviceField310.setOffsetNid(1257);
    deviceTable16.setRowNames(null);
    deviceTable16.setColumnNames(new String[] {"0", "-1", "-2", "-3", "-4", "-5", "-6", "-7", "-8", "-9", "-10", "-11", "-12", "-13", "-14", "-15", "-16", "-17", "-18", "-19", "-20", "-21", "-22", "-23", "-24", "23", "22", "21", "20", "19", "18", "17", "16", "15", "14", "13", "12", "11", "10", "9",
        "8", "7", "6", "5", "4", "3", "2", "1"});
    deviceTable16.setIdentifier("");
    deviceTable16.setNumRows(1);
    deviceTable16.setNumCols(48);
    deviceTable16.setLabelString("Gain Module:");
    deviceTable16.setOffsetNid(1259);
        deviceField16.setOffsetNid(1295);
        deviceField16.setLabelString("Rise time(s):");
        deviceField16.setNumCols(4);
        deviceField16.setIdentifier("");
        deviceField40.setOffsetNid(1297);
        deviceField40.setLabelString("Rise time(s): ");
        deviceField40.setNumCols(4);
        deviceField40.setIdentifier("");
        deviceField41.setOffsetNid(1299);
        deviceField41.setLabelString("Rise time(s):");
        deviceField41.setNumCols(4);
        deviceField41.setIdentifier("");
        deviceField42.setOffsetNid(1301);
        deviceField42.setLabelString("Rise time(s):");
        deviceField42.setNumCols(4);
        deviceField42.setIdentifier("");
        jPanel60.setLayout(gridLayout14);
        gridLayout14.setColumns(1);
        gridLayout14.setRows(4);
        deviceField50.setOffsetNid(1311);
        deviceField50.setLabelString("Start Time (s)");
        deviceField50.setIdentifier("");
        deviceField49.setOffsetNid(1313);
        deviceField49.setLabelString("End Time (s):");
        deviceField49.setIdentifier("");
        deviceField53.setOffsetNid(1305);
        deviceField53.setLabelString("Kp: ");
        deviceField53.setIdentifier("");
        deviceField52.setOffsetNid(1307);
        deviceField52.setLabelString("Ki: ");
        deviceField52.setIdentifier("");
        deviceField51.setOffsetNid(1309);
        deviceField51.setLabelString("Kd: ");
        deviceField51.setIdentifier("");
        deviceField54.setOffsetNid(1321);
        deviceField54.setLabelString("Ki: ");
        deviceField54.setIdentifier("");
        deviceField55.setOffsetNid(1325);
        deviceField55.setLabelString("Start Time (s)");
        deviceField55.setIdentifier("");
        jPanel64.setLayout(gridLayout15);
        deviceField410.setOffsetNid(1327);
        deviceField410.setLabelString("End Time (s):");
        deviceField410.setIdentifier("");
        gridLayout15.setColumns(1);
        gridLayout15.setRows(4);
        deviceField56.setOffsetNid(1323);
        deviceField56.setLabelString("Kd: ");
        deviceField56.setIdentifier("");
        deviceField57.setOffsetNid(1319);
        deviceField57.setLabelString("Kp: ");
        deviceField57.setIdentifier("");
        deviceField58.setOffsetNid(1317);
        deviceField58.setLabelString("Reference Wave Y: ");
        deviceField58.setNumCols(40);
        deviceField58.setIdentifier("");
        deviceField59.setOffsetNid(1331);
        deviceField59.setLabelString("Reference Wave Y: ");
        deviceField59.setNumCols(40);
        deviceField59.setIdentifier("");
        deviceField60.setOffsetNid(1315);
        deviceField60.setLabelString("Reference Wave X: ");
        deviceField60.setNumCols(40);
        deviceField60.setIdentifier("");
        deviceField61.setOffsetNid(1329);
        deviceField61.setLabelString("Reference Wave X: ");
        deviceField61.setNumCols(40);
        deviceField61.setIdentifier("");
        jPanel414.add(deviceField420, null);
    jPanel414.add(deviceField423, null);
    jPanel414.add(deviceField419, null);
    jPanel414.add(deviceField318, null);
    jPanel49.add(deviceField319, null);
    jPanel49.add(deviceField316, null);
    jPanel49.add(deviceField321, null);
    jPanel49.add(deviceField315, null);
    jPanel49.add(deviceField317, null);
    jPanel412.add(deviceField4112, null);
    jPanel412.add(deviceField422, null);
    jPanel412.add(deviceField4113, null);
    jPanel412.add(deviceField314, null);
    jPanel48.add(deviceField418, null);
    jPanel48.add(deviceField4110, null);
    jPanel48.add(deviceField4111, null);
    jPanel48.add(deviceField3110, null);
    jPanel41.add(jPanel49, null);
    jPanel41.add(jPanel414, null);
    jPanel41.add(jPanel413, null);
    this.getContentPane().add(jPanel9,  BorderLayout.NORTH);
    jPanel9.add(jPanel40, BorderLayout.CENTER);
    jPanel40.add(jPanel10, null);
    jPanel10.add(deviceField1, null);
    jPanel40.add(jPanel27, null);
    jPanel27.add(deviceChoice2, null);
    this.getContentPane().add(jPanel33,  BorderLayout.CENTER);
    jPanel33.add(jTabbedPane1,  BorderLayout.CENTER);
    jTabbedPane1.add(jScrollPane4,  "Rot. Perturbation");
    jScrollPane4.getViewport().add(jPanel5, null);
        jPanel24.add(deviceField2111, null);
    jPanel24.add(deviceField31, null);
    jPanel24.add(deviceField2113, null);
    jPanel24.add(deviceField2110, null);
    jPanel24.add(deviceField2112, null);
    jPanel24.add(deviceField219, null);
    jPanel24.add(deviceField218, null);
        jPanel24.add(deviceField40, null);
    jPanel5.add(jPanel6, null);
    jPanel5.add(jPanel24, null);
        jPanel6.add(deviceField20, null);
    jPanel6.add(deviceField30, null);
    jPanel6.add(deviceField21, null);
    jPanel6.add(deviceField22, null);
    jPanel6.add(deviceField23, null);
    jPanel6.add(deviceField24, null);
    jPanel6.add(deviceField25, null);
        jPanel6.add(deviceField16, null);
    jPanel5.add(jPanel23, null);
        jPanel23.add(deviceField215, null);
    jPanel23.add(deviceField32, null);
    jPanel23.add(deviceField217, null);
    jPanel23.add(deviceField214, null);
    jPanel23.add(deviceField216, null);
    jPanel23.add(deviceField213, null);
    jPanel23.add(deviceField212, null);
    jPanel5.add(jPanel7, null);
    jPanel7.add(deviceField29, null);
    jPanel7.add(deviceField33, null);
    jPanel7.add(deviceField211, null);
    jPanel7.add(deviceField28, null);
    jPanel7.add(deviceField210, null);
    jPanel7.add(deviceField27, null);
    jPanel7.add(deviceField26, null);
    jTabbedPane1.add(jScrollPane6,  "Lock Control");
        jTabbedPane1.add(jScrollPane5,   "Mode Control 1");
    jScrollPane5.getViewport().add(jPanel42, null);
    jPanel44.add(deviceField35, null);
    jPanel44.add(deviceField34, null);
    jPanel44.add(deviceChoice5, null);
    jPanel42.add(jPanel47, BorderLayout.CENTER);
    jPanel42.add(jPanel44, BorderLayout.NORTH);
    jPanel47.add(deviceTable7, null);
    jPanel47.add(deviceTable11, null);
    jTabbedPane1.add(jScrollPane14,  "Mode Control 2");
    jTabbedPane1.add(jScrollPane7,  "Mode Control 3");
    jTabbedPane1.add(jScrollPane8,  "Mode Control 4");
        jTabbedPane1.add(jPanel60,    "Bt Control: PID parameters");
        jPanel60.add(jPanel61, null);
        jPanel61.add(deviceField50, null);
        jPanel61.add(deviceField49, null);
        jPanel60.add(jPanel62, null);
        jPanel62.add(deviceField53, null);
        jPanel62.add(deviceField52, null);
        jPanel62.add(deviceField51, null);
        jPanel60.add(jPanel66, null);
        jPanel66.add(deviceField58, null);
        jPanel60.add(jPanel68, null);
        jPanel68.add(deviceField60, null);
        jTabbedPane1.add(jPanel64,   "F Control: PID Parameters");
        jPanel65.add(deviceField55, null);
        jPanel65.add(deviceField410, null);
        jPanel64.add(jPanel65, null);
        jPanel64.add(jPanel63, null);
        jPanel63.add(deviceField57, null);
        jPanel63.add(deviceField54, null);
        jPanel63.add(deviceField56, null);
    jPanel64.add(jPanel67, null);
    jPanel67.add(deviceField59, null);
        jPanel64.add(jPanel69, null);
        jPanel69.add(deviceField61, null);
    jScrollPane8.getViewport().add(jPanel4110, null);
    jPanel419.add(deviceTable16, null);
    jPanel419.add(deviceTable18, null);
    jPanel4110.add(jPanel4111, BorderLayout.NORTH);
    jPanel4110.add(jPanel419, BorderLayout.CENTER);
    jPanel4111.add(deviceField311, null);
    jPanel4111.add(deviceField310, null);
    jPanel4111.add(deviceChoice8, null);
    jScrollPane7.getViewport().add(jPanel417, null);
    jPanel416.add(deviceTable9, null);
    jPanel416.add(deviceTable15, null);
    jPanel417.add(jPanel418, BorderLayout.NORTH);
    jPanel417.add(jPanel416, BorderLayout.CENTER);
    jPanel418.add(deviceField39, null);
    jPanel418.add(deviceField38, null);
    jPanel418.add(deviceChoice7, null);
    jScrollPane14.getViewport().add(jPanel45, null);
    jPanel415.add(deviceTable8, null);
    jPanel415.add(deviceTable13, null);
    jPanel45.add(jPanel46, BorderLayout.NORTH);
    jPanel45.add(jPanel415, BorderLayout.CENTER);
    jPanel46.add(deviceField37, null);
    jPanel46.add(deviceField36, null);
    jPanel46.add(deviceChoice6, null);
    this.getContentPane().add(deviceButtons1, BorderLayout.SOUTH);
    jScrollPane6.getViewport().add(jPanel410, null);
        jPanel410.add(jPanel41,  BorderLayout.CENTER);
        jPanel410.add(deviceTable4,  BorderLayout.SOUTH);
        jPanel411.add(deviceField415, null);
        jPanel411.add(deviceField417, null);
        jPanel411.add(deviceField416, null);
        jPanel411.add(deviceField320, null);
        jPanel41.add(jPanel411, null);
    jPanel413.add(deviceField425, null);
    jPanel413.add(deviceField421, null);
    jPanel413.add(deviceField424, null);
    jPanel413.add(deviceField3111, null);
    jPanel41.add(jPanel412, null);
    jPanel41.add(jPanel48, null);
        jPanel23.add(deviceField41, null);
        jPanel7.add(deviceField42, null);
  }

}
