include $(MAKE_OPTIONS)

OBJECTS = MdsLibIdl.o

../shlib/libMdsLibIdl.$(SHARE_TYPE) : $(OBJECTS) ../shlib
	$(LD) -o $@ $(LD_SHARED_LIB_OPTIONS) $(OBJECTS) -L../shlib -lTdiShr -static -lTreeShr -lMdsShr

../shlib :
	mkdir ../shlib

clean :
	- rm *.o
	- rm ../shlib/libMdsLibIdl.$(SHARE_TYPE)
	- rm .depend

.depend :
	find *.c -exec $(MAKE_DEPEND)

include $(DEPEND)
