
include @top_builddir@/Makefile.inc
include ../../testing/testing.am


## ////////////////////////////////////////////////////////////////////////// ##
## // TESTS  //////////////////////////////////////////////////////////////// ##
## ////////////////////////////////////////////////////////////////////////// ##

TEST_EXTENSIONS = .sh

TESTS = \
  LocalEventTest.sh\
  RemoteEventTest.sh

# Files produced by tests that must be purged
#
MOSTLYCLEANFILES = \
	./*.log ./*.err

## ////////////////////////////////////////////////////////////////////////// ##
## // TARGETS  ////////////////////////////////////////////////////////////// ##
## ////////////////////////////////////////////////////////////////////////// ##


#clean-local: clean-local-tests

check_PROGRAMS =
check_SCRIPTS  = $(TESTS)
